### ISSUE TITLE
Frage zum Frontendediting

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#1]
Ist es angedacht, dass ein Mitglied via dem Frontendediting einen Eintrag machen kann, welcher dem Mitglied auch zugeordnet wird, so dass nur dieses Mitglied diesen Eintrag weiter bearbeiten kann? Oder ist diese Option vielleicht schon gegeben? Ich habe in den einzelnen Einstellungen dazu noch keine Möglichkeit gefunden?

Beste Grüße

**Comment by alnv** [comment]
Dieses Feature ist bereits implementiert. 

Kurze Anleitung:

- Jeder Datensatz benötigt eine User ID ( tl_member.id )
- Per {{user::id}} Inserttag kann die ID des eingeloggten Benutzer ausgelesen werden.
- {{user::id}} Inserttag ins Taxonomies/Filtern Widget eintragen
- Bei den Mitgliedergruppen können die Rechte verfeinert werden
- Im FE Modul [ Catalog Listenansicht  ] > "Benutzerberechtigungen aktivieren"-Checkbox auswählen, damit die Mitgliedergruppen Rechte auch greifen 

Siehe [Catalog Manager Demo](http://catalog-manager-demo.alexandernaumov.de/todo-liste.html) dort findest du ein Beispiel. Gehe ins Backend und wähle unter Benutzerverwaltung einen Mitglied aus und logge dich über die Vorschau Funktion ein. Auf der "Todo Listen"-Demo Seite kannst du es dir näher anschauen.

In der Doku werde ich darüber ausführlicher schreiben…

**Comment by Benjaminscherf** [comment]
Vielen Dank.
Das hört sich super an. Ich werde das ausprobieren.
Danke nochmal für die Anleitung.

**Comment by Benjaminscherf** [comment]
Ich habe es mir angesehen und muß sagen es ist sehr gut gelöst.
Ich habe in den Backend Einstellungen rumgespielt um das User-ID-Feld als Verstecktes Feld einzubinden. Ich habe soweit alles rückgängig gemacht denke jedoch,  dass sich das System von alleine zurücksetzt.
Soweit kann ich nur sagen super Arbeit.
