### ISSUE TITLE
Sortierung in Auswahllisten aus Fremdtabelle

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#10]
1.
Gibt es auch einen "Trick", die Werte in Select-Feldern zu sortieren, die man aus einer anderen Tabelle zur Auswahl anbietet?

2.
Kann man den Werten in einer Auswahlliste ein "Bitte wählen" oder so voranstellen, ohne dass das ein Pflichtfeld torpediert?

![cm-dropdown](https://user-images.githubusercontent.com/1300920/27083015-63ad9f06-5047-11e7-9a56-4a44f9833582.jpg)

**Comment by alnv** [comment]
1. Noch nicht. Ich überlege dazu etwas.
2. Du kannst bei dem Eingabefeld Select Menü die Checkbox "**Leere Auswahl hinzufügen**" aktivieren und danach bei "**Leeres Zeichen ersetzen**" dein Label eintragen. Ich prüfe noch ob ich die Zeichenlänge vergrößern kann.

**Comment by alnv** [comment]
Zum Entwicklungstand:

Im ersten Schritt (v1.4) kommt die automatische Sortierung je nach dem welche Sortierung man in dem DCA/Backend Modul definiert hat.

Im nächsten Schritt kommt die individuelle Sortierung.

**Comment by alnv** [comment]
Schritt 1 ist erledigt. Die Sortierung wird vom Backend Modul übernommen.
