### ISSUE TITLE
Abhängige Kategorien

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#100]
Hallo,

ich würde gerne die Produkte eines Kataloges in Kategorien einteilen. Es sollen 3 Kategorie-Level erzeugt werden. Jede Kategorie beinhaltet Ihrer eigenen Detailfelder, die nach Auswahl dem 
Produkt zur verfügung stehen sollen.

z.B.

A  (Nadelbaum)
AA (Tanne) --> Borke, Nadel, Zapfen
AA (Kiefer) --> Borke, Nadel, Zapfen

B (Laubbaum)
BB (Eiche) --> Eicheln, Rinde, Galle
BB (Buche)
BBB (Blutbuche)

C (Sträucher)
CC (Blütensträucher)
CC (Dornensträucher)

Im Frontend soll das Produkt nun vom Benutzer der Kategorie zugeordnet werden. 
Das habe ich schon über die Selektbox mit Datenbank Auswahlliste hinbekommen.
Ich habe es einmal über die Seitenstruktur versucht dabei entsteht das Problem, dass alle Seiten / Kategorien (sehr unübersichtlich weil lang) im Selektfeld angezeigt werden. 

Und einmal habe ich es über einen eigens angelegten Katalog versucht. Ebenfalls mittels der Selektbox. Hierbei entsteht das Problem das ich für die verschiedenen Level Kinderkataloge angelegt habe. Das Selectfeld zeigt aber natürlich nur die Auswahl der Elternelemente an. 

Die grobe Zuordnung der Kategorien funktioniert zwar, aber die Kategorieliste inkl der Subkategorien wird recht lang. 

Die entsprechenden Detailfelder bekomme ich nicht in die Abhängigkeit. 

Meine Frage:

Ist ein Prozess möglich, bei dem das Mitglied im Frontend das Produkt anlegt, es dann einer Kategorie zuordnet und ihm folglich dann die Subkategorie zur verfügung gestellt wird?
Und letztlich ihm die der Kategorie zugeordneten Detailfelder angezeigt werden?

Beste Grüße

**Comment by alnv** [comment]
Mit {{feldname}} kannst auch auf die Active-Record-Werte zugreifen und so Abhängigkeit erstellen. 

Siehe Screenshot.
![](https://catalog-manager.alexandernaumov.de/files/theme/media/github/filter-by-active-record.png)

Ein Beispiel findest du auf der Demoseite ( Siehe Immobilien Modul). Dort werden die Objekttypen nach dem jeweiligen Immobilientyp gefiltert.

**Comment by Benjaminscherf** [comment]
Vielen Dank, dass hat recht gut funktioniert. 

Ich habe nun eine 3 auf einander folgende Abhängige Felder erstellt. Im Backend funktioniert alles perfekt. Im Frontend gibt es jedoch ein Problem, und ich glaube es ist ein Bug. 

Bei der Ersterstellung eines Produktes im Frontend funktionieren die Abhängigen Felder wie gewollt. Durch Auswahl des ersten, stehen dem zweiten die Werte zur Verfügung. Durch Auswahl des zweiten, werden dem dritten die Werte zur Verfügung gestellt. 

Möchte man diesen Eintrag jedoch später Bearbeiten, werden die alten Werte nicht neu erzeugt, sondern bleiben bestehen. Ändert man im ersten Feld den Wert A auf B bleiben im Feld zwei und drei die abhängigen Werte von A erhalten.  Erst durch das Abspeichern des gesamten Formulars, werden die abhängigen Werte ersetzt.

**Comment by alnv** [comment]
Hast du bei den Eingabefeld-Einstellungen "Submit on change" Checkbox aktiviert?

**Comment by Benjaminscherf** [comment]
Ja, die ist aktiviert. Dies funktioniert auch. Das Formular wird übertragen und die Seite springt an den Anfang.

**Comment by alnv** [comment]
Mit v1.7 wird FE-Editing etwas optimiert. Eventuell wird es dein Problem lösen.

**Comment by Benjaminscherf** [comment]
Danke

**Comment by alnv** [comment]
Dein Problem konnte ich soweit reproduzieren. Wenn du magst kannst du die v1.17.beta3 runterladen und testen.

Unter Contao 3.5 ist es die 1.17.0-beta1

**Comment by alnv** [comment]
Behoben in v1.7.0
