### ISSUE TITLE
Autovervollständigung von Textfeldern

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#101]
Diese Funktion scheint nicht so recht zu funktionieren. 

Wendet man die Funktion auf ein Textfeld an, wird im Backendformular zwar ein Textfeld erzeugt dieser Bleibt jedoch leer. Dazu erscheint beim Hover und Focus über das Feld, das kleine Dreieck einer Select-Menü am rechten Rand, so als wenn hier eine Selcetfunktion erwartet wird. 

Mit dem Select-Menü funktioniert es.

**Comment by alnv** [comment]
Man muss in das Textfeld  2-3 Zeichen eingeben, damit die Autovervollständigung-Liste erscheint.

Select-Menü ist keine Autovervollständigung sondern einfach eine Auswahlliste an vordefinierten Items.

**Comment by Benjaminscherf** [comment]
Ja natürlich. Das habe ich Grundsätzlich verwechselt. Die Option die ich suche, ist ein Normales Textfeld durch den Wert eines Feldes aus einer anderen Datenbank vorzubelegen. So wie die Werte in einem Selcet-Menü aus einer anderen Tabelle geholt werden können.

**Comment by alnv** [comment]
So eine Option gibt es nicht.

**Comment by Benjaminscherf** [comment]
Ok, danke schön.
