### ISSUE TITLE
Liste und Liste-Kartenansicht kombinieren?

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#102]
Gibt es die Möglichkeit, Die normale Listenansicht mit einer Kartenansicht zu kombinieren?
So dass, bei einer Umkreissuche die gefundenen Items sowohl in der Googlemap, als auch darunter in Listenform angezeigt werden können?

**Comment by alnv** [comment]
Du kannst eine weitere Listenansicht erstellen und die Filterkriterien aus der Kartenansicht übernehmen.
