### ISSUE TITLE
Leere Eingabefelder im Formulargenerator

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#103]
Hallo,
ich habe ein CatalogManager v1.17.0 + Contao/Managed Edition 4.4.9.

Im Contao-eigenen Formulargenerator tauchen seit kurzem leere Eingabefelder auf:

<img width="476" alt="bildschirmfoto 2018-01-21 um 09 36 08" src="https://user-images.githubusercontent.com/8830861/35192271-94a39d7c-fe8e-11e7-8232-621439d677f2.png">

Diese Felder sind mit catalogMessageForm und catalogFineUploader bezeichnet.
<img width="572" alt="bildschirmfoto 2018-01-21 um 09 36 27" src="https://user-images.githubusercontent.com/8830861/35192272-9d4210e4-fe8e-11e7-830e-a67ece1f5d83.png">

Habe ich irgendetwas versehentlich eingestellt? 
Ein Frontend-Editing ist bei mir nicht aktiviert.

**Comment by alnv** [comment]
Danke für den Hinweis. Ich werde es mir ansehen und gegebenenfalls fixen.

**Comment by alnv** [comment]
Ist gefixt in v1.8
