### ISSUE TITLE
Slider für Umfangssuche verwenden

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#104]
Hallo,
kann für die Umfangssuche optional der [jQuery Slider](https://jqueryui.com/slider/) in den CM eingebaut werden. Interessant sind die Optionen
- Custom handle
- Range slider
- Range with fixed maximum
- Range with fixed minimum
- Snap to increments

**Comment by alnv** [comment]
Kann man einbauen.

**Comment by alnv** [comment]
Ich will mich zu diesem Zeitpunkt nicht auf ein JS Framework festlegen. Wer Support benötigt, kann gerne bei mir anfragen. 

Im Grunde ist es hier alles gut dokumentiert:  http://api.jqueryui.com/slider/

Alternativen:
http://rangeslider.js.org
https://refreshless.com/nouislider (Mein Favorit)
