### ISSUE TITLE
json_encoding schlägt fehl bei JSON-Request und Einsatz einer Bildergalerie

### ISSUE THREAD

**Issue by RoflCopter24** [alnv/catalog-manager#106]
Moin!
erstmal vielen Dank für deine super Arbeit hier mit der Erweiterung!

Ich bin gerade dabei, eine dynamische Umkreissuche mittels JSON-Requests umzusetzen und lasse mir die Ergebnisse als Array liefern. Interessanterweise bin ich dann darüber gestolpert, dass in meinem Fall ab gesetzten Ort + Distanz >= 15 nur eine leere Antwort mit Content-Size 0 kommt. Eine Fehlermeldung habe ich auch nirgendwo finden können.

Entsprechende Problemseite [findest du hier](https://huth.webtool.info/gf-filter.html?rs_cty=Dormagen&rs_dstnc=15 )
Sobald ich den Distance Parameter auf 14 oder weniger setze, läuft alles. Wenn ich mir die Datensätze als HTML ausgeben lasse, geht auch alles. Der Fehler tritt nur auf, wenn ich 'als Array ausgeben' gewählt habe und den JSON-Contenttype aktiviere. Im Backend wurden abgesehen davon nur die Pflichtfelder Lat & Lng gesetzt.

Hast du da eine Idee, woran das scheitern könnte bzw. wo ich nachschauen kann?

Gruß
Florian

**Comment by alnv** [comment]
Ich werde es versuchen zu reproduzieren und gegebenenfalls nach bessern. Danke für den Hinweis

**Comment by RoflCopter24** [comment]
Habe nochmal ein bisschen gegraben und den Fehler weiter eingekreist:
Das Problem ist das Encoding der Daten zu JSON, denn sobald man eine Bildergalerie hinzufügt und befüllt schlägt dies fehl, es wird `"Malformed UTF-8 characters, possibly incorrectly encoded" `  von `json_last_error_msg()` geliefert.

Da der Fehler nicht abgefangen wird, gibt es natürlich eine leere Antwort. Lasse ich die Galerie unbefüllt, klappt auch alles.

hope this helps!

**Comment by alnv** [comment]
Sollte in v1.19.2 gefixt sein.

**Comment by RoflCopter24** [comment]
Vielen Dank 👍
