### ISSUE TITLE
Einzelne Felder im Filtergenerator als Pflichtfelder definieren

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#107]
Hallo,
kann man beim Filtergenerator bei den einzelnen Feldern eine Option hinzufügen, so dass die Felder als Pflichtfelder ausgewisen werden können (die Felder müssen ausgefüllt sein, damit man den Filer anwenden kann).
![filtergenerator-pflichtfeld](https://user-images.githubusercontent.com/2067428/35583857-82c4ef9a-05f3-11e8-89d9-1ad7819a4a4e.png)

**Comment by alnv** [comment]
Grundsätzlich, wäre es keine große Sache. Aber was meinst du mit:

> Die Felder müssen ausgefüllt sein, damit man den Filter anwenden kann

**Comment by Schmidty2** [comment]
Da habe ich mich etwas unverständlich ausgedrückt :-(
Beispiel 1: Du hast z.B. eine Suche mit folgenden Feldern:
* Name
* Ort
* Land
* Kategorie

Ort und Kategorie sollen ein Pflichtfeld sein.
==> Die Filterung darf erst dann ein Ergebnis anzeigen, wenn die Felder Ort und Kategorie einen Inhalt haben

Beispiel 2: Eine Suche nach Veranstaltungen mit den Feldern:
* Veranstaltungsdatum
* Veranstaltungsart
* Veranstaltungsort

Das Veranstaltungsdatum soll ein Pflichtfeld sein.
==> Die Filterung darf erst dann ein Ergebnis anzeigen, wenn ein Veranstaltungsdatum zur Filterung eingetragen ist

Ich hoffe, ich habe das jetzt verständlich erklärt

**Comment by Schmidty2** [comment]
Sorry, habe ich versehentlich geschlossen...
..und wieder geöffnet

**Comment by alnv** [comment]
Das macht Sinn. Ich packe es auf die todo liste.

**Comment by alnv** [comment]
In der v1.20 können die Filter - Eingabefelder als Pflichtfelder eingestellt werden.
