### ISSUE TITLE
Testfeld - Eingabeprüfung auf Währung

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#108]
Hallo,
kann bei der Eingabeprüfung beim Textfeld die Option "Gültiger Währungs/Euro-Betrag" hinzugefügt werden? Es sollen max. zwei Nachkommastellen vorhanden sein.
![textfeld-wahrung](https://user-images.githubusercontent.com/2067428/35584469-684c8d1a-05f5-11e8-8381-f63009201317.png)

**Comment by alnv** [comment]
Eingabeprüfungen kann ich einbauen. Für spezielle Prüfungen wie Währung, Komma stellen etc. kann ich ein Feld für eigenen Regex einbauen.
