### ISSUE TITLE
Catalog Manager + Fehler 404: Fehlerseite wird fehlerhaft gerendert

### ISSUE THREAD

**Issue by denniserdmann** [alnv/catalog-manager#109]
Nachzuvollziehen über die Catalog Manager Demo:

1. Seite vom Typ Fehler 404 anlegen
2. eine vom Catalog Manager generierte URL mit beliebiger falscher Schreibweise aufrufen, z.B. http://catalog-manager-demo.alexandernaumov.de/vereinsseite/---tsg-phoenix.html

==> Die Fehlerseite wird fehlerhaft gerendert, es erscheint 
`grid1" itemscope itemtype="http://schema.org/WebPage">` als erste Zeile im`<body>`.

![bildschirmfoto 2018-02-01 um 08 27 06](https://user-images.githubusercontent.com/3773697/35666285-bb784eb8-0729-11e8-80e6-6b94fec821b7.png)

Sieht so aus, als würde es ein Problem mit der body-class geben.

**Comment by alnv** [comment]
Ist gefixt in v1.8.2
