### ISSUE TITLE
Umkreissuche :: Darstellung des Kreises der Google API 

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#11]
Es wäre toll wenn bei der Umkreissuche die Darstellung der Google API nutzbar wäre :-)

**Comment by alnv** [comment]
Über die Templates ist ein Zugriff auf die Google API schon jetzt möglich.

- mod_catalog_map_default
- ctlg_map_default

Dort kannst du die Darstellung der Map manipulieren.

**Comment by codiso** [comment]
Super danke :-D
