### ISSUE TITLE
[Frage] Elemente in mod_booknav aufnehmen

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#110]
Bisher kennt die mod_booknav nicht die Catalog-Einträge in der Datenbank.
Kann man den Catalog-Manager erweitern, dass `$this->hasNext` bzw. `$this->hasPrevious` erkannt und vergeben werden?

**Comment by alnv** [comment]
Ich habe jetzt keine Schnittstelle für die Buchnavigation entdeckt.  Catalog Manager zu erweitern wäre möglich.

**Comment by akroii** [comment]
Closed, ... wurde ja erledigt.👍
[https://github.com/alnv/catalog-manager/commit/fb3b01cea2003cf658e6e1fc256a89815bcee171](https://github.com/alnv/catalog-manager/commit/fb3b01cea2003cf658e6e1fc256a89815bcee171)
