### ISSUE TITLE
Dynamischer Wert für eindeutige Bezeichnung wird erst beim zweiten speichern generiert

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#111]
Hallo,
ich generiere in einer Adressdatenbank die eindeutige Bezeichnung aus drei Eingabefeldern (Vorname, Familienname, Geburtsdatum).
![01a279d0-344b-40f9-9f49-5021c204225a](https://user-images.githubusercontent.com/2067428/35835715-96b3feea-0adc-11e8-81e2-fed3e2b0c17d.jpeg)
Wenn ich jetzt einen neuen Datensatz erstelle, wird die eindeutige Bezeichnung beim speichern nicht erstellt (das Feld bleibt leer), beim Alias wird ein Zahlenwert (z.B. _157) eingetragen. Erst wenn der Datensatz das zweite Mal gespeichert wird, wird die eindeutige Bezeichnung generiert - wenn der Alias zuvor gelöscht wurde, wird die eindeutige Bezeichnung auch in den Alias übernommen.
Kann das Ganze so abgeändert werden, dass die eindeutige Bezeichnung (und der Alias) gleich beim ersten speichern richtig generiert wird?
In der gleichen Tabelle wird aus den Adressdaten die Geoposition (Latitude und Longitude) berechnet, das wird - so wie es sein soll - beim ersten speichern generiert.

**Comment by alnv** [comment]
Wird behoben beim nächstem Update.
