### ISSUE TITLE
Datum mit Wochentag - Filter funktioniert nicht mehr

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#112]
Hallo,
ich beziehe mich auf [diesen Beitrag](https://catalog-manager.alexandernaumov.de/feedback/datumsausgabe-optional-mit-wochentag.html).
Die Ausgabe des Datums mit dem Wochentag funktioniert damit auch im Frontend und im Backend.

Aber die Filter, die nach einem Datum filtern funktionieren mit dieser Einstellung nicht mehr. Auch bei Timestamp-Werten die berechnet werden (z.B.: {{CTLG_TIMESTAMP::?add=604800}} ) gibt es einen Fehler, genauso wie bei der Backend-Dateneingabe, die ein ungültiges Datum bemängelt.

Contao 4.4.13, CatalogManager 1.18.2 - Hier noch die Fehlermeldung aus var/logs:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Exception(code: 0): Invalid date format \"D., d.m.Y\" at /www/htdocs/verzeichnisname/vendor/contao/core-bundle/src/Resources/contao/library/Contao/Date.php:328)"} []`

**Comment by alnv** [comment]
Das betrifft die Date.php Klasse. Diese kann aus einem Timestamp dir ein "D., d.m.Y" Format erstellen aber aus "D., d.m.Y" kein Timestamp. Scheint ein generelles Contao Problem zu sein…

Workaround: Verwende im Backend "d.m.Y" Format und im Frontend kannst du in den jeweiligen Templates dein Wunschformat ausgeben:

<?= $this->parseDate(  'D., d.m.Y', $this->origin['meinFeldname']  )  ?>
