### ISSUE TITLE
Dynamischer-Wert für eindeutige Bezeichnung/Alias bei Checkbox Menü nicht korrekt 

### ISSUE THREAD

**Issue by 108g** [alnv/catalog-manager#113]
Hallo! Der Dynamische-Wert für eine eindeutige Bezeichnung bzw. Alias bei Zuweisung per simple Tokens eines Checkbox Menü Feldtyps funktioniert nicht korrekt in der Version 1.18.3.

Ist der Feldtyp Checkbox Menü kein Pflichtfeld und wird somit leer gelassen, erscheint beim Speichern im Feld Bezeichnung bzw. Alias zusätzlich der Eintrag Array (bzw. beim Alias -array).

Bei Mehrfachauswahl werden die Werte ohne "-" Minus im Alias (bzw. ohne Leer nach dem Komma in der Bezeichnung) dargestellt.

Wäre es möglich all dies noch zu beheben?

Danke für diese tolle Contao-Erweiterung!

![2018-02-07 13_28_41-stellenanzeigen - contao open source cms 3 5](https://user-images.githubusercontent.com/20578959/35916609-3e4e6fa8-0c0b-11e8-9958-c1e3d2ede1cc.png)

![2018-02-07 13_35_19-stellenanzeigen - contao open source cms 3 5](https://user-images.githubusercontent.com/20578959/35916800-f36e98f4-0c0b-11e8-85d2-1df12d2183d8.png)

**Comment by alnv** [comment]
Das mit dem array kann ich fixen. Hat es vor dem Update funktioniert?

Die Sache mit den Kommas:
Catalog verwendet die selbe Methode bei der Alias Generierung wie die Contao Core Module. Das Komma wird einfach entfernt. Leerzeichen werden zu "-" Minus. Da es keine Leerzeichen zwischen den Kommas gibt, werden die Einträge nebeneinander ohne Trennzeichen zu zusammen gefügt.

**Comment by 108g** [comment]
Hat vor dem Update auch nicht korrekt funktioniert. Werte aus den Feldern wurden z.B. erst beim zweiten mal Speichern übernommen. Änderungen wurden gar nicht übernommen. Das funktioniert aber seit 1.18.3 gut.

Ein Minus bei Alias zwischen Array Werten wäre für SEO gut. Aber wenn es nicht geht, muss ich damit leben. Danke.

**Comment by 108g** [comment]
Mir ist weiterhin aufgefallen, dass über das Frontend Editing die Dynamischen-Wert für eindeutige Bezeichnung nicht richtig funktionieren. Nur beim Erstellen eines neuen Eintrags werden Werte vom Typ Textfeld übernommen. Feldtyp Checkbox wird immer mit "Array" dargestellt. Beim Bearbeiten eines bestehenden Datensatzes übers FE werden die Dynamischen-Wert für eindeutige Bezeichnung gar nicht aktualisiert. Übers BE jedoch schon.

**Comment by alnv** [comment]
> Beim Bearbeiten eines bestehenden Datensatzes übers FE werden die Dynamischen-Wert für eindeutige Bezeichnung gar nicht aktualisiert.

Kann ich nicht nachvollziehen. Welche CM Version hast du?

**Comment by 108g** [comment]
Ich habe die v1.18.3 unter Contao 3.5.33 installiert. Hier das genaue Verhalten im Frontend:

Der dynamische Wert für die eindeutige Bezeichnung wird aus zwei simple Tokens generiert. Feldtyp Textfeld und Feldtyp Checkbox.
Beim neu Erstellen über das FE wird die eindeutige Bezeichnung und der Alias fehlerfrei erstellt, solange keine Checkbox ausgewählt ist.
Wird eine Checkbox beim neu Erstellen ausgewählt, steht Array in der eindeutigen Bezeichnung und -array im Alias mit dabei.

Wird eine bestehender Eintrag über das FE bearbeitet, wird der Alias nicht mehr neu erzeugt. Die eindeutige Bezeichnung schon, aber wieder mit Array anstatt mit den Werten der Checkbox.

**Comment by alnv** [comment]
wird gefixt in der nächsten Version.

**Comment by alnv** [comment]
Update ist online. Standardmäßig wird der Alias nur generiert wenn es noch keinen Alias gibt. Wenn du dieses Verhalten abstellen möchtest, trage folgendes in deine localconfig.php ein:

`$GLOBALS['TL_CONFIG']['dynAlias'] = true;`
