### ISSUE TITLE
Kleine Verbesserungsvorschläge

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#114]
Nach längerer Pause erstelle ich gerade wieder eine Datenbank und freue mich darüber, was alles verbessert wurde! Zwei Kleinigkeiten fallen mir bisher noch auf:

In ctlg_form_fine_uploader.html5 wäre es schön, wenn es dazu Sprachfiles gäbe, damit auf deutschen Seiten der Upload-Button und die Dropzone auf deutsch beschriftet werden können. Das erspart die Änderung des Templates.

ctlg_form_default/grouped.html5 enthält auch den Submitbutton. Hier finde ich schade, dass man ihm nicht wie im Core-Formulargenerator, wo der Submitbutton manuell hinzugefügt wird, eine CSS-Klasse mitgeben kann (außer übers Template). Ist z.B. interessant bei Einsatz eines externen CSS-Frameworks.

**Comment by alnv** [comment]
Das mit dem Sprachfiles werde ich prüfen.
Das mit dem Absende-Button kann ich auf die todo liste packen.

**Comment by alnv** [comment]
v1.20 Update:

Sprachfiles wurden hinzugefügt:

``` php
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['yes'] = 'Ja';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['no'] = 'Nein';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['ok'] = 'Okay';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['close'] = 'Schließen';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['cancel'] = 'Abbrechen';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['drop'] = 'Datei ablegen';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['retry'] = 'Erneut versuchen';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['upload'] = 'Datei hochladen';
$GLOBALS['TL_LANG']['MSC']['FINE_UPLOADER']['processing'] = 'Dateien werden verarbeitet …';
```

Dem Absende Button können individuelle Klassen hinzugefügt werden (Über die Filter Generator Einstellungen). Des weiteren wird ein Button Element anstelle eines Input types verwendet.
