### ISSUE TITLE
Catalog Listenansicht: Taxonomy/Filterung mit Textarea möglich?

### ISSUE THREAD

**Issue by denniserdmann** [alnv/catalog-manager#116]
Ich nutze den Catalog Manager zur Darstellung von Orten in einer Liste, die über ein Filterformular mit einem einfachen Suchfeld gefiltert werden können. Das funktioniert soweit auch sehr gut.

Nun kam der Wunsch auf, dass das Suchfeld auch 2 Textareas (Teaser und Beschreibung) durchsuchen soll, bei dem Modul _Catalog Listenansicht_ kann ich allerdings nur einfache Textfelder und Checkboxes auswählen, die erstellten Textareas werden nicht angezeigt und eine Filterung lässt sich so nicht einstellen. 

Mache ich etwas falsch oder ist es (aktuell) nicht möglich? 
Contao 3.5.27
Catalog Manager: v1.2.8

![bildschirmfoto 2018-02-19 um 11 48 11](https://user-images.githubusercontent.com/3773697/36374212-d8fbbd22-156a-11e8-87fc-21cbf6305df8.png)

**Comment by alnv** [comment]
Möglich wäre es schon. Aber nicht performant oder skalierbar bei großen Datensätzen. Daher habe ich es rausgenommen.

Besser geeignet wäre ein Textfeld mit einigen Komma getrennten Werten.

**Comment by denniserdmann** [comment]
Ok, danke für den Hinweis. Dann werden wir uns etwas anderes einfallen lassen und ggf. mit einem Stichwort-Feld wie von dir vorgeschlagen arbeiten

**Comment by alnv** [comment]
In der v1.20 können auch blanke textareas verwendet werden (Ohne RTE).
