### ISSUE TITLE
Feature requests: Fieldsets und HTML-Felder

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#117]
Offenbar lassen Fieldsets sich nicht verschachteln. Ich habe innerhalb eines Fieldsets ein weiteres Fieldset erstellt, das nur ein längeres Erklärungsfeld enthält und standardmäßig eingeklappt sein soll. 

Im Backend werden dann die nachfolgenden Felder, die gar nicht Teil dieses inneren Fieldsets sind, mit eingeklappt. Im Frontend wird das innere Fieldset ignoriert.

Es wäre schön, wenn man Fieldsets a) verschachteln könnte und wenn man ihnen b) ebenfalls eine CSS-Klasse mitgeben könnte. 

Ferner (oder auch alternativ zum verschachtelten Fieldset) würde ich mir wünschen, HTML-Felder ins Formular einfügen zu können (wie das CE HTML), um umfangreiche FE-Eingabeformulare freier gestalten zu können.

**Comment by alnv** [comment]
Verschachtelte Fieldsets zu implementieren wäre sehr aufwendig. Ein Eigenes-HTML Element wäre möglich, aber das müsste ich mir genauer anschauen.

**Comment by Anke** [comment]
Dann vergiss das verschachtelte Fieldset - HTML-Element wäre viel wichtiger, da hat man alle Möglichkeiten offen. Das wäre echt toll, wenn das ginge!

**Comment by alnv** [comment]
@todo: Individuelle Templates für Eingabefelder (Nur im FE)

**Comment by alnv** [comment]
Ist erledigt. Eingabefelder verfügen über ein eigenes Template. Dieser kann individualisiert werden.
