### ISSUE TITLE
Zeitstempel im FE Editing immer 0 bzw. 01.01.1970 00:00

### ISSUE THREAD

**Issue by 108g** [alnv/catalog-manager#118]
Ich benötige für einen Stellenmarkt ein Feld mit einem eindeutigen Zeitstempel der nicht verändert werden kann. Dazu habe ich ein Datumsfeld mit SQL Datentyp int(10) und Eingabefeld-Einstellungen -> Zeitstempel angelegt. Ein neuer Eintrag über das BE funktioniert damit einwandfrei. Über das FE Editing wird das Feld mit Zeitstempel deaktiviert, damit es nicht beeinflusst werden kann. Jedoch wird hier beim Speichern 0 in die DB geschrieben. Lege ich einen Standardwert mit UNIX_TIMESTAMP(), {{date::U}} oder {{date::d.m.Y}} für das Feld fest, gibt es einen PHP-Fehler:

> PHP Fatal error: Uncaught exception 'OutOfBoundsException' with message 'Invalid date "{{date::d.m.Y}}"' thrown in C:\xampp\htdocs\stellenmarkt\system\modules\core\library\Contao\Date.php on line 438
> #0 C:\xampp\htdocs\stellenmarkt\system\modules\core\library\Contao\Date.php(79): Contao\Date->dateToUnix()...

Gibt es dafür eine Lösung? Danke!

![2018-02-21 13_58_42-themes refa-jobs de frontend-module modul id 19 bearbeiten - contao open s](https://user-images.githubusercontent.com/20578959/36481198-6373d57a-170f-11e8-8a92-936f3ac81946.png)

**Comment by alnv** [comment]
Ich würde in deinem Fall ein "varchar(255)" verwenden weil Inserttags (fast) immer ein String zurück geben. 

Statt {{date::*}} kannst du den CM internen Inserttag verwenden: {{CTLG_TIMESTAMP}}
