### ISSUE TITLE
MySQL-Befehle im Feld Wert bei Taxonomies/Filter

### ISSUE THREAD

**Issue by 108g** [alnv/catalog-manager#119]
Besteht die Möglichkeit im Frontend beim Modultyp Catalog Listenasicht im Bereich Taxonomies/Filter MySQL Befehle im Feld Wert mit anzugeben?

Meine Vorstellung wäre:
![2018-02-21 14_08_59-themes refa-jobs de frontend-module modul id 19 bearbeiten - contao open s](https://user-images.githubusercontent.com/20578959/36481671-d3c1424e-1710-11e8-88c4-1c0c127f9293.png)

Es dürften nur Einträge, die nicht älter als 30 Tage sind, ausgegeben werden. Ich finde keine Möglichkeit. Oder habe ich was übersehen?

Eine Möglichkeit allgemein MySQL Befehle als Werte zu verwenden wäre noch eine Bereicherung für die ohnehin schon geniale Erweiterung Catalog Manager.

**Comment by alnv** [comment]
Erstmal nicht… Verwende den  {{CTLG_TIMESTAMP}} Inserttag. Mit diesem Inserttag kannst du auch rechnen z.B

{{CTLG_TIMESTAMP::?add=604800}} => Heute + sieben Tage
{{CTLG_TIMESTAMP::?add=2592000}}  => Heute + 30 Tage
{{CTLG_TIMESTAMP::?subtract=2592000}}  => Heute - 30 Tage

Weiter gibt es noch "multiply" und "divide".

Ich würde statt dem BETWEEN Operator "Größer gleich" und "Kleiner gleich" verwenden.

**Comment by 108g** [comment]
Perfekt! Sie sind der Beste ;-) Dankeschön.
