### ISSUE TITLE
tl_page modifier

### ISSUE THREAD

**Issue by kgansberger** [alnv/catalog-manager#121]
alias wird bei gewähltem folderURL in den settings auf rgxp => alias überschrieben

`
//standard:
...
'alias' => ['rgxp' => 'alias']
...`
`
//folderurl: $GLOBALS['TL_CONFIG']['folderUrl'] = true;
...
'alias' => ['rgxp' => 'folderalias']`
...

**Comment by alnv** [comment]
Catalog Manager ist "folderalias" RGXP nicht bekannt. Dafür muss ich mir eine Lösung überlegen. Soweit ich weiß werden die RGXP Typen nicht zentral von Contao verwaltet.

**Comment by kgansberger** [comment]
es wird ohnehin nur gültig wenn man den tl_page modifiziert und Ordner-URLs aktiviert hat. Ich hab allerdings länger nach dem Grund gesucht :)

**Comment by alnv** [comment]
Ab v1.21 werden standard Eingabefelder wie "Eindeutige Bezeichnung" und "Alias" deaktiviert. Damit wäre das Problem gelöst.

**Comment by alnv** [comment]
Ist implementier in v1.21.beta.3
