### ISSUE TITLE
Select-Widget wird nicht mit hinterlegten Optionen befüllt

### ISSUE THREAD

**Issue by trilobit-gmbh** [alnv/catalog-manager#122]
Neuen Katalog anlegen
Feldtyp "Select-Menü" auswählen und
konfigurieren.
Optionen setzen (hierbei ist es egal, ob sie vom Type "Auswahlliste" oder "Datenbank Auswahlliste" sind)

In der Katalog-Eingabemaske werden keine Optionen aus dem Select ausgegeben.

./vendor/alnv/catalog-manager/library/alnv/Fields/Select.php

In der "generate" Methode ist die Variable "$blnActive" "false". Wird diese manuell auf "true" gesetzt, werden die Optionen aufbereitet und eingebunden.

**Comment by trilobit-gmbh** [comment]
Betrifft die Version:
v1.21.0

**Comment by alnv** [comment]
Funktioniert es unter v1.20 auch nicht? Das Problem muss ich erstmal reproduzieren. Könntest du mir deine Catalog Einstellungen durchgeben?

**Comment by trilobit-gmbh** [comment]
Hallo Alex,

ich habe Dir direkt eine Mail mit den fraglichen Daten geschickt - ist nicht für den Issue hier ;-)

Danke Dir für den Support!
VG Peter

**Comment by trilobit-gmbh** [comment]
Danke für das Feedback und die richtigen Hinweise.

Gelöst.

Der Fehler lag daran, dass die Module nicht über die Catalog-Manager-Eigenschaften des jeweiligen Katalogs als BE-Modul aktiviert war (sondern manuell über eine config.php).
VG Peter
