### ISSUE TITLE
Loggen von Änderungen in den Catalog Daten

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#123]
Hallo. Ist es möglich, Änderungen in den Catalog-Inhalten in ein Logfile/Datenbank zu schreiben?

Hintergund:
Bei einem unserer Kunden hat ein Mitarbeiter etwas geändert, was rechtlich inkorrekt war.
Nun der große Aufschrei, aber wir können nicht nachvollziehen, welcher Mitarbeiter die Änderung erstellt hat.

Hier wäre es gut, wenn man Änderungen in einem Logfile o.ä. nachvollziehen könnte.
Ausreichend wäre ja ggf. schon "Benutzer xyz hat am 13.04. um 14:23 den Datensatz 1234567 geändert".

Mit der Contao Funktion System::log() beispielsweise. ;-)

**Comment by alnv** [comment]
Logs sind bereits implementiert. Das macht das "DC_Table" Treiber automatisch. Optional kann auch die Versionierung aktiviert werden. Siehe Catalog Manager > Modul Einstellungen > [Versionierung](https://catalog-manager.alexandernaumov.de/feedback/versionierung-im-frontend.html)

Die Logs erfassen keine Änderungen, es seiden die Versionierung ist aktiv.

**Comment by ricowe** [comment]
Klasse, danke! 
Hatte eine alte Catalog Version installiert, deswegen bin ich nicht drauf gekommen.
