### ISSUE TITLE
Validierung bei Verwendung vom Datepicker

### ISSUE THREAD

**Issue by RVGunnar** [alnv/catalog-manager#124]
So wie es für mich aussieht, nutzt der CM im FE grundsätzlich die Zeitformatierung aus den Contao Einstellungen. Folgende Problematik bei Nutzung des Datepickers im Input-Feld:

Der Date-Picker befüllt das Textfeld im Format YYYY-MM-DD (Standartisiertes Format), die Validierung vom CM greift allerdings beim Submit der Formulars (egal ob ein FE-Edit oder Filterfomular) und erwartet einen Wert im gesetzten Format (in meinem Fall: DD.MM.YYYY)

Ist es vorgesehen, die Formatnutzung dem internationalen Standard anzugleichen (um die Ausgabe im FE kümmern sich ja die Browser heutzutage von selbst), um eine möglichst große Kompatibilität zu gewährleisten?

**Comment by alnv** [comment]
Du kannst in der Seitenstruktur oder den Einstellungen, das Format entsprechend anpassen:

Y-m-d entspricht  YYYY-MM-DD

Was die Standardisierung angeht,  bitte ein Ticket an das Contao Core Team. Da kann ich nichts machen. Ich nutze nur das was Contao mir zur Verfügung stellt.

Am Haus eigenen Datepicker für CM bin ich dran ;)

**Comment by codesache** [comment]
@alnv 
Gibt es den schon?

Für das Frontend Editing wäre das hilfreich.
Aktuell wird mir für "Anzeigen ab" und "Anzeigen bis" nur das normale Eingabefeld angezeigt.
Oder kann ich den DatePicker von Contao irgendwie dafür aktivieren.

**Comment by landzone21** [comment]
> Am Haus eigenen Datepicker für CM bin ich dran ;)
Ich möchte auch nochmal fragen, ob es mittlerweile einen Datepicker für das Frontend-Editing gibt.
