### ISSUE TITLE
Fehler bei automatischer Berechnung von Latitude & Longitude

### ISSUE THREAD

**Issue by Y-Nell** [alnv/catalog-manager#125]
Mir ist leider jetzt er bei einer Installation ist mir aufgefallen, dass Latitude & Longitude nicht mehr automatisch berechnet werden.

Aktuell habe ich die v1.20 installiert. Mit Version 1.6 bzw. 1.7 hat es zu Anfang funktioniert.

Gab es zwischenzeitlich eine Änderung bei den Updates bzw. ein weiterer Schritt, der nicht in der Dokumention enthalten ist?

**Comment by alnv** [comment]
Du benötigst einen Schlüssel von Google für die API Nutzung. 

Schlüssel für 
- JS API
- GeoCoding

@todo an mich: Doku erstellen.

**Comment by Y-Nell** [comment]
Danke Alex, die Einbindung der GeoCoding API fehlte. War für mich neu.

Jetzt ist nur das Problem, dass bei einigen Datensätzen die Werte mit "Speichern" direkt berechnet und angezeigt werden und bei Einigen erst nachdem ich die geöffnete Seite mit dem betreffenden Datensatz 1-2x neu lade und dann wieder auf "Speichern" klicke.

Liegt das evtl. nur am Cache, Contao oder Browser?

**Comment by alnv** [comment]
Ich vermute, dass es auch am Key liegt. Das passiert meistens wenn die Anzahl an Request überschritten ist…

**Comment by Y-Nell** [comment]
Den Key ist für beide APIs neu generiert und die Anzahl der bearbeiteten Datensätze war nur ca. ein Dutzend.
