### ISSUE TITLE
Anlage von DB-Schema nicht möglich

### ISSUE THREAD

**Issue by sleitz** [alnv/catalog-manager#126]
Beim initialen Anlagen der Datenbankstruktur für die Erweiterung erscheint folgende Fehlermeldung, wenn MariaDB 10 im Einsatz ist:

> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  cols SMALLINT UNSIGNED DEFAULT 0 N' at line 14

Das Schema sieht eine Tabelle `tl_catalog_fields` vor, die eine Spalte `rows` hat.

MariaDB betrachtet `rows` aber als reserviertes Wort, siehe [Dokumentation](https://mariadb.com/kb/en/library/reserved-words/). Es genügt vollkommen, im Schema stattdessen `` `rows` `` zu schreiben. Natürlich auch ein allen entsprechenden SQL-Abfragen. Könnte das im Schema angepasst werden?

**Comment by robert-scheck** [comment]
Bereits die [Dokumentation](https://dev.mysql.com/doc/refman/5.5/en/keywords.html#keywords-5-5-detailed-R) von MySQL 5.5 listet `ROWS` als reserviertes Wort auf.

**Comment by alnv** [comment]
Gefixt in v1.21.1
