### ISSUE TITLE
Zugriff auf Elemente einer verknüpften Tabelle bei N:M-Beziehungen

### ISSUE THREAD

**Issue by sleitz** [alnv/catalog-manager#127]
Es ist laut [Anleitung](https://catalog-manager.alexandernaumov.de/dokumentation/catalog-manager-joins.html) möglich, im Template auf die ausführlichen Felder verknüpfter Tabellen zuzugreifen.

Das funktioniert soweit gut, wenn es sich bei der Verknüpfung um Felder der Typen "Radio-Buttons", "Auswahl-Menü" etc. funktioniert, die eine 1:N-Beziehung modellieren.

Sobald aber ein "Checkbox-Menü" mit Mehrfachauswahl ins Spiel kommt, versagt die Logik. In der Datenbank werden dann zwar die korrekten Werte (z.B. "7,1") abgelegt, aber im Template besteht nur Zugriff auf den ersten der beiden angegebenen Datensätze.

Vorschlag: Könnte in diesem Fall die Template-Variable ein Array sein? Also statt

```php
array:47 [
    …
    "hauptcatalog_nebencatalogTitle" => "Gummibärchen",
    …
]
```

lieber so etwas:

```php
array:47 [
    …
    "hauptcatalog_nebencatalogTitle" => array:2 [
        "Gummibärchen",
        "Schokolade",
    ],
    …
]
```

**Comment by sleitz** [comment]
Ich glaube, da ist sogar noch ein Bug drin. Zumindest in meinem Test-Setup wird ein Eintrag mit zwei verknüpften Datensätzen in der Listenansicht doppelt angezeigt.

**Comment by alnv** [comment]
Es werden lediglich alle Datenbank Ergebnisse ausgegeben und bei einer N:M Beziehung kommen Datensätze mehrfach vor.  Das Ergebnis ist zwar nicht ganz optimal aber ein Bug ist es nicht.

Eine Lösung wäre alle Datensätze auszulesen und durch eine PHP-Schleife zu jagen und zu verschachteln aber darauf habe ich Bewusst verzichtet ( schlechte Performance, lange Ladezeit und nicht skalierbar).

**Comment by sleitz** [comment]
Der Kunde braucht hierfür eine Lösung. Können wir telefonieren, um das zu besprechen? Kosten würde der Kunde in gewissem Rahmen übernehmen, falls Anpassungen erforderlich sein sollten.

**Comment by alnv** [comment]
@sleitz du kannst mir gerne eine E-Mail schreiben: me@alexandernaumov.de

**Comment by alnv** [comment]
Ich packe es auf die todo liste…

**Comment by denniserdmann** [comment]
Moin,

ich stehe vor einem ähnlichen Problem. Ich schreibe dir dazu mal eine Mail, @alnv.

**Comment by alnv** [comment]
Vielen Dank an @denniserdmann für den Support. Eine N:M Verknüpfung wurde implementiert ( ab v1.24 ).

Unter der "Verknüpfungs-Einstellungen" Palette gibt es jetzt eine Checkbox "Mehrfache Verknüpfungen als Array ausgeben." 

Siehe:
![](https://catalog-manager.alexandernaumov.de/files/theme/media/github/nToMRelation.png)

Im Template werden alle verbundenen Datensätze als Array ausgegeben.

``` php
<?php if ( is_array( $this->myField ) && !empty( $this->myField )  ): ?>
<?php foreach ( $this->myField as $arrField ): ?>
   <?= $arrField['myColumn'] ?>
<?php endforeach; ?>
<?php endif; ?>

```

**Comment by alnv** [comment]
Lässt sich auch auch so ausgeben:

``` php
<?php 
implode( ', ',  array_map( function( $arrValue ) { return $arrValue['title'] }, $this-> myField ) ) 
?>
```
