### ISSUE TITLE
Mehrere bearbeiten: Löschen ist auswählbar trotz Einschränkung in der Rechtevergabe

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#129]
Hallo,

ich habe einer Benutzergruppe Rechte für einen Catalog zugewiesen.
Anlegen und Bearbeiten ist ok, Löschen soll allerdings gesperrt werden.
Wenn ich im Catalog die Items ansehe, ist auch kein "X" zum löschen vorhanden.
Wenn ich dann jeoch oben "Mehrere bearbeiten" klicke, könnte ich alle markieren und unten den Button "Löschen" betätigen.

**Comment by alnv** [comment]
Das Löschen von Datensätzen sollte in dem Fall trotzdem nicht funktionieren. Falls einer aus versehen drauf klickt.

Ich werde es mir die Tage näher anschauen.

**Comment by alnv** [comment]
Scheint ein Contao 4 Problem zu sein.
