### ISSUE TITLE
Parameter via POST unterstützen

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#13]
Neben GET sollte auch die Übergabe von Parametern über POST unterstützt werden.

**Comment by alnv** [comment]
Kein Problem kommt mit dem nächstem Update.
Siehe: https://github.com/alnv/catalog-manager/commit/ed6d176b93bc420419c6e4481ea78281c617aaae

**Comment by codiso** [comment]
Cool … Danke!

**Comment by alnv** [comment]
Beim Filterformular kann man jetzt zwischen GET und POST wählen. Der CTLG_ACTIVE Inserttag greift auf POST sowie GET Parameter zu.
