### ISSUE TITLE
Fehlemeldung im SystemLog Unknown insert tag

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#130]
Im SytemLog wird "Unknown insert tag {{feldname}}" angezeigt.
Der Inserttag wird wird bei einem Select-Filter aus einer Tag-Liste übernommen.

**Comment by alnv** [comment]
Bugfix kommt in der nächsten Version.

**Comment by alnv** [comment]
Ist gefixt in v1.22
