### ISSUE TITLE
Bei verknüpften Tabellen wird die Kartendarstellung nicht ausgegeben

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#131]
Ich beziehe mich auf diese [Anleitung](https://catalog-manager.alexandernaumov.de/dokumentation/catalog-manager-joins.html).
Bei verknüpften Tabellen wird die Kartenansicht, die in der verknüpften Tabelle hinterlegt ist, nicht ausgegeben. Die anderen verknüpften Felder werden wie gewünscht ausgegeben.
Mit diesem Befehl binde ich die Karte ein:
`<?= $this->cat_tabellennameFeldname ?>`

**Comment by alnv** [comment]
Nachrichten und Kartenansicht werden etwas anders ausgegeben als andere Feldtypen. Daher kommen da keine Ergebnisse. Ab der nächsten Version wird die Kartenansicht auch ausgegeben.

**Comment by alnv** [comment]
Ist implementiert in v1.22
