### ISSUE TITLE
JOIN mit GROUP BY oder Sub-Query für Kind Tabelle

### ISSUE THREAD

**Issue by bitkorn** [alnv/catalog-manager#132]
wir haben eine Tabelle für **Produkte** und eine Tabelle **Bestand** mit einer Spalte **Anzahl**. In Bestand sind für jedes Produkt mehrere Datensätze.
Wir möchten in einer Liste der Produkte, die Summe der Anzahl aus Bestand zu jedem Produkt anzeigen.

In der Doku zu **Tabellen verknüpfen** kann man einen JOIN zu anderen Tabellen machen. Aber hier würde für unser Problem noch ein GROUP BY fehlen. Sonst haben wir nicht eine Liste der Produkte, sondern eine Liste der Einträge aus Bestand mit Produkdaten. Also viel zu viele Reihen als Ausgabe. Und ein JOIN wäre hier sowieso falsch.

Richtig wäre hier eine SQL Unterabfrage in der Art : SELECT produkt.*, (SELECT COUNT(id) AS c_bestand FROM bestand WHERE produkt_id = produkt.id) AS bestand_quantity FROM produkt;

In der Doku zu **Tabellen Beziehungen** werden Eltern-/Kind-Tabellen beschrieben. Ist so eine Unterabfrage vielleicht dort möglich?

Ist so etwas generell mit dem Catalog Manager möglich?

**Comment by alnv** [comment]
Die beste Lösung wäre es eine eigene Abfrage zu definieren. Dazu gibt es auch einen passenden HOOK:

```php
// config.php
$GLOBALS['TL_HOOKS']['catalogManagerOverwriteQuery'][] = [ 'MyClass', 'execute' ]
```

```php
class MyClass {
  
  public function execute ( $arrQuery, $strQuery, &$arrValues ) {
     
      if ( TL_MODE == 'BE' ) return $strQuery;
      
      if ( $arrQuery['table']  == 'meine_tabelle'  ) {
          
           $arrValues = []; // Hier werden die Abfrage werte für die Database->execute() Funktion übergeben.
           return "SELECT * FROM …"; // Meine Abfrage
      }
      
      return  $strQuery;
  }
}
```

**Comment by bitkorn** [comment]
dieser Hook funktioniert bei mir nicht. Wenn ich statt catalogManagerOverwriteQuery den TL_HOOKS generatePage teste, funktioniert es mit meiner MyClass und deren execute().

"alnv/catalog-manager": "^1.20",

**Comment by bitkorn** [comment]
super, das funktioniert. Meine SQL Query konnte ich jetzt anpassen.
Aber nach dem Update funktioniert eine Taxonomie eines CM Moduls nicht mehr:
![contao_catalogmanager_product_taxonomie_onlymembergroupid](https://user-images.githubusercontent.com/4003643/41464729-98f63fe0-709b-11e8-9652-12506c7d6faf.png)

Vor dem Update hat es die Daten gefiltert. Nach dem Update filtert es alle Daten. Mache ich die Taxonomie raus, sehe ich wieder Daten.

**Comment by alnv** [comment]
Wenn du den `catalogManagerOverwriteQuery` Hook verwendest, überschreibst du auch die Taxonomie-Einstellungen.

Übrigens: Im `$arrQuery` Parameter werden die besagten "Taxonomie-Einstellungen" mitgegeben. Das bedeutet du kannst diese einbinden.

Siehe `$arrQuery['where']`.

Die SQL-Abfrage wird in der `SQLQueryBuilder` Klasse zusammengebaut: https://github.com/alnv/catalog-manager/blob/master/library/alnv/SQLQueryBuilder.php

Einen Fehler konnte ich nicht feststellen.

**Comment by bitkorn** [comment]
ah, ok. Weil ich der Query nichts abschneide (nur nach dem Asterisk hinzu füge) und in ``$arrQuery['where']`` nichts von der Taxonomie ist, liegt der Fehler wohl woanders.
dank dir
