### ISSUE TITLE
Merkliste zeigt keine Auswahlmöglichkeit im FE an

### ISSUE THREAD

**Issue by mueller-steinhauer** [alnv/catalog-manager#133]
Hallo zusammen,

Im FE zeige ich Paletten an die der User in eine Merkliste übernehmen soll.

![opera momentaufnahme_2018-06-15_143943_dev paul-klaes de](https://user-images.githubusercontent.com/40296986/41468366-08e28cba-70aa-11e8-9950-0342bbc54010.png)

Jetzt habe ich die Wishliste/Merklisten Erweiterung aktiviert und auch in der Listenansicht ausgewählt.
![opera momentaufnahme_2018-06-15_144247_dev paul-klaes de](https://user-images.githubusercontent.com/40296986/41468473-69d1f132-70aa-11e8-99b6-abe7480ccadc.png)
Leider zeigt er mir im Frontend nix an, in der Dokumentation kann man nicht erkennen was nach dem aktivieren passieren sollte im Frontend.

Ich gehe jetzt davon aus das man eigentlich eine checkbox oder ähnliches sehen sollte ?

Die Tabelle "pallets" ist eine kindtabelle von der Tabelle "articles" oder geht die Merklisten Funktion nur mit Elterntabellen ?

**Comment by alnv** [comment]
Womöglich hast du dein **ctlg_view_table** Template angepasst. Dadurch wird nichts angezeigt.

Überprüfe ob diese IF-Abfrage in deinem **ctlg_view_table** Template vorkommt:

``` php
<?php if ( $this->useWishlist ): ?>
     // …
```
Die selbe Abfrage sollte auch im **mod_catalog_table** Template vorkommen. Sollte es nicht der Fall sein musst du deine Templates entsprechend erweitern:

Siehe hier: 
https://github.com/alnv/catalog-manager-wishlist/blob/master/templates/ctlg_view_table.html5
https://github.com/alnv/catalog-manager-wishlist/blob/master/templates/mod_catalog_table.html5

Übrigens hier geht es zum Wishlist Repository: https://github.com/alnv/catalog-manager-wishlist.

Einen ähnlichen Task gibts bereits: https://github.com/alnv/catalog-manager-wishlist/issues/2

Bzgl. der Elterntabelle. Die Merkliste wird in der jeweiligen Listenansicht angezeigt. Egal ob es eine Kind oder Elterntabelle ist.
