### ISSUE TITLE
Filter mit Find in Set umkehren

### ISSUE THREAD

**Issue by Benjamin-Scherf** [alnv/catalog-manager#134]
Hallo,

Folgende Situation:
Im Filterfeld wird ein Datum eingetragen. Der Filter schaut in einer Tabelle, in der mehrere Daten mit Komma getrennt hinterlegt sind nach, ob das Datum existiert. Wenn der Filter jetzt eines der Daten in der Liste findet, zeigt er das Objekt an. 
Gibt es die Möglichkeit die Bedingung umzudrehen. Also wenn er eines der Daten findet wird das Objekt ausgeblendet.

Vielen Dank

**Comment by Benjaminscherf** [comment]
Vielen Dank

**Comment by Benjaminscherf** [comment]
Das selbe würde auch für NOT BETWEEN interessant sein. 
Vielen Dank

**Comment by Benjaminscherf** [comment]
Um das NOT BETWEEN / NOT FIND IN SET zu umgehen, hätten Sie für folgende Überlegung (Screenshot) eine Alternative. 

![image](https://user-images.githubusercontent.com/3870020/41910295-8b34f606-7949-11e8-83cd-03ff18413278.png)

**Comment by alnv** [comment]
Die "NOT" Operatoren kann ich bis v1.23/v1.24 umsetzen. Ich packe es auf die todo Liste. Ansonsten kannst du auch den "catalogManagerOverwriteQuery" Hook verwenden. Siehe #132 

Oder [Support Ticket](https://catalog-manager.alexandernaumov.de/support-ticket.html) erstellen.
