### ISSUE TITLE
Koordinaten übergeben

### ISSUE THREAD

**Issue by Neginjafari** [alnv/catalog-manager#135]
Hallo.

Ich arbeite mich durch den Katalog, um rauszufinden, ob er geeignet ist für mich. an einer Stelle komme ich nicht weiter, weiß jedoch nicht ob das ein Denkfehler ist. Es soll ein Elternkatalog (EK Bildungsinstitute) und ein Kindkatalog (KK Kurse) erstellt werden. Sowohle Elternkatalog als auch Kindkatalog soll im Frontend per Kartensuche dargestellt werden. Der User erstellt im Frontend sein Institut (EK) und beschreibt es mit Bezeichnung, Adresse, Kontakt, Öffnungszeiten etc.. Dann soll seinem Institut Kurse untergeordnet werden (KK). Soweit funktioniert es.

Da dem Institut ja eine Adresse zugeordnet wurde, kann das EK-Element gut per Kartensuche gefunden werden. Dem Kindelent, den Kursen muss nun aber auch jeweils eine Adresse nachgetragen werden. Ich habe es nun umständlich geschaft dem Kindelement die Latitude und die Longitude beim erstellen mit zu übergeben, das durch jeweils ein Select-Menü mit Datenbank-Auswahlliste und der Taxonomie. Erstellt der Kunde jetzt ein Kindelement werden die beiden Felder mitgespeichert. 

Das Problem entsteht wenn sich die Adresse des Institutes, des EK-Elementes ändert, dann ändern sich auch die Koordinaten. Jetzt muss jedes Kindelement neu geöfnet und gespeichert werden um den Datenbankeintrag zu aktualisieren. 

Gibt es eine Möglichkeit, dem Kindelement die Kooerdinaten des Elternkataloges auf einen einfachen Weg mitzugeben. Ich stehe da etwas auf dem Schlauch und würde mich über Hilfe freuen.

**Comment by alnv** [comment]
Für solche Fälle habe ich in der v1.22 eine Lösung implementiert.

Es gibt einen neuen Insert tag **{{CTLG_LIST}}**. Damit kannst du die Filterergebnisse der Eltern-Listenansicht auslesen und der Kind-Listenansicht übertragen.

z.B {{CTLG_LIST::?module=30&get=id&delimiter=,}} liefert alle IDs der Eltern-Listenansicht (gefiltert).

Erlaube Parameter:
**module** => _[Erwartet die Id der Eltern-Listenansicht]_
**get** => _[Eine Spalte die ausgegeben werden soll]_
**delimiter** => _[Trennzeichen]_
**if** => Liste an GET Parametern die Aktiv bzw. gegeben sein müssen, damit der Insert tag Ergebnisse liefert.

Vorausgesetzt  Eltern/Kind Listenansichten sind auf der selben Seite!

**Comment by Neginjafari** [comment]
Gibt es dazu ein Beispiel in der Demo?

**Comment by alnv** [comment]
Nein, auf der Demoseite gibt es keine vergleichbare Fallbeispiele. Die Dokumentation kommt noch.

Bei Fragen, kannst du dich an mich wenden.

**Comment by Neginjafari** [comment]
Vielen Dank

**Comment by Neginjafari** [comment]
Hallo, der instert tag funktioniert. 

Im Frontendediting-Bereich funktioniert alles. Ich habe eine Lise erstellt, welche über die Taxonomie
ID = {{CTLG_ACTIVE::pid}}
nur das eine gewünschte Eltern-Objekt ausgibt und die Koordinaten werden im Kind-Element übernommen.

Nutze ich nun jedoch ein verstecktes Feld und trage den Inserttag als Standard-Wert ein, so wird die Koordinate fest in die Datenbank geschrieben und es entsteht wieder das Problem, dass sich der Wert natürlich nicht ändert wenn sich z.B. im Elternkatalog die Adresse und somit auch die Koordinaten ändern.

Nutze ich ein normales Textfeld und trage den Inssertatg als Dynamischen Wert ein, wird der tag auch so in die Datenbank übernommen. 

Nun entsteht das Problem in der normalen öffentlichen Listenansicht. Dort werden ja alle Kinobjekte der Elterntabelle angezeigt (Beispiel wie oben - Die Kurse aller Institute). Dort übernimmt das Feld durch den Inserttag jetzt alle Koordinaten der einzelnen Elternobjekte. 

Eine Einschränkung der Liste macht an dieser Stelle auch keinen Sinn, da ja anfangs alle Objekte ausgegeben und erst später gefiltert werden sollen. 

Kann man das Insertag auf auf den Abruf seines direkten Elternobjektes beschränken?

**Comment by alnv** [comment]
Ich verstehe nicht ganz, wieso du die Koordinaten in die Kind Tabelle übertragen willst, wenn diese schon in der Elterntabelle zu finden sind. Da gibt es bessere Wege. Wenn du magst, kannst du mir ein [Support Ticket](https://catalog-manager.alexandernaumov.de/support-ticket.html) erstellen.

Jedenfalls soll der {{CTLG_LIST}} Insert tag als ein Filterwert verwendet werden nicht als Standardwert.

**Comment by Neginjafari** [comment]
Es gibt ein Elternkatalog Schulen
Nach den Schulen soll ein Nutzer suchen können. Schule in seinem Umfeld.

Jede Schule bietet Kurse an. Das ist der Kindkatalog. Mathe, Deutsch, Englisch
Die Kurse sind beschrieben. Datum, Länge, Lehrer, etc. 
Auch nach diesen Kursen soll ein Nutzer suchen können ohne die Schule zu berücksichtigen. 
Deutsch-Kurs in meinem Umfeld.

Ich finde keine Möglichkeit eine Liste anzulegen, welche mir die Kindelemente des Elternkataloges ausgibt und mich dabei nach Datum, Länge, Lehrer filtern lässt und gleichzeitig die Geokoordinaten des Elternkataloges berücksichtigt. 

Natürlich kann ich jedem Kurs eine Adresse hinzufügen, aber das schein ja überflüssig, denn die Adresse liegt ja schon im Elternkatalog. Adresse = Geokoordinaten.

**Comment by alnv** [comment]
Den CTLG_LIST Insert Tag kannst du dazu verwenden um an die Elternkatalog Daten ranzukommen. 

Wie gesagt, du kannst mir ein [Support Ticket](https://catalog-manager.alexandernaumov.de/support-ticket.html) erstellen oder E-Mail schreiben. Dort kann ich dir direkt helfen.

**Comment by alnv** [comment]
ups aus versehen geschloßen. Kannst gerne schließen, wenn alles geklärt ist :)

**Comment by alnv** [comment]
Solltest du weitere Hilfe benötigen, kannst du den Task wieder aufmachen.  Der **CTLG_LIST** InsertTag wird in diesem Demo Fallbeispiel aufgeführt: 
https://catalog-manager-demo.alexandernaumov.de/de/kurse
Siehe FE Modul: _CM Listenansicht: Kurse [DE]_
