### ISSUE TITLE
Backend CSS-Classes erweitern

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#136]
Oft hat man viele kleinere Optionen, die mit zweispaltiger Eingabemaske sehr lange Formulare prodzieren.
Beispiel Adresse:  "PLZ","Ort","Strasse", "Nummer"

Neben den Optionen "Zweispaltig" etc. wäre es gut, wenn man auch kleinere Felder mittels "w25" Klasse erstellen könnte (also dann "Vierspaltig" o.ä.)

**Comment by alnv** [comment]
Der Standard Theme von Contao unterstützt nur 2-Spaltige Eingabemasken.  Sollte es sich irgendwann  ändern, werde ich es nachrüsten.

**Comment by ricowe** [comment]
Wäre es nicht möglich, dass CM ein Backend cumstom CSS mitbringt?
Ds dürfte doch kein Problem sein und wenn man die Classes individuell benennt dürfte es auch keine Kollisionen geben.

**Comment by alnv** [comment]
Es würde mehr Sinn machen, wenn es im Core Theme implementiert wäre. Irgendwelche CSS Sachen will ich nicht machen.

Grundsätzlich kannst du deine eigene CSS einbinden und entsprechende Klassen erstellen.

Die Klassen kannst du über die **dcaconfig.php** vergeben:

$GLOBALS['TL_DCA']['my_table']['fields']['my_field']['eval']['tl_class'] .= ' w25';
