### ISSUE TITLE
Neuer Datensatz wird leer gespeichert und ist gleich sichtbar

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#137]
Wenn ich einen Datensazu anlege (Backend-Formular mit abhängigen Selects) wird bei der Auswahl der abhängigen Selects der Datensatz gespeichert, obwohl er noch nicht fertig ausgefüllt ist. Mir ist klar, dass es durch "Submit on change" nicht anders möglich ist. 

Könnte man nicht zur Abhilfe die Checkbox "Datensatz verstecken" automatisch aktivieren, bis man den Datensatz fertig speichert?

**Comment by alnv** [comment]
Du kannst es damit versuchen:

_system/config/dcaconfig.php_
`$GLOBALS['TL_DCA']['my_table']['fields']['invisible']['default'] = '1';`

**Comment by ricowe** [comment]
Klappt prima. Vielen Dank.
Gibt es da auch eine Möglichkeit, einen Datensatz beim Kopieren auf invisible zu setzen?
Sonst habe ich direkt nach dem Kopieren 2x den gleichen Datensatz online.

**Comment by alnv** [comment]
Wenn das oben nicht funktioniert, dann nicht. 

Mit Catalog Manager kannst du ganz einfach deine eigene Logik implementieren. Lege dir ein neues Feld "published" an und filtere deine Listenansicht danach. Das Standardverhalten kannst du deaktivieren. Siehe Catalog Einstellungen > Operatoren-Einstellungen > Aus/Einblenden Checkbox.
