### ISSUE TITLE
Select-Menü mit Auswahlliste ignoriert "0" als Wert

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#139]
Hallo! Mache ich was falsch? Ich habe mehrere Pflichtfelder mit Select-Menüs, die die Zahlen 0 bis 8 plus "Leerauswahl" zur Auswahl anbieten sollen (varchar(16) NOT NULL default). 

Da die Leerauswahl beim Pflichtfeld nicht als "Auswahl" durchgeht, hatte ich die Nullwerte dazu gesetzt. Wenn man die Formulare aufruft, wird aber die "0" nicht angezeigt, sondern nur die Zahlen 1 bis 8. Es funktioniert nur, wenn ich "none" statt "0" als Wert eintrage.

Liegt das am "NOT NULL", dass das Feld nicht nur nicht leer sein, sondern auch keine 0 enthaten darf? - Sorry, ich bin nicht so der MySQL-Guru ...

**Comment by alnv** [comment]
Das hat mit der Datenbank nichts zu tun (eher PHP). 

Die Wertspalte kann in dem Fall leer bleiben.
