### ISSUE TITLE
AJAX beim refresh der Seite unterstützen

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#14]
Wenn Filter im Frontend genutzt werden, so sollten Daten auch via AJAX in die Seite zurücklaufen. Somit entfällt der hässliche Reload der kompletten Seite.

**Comment by alnv** [comment]
Ich setze es auf die Todo Liste :)

**Comment by codiso** [comment]
Gibt es denn schon jetzt eine Möglichkeit selbst dies per AJAX zu triggern?

**Comment by alnv** [comment]
Nicht vollständig ausgebaut. Man kann bereits jetzt die Liste als JSON zurück liefern lassen. 
Siehe **Catalog Listenansicht** > **Format-Einstellungen** > Als Array ausgeben > **application/json Header**

Man müsste es noch so erweitern, dass die Liste automatisch beim AJAX Request ein JSON zurückgibt. Das gleiche sollte auch für den Filterformular möglich sein.

**Comment by alnv** [comment]
In der v1.3 habe ich eine Lösung dafür implementiert. Alles noch experimentell und in der Wildnis noch nicht getestet :)

**Schritt 1:**
In der Listenansicht sowie dem Filterformular kann man "_Ajax_" freischalten. Das ganze liegt unter der _JSON Einstellungen_ Palette. Siehe Screenshots:
![install-error](https://catalog-manager.alexandernaumov.de/files/theme/media/github/FE-Module-Ajax.png)
![install-error](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Filterform-Ajax.png)

Wenn wir Ajax aktiviert haben können wir im **2. Schritt** unsere Ajax Request abfeuern.

_fe_page_ Template:
```
<script async>
   (function(){
      var xhttp = new XMLHttpRequest();
         xhttp.onreadystatechange = function() {
            if ( this.readyState == 4 && this.status == 200 ) {
               console.log( JSON.parse(this.responseText) );
            }
         };
         xhttp.open( "GET", "{{env::request}}{{CTLG_FILTER_VALUES::POST}}&ctlg_ajax=1&ctlg_module=3", true );
	xhttp.setRequestHeader( 'HTTP_X_REQUESTED_WITH', 'XMLHttpRequest' );
	xhttp.send();
			
   })();		
</script>
```
Wichtige Parameter:
**ctlg_ajax** => Damit signalisieren wir, dass wir ein Ajax Request gesendet haben. Einige Server erkennen auch ohne Parameter wenn es sich um ein Ajax Request handelt. Allerdings nicht alle.
**ctlg_module** => FE Modul oder Filterformular, den wir ansprechen wollen. Es wird die Datensatz ID übergeben.

`this.responseText` liefert ein String den wir zum JOSN Objekt umwandeln können. Dort liegen alle wichtigen Informationen…

Ich werde noch eine ausführlichere Dokumentation dazu schreiben.
