### ISSUE TITLE
Rechtevergabe für bestimmte Felder

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#141]
Hallo,

ist es möglich, bestimmte Felder im Catalog nur für bestimmte Benutzer/Gruppen freizugeben?
Also so, dass z.B. der Administrator alle Felder eines Catalogs bearbeiten kann, ein Redakteur jeoch nicht.
Habe dazu in der Doku nichts gefunden.

**Comment by alnv** [comment]
Ist möglich aber ist undokumentiert. Im Grunde funktioniert es wie bei Core Modulen. Nur das du den Catalog erst für die Berechtigungen freigeben musst. Siehe hier: https://github.com/alnv/catalog-manager/issues/90

Die einzelnen Felder müssen ausgeschloßen werden. Diese Einstellung findest du unter den jeweiligen "Feld-Einstellungen" in der Palette "Panel Layout-Einstellungen" > "Feld ausschließen".
