### ISSUE TITLE
Individuelle Felder erstellen mit Name/Wert

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#142]
Hallo,
ich möchte für einen Kunden die Möglichkeit bieten, im Catalog Angebotsdaten individuell einzustellen (und daraus z.B. eine HTML-Tabelle zu generieren). Dazu wäre eine Möglichkeit gut, mit der man einen Datentyp mit 2 Felder hat (Feldname / Feldwert) und diese mittels Plus-Funktion entsprechend der gewünschten Anzahl hinzufügen kann.

So etwa:
![felder_ctlg_add](https://user-images.githubusercontent.com/37615273/42844284-c4b2a8cc-8a12-11e8-8410-81cf77cfed5e.jpg)

**Comment by alnv** [comment]
Grundsätzlich möglich, alle Felder lassen sich in der dcaconfig.php anpassen und modifizieren. Bei Gelegenheit kann ich ein Anleitung zu diesem Thema erstellen. 

Ansonsten können wir es auch über den [Support Ticket](https://catalog-manager.alexandernaumov.de/support-ticket.html) lösen.

**Comment by ricowe** [comment]
Ich habe jetzt lange rumprobiert, aber noch keine nutzbare Lösung gefunden.
Ist es ggf. möglich, den MultiColumnWizard dafür zu nutzen? Wenn ja, wie?

https://github.com/menatwork/MultiColumnWizard

**Comment by ricowe** [comment]
Klasse! Läuft prima mit dem keyValueWizard. Ist das auch irgendwo dokumentiert?
Gibt es da ggf. noch weitere Wizards?

Danke ;-)

**Comment by ricowe** [comment]
Der keyvaluewizard speichert die eingegebenen Daten in json.
Allerdings kann ich die Daten nicht sauer weiterverarbeiten?!
In der Datenbank steht ein (invalides) JSON:

`a:1:{i:0;a:2:{s:3:"key";s:11:"Gesamtpreis";s:5:"value";s:13:"123456,78";}}`

Was muss ich tun, um diese Daten nutzen zu können?
Mit json_decode() komme ich hier nicht weiter.

**Comment by alnv** [comment]
Es ist kein JSON. 

Du kannst unter Contao 4.4 folgende Funktion verwenden: \StringUtil::deserialize()
Bei Contao 3 ist es nur deserialize().

Siehe hier:
https://github.com/contao/core-bundle/blob/master/src/Resources/contao/library/Contao/StringUtil.php

**Comment by ricowe** [comment]
Danke, funktioniert prima. 
Da muss man auch erstmal drauf kommen.

Für solche Fälle gibt es keine Dokumentation, oder?

**Comment by tognit** [comment]
Aber funktioniert das auch bei einer Modifizierung? Habe es bis jetzt noch nicht geschaft!
