### ISSUE TITLE
Contao Formulargenerator Select-Menü mit Inhalten aus einer Catalog-Tabelle

### ISSUE THREAD

**Issue by ricowe** [alnv/catalog-manager#143]
Ist es möglich, im Contao Formulargenerator ein Select-Menü mit Inhalten aus einer Catalog-Tabelle zu füllen? Ich habe es schon mit einem Modifizierer-Catalog probiert, finde aber nicht den richtigen Ansatz.

**Comment by alnv** [comment]
Du benötigst ein eigenes Eingabefeld. Mit dem Modifizierer kommst du nicht weit.

Gerne ein [Support Ticket ](https://catalog-manager.alexandernaumov.de/support-ticket.html)an mich.
