### ISSUE TITLE
Fine uploader Frontendediting

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#145]
Wir der Fine Uploader im Frontend benutzt, dann funktioniert der erste Upload. Öffnet man das Objekt erneut um den Eintrag zu Editieren, werden beim erneuten abspeichern die Bilder wieder gelöscht. Es wird also zwingend, bei jedem Editieren die Bilder ebenfalls neu hochzuladen.

**Comment by alnv** [comment]
Seltsam früher war es nicht so. Wo möglich  hängt es mit einem Contao Update zusammen. 

Bugfix gibt es in v1.23

**Comment by Benjaminscherf** [comment]
Supper

**Comment by kissinger999** [comment]
Das ist immer noch so, zumindest bei mir

**Comment by alnv** [comment]
Funktioniert es auch mit dem "standard" Upload nicht? 
Hast du in der Listenansicht "Hochgeladene Dateien speichern" aktiviert?

**Comment by kissinger999** [comment]
Beim Standard-Upload, also bei deaktiviertem FineUploader das gleiche. 
Ja, in der Listenansicht ist "Hochgeladene Dateien speichern" aktiviert.

**Comment by mucka-veli** [comment]
In Contao 3.5.38 habe ich momentan dasselbe Problem. Das Häkchen bei "bestehende Dateien erhalten" ist gesetzt. Der Unterschied: nutze ich den Standard-Upload funktioniert alles wie es soll.

**Comment by alnv** [comment]
Welchen SQL-Datentyp hast du bei dem Upload ausgewählt?

**Comment by janoschbatschi** [comment]
Habe hier das selbe Problem bei SQL-Datentyp blob (C4.4.38). 

Bei Wechsel auf binary kommt folgende Fehlermeldung:
An exception occurred while executing 'UPDATE table1 SET `files`='a:1:{i:0;s:16:\"�b�j�����X!��i\";}' WHERE id='2'': SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'files' at row 1

**Comment by alnv** [comment]
Soweit ich sehen kann, hast du serialisierte arrays im Speicher. Der Binary Datentyp kann nur einzelne Bilder speichern, darüberhinaus (z.B für Galerien) benötigst du ein "blob".

**Comment by janoschbatschi** [comment]
Alles klar, aber gibt es mittlerweile eine Lösung für das Problem, dass beim Editieren, alle vorher upgeloadeten Bilder wieder gelöscht werden? Es ist zur Zeit zwingend notwendig, bei jedem Editieren die Bilder ebenfalls neu hochzuladen.

**Comment by alnv** [comment]
Wenn  man ein leeres Upload Feld speichert werden keine Bilder überschrieben bzw. gelöscht. Zumindest ist das Problem seit v1.23 gelöst.

**Comment by martin-hofmann-netprofit** [comment]
Hab leider das Problem auch (Contao v4.7.5 - Catalog Manager v1.30). Bei jedem Upload über das Frontendediting verliert der Catalog Manager alle alten Uploads (PDFs,Doc,Docx) die zugewiesen waren. Die Dateien bleiben aber in der Dateiverwaltung noch erhalten.

**Comment by alnv** [comment]
Beim erneuten Upload werden alte Dateien (Uploads) überschrieben. Es findet keine Zusammenführung von alten und neuen Uploads statt oder werden bei dir Uploads generell gelöscht auch wenn keine neuen Dateien hochgeladen werden? Das war vorhin das Problem, das wurde in der v1.23 behoben. In der v1.30 kann ich kein Upload Problem feststellen. Siehe https://demo.catalog-manager.org/de/vereinsmitglieder/edit/thomas-gebauer?act14=edit&id14=5

Einen automatische Löschung von Dateien finden nicht statt.

**Comment by martin-hofmann-netprofit** [comment]
Ne, das erneute leere abspeichern, nachdem nichts geändert wurde, funktioniert bei mir, wie es soll.
Hab aber das gleiche Problem wie @janoschbatschi , dass alle Dateien verloren gehen, wenn beim editieren ein weiteres Bild zu den schon vorhandenen zwei drei Bilder hochgeladen wird.
Ist das ein Bug oder kann man hier mit einer Änderung/Anpassung rechnen?

**Comment by alnv** [comment]
@martin-hofmann-netprofit du kannst mir dazu ein neues Ticket anlegen. Wenn es Akut ist gerne auch ein Support Ticket: https://catalog-manager.org/support-ticket.html
