### ISSUE TITLE
Routing verwenden führt zu Fehler im Frontendediting

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#146]
Es ist ein sehr komisches Problem aufgetreten. Etwas kompliziert. 
Es existiert:
 
Katalog (Bezeichnung, Stadt etc.)

    Öffentliche Seite Liste 
    Öffentliche Seite Details (Master & Routing aktiviert. Parameter z.B. Stadt + auto item)

    Interne Seite Liste (Frontendediting mit Benutzerberechtigung)

In dieser Konstellatioon, kommt es zu dem Fehler, dass nach klicken auf **bearbeiten** in der
"internen Seite Liste" eine 404 Seite kommt. 

Umgehen, kann man das Problem in dem im Modul "interne Seite Liste FE EDIT" die allgemeine Weiterleitung zu der Detailseite deaktiviert, oder auf eine andere Seite umleitet, in der das Routing nicht gesetzt wird.

Ich hoffe das war verständlich.

**Comment by alnv** [comment]
Grundsätzlich muss das selbe Routing in der internen Seite sein wie auf der öffentlichen Detailseite.

**Comment by Benjaminscherf** [comment]
Hallo Alexander,

ich habe dir zwei Mails gesendet mit Zugangsdaten und Erläuterung.

**Comment by Benjaminscherf** [comment]
Zum Routing:

Die Liste mit Editing im internen Bereich, leitet auf die Selbe Detailseite wie im öffentlichen Bereich weiter. Die 404 Seite kommt aber beim klick auf die Bearbeitungsansicht (Editing). Die Listenseiten auf der das Editing stattfindet haben ja kein Routing.

**Comment by alnv** [comment]
Die Seite wo sich die interne Liste befindet benötigt ebenfalls ein Routing. Dort müssen die selben Parameter eingetragen sein wie auf der Detailseite. Du kannst diese auch im Template setzen…

**Comment by Benjaminscherf** [comment]
Ok das habe ich getan und es funktioniert. 
Das war nicht voraus zu ahnen.
Vielen Dank
