### ISSUE TITLE
Baumstruktur für Kategorien im Backend verwenden

### ISSUE THREAD

**Issue by denniserdmann** [alnv/catalog-manager#147]
Beispiel: 
Ich habe 2 Kataloge. Katalog A sind die Kategorien für Katalog B. 
Katalog A sieht zum Beispiel so aus:

1. Elektotronik
1.1. Smartphones
1.2. Tablets
2. Garten
2.1. Rasen
2.2. Beet usw.

Katalog A habe ich als Baumstruktur angelegt. Jetzt würde ich gerne die Darstellung aus Katalog A auch bei der Auswahl der Kategorie in Katalog B nutzen. Aktuell finde ich nur Radio-Buttons, Checkbox-Menü (mit Mehrfachauswahl) und Select (inkl. Chosen). Gibt es eine Möglichkeit, dass ich eine Art Page-Picker verwenden kann, in dem ich durch die Struktur gehen kann und dort wahlweise *Smartphones* oder *Elektronik* + *Smartphones* auswählen kann? 

Ohne die Hierarchie fürchte ich, dass es sehr unübersichtlich wird.
Oder gibt es andere Ansätze, um dies zu lösen?

**Comment by alnv** [comment]
Diese Möglichkeit existiert nicht. 

Für solche Fälle verwende ich meistens zwei Select-Menüs die abhängig voneinander ausgewählt werden können.

Quasi ein Select-Menu für Elektotronik/Garten und ein Select-Menu für die jeweiligen Unterpunkte.

**Comment by denniserdmann** [comment]
Ich habe es jetzt über die voneinander abhängigen Select Felder gelöst. Allerdings ist die Verwendung doch stark eingeschränkt. Da ich bei der Filterung der Kind-Elemente nur nach PID filtern kann, muss dieser entweder im Alias vorkommen, oder ich verwende direkt die PID. Das bedeutet aber auch, dass ich im Frontend nicht mehr einen suchmaschinenfreundlichen Alias verwenden und auswerten kann, bzw. keine Vergleiche zum Alias aus der URL herstellen kann.

Was allerdings helfen würde wäre ein Insertag: {{FELDNAME::PID}}
Gibt es so etwas in der Art? Habe auch mit Simple-Tokens experimentiert, aber auch da ohne Erfolg.

**Comment by alnv** [comment]
Wo genau willst du den  {{FELDNAME::PID}} Insertag verwenden?

Es lässt sich bestimmt auch anders lösen. Aber dazu müsste ich mich näher mit deinem Aufbau/Projekt beschäftigen. Wenn du magst können wir es über den Support Ticket abwickeln:  https://catalog-manager.alexandernaumov.de/support-ticket.html

**Comment by denniserdmann** [comment]
Vielen Dank für den Hinweis. Ich benötige erst noch eine Freigabe, melde mich aber dann über das Support-Ticket, sollten wir die Variante so umsetzen.
