### ISSUE TITLE
Filtern nach Werten aus mehreren Tabellen "Join"

### ISSUE THREAD

**Issue by mueller-steinhauer** [alnv/catalog-manager#148]
Hallo,

ich versuche gerade einen Filter zu erstellen der in der Taxonomie auf zwei Tabellen zugreifen kann, ist die möglich ?

Folgenden Fall habe ich:
Tabelle Artikel und Tabelle Bestellungen

Jetzt gibt es ein Modul wo ich die beiden Tabellen "joine" und aus beiden die Daten ziehe und in einer Tabelle anzeige.
![opera momentaufnahme_2018-07-25_095220_dev paul-klaes de](https://user-images.githubusercontent.com/40296986/43186921-7398b16e-8ff0-11e8-80f9-911078b7fcce.png)

Jetzt möchte ich gerne das der Filter den ich als Modul angelegt habe auf die Felder von beiden Tabellen zugreift, derzeit kann ich in der Taxonomie noch nicht auf die Felder von der Tabelle Artikel zugreifen nur auf die Felder der Tabelle Bestellungen

**Comment by alnv** [comment]
Verknüpfte Spalten kann über den normalen Weg nicht filtern.

Eine Lösung wäre es eine eigene Abfrage zu definieren:

``` php

// config.php
$GLOBALS['TL_HOOKS']['catalogManagerOverwriteQuery'][] = [ 'myClass', 'myMethod' ];

class myClass {

   public function myMethod( $arrQuery, $strQuery, $arrValues ) {

     return 'SELECT * FROM …'; // Deine individuelle Abfrage
  }
}
```

**Comment by mueller-steinhauer** [comment]
Ok danke dir, dann gehe ich erstmal den weg und binde datatables.js ein und gehe bei der suche übers Frontend

**Comment by mlwebworker** [comment]
Ist der Stand noch immer so, dass eine Filterung verküpfter Spalten über den Filtergenerator nicht möglich ist?
Die eigene Abfrage müsste ich in einer eigenen Erweiterung machen?

**Comment by alnv** [comment]
Es gibt noch keine Lösung dafür. Ja, dazu bräuchtest du eine eigene Erweiterung.

**Comment by robvis** [comment]
Hallo,
Ich habe dies versugt, aber bekomme die Fehler "_Exception\\ClassNotFoundException(code: 0): Attempted to load class \"MyDatabaseActions\" from the global namespace.\nDid you forget a \"use\" statement"_
Irgendwo geht is fasch im config.php oder meine Class.
Ich nutze Contao 4.4.38
config.php is in: system\modules\mymodule\config
class ist in: system\modules\mymodule\

**config.php:**
_<?php
$GLOBALS['TL_HOOKS']['catalogManagerOverwriteQuery'][] = [ 'MyDatabaseActions', 'readDbTable' ];

**Class:**
<?php
namespace CatalogManager;
class MyDatabaseActions {
   public function readDbTable( $arrQuery, $strQuery, $arrValues, $table, $key ) {
   if ( TL_MODE == 'BE' ) return $strQuery;
     return 'SELECT * FROM ctlg_campagne WHERE campagne = $key'; // Deine individuelle Abfrage
  }
}

Hoffe das jemand mich helfen can.

**Comment by robvis** [comment]
**Class:**
<?php
namespace CatalogManager;
class MyDatabaseActions {
   public function readDbTable( $arrQuery, $strQuery, $arrValues, $table, $key ) { 
   if ( TL_MODE == 'BE' ) return $strQuery;
     return 'SELECT * FROM ctlg_campagne WHERE campagne = $key'; // Deine individuelle Abfrage
  }
}

**Comment by alnv** [comment]
Vermutlich hast du die Klasse nicht im Autoloader definiert. Siehe https://docs.contao.org/books/cookbook/de/Autoloading.html

**Comment by robvis** [comment]
Hallo Alexander,
Iche habe jetzt:
- die Classe in alnv/catalog-manager/library/alnv/ geplatzt
- im Autoloader angepasst
- TL_HOOKS in die alnv/catalog-manager/config/ die config.php angepasst

Aber ich denke, dass ich etwas falsch mache. Ich rufe die Function readDbTable an vom catalog_view_detail template. Jetzt bekomme ich ein Fehler auf die "namespace".

Meine situation ist we hierunten erklaert:
-Producten Tabelle met Productnummer und Standard Preise
-Campagne Tabelle met Campagne_id, Datumvon und Datumbis
-Preis Tabelle mit Reference nach Productnummer und campagne_id
Jetzt will ich die richtige Preis schauen von Heute.

Es ist moeglich die Preise Tabelle als Kind zo benennen vom Product Tabelle.
Aber die Preise Tabelle ist auch eind Kind vom Campagne Tabelle.
(Preise tabllen sind ja verknuepft an Product Tabelle (Productnummer), aber ich kan nicht tiefer nach Campagne Tabelle weiter knuepfen).
When Ich die Preise Tabelle Record habe, moechte Ich die Campagne Tabelle lesen mit Campagne_id vom Preise Tabelle.
(Ich hoffe, dass es noch Klar ist)
