### ISSUE TITLE
Export :: XML oder JSON

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#15]
Export von Daten des Managers für weitere Verarbeitung per XML oder JSON.

**Comment by alnv** [comment]
Sollte kein Problem sein. Sobald Catalog v1.3 fertig ist setze ich mich dran.

**Comment by codiso** [comment]
Cool, ich danke Dir schon mal vielmals für Dein Engagement :-D

**Comment by alnv** [comment]
Ich werde zuerst eine JSON und CSV Export/Import Funktion implementieren. Im späteren Verlauf auch XML.

Bis zum Release kann es noch dauern…

**Comment by Schmidty2** [comment]
+1

**Comment by alnv** [comment]
Entsprechende Erweiterungen ist da: Export Typen werden nach und erweitert je nach Nachfrage.
Siehe: [Catalog Manager Export](https://github.com/alnv/catalog-manager-export)

**Comment by alnv** [comment]
Bzgl. Export-Typen oder sonstigen Features bitte hier [melden](https://github.com/alnv/catalog-manager-export/issues).
