### ISSUE TITLE
Metadaten aus Dateiverwaltung übernehmen

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#150]
Es wäre schön, wenn wie in Contao 4 die Metadaten für Bilder aus der Dateiverwaltung übernommen werden und die Möglichkeit zum Überschreiben dieser Daten gegeben ist.

**Comment by alnv** [comment]
Solange Catalog Manager an Contao 3.5 gekoppelt ist, kann ich es nicht umsetzen.

Erst machbar bei Catalog Manager 2.0.

**Comment by mlwebworker** [comment]
Danke für die Info.

**Comment by Fanni-Portier** [comment]
Ich habe das Thema jetzt auch bei einer alten Contao 3.5 Seite.
Gibt es da mittlerweile eine Lösung?

**Comment by mlwebworker** [comment]
Für Contao 3.5 wird sich da sicher nichts ändern. Contao 3.5 wird nicht mehr supported und sollte upgedated werden.. 
Der Catalog Manager 2.0 wird dann folgerichtig auch nicht mehr mit Contao 3.5 kompatibel sein.
