### ISSUE TITLE
Hinweis bei Installation der Erweiterung in Contao 4.5

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#151]
Bei der Installation der Erweiterung in Contao 4.5 erhalte ich folgenden Hinweis:
`Using config.component-dir has been deprecated. Please use extra.contao-component-dir instead`.
Als Nichtentwickler weiss ich nicht wie wichtig das für die Zukunft ist.

**Comment by alnv** [comment]
Das ist nicht weiter schlimm. Dazu genügt eine kleine Anpassung in der composer.json:

``` js
"extra": {
   "branch-alias": {
       "dev-4.4": "4.4.x-dev"
   },
   "contao-component-dir": "assets"
}
```

``` js
// config block kann gelöscht werden
"config": {
    "component-dir": "assets",
}
```

Ich habe gesehen, dass es im Contao 4.6 bereits behoben ist. Daher einfach ein Update abwarten :)

**Comment by mlwebworker** [comment]
Super! Danke für die Info.
