### ISSUE TITLE
Eltern-Kind-Tabelle

### ISSUE THREAD

**Issue by larhansen** [alnv/catalog-manager#154]
Hallo
Ist das möglich eine Kindtabelle in einer anderen Tabelle als Elterntabelle zu verwenden?
Im Projektaufbau sieht es dann so aus, dass aus einer Kundenliste eine Tabellenübersicht zu den jeweiligen Aufträgen des Kunden entsteht. Anschießend soll zu einzelnen Aufträgen eine Übersicht mit Auftragsdateien zu sehen sein.
Vielen Dank im Voraus!

**Comment by alnv** [comment]
Das ist möglich.  Siehe Demo https://catalog-manager-demo.alexandernaumov.de/de/vereine.html

Jedes Verein hat ein Link zu den Vereinsmitgliedern und Vereinstrainern.

Hier die Doku dazu: https://catalog-manager.alexandernaumov.de/dokumentation/catalog-manager-tabellen-beziehungen.html
