### ISSUE TITLE
Bei Listenansicht auf Indexseite wird kein Zurück-Link erzeugt

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#156]
Wenn ich eine Listenansicht auf der Indexseite (Alias index und damit nur Domainname als URL) mit Detailweiterleitung habe, wird trotz angehaktem "Zurück-Link erstellen" kein Link angezeigt. Die Variable "goBacklink" bleibt in dem Fall leer. Sobald ich den Seitenalias ändere funktioniert es problemlos.

**Comment by alnv** [comment]
Ist gefixt in v1.23

**Comment by mlwebworker** [comment]
Danke
