### ISSUE TITLE
Javascript errors

### ISSUE THREAD

**Issue by daniel-nemeth** [alnv/catalog-manager#159]
Hi,
ich habe einen Catalog für Google-Maps. Nun habe ich die folgenden Fehlermeldungen in meiner Konsole:

<img width="1418" alt="screen shot 2018-10-16 at 11 34 34" src="https://user-images.githubusercontent.com/5083254/47006984-7e77ff80-d137-11e8-9d02-cdb2bc2f52f3.png">

Der API-Key wurde korrekt angelegt. Somit nehme ich an das dieses Problem nicht mit der Erweiterung zusammenhängt. Jedoch sagt er mir dass die API mehrmals verwendet wird.

Von den drei Markern werden auch nur 2 angezeigt, jene die als Entity angelegt sind.

[Hier](http://c46.daniel-nemeth.com/einsatzscreen.html) ist mein Test online.

Vielen Dank,
LG Daniel

**Comment by alnv** [comment]
Du hast das Script 2 mal auf deiner Seite eingebunden. Siehe Screenshot.
![](https://catalog-manager.alexandernaumov.de/files/air-theme/media/github/multiple-map-js.png)

Wenn du das obige Script entfernt, sollte der Fehler verschwinden.

**Comment by daniel-nemeth** [comment]
Danke, das war es. Das Problem war dlh_googlemaps.
Ich wusste nicht, dass ein Code von dlh_googlemaps eingebunden wird, obwohl keine Map in die Seite eingebunden wird. 

Vielen Dank und sorry für die Umstände!
