### ISSUE TITLE
Catalog Manager & Notification Center

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#16]
Ich habe im NC drei Benachrichtigungen eingerichtet vom Typ "Catalog Manager: Frontend Editing löschen/erstellen/bearbeiten" und in den Sprachenmodulen im Mailbody die Feldnamen-Tokens aufgelistet (##field_*##). Verwendet wird das vorgegebene Template "mail_default". 

Im FE-Modul für die Listenansicht habe ich unter Frontend-Editing-Einstellungen die drei NC-Benachrichtigungen ausgewählt. Eine Frontend-Editing-Seite ist nicht definiert.

Beim Ändern eines Datensatzes bekomme ich auch pronto eine Benachrichtigungsmail, allerdings mit den Tokens und nicht mit Feldwerten.

**Comment by alnv** [comment]
Für Feldwerte gibt es diese Tokens:
##clean_*## => Gibt ein formatieren Wert zurück
##raw_*## => Gibt den tatsächlichen Datenbank Wert zurück
##field_*## => Gibt die Feld Einstellungen zurück. Wie Title, Description etc.

Wenn du ein Update machst, gibt es noch zusätzliche tokens:
##rawOld_*##
##cleanOld_*##

**Comment by Anke** [comment]
Dankeschön, das funktioniert jetzt mit ##raw_*##, was aber beim Notification-Typ "Catalog Manager: Frontend Editing löschen" als nicht unterstützt gemeldet wurde; dort wurde ##rawOld_*## angeboten.

Der Token ##field_*## gab bei einer Datensatzänderung gar nichts zurück, er erschien als plain text in der Mail.

**Comment by Anke** [comment]
Das ist ja eine coole Sache, dass man mit der Mailbestätigung mit ##raw_*## und ##rawOld_*## die vorgenommenen Änderungen nachverfolgen kann!!!

Bei ##clean_*## bzw. ##cleanOld_*## verstehe ich noch nicht, was unter "formatiert" zu verstehen ist.

**Comment by alnv** [comment]
raw => ist immer das was tatsächlich in der Datenbank steht. Meistens irgendwelche Keys.
clean => gibt die hinterlegten Labels zurück also ein lesbares Format…

Nehmen wir an du hast eine Select Box mit folgenden Werten:
"r" => "Red"
"g" => "Green"
"b" => "Blue"

raw => gibt "r", "g" oder "b" zurück
clean => gibt "Red", "Green" oder "Blue" zurück
