### ISSUE TITLE
Frage: Taxonomy/Filterung im FE & Feld-Abhängigkeiten im BE

### ISSUE THREAD

**Issue by daniel-nemeth** [alnv/catalog-manager#160]
Hallo,
ich bin gerade beim Umstieg von MetaModels auf deine ausgezeichnete Erweiterung!
Nun hätte ich die folgenden beiden Fragen.

1. Ich habe einen Catalog für Termine. Dazu habe ich ein Listenmodul erstellt. Soweit wird alles korrekt angegeben. Nun möchte ich nur Einträge zeigen, deren Startdatum in der Zukunft liegt. Dazu habe ich im Modul folgendes eingestellt:

![screen shot 2018-10-23 at 13 12 18](https://user-images.githubusercontent.com/5083254/47357010-e2fe0600-d6c5-11e8-9982-f7486ea89838.png)

Das Feld startdate ist vom Typ "Datum", und die Checkbox "Timestamp" ist aktiviert.
Wenn ich den Operator auf "Lower" ändere zeigt er alle Beiträge an, bei ändern auf "greater" oder "greater then" nichts mehr.

2. Ich habe ich Backend eine Checkbox. Beim aktivieren dieser Checkbox würde ich nun gerne ein Fieldset einblenden, oder nur diverse Felder. Ist dies irgendwie möglich?

Vielen Dank!

**Comment by alnv** [comment]
Hallo Daniel, danke für dein Feedback :)

1.) Statt {{date::U}} kannst du {{CTLG_TIMESTAMP::?add=604800}} verwenden. Mit dem CTLG_TIMESTAMP Insert Tag kannst du rechnen z.B ?add=604800. Das entspricht heute + 7 Tage.
Ein Tag sind (60 * 60) * 24. Also ganz normale Unixzeit.

2.) Diese Möglichkeit gibt es nicht. Zumindest kann man es nicht zusammen klicken. Mit einer entsprechenden Änderungen im "DCA" wird es schon gehen.

**Comment by daniel-nemeth** [comment]
Danke für die rasche Antwort Alex!
Get der Inserttag auch ohne eine Zeit hinzuzufügen? Ich würde gerne den jetzigen Zeitpunkt nehmen.
Reicht da ein {{CTLG_TIMESTAMP}} ?

Vielen Dank!

**Comment by alnv** [comment]
Ja, ein {{CTLG_TIMESTAMP}}  reicht aus.

**Comment by daniel-nemeth** [comment]
Funktioniert wunderbar!

Vielen Dank!
