### ISSUE TITLE
Möglichkeit zum "Clear name" umbennen

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#161]
Hallo!

Ich hätte einen Vorschlag zum Feld "Clear name".
Ideal wäre es, wenn man dieses direkt beim Anlegen des Kataloges, auf Wunsch, benennen könnte.

Hier ein Beispiel:
![renameclearname](https://user-images.githubusercontent.com/5083254/47411196-4476b100-d768-11e8-8ca8-ba0a354aeb9f.PNG)

Natürlich müsste man das Feld umgestalten (z.B. mit MCW), damit man im ersten Feld ein Select mit sämtlichen Sprachen hat, im zweiten Feld das Textfeld für den Wert.

Gerne kann ich auch bei der Umsetzung behilflich sein. Dazu bräuchte ich nur ein paar Infos.

LG Daniel

**Comment by alnv** [comment]
Oder man macht es über die langconfig.php

``` php
if ( $GLOBALS['TL_LANGUAGE'] == 'de' ) {
   $GLOBALS['TL_LANG']['catalog_manager']['ctlg_club_member']['title'] = ['Irgendeine Bezeichnung…', 'Beschreibung…'];
}
```

Wenn ich eine Datenbank gestützte Übersetzung implementieren würde, dann für alle Felder.

**Comment by daniel-nemeth** [comment]
Es würde mehr um das Umbennen als um die Mehrsprachigkeit gehen.

Für uns ist es immer wichtig, so wenig als möglich in Dateien zu schreiben damit jederzeit jemand etwas umkonfigurieren kann.

Deshalb wäre diese Idee praktisch gewesen. Wir machen uns dazu einfach ein kleines Addon.

Danke für die Rückmeldung und Hut ab für diese geniale Erweiterung! Endlich kein Metamodel mehr.

**Comment by alnv** [comment]
Danke :) 

Ich pack es auf die todo Liste. Eventuell wäre es was für die v2.0 Version.
