### ISSUE TITLE
Detailansicht / Seitennummerierung Listenansicht

### ISSUE THREAD

**Issue by larhansen** [alnv/catalog-manager#162]
Hallo Alexander,
1.) ein Kunde bekommt all seine Aufträge als Tabelle angezeigt und leider ergibt sich in der Detailansicht immer wieder der selbe Fehler, es werden zwei Aufträge hintereinander angezeigt.
In der URL, die auf die Unterseite für die Detailansicht weiterleitet, wird der richtige Elias als Parameter übergeben, auch sonst haben die doppelt angezeigten Auftäge keine Gemeinsamkeiten. 
Vielleicht hast du eine Idee woher der Fehler kommt?

2.) Besteht eine Möglichkeit nach dem Bearbeiten eines Datensatzes wieder auf der Seite mit der selben Seitennummerirung zu landen und nicht auf Seite Nr.1

Viele Grüße
Larissa

**Comment by alnv** [comment]
Hi,

1.) Entweder gibt es doppelte Alias-Einträge oder auf der Seite befinden sich zwei Detailansicht Module. Bitte beachte, dass das Listenansicht Modul auch eine Detailseite anzeigen kann.
Schau in deiner Listenansicht unter der Palette "Detailansicht-Einstellungen" ob die Checkbox "Detailansicht nicht anzeigen" deaktiviert ist.

2.) Diese Möglichkeit gibt es nicht.  Aber eigentlich genügt es wenn man den letzten "page" Parameter zwischen speichert. Kann gut sein, dass ich da nachrüste.
