### ISSUE TITLE
Feature: Selectable backend template for formfields

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#163]
Hallo,
wie immer super Arbeit!

Ich hätte einen feature-request für das Backend. Es wäre nett, wenn man auch für das Backend ein Template auswählen kann, gleich wie es bei den Frontend-Formfeldern der Fall ist. So könnte man kleine optische Anpassungen im Backend vornehmen (z.B. eine Google Map via Inserttag einblenden, die mit Mausklicks Koordinaten in das lat und long Feld einfügt).

Vielen Dank!

**Comment by alnv** [comment]
Danke für dein Feedback. Soweit ich weiß gibt es im Backend überhaupt keine Template Struktur für Widgets. Das HTML wird direkt in der generate() Methode implementiert.

Wäre aber eine tolle Sache, wenn man einfach ein Template anpassen könnte statt eine Klasse zu duplizieren 👍
