### ISSUE TITLE
Alias Generierung bei Import

### ISSUE THREAD

**Issue by Falkgeist** [alnv/catalog-manager#164]
Hallo Alexander,

eigentlich ein Problem mit dem Importer, doch da ich dort keine Issues gesehen habe, ist es hier wahrscheinlich übersichtlicher aufgehoben:

Wenn ich eine CSV importiere, die Eindeutige Bezeichnung mit einem der Feldwerte belege (##album## in diesem Fall) und den Alias automatisch generieren lasse, passiert es, dass bei Duplikaten des Wertes aus 'album' zwei Datensätze mit gleichem Alias entstehen.

Ist es entweder möglich, beim Importieren automatisch "_1", "_2", etc. (oder ähnliches, aber auf jeden Fall fortlaufend) anzuhängen oder dies durch einen weiteren simple token zu erzwingen?

LG Falkgeist

**Comment by alnv** [comment]
Danke für Feedback. Das Problem kann ich nachvollziehen. Lässt sich bestimmt beheben :) 

Ich denke, in 1-2 Werktagen habe ich eine Lösung gefunden.

**Comment by Falkgeist** [comment]
Super, danke!

**Comment by alnv** [comment]
Ist Gefixt. Da es zum Zeitpunkts des imports noch keine ID gibt, wird eine "unique id" gesetzt, falls Alias besetzt ist.
