### ISSUE TITLE
Checkbox-Menü soll Auswahl aus einer Kindtabell beziehen wo der Wert über eine Select-Menü bezogen wird.

### ISSUE THREAD

**Issue by MarcoSchaedlich** [alnv/catalog-manager#166]
Hallo,

ich stehe gerade vor folgendem Problem. 
Ich möchte ein Checkbox-Menü einbinden und dabei Auswahliste einbinden -> Datenbank Auswahliste. Bei der Datenbank Auswahliste handelt es sich um eine Kindtabelle einer anderen Elterntabelle. Ich möchte aber nur die passenden Einträge der Kindtabelle anzeigen lassen. Dafür muß der User vorher über ein Select-Menü die Elterntabelle auswählen. Wenn er das tut speichert das Formular automatisch. Jetzt will ich unter Taxonomie das es den Wert auf das Select-Menü setzen um es mit der Kindtabelle abzugleiche. Was muß ich für ein Inserttag nehmen und den Wert des Select-Menüs zu erhalten. Geht das überhaupt?
Viele Grüße
Marco

**Comment by MarcoSchaedlich** [comment]
Habe gerade festgestellt das es mit dem insert-tag {{CTLG_ACTIVE::pa_work}} funktioniert. Leider aber nur im Frontend. Im Backend ändert sich nicht das Checkbox-Menü. Da steht immer da: "Keine Einträge gefunde".

**Comment by alnv** [comment]
Es genügt wenn du es einfach so einträgst {{pa_work}}. Das funktioniert im BE und im FE.
Mit {{feldname}} kannst du die irgendein Wert aus dem Active Record auslesen.

**Comment by MarcoSchaedlich** [comment]
Vielen Dank, hat funktioniert.
