### ISSUE TITLE
passenden Inhalte der Kindtabelle auf Detailseite der Elterntabelle ausgeben.

### ISSUE THREAD

**Issue by MarcoSchaedlich** [alnv/catalog-manager#168]
Hallo,
ich schaffe es nicht auf der Detailseite meiner Elterntabelle die dazugehörigen Inhalte von der Kindtabelle auszugeben. 
Wie muß ich denn da vorgehen?
Ich habe es mit dem Modul Detailansicht und Listenansicht probiert. Immer wenn ich ein zweites Modul der Kindtabelle hinzufüge bekomme ich einen Error.

**Comment by alnv** [comment]
Kurze Anleitung:

1.) Seitenstruktur
Auf der Detailseite sollte eine entsprechende Master Tabelle ausgewählt werden.

2.) Frontend Modul
In der Kind-Listenansicht kannst du den CTLG_MASTER Insert tag verwenden um die Liste zu filtern.
Feld => Elternelement
Operator => Gleich
Wert => {{CTLG_MASTER::id}}

Schau dir das Vereinsbeispiel (https://demo.catalog-manager.org/de/vereine/seepferdchen-crowd-stiftung) auf der Demoseite an. Der einzige unterschied ist, dass statt dem Elternelement das Mitglieder Feld verwendet wird.

**Comment by alnv** [comment]
Aktiviere bei deiner Kind-Listenansicht die Option " Detailansicht nicht anzeigen
". Damit Solltest du kein 404 bekommen.

**Comment by MarcoSchaedlich** [comment]
Das funktioniert, jetzt kommt keine Fehlermeldung mehr. Ich sehe jetzt die Listenansicht mit den passenden Kindeinträgen. Ich würde aber gern die Detailansicht der Kindeinträge sehen.

**Comment by alnv** [comment]
Dazu kannst du das Template anpassen. Du hast Zugriff auf alle Felder unabhängig von der Ansicht.

**Comment by MarcoSchaedlich** [comment]
Okay... es geht jetzt. Ich hatte noch als Tabelle darstellen an und Felder ausgewählt. Jetzt seh ich alles. 
Vielen Dank!
