### ISSUE TITLE
Modifizierer für tl_news

### ISSUE THREAD

**Issue by leycommediasolutions** [alnv/catalog-manager#169]
Bei Nutzung eines Modifizierers für tl_news erscheinen weder angelegte Felder noch eine erstellte Palette / Fieldset. Bei tl_calendar_events ist die Funktionsweise direkt gegeben. Ist das ggf. ein Bug oder kann auch contao-internen Gründen tl_news nicht modifiziert werden? Die Umgebung: Contao 4.6.8.

Trotzdem ein Spitzen-Werkzeug der catalog-manager.

Viele Grüße,
Ralph

**Comment by alnv** [comment]
Hallo Ralph, leider kann ich dein Problem nicht reproduzieren. Bei mir funktioniert es auch mit der tl_news Tabelle. 

Getestet unter Contao: 4.6.8

Wenn du magst, kannst du es auf der Demoseite testen und mir bescheid geben wenn es dort auch nicht funktioniert. Entsprechende Module wurden installiert.

**Comment by leycommediasolutions** [comment]
Besten Dank für Deine Info. Wir haben festgestellt, dass die pct_autogrid-Erweiterung der "Übeltäter" ist. Hast Du diesbezüglich eine Idee?

**Comment by alnv** [comment]
Leider kenne ich das Modul nicht…
