### ISSUE TITLE
Änderungsdatum wird im BE als Timestamp angezeigt

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#17]
Hallo Alexander,

das Änderungsdatum kann man sich im FE und/oder BE anzeigen lassen. Wir hätten gerne nur im BE eine Kontrolle, wann die Datensätze zuletzt bearbeitet wurden. Ist es möglich, im BE statt des Timestamps (wie im FE) Datum und Uhrzeit auszugeben?

VG
Anke

**Comment by alnv** [comment]
Verstehe ich es Richtig. 
- Wenn im FE ein Datensatz bearbeitet wird, soll kein Timestamp gesetzt werden?
- Des weiteren soll der Timestamp im BE im lesbaren Format ausgegeben werden?

**Comment by Anke** [comment]
Im FE ist alles paletti. 
Im BE sollte der Timestamp ebenfalls so geparst werden, dass er dem Datums-/Zeitformat in den Contao-Einstellungen entspricht.

**Comment by alnv** [comment]
Damit der timestamp im lesbaren format ausgeben wird, genügt es ein "flag" Attribute zu setzen.
system/config/dcaconfig.php öffnen und folgenden Code eingeben:
`$GLOBALS['TL_DCA']['_myCatalogTablename_']['fields']['tstamp']['flag'] = 5;`

*_myCatalogTablename_, bitte entsprechend ersetzen.

Damit wäre das Problem vorerst gelöst.

**Comment by Anke** [comment]
Kannst du das auch einrichten für custom Datumsfelder? (Als Workaround klappt es vorerst mit dem Flag.)

**Comment by andre5tz** [comment]
Leider ist das Ticket geschlossen, daher bitte wieder öffnen.

Die Sortierung klappt bei mir auch nicht, ich hätte aber beim Datum gerne das neuste oben, weil es für mich in dem Fall übersichtlicher ist.
Die Sortierung wie auch die Datumsanzeige sollte bitte so wie erwartet funktionieren :-)

**Comment by alnv** [comment]
Lieber neues Issues erstellen, da es hier um die Darstellung geht. 
Wie man im Backend nach Datum sortiert siehe hier #52
