### ISSUE TITLE
Simple Token ##id## bei "Dynamischer-Wert für eindeutige Bezeichnung".

### ISSUE THREAD

**Issue by MarcoSchaedlich** [alnv/catalog-manager#170]
Hallo,

ich habe den Simple Token ##id## im Feld "Dynamischer-Wert für eindeutige Bezeichnung" eingetragen. Wenn ich im Backend eine neuen Eintrag in der Tabelle mache wird die "id" im Feld "title" eingetragen, so wie es auch sein sollte. Erstelle ich einen Eintrag über das **Frontend** wird die "id" im Feld "title" nicht eingetragen und es steht darin "##id##".
Ist das ein bug oder muß ich beim Benutzen von ##id## etwas beachten?

**Comment by alnv** [comment]
Momentan ist es nur für das Backend angedacht. Ich packe es auf die todo Liste für FE.

**Comment by MarcoSchaedlich** [comment]
Okay, Danke!

**Comment by alnv** [comment]
So ich konnte das ganze nochmal prüfen. Das mit der ID kann im FE nicht funktionieren. Da die ID erst beim "Speichern" angelegt wird, anders als im Backend.

Eventuell löse ich das anders… muss mir dazu noch ein paar Gedanken machen-

**Comment by MarcoSchaedlich** [comment]
Danke, habe erst mal einen Workaround mit zwei Werten und einem timestamp gemacht. Muß der Wert zwingend eindeutig sein?

**Comment by alnv** [comment]
Nein. 
In erster Linie sollte es eindeutig für die Auffindbarkeit im System sein. Bezeichnungen können auch mehrmals vorkommen, dass ist an sich kein Problem. Allerdings kann es für den Redakteur schwierig werden, die Datensätze voneinander zu halten z.B in einer Select-Box Auswahl o.ä
