### ISSUE TITLE
Modifizierer: Mehrere Bearbeiten: Verschieben Button nicht sichtbar

### ISSUE THREAD

**Issue by chriza** [alnv/catalog-manager#172]

**Comment by chriza** [comment]
Im Modus Modifizierer ist der Verschieben-Button bei der Mehrfachbearbeitung nicht sichtbar.

**Comment by alnv** [comment]
Was genau meinst du mit "Im Modus Modifizierer"? Welche Tabelle ist betroffen?

**Comment by chriza** [comment]
Ich lege im Catalog Manager eine Erweiterung vom Typ "Modifizierer" an. (Event || Nachrichten)
![grafik](https://user-images.githubusercontent.com/1572887/49142668-a7281300-f2f9-11e8-94bb-87fe3cb9e2c2.png)
In der betroffenen Tabelle ist ein Verschieben der Items nicht mehr möglich.
![grafik](https://user-images.githubusercontent.com/1572887/49142903-1d2c7a00-f2fa-11e8-89b1-b70a003551c7.png)

**Comment by alnv** [comment]
Ich würde die Sortiereinstellungen prüfen. Verschieben geht nicht in allen Modis.

**Comment by chriza** [comment]
Auch wenn ich "Keine Sortierung" auswähle, ist ein Verschieben nicht möglich.

**Comment by alnv** [comment]
Die Elterntabelle muss ausgewählt sein. Siehe Screenshots:

![](https://catalog-manager.org/files/air-theme/media/github/tl_events_settings-1.png)
![](https://catalog-manager.org/files/air-theme/media/github/tl_events_settings-2.png)
![](https://catalog-manager.org/files/air-theme/media/github/events-verschieben.png)
