### ISSUE TITLE
FE-Editing Nach Erstellung der Elterntabelle soll man gleich zur Kindtabelle weitergeleitet werden.

### ISSUE THREAD

**Issue by MarcoSchaedlich** [alnv/catalog-manager#173]
Hallo,

folgendes Problem. Ich habe eine Eltern-Kind-Tabelle und im Frontend kann man Einträge der Elterntabelle und der Kindtabelle erstellen. 
Ist es dabei möglich das man nach dem speichern der Elterntabelle gleich zur Kindtabelle weitergeleitet wird ? Wenn ich im Frontend-Modul Listenansicht als Weiterleitungs-Seite die Seite zur Kind-Tabellenübersichts-Seite weiterleite sehe ich alle Einträge der Kindtabellen.

**Comment by alnv** [comment]
Dazu müssten man die ID des Elternelements an die URL anhängen z.B /childPage.html?pid=1

Ich werde es prüfen und gegebenenfalls nachrüsten.

**Comment by alnv** [comment]
Wenn die Einstellungen korrekt sind, sollte das `pid` Attribute gesetzt werden. Alternative gibt es ein Hook dafür. Da kannst du die Weiterleitungsseite überschreiben.

`$GLOBALS['TL_HOOKS']['catalogManagerFrontendEditingRedirect'][] = ['MyClass', 'myMethod'];`

``` php
public function myMethod( $strUrl, $strAttributes, $objPage, $arrValues, $strAct, $id, $catalogTablename, $objModule) {

   return $strUrl;
}
```

**Comment by MarcoSchaedlich** [comment]
Das pid Attribut fehlt bei mir. Wenn ich "speichern" drücke und die Weiterleitungsseite ist die Listenansicht der Kindelemente dann listet es alle Kindelemente auf. 
Das mit dem Hook muß ich mir erst mal anschauen, damit bin ich noch nicht so vertraut.

**Comment by alnv** [comment]
Okay. Danke für dein Feedback. In der v1.28 wird es eine Möglichkeit geben diverse Parameter an die URL anzuhängen.

**Comment by alnv** [comment]
Ab der Version 1.28.beta.4 findest du bei der Weiterleitung einen weiteren Textfeld "Query-Parameter anhängen". Dort kannst du deine ElternID übergeben. Siehe Screenshot.
![](https://catalog-manager.org/files/air-theme/media/github/fe-query-parameter.png)

**Comment by MarcoSchaedlich** [comment]
Hey, 
erst mal Danke für die schnelle Umsetzung. Hab das jetzt mal ausprobiert. Leider scheint es bei mir noch nicht wie gewünscht zu funktionieren. 
Habe in das Feld "pid=##id##" geschrieben. Wenn ich einen neuen Eintrag erstelle dann setzt er nach "speichern" die falsche "id". Wenn ich den Eintrag bearbeite dann steht da nach "speichern" die richtige "id" drin.

**Comment by alnv** [comment]
Kann ich den Task schließen? Oder geht es immer noch nicht bei dir?

**Comment by MarcoSchaedlich** [comment]
Hallo,

hab mit meinen Kunden das so geregelt das immer der neuste Eintrag oben steht. Hatte es nicht hinbekommen. Beim erstellen eines neuen Eintrages Stand immer die falsche "id" in der Adresszeile.
Ich kann es nochmal probieren wenn du möchtest, ob es jetzt geht.
Sonst kannst du zu machen.
Danke
