### ISSUE TITLE
Frage: Im FE nur Eingabeformular bereitstellen

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#174]
Hallo,

bei einer Datentabelle soll eine bestimmte Mitgliedergruppe nur Daten eingeben, nicht die Liste einsehen, noch Datensätze bearbeiten. Im Moment helfe ich mir mit einem modifizierten Template "mod_ctlg_table", das jetzt nur noch den Create-Button anzeigt.  

Gibt es irgendeine Möglichkeit, den Mausklick auf Create zu überspringen und das Eingabeformular gleich anzuzeigen (außer das Formular mit Contao-Bordmitteln nachzubauen)?

Viele Grüße,
Anke

**Comment by alnv** [comment]
Hi,

man könnte den "act" Parameter an die URL anhängen. Damit würde sich die Listenansicht immer als Formular öffnen z.B `de/vereinsmitglieder?act14=create`. Die "14" nach dem "act" ist die Frontend Modul ID.

Sollte die oben genannte Lösung nicht ausreichen, kannst du gerne ein [Support Ticket](https://catalog-manager.org/support-ticket.html) aufmachen. Ich helfe dir gerne weiter.
