### ISSUE TITLE
Filter-Optionen gruppiert darstellen?

### ISSUE THREAD

**Issue by plorenz-etes** [alnv/catalog-manager#176]
Ich versuche derzeit, Folgendes umzusetzen: Ein Kunde hat mehrere Projekte, die er nach Kategorien unterteilt verwalten möchte. Dabei kann ein Projekt mehreren Kategorien zugeteilt werden.

Auf einer Seite im Frontend sollen nun die Projekte angezeigt und gefiltert werden können. Hierfür wird ein Filterformular eingeblendet, in welchem alle Kategorien als Checkbox ausgewählt werden können.

So weit bin ich gekommen, alles funktioniert, wie es soll. Allerdings sollen jetzt die Kategorien, nach denen gefiltert werden kann, in unterschiedliche Fieldsets gruppiert (aufgeteilt) werden können. Hierfür habe ich mir mal das Template `form_checkbox_tabs.html5` angeschaut. Im Prinzip kann dieses Template bereits das, was ich benötige:

```
...
      <?php if ($option['type'] == 'group_start'): ?>
        <fieldset>
        <legend><?= $option['label'] ?></legend>
      <?php endif; ?>
...
      <?php if ($option['type'] == 'group_end'): ?>
        </fieldset>
      <?php endif; ?>
...
```

Das Problem ist nur, dass ich keine Möglichkeit gefunden habe, diese Funktion zu steuern, sprich, ich kann keine Gruppen erzeugen.

Gibt es diese Möglichkeit überhaupt bzw. könnte man das o.g. überhaupt implementieren?

**Comment by alnv** [comment]
Verstehe ich das Richtig, du willst deine Kategorien in der Checkbox nach einem bestimmten Parameter gruppieren?

Ganz einfache Lösung, die mir einfällt, wäre es für jeden Parameter eine neue Checkbox mit gefilterten Kategorien anzulegen.

Das mit dem Template kann nicht funktionieren. Der "type" Parameter wird nicht gesetzt…

**Comment by plorenz-etes** [comment]
> Verstehe ich das Richtig, du willst deine Kategorien in der Checkbox nach einem bestimmten Parameter gruppieren?
Genau :)

> Ganz einfache Lösung, wäre es für jeden Parameter eine neue Checkbox mit gefilterten Kategorien anzulegen.
Das verstehe ich leider nicht so ganz :thinking: Du meinst quasi jedem Parameter, der gruppiert werden soll, eine weitere Eigenschaft "Gruppe" hinzufügen, es vom Catalog-Manager sortieren zu lassen und im Template dann eine eigene Logik drum herum basteln? Oder gibt es noch eine einfachere Lösung?

**Comment by alnv** [comment]
Nein, nicht ganz. Im Template kannst du sowieso nicht viel machen. Da die Optionen nur Key/Value ausgeben. Daraus kannst keine Gruppe abbilden.

Daher mein Vorschlag, für jede Gruppe eine eigene Checkbox zu erstellen.

Um dir konkret weiterzuhelfen, müsste ich mir dein Setup ansehen. Wenn du magst kannst du mir gerne ein [Support Ticket](https://catalog-manager.org/support-ticket.html) erstellen.
