### ISSUE TITLE
Alias über Slug-Generator

### ISSUE THREAD

**Issue by netzarbeiter** [alnv/catalog-manager#177]
Martin hat für Contao 4.5 einen [Slug-Generator](https://github.com/ausi/slug-generator) geschrieben, damit die 4.4 LTS nicht aussen vor blieb, hat er diese Anpassungen in einer Erweiterung zur Verfügung gestellt.

Könntest du die Aliase bitte, sofern der Slug-Generator für 4.4 installiert worden ist, darüber generieren lassen?

**Comment by alnv** [comment]
Ich bin gerade dabei den Slug-Generator für das v1.28 Update zu prüfen. Eventuell packe ich es noch rein.

**Comment by alnv** [comment]
Wurde in v1.28 implementiert!
