### ISSUE TITLE
Nach Erweiterung von tl_news funktioniert die Alias-Generierung nicht mehr

### ISSUE THREAD

**Issue by rustykowski** [alnv/catalog-manager#178]
Ich habe mit dem Catalog-Manager die Contao-Nachrichten um einige Felder erweitert.
Seitdem wird beim Erstellen einer neuen Nachricht das Feld Nachrichtenalias nicht mehr automatisch ausgefüllt. Beim ersten Speichern bleibt es sogar leer, beim zweiten Speichern wird es mit einer numerischen ID gefüllt. Dieses Problem habe ich sowohl unter C 4.4 als auch unter C 4.6.
Habe ich irgendetwas nicht beachtet?

**Comment by alnv** [comment]
Ist gefixt in v1.28.1. Sollte dennoch etwas nicht stimmen bitte Issue wieder aufmachen.

**Comment by rustykowski** [comment]
Du bist ja wieder mal fix!
Danke – funktioniert wieder, wie es sein soll 👍
