### ISSUE TITLE
Nach Umzug, Frontend leer

### ISSUE THREAD

**Issue by thecompix** [alnv/catalog-manager#179]
Guten Tag Zusammen,

ich habe eben eine Contao Umgebung von 1und1 zu Strato umgezogen. 
Alles da, alles funktioniert soweit - dennoch werden mir keine Produkte mehr auf der Seite angezeigt.
Im Backend ist alles da und vorhanden.

Habe ich etwas vergessen?

**Comment by alnv** [comment]
Überprüfe ob die Templates geladen werden.

**Comment by thecompix** [comment]
Danke, hat sich bereits erledigt.
