### ISSUE TITLE
Problem mit der Befüllung von Title- und Alias-Feld

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#18]
Wenn man in einer Tabelle, die als Backend-Modul zur Verfügung steht einen  Datensatz anlegt oder bearbeitet, so ist es nicht möglich in die Felder "Titel" und "Alias" zu klicken. Man kann die Felder nur über TAB erreichen …

<img width="1050" alt="bildschirmfoto_2017-06-23_um_11_54_19" src="https://user-images.githubusercontent.com/2002902/27477089-69152934-580b-11e7-96f7-4021d6e382a8.png">

**Comment by alnv** [comment]
Ich würde dem Kategorie Select-Feld eine **Clear** CSS Klasse geben.
Wenn du auf **Eingabefeld bearbeiten** gehst und unter der **Eingabefeld-Einstellungen** Palette gibt es eine **Backend CSS-Klassen** Select Box.

**Comment by codiso** [comment]
OK das klappt 👍 
Ich würde aber auch hier die Beschriftung korrigieren …

<img width="513" alt="catalog_manager_ _spangler____reisen_ _eingabefeld_mit_der_id_3_bearbeiten__-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27488527-a4033104-5837-11e7-9a72-ac915e73f6e5.png">

**Comment by codiso** [comment]
Wäre es möglich, das das erste selbst definierte Feld diese Clear-Klasse von sich aus mitbringt?

**Comment by alnv** [comment]
Möglich wäre es, sofern nichts anderes definiert ist. Ich packe es mal auf die todo liste…

**Comment by codiso** [comment]
Ja wenn der User etwas eigenes definiert dann gilt natürlich das. Ansonsten "Clear"

**Comment by do-while** [comment]
Mein erster Test mit dem Catalog Manager (ich war in Deinem Vortrag auf der ck2017) ließ mich in einer Tabelle ein Feld title anlegen. Das lief auf eine Fehlermeldung. Danach war aber die Spalte title, die vom System angelegt wurde verschwunden und die Datentabelle war unbrauchbar. Ich kann keine Datensätze mehr anlegen, weil in MySQL die title-Spalte fehlt, anlegen geht aber auch nicht mehr.

**Comment by alnv** [comment]
@do-while danke für den Hinweis. Das werde ich mir genauer anschauen.

**Comment by Anke** [comment]
Darf ich mich hier mal kurz einklinken? Das mag für euch eine blöde Frage sein, aber muss das title-Feld standardmäßig angelegt werden? Die Antwort ist möglicherweise: "Ja, um den Alias generieren zu können". In dem Fall würde ich mir allerdings wünschen, dass man dem title-Feld wenigstens eine individuelle Feldbezeichnung geben und es idealerweise auch selbst in eine Palette packen könnte.

Ich denke da an die unbedarften FE-Redakteure, die zB Kontaktdaten erfassen sollen und denen man zig mal erklären muss, warum es kein Feld "Nachname" gibt, dass der Nachname ins Feld "Titel" im separaten Fieldset "Settings" eingegeben werden muss und dass nur Vorname, Adresse, Telefon usw in die logisch benannten Felder im Fieldset "Kontaktdaten" kommen.

**Comment by alnv** [comment]
Für die zukünftigen Updates kann man hier noch einiges optimieren. 
Momentan könnte man einfach das entsprechende DCA in der dcaconfig.php überschreiben.

z.B Titel & Beschreibung ändern:
`$GLOBALS['TL_DCA']['meineTabelle']['fields']['title']['label'] = ['Nachname', 'Bitte geben Sie ein…']; `

**Comment by Anke** [comment]
Ups! Diese beiden DCA-Einträge, die das Label "title" jeweils ändern sollen:

```
$GLOBALS['TL_DCA']['ao_clubs']['fields']['title']['label'] = ['Club name', 'Enter the name of your club here'];
$GLOBALS['TL_DCA']['ao_grounds']['fields']['title']['label'] = ['Ground name', 'Enter the name of the ground here'];

```
führen zu einem unerwünschten Ergebnis, auch wenn ich annehme, dass dadurch nicht wirklich etwas angerichtet wird. 

Im Frontend-Modul (Catalog Listenansicht) von 'ao_grounds', steht jetzt mehrfach "Club name [title]" statt "Ground name [title]":

![catalogmanager_club_name](https://user-images.githubusercontent.com/1300920/27586166-75ce4b7e-5b3f-11e7-9d21-42456708cb09.jpg)

**Comment by alnv** [comment]
Zum eigentlichen Topic:
Ab der v1.3 ist die .clr Klasse als Standart eingestellt. Es seiden diese wird überschrieben.
@Anke Dein Problem mit dem Label schaue ich mir gesondert an.
