### ISSUE TITLE
Enable filter options with anchor

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#180]
Ist es möglich beim Filtergenerator neben dem Seitenwähler auch die Eingabe eines Ankers vorzusehen?
Wenn der Filter nicht oben auf der Seite steht springt die Seite sonst immer auf den Anfang. Für die Suche selbst, kann man den Anker auch bei der Action im Template anpassen, aber das Reset wird komplett generiert.

**Comment by alnv** [comment]
Also über das Template (ce_catalog_filterform) sollte es möglich sein (nicht getestet).
Nach dem `<?= $this->action ?>` Action Attribute könnte man ein Anker anhängen `<?= $this->action ?>#block1`.
Und der Reset Link ist nichts weiteres als eine Weiterleitung. Da könnte man einfach `mein-alias.html` eintragen.

**Comment by mlwebworker** [comment]
Das das geht ist mir klar. Habe ich derzeit auch so gelöst. Ist halt nur nicht so flexibel, weil man dann für jeden Filter ein eigenes Filter-Template benötigt.

**Comment by alnv** [comment]
ließe sich einrichten :) Ich packe es auf die todo liste

**Comment by mlwebworker** [comment]
Danke

**Comment by alnv** [comment]
Wurde implementiert in v1.29

**Comment by dive13** [comment]
Sobald ein Anker an der URL dranhängt (also nach der 1. Filterung) funktioniert die Vorschlagssuche nicht mehr.

**Comment by alnv** [comment]
Danke für deinen Hinweis. Wurde gefixt in v1.29.10

**Comment by dive13** [comment]
Wow, so schnell … Danke!

**Comment by dive13** [comment]
Hmm ... scheint trotz Update auf 1.29.10 unverändertes Verhalten zu sein.

**Comment by alnv** [comment]
Hast du deinen Browser Cache gelöscht? Bei mir Lokal funktioniert es einwandfrei. Ansonsten schaue ich nochmal nach.

**Comment by dive13** [comment]
... uups, das war's. Jetzt funktioniert es, vielen Dank!
