### ISSUE TITLE
Taxonomien: Insert-Tags werden nicht verarbeitet

### ISSUE THREAD

**Issue by leycommediasolutions** [alnv/catalog-manager#181]
Beim Testen der Taxonomien ist uns aufgefallen, dass Insert-Tags (z.B. {{date::U}}) nicht verarbeitet werden. Wir benötigen dies bei einem konkreten Fall, um abgelaufene Veranstaltungen, welche mit Timestamp in die Datenbank geschrieben werden, nicht mehr anzeigen zu lassen. Gehen wir das Problem ggf. falsch an?

**Comment by alnv** [comment]
Du kannst den {{CTLG_TIMESTAMP}} Insert Tag verwenden.

{{CTLG_TIMESTAMP}} // Jetzt
{{CTLG_TIMESTAMP::?add=604800}} // Jetzt + 7 Tage
{{CTLG_TIMESTAMP::?subtract=604800}} // Jetzt - 7 Tage
