### ISSUE TITLE
Datumsfeld OutOfBoundsException C3.5

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#182]
Wenn ich ein Datumsfeld unter C3.5 für einen Catalog anlage und anschließend die Eingabemaske versuche aufzurufen erscheint:

```
[07-Jan-2019 11:51:59 Europe/Berlin] PHP Fatal error: Uncaught exception 'OutOfBoundsException' with message 'Invalid date "{{date::d.m.Y}}"' thrown in /Applications/MAMP/htdocs/xxxx/system/modules/core/library/Contao/Date.php on line 438
#0 /Applications/MAMP/htdocs/xxxx/system/modules/core/library/Contao/Date.php(79): Contao\Date->dateToUnix()
#1 /Applications/MAMP/htdocs/xxxx/system/modules/core/library/Contao/Widget.php(1470): Contao\Date->__construct('{{date::d.m.Y}}', 'd-m-Y')
#2 /Applications/MAMP/htdocs/xxxx/system/modules/core/classes/DataContainer.php(268): Contao\Widget::getAttributesFromDca(Array, 'datecreated', '{{date::d.m.Y}}', 'datecreated', 'ctlg_mediathek', Object(Contao\DC_Table))
#3 /Applications/MAMP/htdocs/xxxx/system/modules/core/drivers/DC_Table.php(1943): Contao\DataContainer->row('{general_legend...')
#4 /Applications/MAMP/htdocs/xxxx/system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#5 /Applications/MAMP/htdocs/xxxx/system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('Mediathek_Youtu...')
#6 /Applications/MAMP/htdocs/xxxx/contao/main.php(20): Contao\BackendMain->run()
#7 {main}
```
Ich habe als Standart-Wert den Inserttag {{date::d.m.Y}} eingegeben.

PHP 7.1.20
Catalog Manager: 1.21.7

**Comment by alnv** [comment]
Wo setzt du den Inserttag "{{date::d.m.Y}}" ein?
Dieser verursacht den Fehler.

**Comment by akroii** [comment]
![bildschirmfoto 2019-01-07 um 12 38 45](https://user-images.githubusercontent.com/8830861/50766367-33bedd00-1279-11e9-8653-0dc9a03f3911.png)

**Comment by akroii** [comment]
![bildschirmfoto 2019-01-07 um 12 42 24](https://user-images.githubusercontent.com/8830861/50766492-b21b7f00-1279-11e9-9ac4-93ae4ab79e18.png)

**Comment by alnv** [comment]
An dieser Stelle funktionieren Insert tags nicht. Das hängt mit Contao zusammen. Bei den "Eingabefeld-Einstellungen" gibt es eine Checkbox "Zeitstempel". Diese kannst du aktivieren, wenn du das aktuellste Datum ausgegeben haben möchtest.
