### ISSUE TITLE
Entity creation and submit on change fields

### ISSUE THREAD

**Issue by chibko** [alnv/catalog-manager#183]
Hello,
I have built a catalog with some fields with values that depends on other fields.
I have set the taxonomies/filter for the required field and check the "Submit on change" too.
When i edit a entity, everything works well, if a change a field value, the page reloads and i get the correct option in the other field. Great.
When i create a entity, it does not work, the "Submit on change" fields does not reload… I have to save the entity first, the it works.
How can i avoid this ?

**Comment by alnv** [comment]
Do you edit the entity in backend or frontend?

**Comment by chibko** [comment]
In the backend.

**Comment by alnv** [comment]
I will check it and adapt if necessary.

**Comment by chibko** [comment]
Thank you.

**Comment by alnv** [comment]
wish contao version do you use?

**Comment by chibko** [comment]
Contao 4.4.32

**Comment by chibko** [comment]
Oh wait, i have a JS error in my web console.
<img width="551" alt="capture d ecran 2019-01-11 a 18 16 39" src="https://user-images.githubusercontent.com/8981739/51049152-4f094f80-15cd-11e9-944f-013625124e84.png">
And Submit on change is not working anymore, even on existing entity.
I can remember it was working before upgrading catalog manager to 1.9

**Comment by chibko** [comment]
Grrrr… See what happen
I have added a navigation aera in the Catalog Manager Settings with the same name as my catalog name.
Renamed the catalog name solve this.
