### ISSUE TITLE
Suggestion CatalogInsertTag : Remove empty value in array

### ISSUE THREAD

**Issue by chibko** [alnv/catalog-manager#184]
Hello, 
In my project, i use the CTLG_LIST inserttags. Something like this : {{CTLG_LIST::?module=132&get=epci_doc}} 
It does not works as expected because my "epci_doc" field may be not set form some entity.
I have to modify the CatalogInsertTag.php file on line 253 like this
```
$arrReturn = array_unique( $arrReturn );
// To remove empty value from the array before implode
$arrReturn = array_filter($arrReturn);
```
Catalog Manger 1.28

**Comment by alnv** [comment]
This function will be improved with the next update

**Comment by alnv** [comment]
Please update your CM to v1.29.2.

**Comment by chibko** [comment]
Thanks again.
