### ISSUE TITLE
FE: Es werde nur leere Datensätze erzeugt

### ISSUE THREAD

**Issue by rorso** [alnv/catalog-manager#186]
Version v1.29.5

Ich habe ziemliche Probleme mit dem Frontend Editing und den zugehörigen Einstellungen im CM.
Die Vorgabe ist ziemlich einfach: 

Feld "Jahrgang" - vorbelegen mit aktuellem Jahr
Feld "Ausgabe" (zu befüllen)
Feld "Datum" - vorbelegen mit aktuellem Datum
Ein File-Upload

Alle Eingabefelder sind in der DB als varchar(16) not null default '' definiert. Die Felder numerisch zu deklarieren war überhaupt ein Schlag ins Wasser. Hier würde ich mir sinnvolle Vorbelegungen für die verschiedenen "Feldtypen" wünschen. Was nimmt man für "Datum"?

Versuch 1

Im erzeugten FE-Modul im Bereich "Frontend Editing" habe ich  Vorgaben für die Felder "Jahrgang" und "Datum" wie folgt:
Jahrgang: {{date::Y}}
Datum: {{date::d.m.Y}}

![grafik](https://user-images.githubusercontent.com/4092020/51787188-e8f4fe80-216e-11e9-83f1-235281da2d46.png)

Im FE Erfassungs Formular wird das nicht angezeigt.

Versuch 2

in der Tabelle zu den Feldern einen "Standard Wert" eingetragen:

![grafik](https://user-images.githubusercontent.com/4092020/51787196-1a6dca00-216f-11e9-82f6-070261a81aa1.png)

Im Backend wird die Vorgabe bei der Eingabe im Feld "Jahrgang" angezeigt, im Feld "Datum" ignoriert.
Im Frontend wird stattdessen ein Stück Code in das Feld geschrieben:
![grafik](https://user-images.githubusercontent.com/4092020/51788045-ad136680-2179-11e9-8af2-c4f0cf35c9ef.png)

Wenn ich einen "Standardwert" bei Datum hinterlege bekomme ich im Frontend überhaupt nur eine "es it etwas schief gelaufen" Seite und gar kein Formular mehr.

Unabhängig davon - wenn ich das Formular korrekt ausfülle und auf "speichern" klicke, wird ein völlig leerer Datensatz angelegt. Eine Fehlermeldung wird nicht angezeigt.

![grafik](https://user-images.githubusercontent.com/4092020/51788230-dd5c0480-217b-11e9-9617-d7e491944d1f.png)

Und das trotz Einstellung "leere Werte nicht speichern".
In der Datenbank sind in der Tabelle alle Felder leer, bis auf "id" und "tstamp".

Im Backend kann ich Datensätze anlegen. hier ist, wie man oben sehen kann, "nur" die Datum Spalte nicht übersetzt - im Frontend dagegen schon.

Dass ich im Backend einen Kalender Picker habe, im Frontend aber nicht, ist mir hier jetzt auch schon egal. :-(

Gehe ich ich im FE bei einem Datensatz auf "ändern" und ändere einen der Werte, bekomme ich beim Speichern wieder die "Bei der Ausführung des Skriptes ist ein Fehler aufgetreten. Irgendetwas funktioniert nicht richtig." Meldung.

`[2019-01-26 15:23:59] app.CRITICAL: An exception occurred. {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'UPDATE cat_astroinfo SET  WHERE id = '6'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id = '6'' at line 1 at /home/.sites/576/site5265391/web/contao/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:99, Doctrine\\DBAL\\Driver\\PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id = '6'' at line 1 at /home/.sites/576/site5265391/web/contao/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:109, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE id = '6'' at line 1 at /home/.sites/576/site5265391/web/contao/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:107)"} []`

Ach ja, "Pflichtfeld". Wenn ein Feld als "Pflichtfeld" deklariert ist, kann man das Formular nicht mehr "abbrechen", ohne es vollständig auszufüllen - und dann wird beim Abbrechen trotzdem ein (leerer) Datensatz angelegt.

Setze ich auf das Datums (Text) Feld eine Prüfung auf "gültiges Datum", wird mir bei der Eingebe "1.1.2019" korrekt ein Hinweis auf das richtige Eingabeformat gezeigt und der Wert nicht angenommen. Die Anzeige steht aber nur eine Sekunde da, dann wird das Formular ganz verlassen und man ist zurück in der Liste. Davon kann ich keinen Screenshot machen, das geht zu schnell.

**Comment by alnv** [comment]
Mit dem {{date::*}} Insert Tag ist es ganz schwierig. Irgendwie wird es nicht korrekt aufgelöst. Da müsste man das Contao Team fragen. Wüsste auch nicht wieso das so ist.

> Versuch 1

Hier kannst Standardwerte für Felder festlegen, die nicht im Formular auftauchen.

> Versuch 2

Theoretisch richtig, aber das Date Insert tag ist an sich fehlerhaft.

> Wenn ich einen "Standardwert" bei Datum hinterlege bekomme ich im Frontend überhaupt nur eine 
"es it etwas schief gelaufen" Seite und gar kein Formular mehr.

Liegt höchstwahrscheinlich am Date Insert Tag.

> Im Backend kann ich Datensätze anlegen. hier ist, wie man oben sehen kann, "nur" die Datum Spalte nicht übersetzt - im Frontend dagegen schon.

Siehe [hier](https://catalog-manager.org/feedback/datumsfelder-in-der-backend-liste.html)

> Dass ich im Backend einen Kalender Picker habe, im Frontend aber nicht, ist mir hier jetzt auch schon egal. :-(

Siehe [hier](https://catalog-manager.org/feedback/kalenderfunktion-bei-datumsfeldern-im-frontend-editing-tool.html)

> varchar(16) not null default ''

Wenn du unsicher bist, verwende immer "varchar(255)". Für Datum kannst du auch "int(10)" verwenden. 

> Ach ja, "Pflichtfeld". Wenn ein Feld als "Pflichtfeld" deklariert ist, kann man das Formular nicht mehr "abbrechen", ohne es vollständig auszufüllen - und dann wird beim Abbrechen trotzdem ein (leerer) Datensatz angelegt.

Im Backend kommt es schonmal vor. Da kannst du dich auch an das Contao Core Team wenden. 
Im Frontend sollte es nicht vorkommen.

> Setze ich auf das Datums (Text) Feld eine Prüfung auf "gültiges Datum", wird mir bei der Eingebe "1.1.2019" korrekt ein Hinweis auf das richtige Eingabeformat gezeigt und der Wert nicht angenommen. Die Anzeige steht aber nur eine Sekunde da, dann wird das Formular ganz verlassen und man ist zurück in der Liste. Davon kann ich keinen Screenshot machen, das geht zu schnell.

Das verstehe ich nicht ganz. Hast du eventuell submit on change aktiviert?

Zusammengefasst: Wenn du vordefinierte Datumsfelder benötigst, setze auf eine Clientseitige Lösung. Momentan gibt es mit dem Date Insert Tag zu viele Problem. Da es eine Core Komponente ist, kann ich das nicht so schnell fixen.

Bzgl. Clientseitige Lösung kannst du gerne ein Support Ticket aufmachen.

**Comment by rorso** [comment]
Danke für die Rückmeldung.

Ich habe jetzt alle Vorbelegungen gelöscht. (das könnte man eventuell in der Knfiguration auch besser erklären als "Hier können Sie bestimmte Felder mit standardwerten vorbelegen.")
Ich habe auch alle Feld Prüfungen gelöscht.
Ich habe alle sonstigen Einschränkungen entfernt (Leerzeichen ersetzen, Leerfeld nicht speichern, ...)
Ich habe das Filter Formular von der Seite entfernt.
Ich habe nur noch am Datums Feld eine Prüfung auf "gültiges Datum".

Die Warnung bei falschem Datums Format bleibt jetzt stehen. Das war wohl ein Nebeneffekt des Filterformulars (Jahrgang, Kombobox, Submit on change), auch wenn eingestellt war, dass es auf der Detail Seite nicht anzuzeigen ist - auf der Eingabeseite war es trotzdem.

Wenn man wie beschrieben am Datumsfeld eine "Sortierung nach Tag" konfiguriert, wird das Datum richtig in der Liste angezeigt. Warum auch immer. Es ist ja ohnehin schon als Datumsfeld deklariert, aber danke für den Tip.

**Es werden aber im FE weiterhin nur leere Datensätze angelegt.** Sowohl der Insert als auch der Update SQL Befehl enthalten keine Feld Aufzählung oder Werte. Deshalb auch der Error beim Update.

Ich habe im Protokoll überprüft: Das Formular wird komplett mit Werten im POST übermittelt. Das Problem liegt also serverseitig. Und es liegt wohl nach der Stelle, an der die Bedingung "Leere Werte nicht abspeichern" geprüft wird, denn die scheint ja nicht zu greifen, auch wenn sie aktiviert ist (was sie nicht mehr ist). Und eigentlich sollte sie doch genau DAS verhindern?

> Wenn du unsicher bist, verwende immer "varchar(255)".

Nein, ich bin nicht unsicher. Ich mache seit 20 Jahren Datenbank Design und weiß normalerweise welche Feldtypen ich verwenden möchte. Allerdings wird bei Datumsfeld der einzig sinnvolle Datenbank-Feldtyp "DATE" oder "DATETIME" gar nicht erst angeboten. Warum ich dafür "varchar(255)" nehmen soll erschließt sich mir nicht. Auch nicht, warum das hier überhaupt angeboten wird. Da ich aber die Internas der Erweiterung nicht kenne, kann es ja sein, dass für "Datumsfeld" aus irgend einem programmtechnischen Grund ein anderer Feldtyp optimal ist. Deshalb meine Idee, den dann auch gleich vorzuschlagen und nicht "im Zweifelsfall varchar(255)". Da sträuben sich mir als Datenbank Techniker die Haare. Gerade bei "Datumsfeld" ist die weitere Verarbeitung der Daten ja schon ziemlich fixiert.
 Wenn es gedacht ist, einen "normalen Anwender" die Konfiguration vornehmen zu lassen, würde eine Einschränkung auf sinnvolle Werte hier sicher hilfreich sein.

Ich habe aber auch (noch) nicht verstanden, warum für den File-Upload ein BINARY(16) verwendet wird, das File aber sowieso im Dateisystem liegt. Da hier wohl nur der Pfad abgelegt wird, wäre mir ein varchar() verständlicher gewesen. Aber wie gesagt, ich verstehe die Internas der Komponente nicht. Und solange es funktioniert, muss ich mir darüber auch nicht den Kopf zerbrechen.

**Comment by alnv** [comment]
> Es werden aber im FE weiterhin nur leere Datensätze angelegt.

Leider kann ich es nicht reproduzieren. Wäre es dir möglich dein Setup auf der Demoseite kurz nach zubauen? 

 > Allerdings wird bei Datumsfeld der einzig sinnvolle Datenbank-Feldtyp "DATE" oder "DATETIME"

Dazu habe ich mit Contao kein  Best-Practice. Da auch die Core Module über solche Datentypen nicht verfügen. Da Contao nur den Timestamp speichert ist ein `int` am idealsten, notfalls genügt auch ein `varchar` (wenn es nicht sortierbar sein muss).

> Wenn es gedacht ist, einen "normalen Anwender" die Konfiguration vornehmen zu lassen, würde eine Einschränkung auf sinnvolle Werte hier sicher hilfreich sein.

Wäre eine Überlegung wert.

**Comment by rorso** [comment]
> Wäre es dir möglich dein Setup auf der Demoseite kurz nach zubauen?

klar...
[https://demo.catalog-manager.org/de/astroinfo](https://demo.catalog-manager.org/de/astroinfo)

Ganz 100% konnte ich das nicht nachvollziehen. Im open/close Fieldset wurde mir das "-" immer in ein "_" umgerechnet, scheint aber keine Auswirkung zu haben.

Das Ergebnis ist anders, aber nicht wirklich besser.  Im FE kann ich hier überhaupt keine Datensätze anlegen. Beim Speichern erscheint ein "Bitte beantworten Sie die Sicherheitsfrage!" das zuvor nicht da war, aber entweder ich bin zu blöd um zu rechnen, oder ich bin ein Roboter. Ich komme über die Captcha Abfrage nicht drüber. Der "Zurück" Button geht auch erst, nachdem man das Captcha ausgefüllt hat. Vielleicht zwei Varianten des gleichen Problems?

So ein Captcha erscheint übrigens bei mir NICHT, obwohl "Sicherheitsabfrage deaktivieren" NICHT aktiviert ist. Im Quellcode sehe ich das Captcha aber als "nicht sichtbar" und bereits mit einem Wert befüllt.

Getestet mit FF und Edge. Böhse Add-Ons und Ad-Blocker deaktiviert. Standard Sicherheitseinstellungen.

Falls das einen Unterschied macht: Ich habe Contao 4.4.33 auf "world4you.com" am Laufen und das OpenSauce Theme. Auf der Detail Seite habe ich den Mozilla "pdfjs" Viewer in einem abgeleiteten Template für die Anzeige imlementiert, aber das kommt hier noch nicht zum Tragen.

**Comment by alnv** [comment]
Sicherheitsabfrage geht nun wieder.

Das einzige Problem was mir aufgefallen ist, das beim "dynamischen Wert" Eingabefeld ein String statt einem Datum eingetragen war.

Sonst funktioniert alles. Oder übersehe ich etwas?

**Comment by alnv** [comment]
Kannst du versuchsweise die "catalog-manager-wizards" Erweiterung zu entfernen? 
Oder benötigst du diese?

**Comment by rorso** [comment]
> 
> 
> Kannst du versuchsweise die "catalog-manager-wizards" Erweiterung zu entfernen?
> Oder benötigst du diese?

Ich stochere noch im Nebel. Ich dachte, die passt dazu und könnte nützlich sein. Aktuell habe ich außer der Demo-Seite und einem teilweise angepassten Layout nur den Versuch mit den Artikeln am Start.

Also weg damit.

Und? **ES HAT GEHOLFEN!**

Jetzt werden die Datensätze korrekt eingefügt.

Danke!
