### ISSUE TITLE
Codefehler im Frontend in den meta-Tags

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#187]
Es gibt einen Codefehler im Frontend in den meta-Tags in Contao 4.4. Generiert wird: 
`<link href="/system/modules/catalog-manager/assets/awesomplete/awesomplete.css" rel="stylesheet" type="text/css"></link>↩`
Im Filterformular wird beim Reset die Formular ID mit ausgegeben was zu einer doppelten ID führt.
`<p class="reset"><a href="/meineSeite.html" id="id_form_2">Alle Filtereinstellungen zurücksetzen.</a></p>↩`

**Comment by alnv** [comment]
Danke für den Hinweis. Ich werde es überprüfen.

**Comment by alnv** [comment]
Ist behoben in v1.29.8
