### ISSUE TITLE
Frontendediting Kindkatalog

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#188]
Hallo,

ich bin auf eine kleines Problem gestoßen. Fallbeispiel:
--> Es gibt ein Elternkatalog mit einem Kindkatalog.
--> In der Detailseite des Elternkataloges liegt eine Liste des Kindkataloges mit Frontendediting
--> Die Optionen "Edit", "Delet", und "Duplicate" stehen hier schon zur Verfügung
--> Die Option "Create" noch nicht
--> Nutzt man die Option Kind-Tabellen Wieterleitungsseite kann dort über die Liste ein neues Element  angelegt werden.
--> Das liegt daran, denke ich, dass in der URl die pid mitgegeben wird, was ja auch logisch ist, da das System wissen muss zu welchen Elternkatalog das neue Element gehören soll.
--> Wenn ich nun in der Detailseite den URl Parameter "?pid=X" anhänge erscheint der Button "Create" auch auf dieser Seite

Ich denke, dass es so gelöst ist, dass die pid als CATALOGACTIVE vorhanden sein muss. Wäre es möglich das auf CATALOGMASTER anzuwenden, so dass der Parameter in der URL nicht vorhanden sein muß?

**Comment by alnv** [comment]
Leider nicht, der "pid" Attribut kann nur über den URL Parameter übergeben werden.

**Comment by hoaxone** [comment]
Ok, danke für die Information.
Ich habe es gelöst, in dem ich einen Filter (welcher sowieso eingebunden werden muß) mit einem Feld bestückt habe, welcher die id des Objektes als pid in die URL setzt.
