### ISSUE TITLE
Fehler Feldtyp Erklärung

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#189]
Bei der Nutzung des Feldtyps "Erklärung", wird in der Katalog-Ansicht im Backend der Tabellenname als Label angezeigt.

**Comment by alnv** [comment]
Ich werde es überprüfen und gegebenenfalls fixen.

**Comment by hoaxone** [comment]
Vielen Dank.

**Comment by alnv** [comment]
Ein Label Feld wurde in der v1.29.10 eingetragen.
