### ISSUE TITLE
Sortierung von Checkbox Listen?

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#19]
Ich habe eine Tabelle "Länder" welche als Checkbox-Liste in den Daten der Tabelle "Reisen" genutzt wird. Es werden alle Daten angezeigt, aber ohne die Sortierung der Tabelle "Länder". In der Ansicht des Backend-Moduls wird die Sortierung korrekt genutzt.

<img width="567" alt="spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27477369-3d980898-580c-11e7-9e18-9f4fc2d6cac0.png">

<img width="323" alt="bildschirmfoto 2017-06-23 um 12 05 43" src="https://user-images.githubusercontent.com/2002902/27477399-5adf7436-580c-11e7-94c8-7f7f8a54bc99.png">

**Comment by codiso** [comment]
Ist wohl so ein ähnliches Problem wie in #10

**Comment by alnv** [comment]
Genau. Bin bereits dran :)

**Comment by codiso** [comment]
👍

**Comment by alnv** [comment]
siehe #10
