### ISSUE TITLE
Fehler beim Erzeugen von Datensätzen und Umbenennen des Katalogs

### ISSUE THREAD

**Issue by baddy1000** [alnv/catalog-manager#191]
Hab versucht anhand der Dokumentation einen Katalog anzulegen.
Leider etwas überfragt was ich falsch mache.

Ändern des Katalognamens
![image](https://user-images.githubusercontent.com/15890453/54621964-f476ee80-4a68-11e9-97a8-006c29349505.png)

Erstellung eines Datensatzes:
![image](https://user-images.githubusercontent.com/15890453/54622014-0bb5dc00-4a69-11e9-9d31-c2caf67bce35.png)

**Comment by alnv** [comment]
Laut der Fehlermeldung hast du die Tabelle von references zu cltg_references umbenannt. Die Funktion selber habe ich soeben getestet. Da stimmt alles.

Ich vermute irgendein Feld verweist auf den alten DB Namen. Versuche die Umbenennung wieder Rückgängig zumachen. Dazu kannst du irgendein DB Tool verwenden z.B PHPMyAdmin.

**Comment by baddy1000** [comment]
Die Tabelle wurde nicht umbenannt.
![image](https://user-images.githubusercontent.com/15890453/54669540-ec16c600-4af1-11e9-8c28-85234a2235f1.png)

Kann mir auch nicht vorstellen, dass es eins der Felder ist. Es bestehen zur Zeit nur die Standard-Felder:
![image](https://user-images.githubusercontent.com/15890453/54669684-49ab1280-4af2-11e9-8ffe-5bdb4d2429ef.png)

Der Versuch den Katalog zu löschen endet mit dieser Fehlermedlung:
![image](https://user-images.githubusercontent.com/15890453/54669791-8840cd00-4af2-11e9-9847-c8c44c75c684.png)

**Comment by baddy1000** [comment]
I am back with some good news.
Got it fixed, it was another package causing the issue.
For people that might run into the same problem, Bootstrap-contao bundle was having a issue with forms combined with Contao 4.7.
The author updated the latest Bootstrap package tho. It's now compatable.

**Comment by alnv** [comment]
thanks.
