### ISSUE TITLE
Individueller Zugriff auf Datensätze

### ISSUE THREAD

**Issue by baddy1000** [alnv/catalog-manager#193]
Mir ist nicht ganz klar, wie ich in anderen Modulen bestimmte Datensätze aus dem Katalog am Besten abrufen soll.

Kurze Erklärung was ich versuche:
- Katalog verfügt über: Kunde, Gallerie, Beschreibung
- Modul: Auflistung der wichtigsten Werte -> Kunde, Link/Button (und eventuell das 1. Bild der Gallerie)
- Modul: Modal, dass die vollständigen Daten vom ausgewählten (über den Link/button) Datensatz lädt und seine Container mit diesen Daten befüllt.

**Comment by alnv** [comment]
Alle deine Felder kannst du im "ctlg_view_*" Templates ausgeben. Am Besten du orientierst dich an der Demoseite. Siehe "Immobilien" Beispiel.

Für die Liste verwende ich das "ctlg_view_properties" Template:

``` php
<div class="ce_properties block<?= $this->cssClass ?>">
    <?php if( $this->masterUrl ): ?>
      <h2><a href="<?= $this->masterUrl ?>"><?= $this->title; ?></a></h2>
   <?php else: ?>
      <h2><?= $this->title; ?></h2>
   <?php endif; ?>
    <?php if ( is_array( $this->preview ) && !empty( $this->preview ) ): ?>
        <div class="preview">
            <img src="<?= $this->preview['picture']['img']['src'] ?>" alt="<?= $this->title ?>">
        </div>
    <?php endif; ?>
    <div class="properties">
        <ul>
            <?php if ( $this->provision ): ?>
                <li>Provisionsfrei</li>
            <?php endif; ?>
            <?php if ( $this->living_space ): ?>
                <li>Wohnfläche: <?= $this->living_space ?>m²</li>
            <?php endif; ?>
            <?php if ( $this->rooms ): ?>
                <li>Zimmer: <?= $this->rooms ?></li>
            <?php endif; ?>
            <?php if ( $this->buy_price ): ?>
                <li>Kaufpreis: <?= number_format( $this->buy_price, 2, ',', '.' ) ?>€</li>
            <?php endif; ?>
            <?php if ( $this->move_in ): ?>
                <li>Bezugsfrei: <?= $this->move_in ?></li>
            <?php endif; ?>
        </ul>
    </div>
   <?php if( $this->masterUrl ): ?>
      <p class="btn btn-primary"><a href="<?= $this->masterUrl ?>" title="<?= $this->title; ?>">Zum Objekt</a></p>
   <?php endif; ?>
</div>

```
und für die Detailansicht kommt das "ctlg_view_property" Template zu Einssatz. Die Templates kannst du im jeweiligen FE Modul ändern. Siehe "Template-Einstellungen" Palette.

Über den $this-> Operator kannst deine Variablen/Felder ausgeben. Mit `<?= $this->showTemplateVars() ?>` kannst du alle verfügbare Variablen anzeigen lassen.

Eine ausführliche Dokumentation ist geplant.

Bei weiteren Fagen kannst du das Feedback Formular auf der Catalog Seite verwenden.
