### ISSUE TITLE
Feldtyp Datumsfeld - Datums- und Zeitformat

### ISSUE THREAD

**Issue by stefan-at-work** [alnv/catalog-manager#194]
Es wäre hilfreich, wenn im Feldtyp "Datumsfeld" die Ausgabe des Datums- und Zeitformates individuell einzustellen wäre.

**Comment by alnv** [comment]
Mit $this->parseDate kannst du im jeden Template das Datum individuell einstellen. Im $this->origin findest du dein timestamp z.B $this->parseDate( 'd.m.Y', $this->origin['myDateField'] );
