### ISSUE TITLE
Frontend Editing bei modifiziertem Event

### ISSUE THREAD

**Issue by janoschbatschi** [alnv/catalog-manager#195]
Hallo, ich habe ein Catalog Listenansicht Modul wo ich als Backendmodul ein modifiziertes Event-Modul definiert habe. Dabei habe ich auch das Frontend-Editing aktiviert. Wenn ich jedoch jetzt im Frontend auf editieren klicke kommt folgender Fehler: 
app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to tl_calendar_events::getSourceOptions() must be an instance of DataContainer, null given, called in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php on line 1327 at /vendor/contao/calendar-bundle/src/Resources/contao/dca/tl_calendar_events.php:799 

Was auch auffällt, ist das kein "Erstellen"-Button erscheint - im Gegensatz dazu funktioniert das Ganze bei einer Catalog-Tabelle ohne Probleme.

**Comment by alnv** [comment]
Hi,

das frontend-editing funktioniert überwiegend nur mit eigenen Catalog Tabellen. Da viele DCA nur im Backend aufgerufen bzw. bearbeitet werden können. 

"Erstellen"-Button benötigt ein gültiges PID Parameter, da es eine Kind-Tabelle ist.

**Comment by janoschbatschi** [comment]
Alles klar, danke für die schnelle Antwort!
