### ISSUE TITLE
[Frage] Blob Ausgabe in template

### ISSUE THREAD

**Issue by mucka-veli** [alnv/catalog-manager#196]
Nach erfolgreicher Verbindung zur Datenbank, gebe ich alle entsprechenden Zellen in mod_catalog_table aus. 

Probleme habe ich jedoch mit dem Decrypten der Blob (mehrfacher Bildupload und mehrfache Dateiverknüpfung). 

Gibt es hierfür einen spezielles Inserttag bzw. irgend einen `$this->` Befehl? Wenn ich die Zelle wie üblich mit ` echo $row[9] ` ausgebe, erhalte ich nur Hyroglyphen: 

> ?j�b���2i��

Danke.

**Comment by alnv** [comment]
Das ist eine UUID über diese werden Dateien aufgelöst.

Beispiel:

``` php
$objImage = \FilesModel::findByUuid( $strDeineUUID );
if ( $objImage  !== null ) {
$strPath = $objImage->path;
}
```
Beim Inserttag bin ich mir nicht sicher. Abgesehen davon, Catalog Manager erstellt automatisch Verbindung zur passenden DB und gibt die Werte bereits gerendert aus. Damit kannst du alle verfügbaren Variablen im Template anzeigen:

$this->showTemplateVars();

Die Variablen von den Datensätzen findest du in den ctlg_view_* Templates.
