### ISSUE TITLE
Optionen in Kartenansicht

### ISSUE THREAD

**Issue by juehau** [alnv/catalog-manager#198]
die GoogleMaps-API bietet eine Reihe von Optionen für die Kartenansicht. Wir würden gerne die Option "style=feature:poi%7Cvisibility:off" (mapstyle.withgoogle.com) einsetzen. Wie kann ich das lösen? Änderungen an 
httpdocs/vendor/alnv/catalog-manager/library/alnv/Maps/GeoCoding.php 
führen leider nicht zum Erfolg, Allerdings wäre das auch keine wirklich gute Lösung bzgl. Updates.
Hat jemand eine Idee dazu ?

**Comment by alnv** [comment]
Styles können direkt im Backend eingetragen werden.  Siehe FE-Modul > Listenansicht > Karten-Einstellungen > Eigenes Theme verwenden

**Comment by juehau** [comment]
Vielen Dank!
Ich war davon ausgegangen, dass die URL für GoogleMaps angepasst wird. Dem ist aber nicht so! Es wird die Jason-Syntax benutzt. Die richtige Syntax ist:

[
  {
    "featureType": "poi",
    "stylers": [
      {
        "visibility": "off"
      }
    ]
  }
]
