### ISSUE TITLE
Modifizierer - Reihenfolge neuer Fieldsets

### ISSUE THREAD

**Issue by mlwebworker** [alnv/catalog-manager#199]
Wenn ich mir zwei neue Fieldsets mit Feldern anlege, habe ich bei tl_members folgende kleine Unschönheit beobachtet. Wahrscheinlich tritt das aber grundsätzlich in modifizierten Tabellen auf.
Fieldset Testgruppe1 platziere ich nach einem vorhandenen Fieldset (z.B. Kontakdaten), das einzige Feld test_1 in diesem Fieldset, wird nach dem letzten Feld des Fieldsets Kontaktdaten (Sprache) platziert.
Fieldset Testgruppe2 kommt nach Testgruppe1, das erste Testfeld test_21 kommt nach test_1, das zweite  testfeld_22 nach test_21. Schaue ich mir das Ergebnis im Backend an, ist es wie erwartet.
Jetzt kömmt der Kunde im Laufe des Projektes und möchte Testgruppe 2 vor Testgruppe 1 angezeigt haben.
Also drehe ich den ganzen Spass um. Testgruppe2 kommt nach Kontaktdaten, Feld test_21 kommt nach Sprache, Feld test_22 kommt nach test_21
Testgruppe1 kommt nach Testgruppe2 und Feld test_1 nach test_22. Dabei wird aber zunächst nur noch die Testgruppe2 angezeigt. Erst wenn ich die Reihenfolge der Felder/Feldgruppen in meiner Tabelle im Catalog Manager zusätzlich im Backend anpasse, sehe ich wieder beide Feldgruppen. Das ist dann natürlich doppelter Aufwand und bei mehreren Verschiebungen auch fehleranfällig. Lässt sich das vielleicht einfacher regeln?
Das Beispiel habe ich in der Demo hinterlegt (Mitglieder Test)

**Comment by alnv** [comment]
Die Felder werden nacheinander initialisiert. Deshalb muss man auch die Reihenfolge beim Catalog Manager anpassen. Gut möglich, dass sich der Vorgang mit der nächsten Major Version ändert. Bei Catalog Manager v1 bleibt erstmal alles beim alten.

**Comment by mlwebworker** [comment]
Danke. Dann weiss ich zumindestens, dass ich nicht irgendwo etwas falsch gemacht habe.
