### ISSUE TITLE
2x speichern eines neuen Datensatzes

### ISSUE THREAD

**Issue by Buglover** [alnv/catalog-manager#2]
Wenn ich unter CM 1.2.0 und Contao 3.5.16 einen neuen Datensatz anlege muss ich immer 2x auf "speichern" oder "speichern und schliessen" klicken, ansonsten wird der Datensatz nicht gespeichert.

**Comment by alnv** [comment]
Die Änderungen habe ich mal zurückgenommen. Das Problem ist erstmal behoben. Bitte ein Update durchführen.

**Comment by alnv** [comment]
Fehler ist behoben in v1.2.4
