### ISSUE TITLE
Listendarstellung im Backend-Modul

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#20]
Habe in der Haupttabelle Felder definiert, die aus Werten der Nebentabellen gespeist werden. Ein Feld ist eine Einzel- das andere eine Mehrfachauswahl. Beide sind so eingestellt, dass in der DB die ID's gespeichert werden.

<img width="1025" alt="banners_and_alerts_und_spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27484383-4e0eb312-5829-11e7-8dc3-06c37fe4e2cc.png">

<img width="625" alt="daten_zeigen_von__sp_reisen_-_84_38_79_65_-_adminer" src="https://user-images.githubusercontent.com/2002902/27484477-a4bf02e8-5829-11e7-8fd5-9afc6f0c86ae.png">

In der Listendarstellung des Backend-Moduls der Tabelle ergibt sich folgende Darstellung:

<img width="1031" alt="spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27484526-dc389c52-5829-11e7-9b83-fa89429cbf06.png">

Wäre toll wenn das auch zu einer Auflösung führen würde …

**Comment by alnv** [comment]
Irgendwie gibt es Probleme mit multiplen Werten… Mal schauen was ich da tun kann :)

**Comment by codiso** [comment]
Wäre klasse, wenn Du das in den Grif bekommst. Mit Zahlen kann man oft nicht direkt was anfangen :-D

**Comment by codiso** [comment]
Bei einfacher Auswahl eines Muliselect-Feldes ist alles OK!

<img width="388" alt="spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27486272-592800d0-5830-11e7-8521-107657dfb253.png">

**Comment by alnv** [comment]
Scheint kein direktes Catalog Manager Problem zu sein. Eventuell gibt es dafür Einstellungsmöglichkeiten, allerdings konnte ich bisher nichts in der Contao Dokumentation finden.
 
Ich schaue mir mal den Contao Quellcode an…

**Comment by alnv** [comment]
Das "reference" Attribute sollte zusätzlich zu den "options" oder "options_callback" gesetzt werden. Weiter erwartet Contao DC_Table Klasse ein serialisiertes array. Was bei Catalog Manager nicht der Fall ist. CM verwendet eine Komma getrennte Liste an Werten. Eine Änderung wäre nicht Rückwärtskompatibel. Aber generell sollte es auch mit einer Komma getrennte Liste funktionieren. Man müsse nur die DC_Tablle Klasse erweitern und da will erstmal ansetzen…

**Comment by MDevster** [comment]
Habe bei einem Projekt das gleiche Problem, wäre schön wenn es hier eine Lösung gebe.

**Comment by alnv** [comment]
Leider kann da nicht viel machen. Hierbei handelt es sich um ein Contao Fehler.

In den nächsten Tage erstelle ich im Contao Core Repository ein Task dazu…
