### ISSUE TITLE
catalogActiveParameters wird für Detailseite benötigt

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#200]
Hallo Alexander,
wenn ich in dem Catalog-Lister die Einstellung "Anzeigen bei aktiven URL-Parameter" aktiviere, lässt sich die Detailseite nicht mehr aufrufen.
![Bildschirmfoto 2019-05-29 um 08 05 27](https://user-images.githubusercontent.com/8830861/58533365-942ec680-81e8-11e9-9f9f-933ca891ee32.png)

Ist das so gewollt? Ich müsste mir das Parameter ja irgendwie über die URL mitgeben lassen um eine funktionierende Detailseite aufrufen zu können.

Der Feldname heisst: catalogActiveParameters

**Comment by alnv** [comment]
Du musst "day" als Parameter übergeben, sonst kann die Listenansicht/Detailansicht aufgerufen werden. Du kannst auch eine separate Detailansicht erstellen. Dazu gibt es ein eigenes FE Modul ohne diese Funktion.

**Comment by webaffin** [comment]
Ich hatte das Problem auch gerade bemerkt und habe es lösen können mit dem Hinweis von @alnv Danke!

Habe im Template die Parameter angefügt an den (automatisch generierten) Link für die Detailseite und es läuft. 

Wäre in deinem Fall @akroii in etwa so
`<p class="more"><a href="<?= $this->masterUrl . '?day=' . \Input::get('day') ?>" title="<?= $this->title; ?>">Detailansicht</a></p>`

**Comment by akroii** [comment]
@webaffin Vielen Dank für den Hinweis!
