### ISSUE TITLE
Eingabefeld wird nicht in DB gespeichert, wenn ausgeblendet

### ISSUE THREAD

**Issue by janoschbatschi** [alnv/catalog-manager#201]
Bug or Feature? 
Wenn man bei einem Eingabefeld "Ausblenden" auswählt, um das Bearbeiten des Feldes durch den User zu verhindern, wird dieses nicht in der DB gespeichert.

**Comment by alnv** [comment]
Mit "Ausblenden" deaktivierst du das Eingabefeld ohne es zu löschen. Daher ist es ein Feature :)

**Comment by janoschbatschi** [comment]
Vielen Dank für die rasche Antwort! 
Was ist dann der Unterschied zu "Verstecken"?
Und wie ist die richtige Vorgangsweise, um zB. eine Mitglieds-ID mitzuspeichern?

**Comment by alnv** [comment]
Im Backend geht es nur mit einem Select-Menü. 

Im Frontend kannst du im "FE Modul Listenansicht" > unter der "Frontend Editing-Einstellungen" Palette im "Standardwerte festlegen" Eingabefeld die Mitglied-ID speichern. Spalte auswählen und {{user::id}} als Standardwert eintragen.

Eventuell hilft es dir Weiter: https://github.com/alnv/catalog-manager/issues/1

**Comment by janoschbatschi** [comment]
Danke für den Tipp, genau so mache ich es auch :) Die Frage war, ob es eine elegante Möglichkeit gibt, das Eingabefeld mit der {{user::id}} zu verstecken.
