### ISSUE TITLE
AJAX im Frontend Editing

### ISSUE THREAD

**Issue by janoschbatschi** [alnv/catalog-manager#202]
Es wäre vllt. anzudenken, den Code für "Submit on change" in FrontendEditing.php von this.form.submit() auf zB. - in meinen Fall eine jQuery-Variante - $(this).closest('form').submit() zu ändern.

Dadurch kann man das Event abfangen und die Ajax Funktionalität von https://github.com/richardhj/contao-ajax_reload_element relativ einfach einbauen.

**Comment by alnv** [comment]
Mann könnte auch per JS-Script das "onchange" Attribut manipulieren. Ich würde ungern wegen einem kleinem Code-Schnipsel jQuery verwenden bzw. das Formular von jQuery abhängig machen.

**Comment by janoschbatschi** [comment]
jQuery Abhängigkeit ist natürlich ein Argument.
