### ISSUE TITLE
Beim Duplizieren im FE-Editing bleibt der Link zur Detailansicht gleich

### ISSUE THREAD

**Issue by janoschbatschi** [alnv/catalog-manager#203]
Beim Duplizieren im FE-Editing bleibt der Link zur Detailansicht gleich und die Einträge sind in der Detailansicht doppelt vorhanden (alias bleibt identisch)

Reproduzierbar in Demo: 
https://demo.catalog-manager.org/de/vereinsmitglieder/edit

**Comment by alnv** [comment]
Ist gefixt in v1.31.1
