### ISSUE TITLE
Bilder werden nicht als <picture> ausgegeben

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#204]
Hallo Alexander,
wenn ich mit einem Modifizierer die Tabelle tl_calendar_events erweitere und die Events im Frontend mit dem ctlg_view_teaser abfrage, ist die Variable `$this->picture` nicht mehr vorhanden, sondern nur noch `$this->singleSRC`. 
Wobei `$this->singleRSC` nur ein einfaches `<img>` mit dem singleSRC (keine gecachte/thumbnail URL).

Selbst als ich versucht habe mit:
```
<?php $objFiles = \FilesModel::findByPk($this->origin["singleSRC"]);?>
{{picture::<?= $objFiles->uuid; ?>}}
```
das `<picture>`-Tag des Event Bildes auszugeben, erhalte ich trotzdem immer nur das Resultat von `<img>` und die dazugehörige singleSRC.

Ich wollte eigentlich ein responsives <picture> Tag mit den sources.

**Comment by akroii** [comment]
Jetzt habe ich einmal folgendes versucht:
```
<?php echo \Controller::replaceInsertTags('{{picture::'.$objFiles->uuid.'}}';?>
```

Und erhalte:
```
[2019-07-16 16:57:29] request.CRITICAL: Uncaught PHP Exception Error: "Cannot use object of type Contao\FilesModel as array" at /Applications/MAMP/htdocs/theater/templates/ctlg_view_teaser_events.html5 line 13 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot use object of type Contao\\FilesModel as array at /Applications/MAMP/htdocs/theater/templates/ctlg_view_teaser_events.html5:13)"} []
```

**Comment by akroii** [comment]
😭
?size=21 hat zum picture-tag gefehlt
```
 <?php $objFiles = \FilesModel::findByPk($this->origin["singleSRC"]);?>
				{{picture::<?php echo $objFiles->uuid?>?size=21}}
```

**Comment by landzone21** [comment]
Ich verwende ebenfalls diesen Code zur Ausgabe der Bilder in der Eventliste des CM. Die meisten Bilder werden korrekt ausgegeben, aber bei einigen erscheint statt des Bildes nur die kryptische uuid, z.B. {{picture::�@�}�z����a?size=4}}
Was ist hier falsch und wie muss die Ausgabe korrekt lauten?

**Comment by alnv** [comment]
Alternativ kann man auch $objFiles->path statt $objFiles->uuid verwenden.

**Comment by akroii** [comment]
@landzone21 try this:
```
$objFiles = \FilesModel::findByUuid($this->origin["singleSRC"]); 
{{picture::<?php echo $objFiles->path ?>?size=21}}
```
