### ISSUE TITLE
[FEATURE] AND als Operator zwischen den Attributen einfügen

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#206]
Hallo Alexander,
wir sprachen neulich ja schoneinmal kurz darüber ;)

Ich hatte neulich versucht mit einer Catalog Liste ein komplexes SQL Query zu erstellen.
Mir ist dabei eingefallen, dass es keine Möglichkeit gibt zwischen den Attributen ein MYSQL-'AND' zusetzen. Das würde mir es ermöglichen auch bei Kalendar-Daten (mit Unix-Timestamp) im Catalog-Lister zu arbeiten.

Siehe hier:
![Bildschirmfoto 2019-07-26 um 14 25 06](https://user-images.githubusercontent.com/8830861/61951556-9ecfc700-afb1-11e9-8e53-171de43e90dc.png)

Man kann zwar mehrere Eigenschaften in ein Datenbank-Feld hineinschreiben, was natürlich bei mehreren Zeitstempeln nicht mehr machbar wäre.

**Comment by alnv** [comment]
Wenn du eine "UND" Abfrage erstellen willst, wähle ein neues Feld aus (es kommt ein Reload) und klicke auf das rechts stehende Plus-Icon.

![61951556-9ecfc700-afb1-11e9-8e53-171de43e90dc](https://user-images.githubusercontent.com/1732915/61956068-a8aaf780-afbc-11e9-8115-4c573836372a.png)

Und verwende am Besten {{CTLG_TIMESTAMP}} statt {{date::U}} [Siehe mit Datum arbeiten](https://catalog-manager.org/dokumentation/mit-datum-arbeiten.html)

**Comment by akroii** [comment]
Ich Depp, ich habe immer auf das "OR" geklickt um meine Einträge zu verknüpfen 😭
