### ISSUE TITLE
[FEATURE] Dateiincludes auf Taxonomieebene

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#208]
Hallo Alexander,
manchmal müssen die Taxonomien sehr ausgefeilt sein, wodurch die Contao-Inserttags bzw. Catalog Inserttags nicht ausreichen. Kann man in später einen Datei-Include auf Taxonomie-Ebene ermöglichen?

![Bildschirmfoto 2019-08-13 um 09 48 47](https://user-images.githubusercontent.com/8830861/62924198-e4610200-bdaf-11e9-9cf9-853a063b6016.png)

**Comment by alnv** [comment]
Also {{file::*}} kannst du jetzt schon einsetzen. Wichtig ist, dass das File ein String zurückgibt.
