### ISSUE TITLE
Filter ausblenden während Frontendediting

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#212]
Der Filter stellt die Option zur Verfügung, "ausblenden bei Detailansicht". Es wäre sinnvol, wenn diese Option um "ausblenden während Frontedediting" erweitert werden würde.

**Comment by alnv** [comment]
Welche Catalog Manager Version hast du im Einsatz? Es gibt Sichtbarkeits-Wrapper (Inhaltselemente). Diese können verwendet werden um bestimmte Inhalte auf der Detail/Listenseite zur verbergen.

**Comment by hoaxone** [comment]
Ahh, vielen Dank. Die Elemente waren mir noch nicht bekannt.
