### ISSUE TITLE
W3C Stray end tag

### ISSUE THREAD

**Issue by ideefixx** [alnv/catalog-manager#215]
Laut W3C ist die Einbindung von CSS in der folgenden Form nicht konform.

<link href="/system/modules/catalog-manager/assets/awesomplete/awesomplete.css" rel="stylesheet" type="text/css"></link>

wird in "CatalogScriptLoader.php" Zeile 88 Col 208 & Col 296 via $GLOBALS['TL_HEAD'] implementiert. Hier sollte "</link>" entfernt werden.

**Comment by alnv** [comment]
ja, der schließende Tag bei dem Link Tag ist unnötig. Dieser wird mit dem Nächsten Update entfernt. Was meinst du mit ""?

**Comment by ideefixx** [comment]
da stand der end-tag drin, wurde wohl beim speichern entfernt ¯\_(ツ)_/¯

**Comment by alnv** [comment]
Ist gefixt in v1.31.11
