### ISSUE TITLE
Problem mit Feldtyp Erklärung

### ISSUE THREAD

**Issue by juehau** [alnv/catalog-manager#216]
Es lassen Sich zwar in den einzelnen Formularen für die
Eingabe Felder deaktivieren, aber Erklärfelder die zu den betreffenden
Feldern gehören nicht. So kann ich für Aktualisierungen durch Frontenduser das Feld für die Zustimmung zu den AGBs abschalten, aber das dazu gehörende Erklärfeld mit dem Link zu den AGBs nicht.

Ich denke ähnliche Problem haben mehrere. Wäre es nicht einfach die Felder
für Erklärungen in Modulen genauso zu behandeln wie die Datenbankfelder
selber?

**Comment by alnv** [comment]
wurde Implementiert in v1.31.12
