### ISSUE TITLE
Eigenes options_callback für Select (BE), um m:n Beziehung abbilden zu können

### ISSUE THREAD

**Issue by webaffin** [alnv/catalog-manager#217]
Ich möchte eine m:n-Beziehung zwischen zwei Tabellen abbilden. Dafür habe ich in der Elterntabelle ein Blob-Feld, welches eine kommaseparierte Liste der zugehörigen Kindelement-IDs enthält. 

Beide Tabellen möchte ich in einem Select-Menü darstellen, das Kind-Select soll nur die zugehörigen Elemente darstellen, die im Elternelement im Blob abgelegt sind. 

So wie ich das verstanden habe, geht das nicht mit Catalog Manager Bordmitteln. Aber geht es, ein eigenes options_callback für das Kind-Select-Menü über das DCA-Array anzulegen, dass dann eine komplexere Logik enthält? 

Wie komme ich an das DCA-Feld des im Catalog Manager angelegten Select-Felds, so dass ich einen eigenen options_callback schreiben kann? Und wie komme ich dann an die Daten des aktuell ausgewählten Eintrags?

Es geht um Contao 4.4.

**Comment by alnv** [comment]
Du kannst ein eigens Modul mit entsprechenden DCA Datei anlegen und dort den options_callback überschreiben. Am besten du legst mit dem Catalog Manager eine einfache Datenbank-Spalte (Feldtyp) an und alle weiteren Optionen definierst du über dein Modul.

Siehe https://docs.contao.org/books/api/dca/reference.html

**Comment by webaffin** [comment]
Danke für den Hinweis. Das hat mir weitergeholfen.

Ich habe es jetzt ein klein wenig anders über den globalen Ordner gelöst statt ein eigenes Modul anzulegen:

`/app/Resources/contao/dca` angelegt und dort eine Datei mit dem Namen der Datenbank-Tabelle, die ich über den CM angelegt habe: `ctlg_cad_downloads.php`

Dort habe ich dann den options_callback definiert:

`$GLOBALS['TL_DCA']['ctlg_cad_downloads']['fields'][<Feldname>]['options_callback'] = ['CatalogManager\CadDownloads', 'gearbox_size_callback'];`

In der gleichen Datei dann auch die Klasse mit der Funktion angelegt, die ich im `options_callback` definiert habe.
