### ISSUE TITLE
Timestamp im Feld "Eindeutige Bezeichnung"

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#218]
Im Feld "Eindutige Bezeichnung" wird der Timestamp nicht umgesetzt, der Inserttag bleibt stehen. Die folgenden Einstellungen sind gesetzt:

![Feldeinstellung](https://user-images.githubusercontent.com/2067428/65256204-72db4880-daff-11e9-9276-4ea01177243b.JPG)

Das Ergebnis:
![Ergebnis](https://user-images.githubusercontent.com/2067428/65256229-7a9aed00-daff-11e9-8969-34a6ae58bf66.JPG)

Wie kann als dynamischer Wert im Feld "Eindeutige Bezeichnung" ein Timestamp eingesetzt werden?
{{date::U}} funktioniert ebenfalls nicht.

**Comment by alnv** [comment]
Insert tags werden nur im Front end aufgelöst.
