### ISSUE TITLE
Sortierung von Modullisten

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#22]
Habe Probleme die Listen in den Moduldarstellungen zu sortieren. Ich kann zwar eine Sortierung in der Moduldefinition definieren. Allerdings nicht in der Darstellung der Liste. Habe ich da was übersehen?

<img width="1271" alt="spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27486962-8ace7d4c-5832-11e7-8b53-c229724bca02.png">

**Comment by codiso** [comment]
Hast Du da eine Lösung für mich? Wird das in der Zukunft möglich sein?

**Comment by alnv** [comment]
Sorry für die verspätete Antwort :) Man kann die Datensätze über den Panel Layout sortieren.

Als erstes müssen wir in den **Backend Modul** die **Darstellung** auf **Sortierung nach einem variablen Feld** setzen.
![Catalog Manager Datensätze sortieren im Backend](https://catalog-manager.alexandernaumov.de/files/theme/media/github/catalog-manager-sorting-2.png)

Danach die **Sortierung** im **Panel Layout** aktivieren.

![Catalog Manager Datensätze sortieren im Backend](https://catalog-manager.alexandernaumov.de/files/theme/media/github/catalog-manager-sorting-2.png)

und im letztem Schritt wählen wir Felder für die Sortierung aus. Dazu gehen wir zu den **Eingabefeld Einstellungen** > **Panel Layout Einstellungen**

![Catalog Manager Datensätze sortieren im Backend](https://catalog-manager.alexandernaumov.de/files/theme/media/github/catalog-manager-sorting-3.png)

Ab v1.4 sind folgende Felder standardmässig für die Sortierung aktiviert: 
_Titel, ID, Timestamp_
Momentan gibt es keine Möglichkeit diese auch in die Sortierung aufzunehmen.

**Comment by alnv** [comment]
Title, ID und Timestamp sind nun automatisch für die Sortierung freigeschaltet.
