### ISSUE TITLE
Datensätze anzeigen von/bis bei FE-Editing

### ISSUE THREAD

**Issue by landzone21** [alnv/catalog-manager#220]
Hallo,
ich brauche die Funktion Anzeigen von/bis, wie wird das denn implementiert? In der Demo sehe ich unter Equipment die Felder, aber sie sind nicht eindeutig als Eingabefelder definiert. Wo finde ich die entsprechenden Einstellungen dazu? Die Felder sollen auch im FE-Editing verfügbar sein.
Danke für die Info

**Comment by landzone21** [comment]
Vielen Dank, das hab ich gefunden. 
Nun tritt folgendes Phänomen auf: Ich gebe einem Datensatz ein "Anzeigen-bis"-Datum. Dann verschwindet es ab diesem Dateum wie gewünscht im Frontend, aber auch in der FE-Editing-Ansicht. In der FE-Editing-Ansicht sollte es doch aber sichtbar bleiben, sonst hat der Editierende ja nie wieder Zugriff darauf. Oder lieg ich da falsch in meiner Logik? Kann man das unterscheidbar machen? Danke.

**Comment by landzone21** [comment]
Hab wohl zu kompliziert gedacht. 
Für die FE-Ausgabe erstelle ich eine Listenansicht mit Filter Datum >=timestamp, damit werden alle älteren Daten automatisch ausgeblendet. 
Für das FE-Editing erstelle ich eine weitere Listenansicht ohne diesen Filter. Dann brauch ich die Operatoren "Anzeigen von" und "Anzeigen bis" gar nicht.

**Comment by alnv** [comment]
Schau dir die Einstellung "Sichtbarkeit ignorieren" an. Diese findest du unter FE-Module -> Frontend Editing-Einstellungen. Damit sollte es gehen…
