### ISSUE TITLE
Fine Uploader im Frontend

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#221]
Hallo.

Während der Upload einer Datei funktioniert, wird das Bild dem Datensatz nicht zugewiesen. Die manuelle Auswahl im Backend funktioniert, im Frontend nicht. Es gibt auch keine Fehlermeldung. 
In der Demo unter Vereinsmitgliedern scheint das selbe Problem zu herrschen.

**Comment by alnv** [comment]
Die Option "Hochgeladene Dateien speichern" muss aktiviert sein.
<img width="1098" alt="screenshot" src="https://user-images.githubusercontent.com/1732915/68309085-344d1d80-00ae-11ea-90f1-4dfbf44e31f0.png">

**Comment by hoaxone** [comment]
Diese war aktiviert. Das Problem war die Option Benutzerverzeichnis verwenden.
