### ISSUE TITLE
Relational links

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#222]
Hi Alexander,

Great product!!!

I have an issue with "relational links" in the "catalog list view" module.
I only see 1 child table for a relational link, but I have 3 child tables on the parent table.
The 3 child tables are shown some lines above in "Join child tables".
See below snapshots
Addtionally:

1. Is it possible to add parameters to the relational link(e.g. ?user=username). If I do so, the pid parameter can not be used, because of a wrong parameter list, pid always is added at the end, like this: ?user=username?pid=123
2. Can I catch the pid or {{CTLG_ACTIVE::pid}} before the next page is called?

![ScreenHunter_123 Oct  28 15 11](https://user-images.githubusercontent.com/32883690/68305731-75daca00-00a8-11ea-9db2-fe56bcce5bff.jpg)

![ScreenHunter_128 Nov  06 15 15](https://user-images.githubusercontent.com/32883690/68305657-5d6aaf80-00a8-11ea-8196-f85a858cf498.jpg)

**Comment by robvis** [comment]
Hallo Alexander,
Gib's schon eine Loesung fuer diesem Problem?

**Comment by alnv** [comment]
Hi,

1. Currently not possible. But would be possible via the template.
2. The {{CTLG_ACTIVE::*}} Insert tag reads the GET/POST parameters. The parameters are removed when the page is changed. The GET parameters can theoretically be appended to the URL e.g. ?pid=123
