### ISSUE TITLE
losing pid and {{CTLG_ACTIVE::xxxx}} parameter in Wishlist

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#223]
Hi Alexander,

Wishlist usage:
On using the buttons "add to wishlist" and "remove from wishlist" I'm loosing the {{CTLG_ACTIVE}} fields, including the pid. So on return off the button push my list has been extended with other records with a different pid. (pid = null now).
Filter and wishlist are on 2 different pages, like below.

![ScreenHunter_128 Nov  06 15 28](https://user-images.githubusercontent.com/32883690/68307207-28139100-00ab-11ea-8c66-43432cefdcfb.jpg)

**Comment by robvis** [comment]
Hallo Alexander,
Haben Sie schon dass Problem angeschaud?

**Comment by alnv** [comment]
The links are not generated generically. These must be extended accordingly in the template. Try to append the parameters to the URLs.
