### ISSUE TITLE
Fine Uploder MySql Blob

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#224]
Ich hätte eine Frage zum Datenbankeintrag durch den File Uploader. Wir führen eine Austausch zwischen einer SQL und der MySQL Datenbank durch und greifen auch die Bilder ab. 

Bei jedem Upload eines Bildes wird anscheinend die ID des Bildes als Blob in das entsprechende Datenbankfeld des Kataloges eingetragen. Der Eintrag ist immer entweder ein [BLOB - 16 B] oder ein [BLOB - 34 B]. In den meisten Fällen verweist der Eintrag auf die UUID des Bildes. In einigen Fällen wird dem anscheinend noch was hinzugefügt. Gibt es hier eine einfache Erklärung? Und an welcher stelle des Codes kann man das Generieren des bLobs nachvollziehen?

**Comment by alnv** [comment]
Das hängt mit dem Contao Framework zusammen. Dabei handelt es sich um ein Datenbank gestütztes Filesystem, man muss beim auslesen die Pfade über die tl_files Tabelle auflösen:

``` php
$objFile = \FilesModel::findByPk($this->uuid);
$strPath = $objFile->path;
```

**Comment by hoaxone** [comment]
Vielen dank
