### ISSUE TITLE
Beschränkung der Auswahl von Items

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#225]
Hallo Alexander,

für die Situation, dass in Katalag A Items angelegt werden (z.B.: 101, 102, 103, 104) und in Katalog B  diese Items ausgewählt werden können. 

Ist es möglich die Auswahl der Items so einzuschränken, dass wenn 
"Eintrag 1 Katalog B"  101, 102 
auswählt, für 
"Eintrag 2 Katalog B"  nur noch 103, 104 
zur Verfügung steht?

Ich hoffe ich konnte das anständig erklären.

**Comment by alnv** [comment]
Grundsätzlich ja, wenn die beiden Felder verknüpft sind. Das Thema an sich ist etwas komplizierter, gerne kannst du dazu das Support Ticket verwenden: https://catalog-manager.org/support-ticket.html

**Comment by hoaxone** [comment]
Ist das eine Frage der Konfiguration oder muss hierfür zugearbeitet werden?
