### ISSUE TITLE
No template variable for ContentVisibilityPanelStart/-Stop leads to type error

### ISSUE THREAD

**Issue by FKasy** [alnv/catalog-manager#226]
https://github.com/alnv/catalog-manager/blob/48157dcdc0da26a4c3b5108b804893e50fbeaab3/library/alnv/Elements/ContentVisibilityPanelStart.php#L6

Currently the [contao-bootstrap/core-bundle](https://github.com/contao-bootstrap/core) throws an error when using it together with the [Catalog Manager](https://github.com/alnv/catalog-manager) which is:
> Type error: Argument 2 passed to ContaoBootstrap\Core\Listener\TemplateParseListener::parse() must be of the type string, null given, called in ...

This happens when using the Content Element ContentVisibilityPanelStart (_Catalog Manager (Sichtbarkeit - Umschlag Anfang)_ ) and ContentVisibilityPanelStop (_Catalog Manager (Sichtbarkeit - Umschlag Ende)_ ) inside an article. 

The problem is that unfortunately the Content Element does not provide a strTemplate variable.

This could be resolved by simply including a empty template file 
(e.g. called ce_ContentVisibilityPanelStart.html) together with the respective declaration:
`protected $strTemplate = 'ce_ContentVisibilityPanelStart';` 
inside the class.

Meanwhile these content elements can't be used when having any of the contao-bootstrap bundles installed (since they all depend on the core).

**Comment by alnv** [comment]
Ist gefixt in v1.31.20
