### ISSUE TITLE
Getrennte Kleinschreibung u. Umschreibung für das Routing und BE/FE

### ISSUE THREAD

**Issue by CONTEGRA** [alnv/catalog-manager#227]
Hallo Alexander,

ich habe einen Katalog für Stadtteile angelegt, in dem die eindeutige Bezeichnung in Großbuchstaben und der Alias ordnungsgemäß umgeschrieben (ohne Umlaute) und in Kleinbuchstaben generiert wird.

In einem anderen Katalog wird per Select-Menü und Datenbank Auswahlliste die Wertspalte mit dem Stadtteil-Alias gefüllt. Das Routing wäre mit dieser Einstellung korrekt, allerdings erfolgt dann im BE als auch im FE per {{CTLG_ACTIVE::stadtteil}} die Ausgabe in Kleinschrift.

Befülle ich die Wertspalte z.B. mit der eindeutigen Bezeichnung des Stadtteils, dann wird beim Routing der Stadtteilname in der URL mit Großbuchstaben und Umlauten geschrieben, was nicht gewünscht ist.

Gibt es hierfür eine Lösung oder ließe sich das in einer zukünftigen Version realisieren?

**Comment by alnv** [comment]
Dein Anliegen verstehe ich nicht ganz, was genau versuchst du zu konfigurieren? 

Das {{CTLG_ACTIVE::*}}  Insert Tag ließt nur die GET-Parameter aus und gibt diese so wie sie sind zurück.
