### ISSUE TITLE
[Feature] Weiteres duplizierbares Eingabefeld

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#228]
Es wäre schön, wenn man ein Eingabefeld hinzufügen könnte, welches man per (+) Button im Backend duplizieren kann. Dieses speichert dann Eingaben in einem serialisierten Array in einer Spalte.

Zugegeben, es ist nicht ganz einfach. Denn wiederum müsste man das Feld auch wieder auslesen. Ist daher nur eine Idee.

Als Idee:
<img width="718" alt="Bildschirmfoto 2019-11-10 um 18 32 41" src="https://user-images.githubusercontent.com/8830861/69987206-40a68800-153f-11ea-93ed-874afb3aafcd.png">

**Comment by ngdot** [comment]
Einfacher wäre doch das Inhaltselement "Aufzählung" mit aufzunehmen, oder? @alnv 
Könnte ich aktuell auch gut gebrauchen.

**Comment by alnv** [comment]
Im Grunde ist es wie hier beschrieben: 
https://github.com/alnv/catalog-manager/issues/142#issuecomment-455451222

Nur "listWizard" statt "keyValueWizard".
