### ISSUE TITLE
Dokumentation: Fehler bei "Datensatz an Benutzer binden"

### ISSUE THREAD

**Issue by Samson1964** [alnv/catalog-manager#229]
Im Schritt 4 unter https://catalog-manager.org/dokumentation/catalog-manager-frontend-editing.html fehlt der Hinweis, daß das Autor-Feld als verstecktes Feld erstellt werden sollte. Als Wert wird dort dann {{user::id}} eingetragen.
In der aktuellen Doku ist es ein select-Menü und der Browser hängt sich bei der Erstellung der Auswahlliste mit -zig Tausenden Mitgliedern gern mal auf. Man müßte dort umständlich seinen eigenen Namen suchen. Wenn man den falschen Namen erwischt, wird der Datensatz nach dem Speichern dem falschen Mitglied zugeordnet.

**Comment by alnv** [comment]
Grundsätzlich sollte man je nach Anforderung das passende Eingabefeld wählen. Daher gibt es mehrere Eingabefelder zur Auswahl. Ich belasse die Doku erstmal wie es ist. Wichtig, ist das man das Prinzip/Aufbau verstanden hat.

**Comment by 360fusion** [comment]
I've been trying to work out how to do this on an off for days.

I've been using a dropdown and when a user creates a new entry it's not assigned to them. I was using the dropdown as it was on the documentation page.

It would be really helpful to add some documentation around frontend editing and the reocrd being assigned automatially to the user that created it.

Just saying use a hidden field and add {{User:id}} to the default value would be great. For others, obviously I know this now.
