### ISSUE TITLE
Datei-Upload beim FE-Editing

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#23]
Hallo Alexander,

wenn man im FE einen Datensatz editieren will, der ein (hochgeladenes) Bild enthält, findet man dort den Button "Durchsuchen" und dahinter den Zusatz "Keine Datei ausgewählt". 

Da ich fürchte, dass FE-User glauben, was da steht, und daher ein Bild noch einmal (und noch einmal) hochladen - ist es möglich, in der Editiermaske den im Datensatz gespeicherten Dateinamen und/oder das Bild mit auszugeben?

VG
Anke

**Comment by alnv** [comment]
Möglich ist es. Ich packe es auf die todo Liste.

**Comment by Anke** [comment]
Danke :-). Wusste nicht, ob das evtl über das Template möglich ist

**Comment by alnv** [comment]
Eine Vorschau Funktion für den Datei/Bild Upload kommt voraussichtlich mit der 1.5 Version.

**Comment by alnv** [comment]
Vorschau Bild wurde implementiert.  Es gibt zwei neue Attribute:
- catalogAttributes
- preview

Das **catalogAttributes** Attribute liefert alle Werte des Datensatzes aus. Dieses Attribute kann bei folgenden Templates verwendet werden:
- form_*
- form_catalog_*

Das **preview** Attribute liefert das Vorschau Bild. Nur bei _form_upload_ & _ctlg_form_fine_uploader_ Templates möglich.

Beispiel Code für die Ausgabe ( ctlg_form_fine_uploader ):

``` php
<?php if ( $this->preview && is_string( $this->preview ) ): ?>
      <?= $this->preview ?>
<?php endif; ?>
```
