### ISSUE TITLE
Checkbox-Menü: BE-Formular zeigt keine ausgewählten Elemente

### ISSUE THREAD

**Issue by Samson1964** [alnv/catalog-manager#231]
Beim Typ Checkbox-Menü sind im Backend-Formular die Checkboxen nicht aktiviert, die gespeichert wurden. In der Datensatz-Übersicht werden die ausgewählten Optionen richtig angezeigt.

Im Frontend wird ein vom Formular-Generator (FG) erstelltes Formular abgeschickt. Das Feld Checkbox-Menü des FG speichert in der Datenbank einen serialisierten String. Der CM kommt damit im Backend in der Datensatz-Übersicht klar. Nur in der Formular-Ansicht im Backend wird wohl was anderes erwartet.

Speichert man im Backend den Datensatz mit aktivierten Optionen, werden die Optionen in der Form "Option1,Option2" in die Datenbank geschrieben. Nun klappen auch beide Ansichten (Datensätze, Formular).

In der Datensatz-Übersicht ist zudem die Anzeige unterschiedlich. Steht nur 1 Option in der Datenbank, wird der Name angezeigt - also "1. Turnier" statt "1". Sind zwei Optionen aktiviert steht nicht da "1. Turnier,3. Turnier" sondern "1,3".

**Comment by alnv** [comment]
> Beim Typ Checkbox-Menü sind im Backend-Formular die Checkboxen nicht aktiviert, die gespeichert wurden. In der Datensatz-Übersicht werden die ausgewählten Optionen richtig angezeigt.

Dazu benötige ich deine Konfiguration. Ich kann es leider nicht reproduzieren

> Im Frontend wird ein vom Formular-Generator (FG) erstelltes Formular abgeschickt. Das Feld Checkbox-Menü des FG speichert in der Datenbank einen serialisierten String. Der CM kommt damit im Backend in der Datensatz-Übersicht klar. Nur in der Formular-Ansicht im Backend wird wohl was anderes erwartet.

Erwartet wird eine "CSV" Liste: wert1,wert2

> In der Datensatz-Übersicht ist zudem die Anzeige unterschiedlich. Steht nur 1 Option in der Datenbank, wird der Name angezeigt - also "1. Turnier" statt "1". Sind zwei Optionen aktiviert steht nicht da "1. Turnier,3. Turnier" sondern "1,3".

Ist ein Contao Bug: https://github.com/alnv/catalog-manager/issues/20
Man müsste es an das Contao Core-Team weitergeben.
