### ISSUE TITLE
KeyValue Wizard - Labels anpassen

### ISSUE THREAD

**Issue by saress** [alnv/catalog-manager#232]
Hallo,

es wäre ideal, wenn man beim KeyValue-Wizard die Labels (Schlüssel , Wert) anpassen könnte.

Vielen Dank und beste Grüße
Sares

**Comment by alnv** [comment]
Hi,

das Widget ist ein Bestandteil von Contao: https://github.com/contao/core-bundle/blob/master/src/Resources/contao/widgets/KeyValueWizard.php

Laut Quellcode kannst du es über die `$GLOBALS['TL_LANG']['MSC']['ow_key']` und `$GLOBALS['TL_LANG']['MSC']['ow_value']` Variablen anpassen.
