### ISSUE TITLE
Google Maps: Infobox automatisch schließen

### ISSUE THREAD

**Issue by tastethecake** [alnv/catalog-manager#233]
Moin. 
Gibt es bei der Google-Map-Funktion die Möglichkeit, dass die kleinen Infoboxen zu den Orten  automatisch wieder verschwinden, wenn man einen anderen Ort anklickt?
Das ist das normale Verhalten dieser Infoboxen bei Google Maps. Nicht jedoch, wenn ich einen Katalog mit vielen Orten erstelle und diesen als Liste mit Kartenansicht ausgebe. 
Da bleiben die Infoboxen offen und müssen händisch geschlossen werden.

**Comment by alnv** [comment]
Hallo,

im "ctlg_map_default" Template sind entsprechende Einstellungen zu finden, vermutlich gibt es dazu ein Codeschnipsel, welches man einfügen könnte.

Ich packe es auf die todo liste.

**Comment by tastethecake** [comment]
Super, danke!

Was mir noch aufgefallen ist: die Infoboxen erscheinen nicht auf der Detailseite eines Ortes, wenn dort auch die Karte integriert ist. Dort erscheint nur ein kleine leere Box. 
Es wäre toll, wenn auch dafür Infos eingegeben werden können, zumal die Orte, die direkt von Google kommen, alle eine volle Infobox haben.

**Comment by Floxn** [comment]
`objInfoBox.close()` wäre das Stichwort. Nur weis ich nicht wo genau einfügen. Direkt vor [Zeile 19](https://github.com/alnv/catalog-manager/blob/master/templates/ctlg_map_default.html5#L19) hatte ich gedacht, aber das tut leider nicht :(
