### ISSUE TITLE
Filtergenerator mit Select-Menü zeigt keine Werte an, die in Datenbank ID 1 haben

### ISSUE THREAD

**Issue by webaffin** [alnv/catalog-manager#234]
Contao: 4.4.46
Catalog Manager: 1.31.21

Ich habe einen dreistufigen Filter mit dem Filtergenerator erstellt, der mir am Ende mögliche Downloads ausgibt. Es geht um CAD-Zeichnungen von Getrieben. Die einzelnen Filterstufen hängen voneinander ab. In der letzten Stufe muss die Getriebe-Übersetzung ausgewählt werden. Anbei ein Screenshot der Einstellungen des Filtergenerators der letzten Filterstufe.

![Filtergenerator-Auswahlliste-Einstellungen-Übersetzungen](https://user-images.githubusercontent.com/12136756/73254751-4a570f80-41bf-11ea-958d-8f2d46c44bdc.png)

Hier gibt es den sonderbaren Effekt, dass eine im Backend zugeordnete Übersetzung nicht angezeigt wird (nämlich die `1:1`). Ich konnte feststellen, dass es sich um die Übersetzung handelt, die in der zugehörigen Datenbank die ID `1` besitzt. Alle anderen Übersetzungen werden korrekt im Dropdown aufgelistet.

Die Übersetzungen werden im Backend über ein Checkbox-Menü (also multiselect) ausgewählt. Die IDs der zugeordneten Übersetzungen werden in der Datanbank in einem Blob gespeichert.

Ich habe einen Screenshot angehängt von den im Backend zugeordneten Übersetzungen (bei mehreren werden nur die IDs angezeigt), man erkennt auch die `1`; außerdem einen Screenshot vom ausgeklappten Dropdown des Filters. Man sieht, dass hier die 1:1 fehlt (das ist die Übersetzung mit ID `1`).

![Liste-Downloads-mit-Übersetzungen-BE](https://user-images.githubusercontent.com/12136756/73254713-3c08f380-41bf-11ea-9229-9210af7d0ea5.png)

![Liste-Downloads-mit-Übersetzungen-FE](https://user-images.githubusercontent.com/12136756/73254736-44f9c500-41bf-11ea-874b-3302839cfc33.png)

Ich habe nun zum Test die Übersetzung 1:1 mit der ID `1` in der Datenbank an allen Stellen auf eine andere ID gesetzt (z.B. `123`) und siehe da: die 1:1 (jetzt mit ID `123`) wird im Dropdown des Filters plötzlich korrekt angezeigt.

Die Werte der anderen drei Dropdowns haben zufällig alle keine IDs mit `1`, sondern höhere Werte. Das habe ich auch noch in der DB kontrolliert. Hier sind die angezeigten Daten auch vollständig.

Meine Idee: Könnte es vielleicht sein, dass dieser Bug irgendwo in der Programmierung des Catalog Managers durch einen nicht strengen Vergleichsoperator verursacht wird? Der die `1` nicht als Zahl sieht, sondern als true?

P.S. Ich habe gerade noch etwas herausgefunden: Steht in dem o.g. Blob als einzige ID die `1`, dann wird die entsprechende Übersetzung angezeigt! 

Und noch etwas: Stehen die ID `1` und weitere IDs im Blob, so wird die die der ID `1` zugehörige Übersetzung 1:1 tatsächlich auch angezeigt, wenn die `1` die erste ID in der Reihe der IDs ist.

Beispiel: 
`2,3,1,11,12,7,5` => 1:1 wird nicht angezeigt
`1,2,3,11,12,7,5` => 1:1 wird angezeigt

**Comment by alnv** [comment]
Es müsste eine andere Ursache geben, das mit der ID 1 konnte ich nicht reproduzieren.

**Comment by webaffin** [comment]
Okay, hätte ja sein können, dass dir etwas auffällt. Ich kann es mir aktuell auch nicht erklären.

Ich habe nun erstmal als Workaround alle Einsen in den Zahlenreihen, die in der Tabelle in den Blobs gespeichert sind, manuell an den Anfang der Reihe verschoben. So funktioniert es erstmal.

Ich behalte das Problem im Auge und poste, falls ich neue Erkentnisse gewinne.
