### ISSUE TITLE
Verstecktes Feld auch im Backend

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#237]
Hallo Alexander,
ist es möglich, dass man ein `Verstecktes Feld` auch im Backend für anderen Nutzern verstecken kann? Also praktisch ein `<input type="hidden" .... >` nur im Backend.

**Comment by alnv** [comment]
Hallo,

dazu fehlt das passende Widget im Contao: https://github.com/contao/core-bundle/tree/master/src/Resources/contao/widgets

Sollte ein Hidden-Feld existieren, kann man es ganz einfach mit einer DCA-Anpassung verwenden: https://github.com/alnv/catalog-manager/issues/142#issuecomment-455451222
