### ISSUE TITLE
FR: Catalog-Listenansicht: Bild ausgeben

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#24]
Wie in der Catalog-Demo habe ich Vereine zu verwalten, zu denen auch jeweils ein Vereinslogo vorliegt. Das würden wir gerne nicht nur in der Detailansicht, sondern auch in der Listenansicht mit ausgeben. Das Feld (in unserem Fall 'club_logo') ist aber unter "Listeneinstellungen/Kopfzeilen auswählen" nicht vorhanden, auch in der Demo nicht. Kannst du das gelegentlich mit aufnehmen?

**Comment by alnv** [comment]
Hi, kommt mit dem nächsten Update (v1.3), wenn alle tests erfolgreich waren :)

**Comment by alnv** [comment]
Catalog Manager v1.3 ist online. Bilder können ausgegeben werden.
