### ISSUE TITLE
frontend editing mehrfachauswahl

### ISSUE THREAD

**Issue by raynor84** [alnv/catalog-manager#240]
Hi,

kann es sein, dass die mehrfachauswahl nur im Backend funktioniert? Im Frontend kann man nur einen Eintrag aus der Datenbank wählen. Im Backend mehrere.

**Comment by alnv** [comment]
Welches Eingabefeld meinst du?  Wenn Mehrfachauswahl gesetzt ist, sollte es funktionieren.

**Comment by raynor84** [comment]
![Bildschirmfoto 2020-03-26 um 08 03 30](https://user-images.githubusercontent.com/4583529/77619505-a082cd80-6f38-11ea-8c76-1e096597e1d1.png)
Die Datenbank auswahl erscheint, aber im Frontend wird kein Komma nach dem ersten Eintrag gemacht und wenn ich nach dem Komma was eintrage, dann werden keine Vorschläge gemacht.

**Comment by raynor84** [comment]
Das Eingabefeld ist ein Textfeld.

**Comment by alnv** [comment]
Ich kann das Problem nicht reproduzieren. Wichtig ist ein Leerzeichen zwischen den Kommas zu lassen z.b Test, Test123.

**Comment by raynor84** [comment]
hmmm… naja gut, ich werds bei Gelegenheit nochmal testen. Brauche das Feature doch nicht mehr.
