### ISSUE TITLE
Größer / Größer gleich Filter funktionieren nicht.

### ISSUE THREAD

**Issue by m-knorr** [alnv/catalog-manager#242]
Wir erarbeiten aktuell einen größeren Produktkatalog mit Filter Funktion.

Nun gibt es ein Problem bei den Filtern Größer & Größer gleich.

Der Produktkatalog hat ein Feld Temperatur, hier dürfen nur Zahlenwerte eingetragen werden.

Als Filter dient ein Textfeld zur Eingabe. Testweise hatten wir auch ein Select genutzt.

Filtersetup im Listing ist

- Feld: Temperatur
- Operator: Größer oder Größer gleich
- Wert: {{CTLG_ACTIVE::temperature}}

Bei einem Wert von z.B. 200, werden die Items mit den Temperaturwerten 62, 80, 70 & 84 angezeigt. Was ja leider nicht korrekt ist. 🤔 

Wo könnte der Fehler liegen?

**Comment by alnv** [comment]
Ist der SQL-Datentyp auf INT gestellt?

**Comment by m-knorr** [comment]
Danke für deine Rückmeldung.

Ja der Datentyp ist `int(10) unsigned NOT NULL default '0'`

**Comment by alnv** [comment]
Überprüfe ob im Feld "Temperatur" auch tatsächlich die Datenstehen die du erwartest. Das kannst zu z.B mit PHPMyAdmin machen.

Ein Bug beim CM sehe ich momentan nicht.

**Comment by m-knorr** [comment]
In der Datenbank per Sequel Pro geprüft, da sind die korrekten Daten eingetragen. 🤔

**Comment by m-knorr** [comment]
Bei einer Filterung nach "Gleich" funktioniert der Filter korrekt.

Beim Filtern Kleiner/Kleiner Gleich, scheint er nur Zahlen die dreistellig sind zu "respektieren" 🤔 

Bei einer im Filter eingetragenen Ziffer von 190 gibt das Listing 4 Ergebnisse mit 130, 150, 100 & 155 aus. Es müssten aber auch Elemente mit Werten unter 100 auftauchen.

Ich habe bereits das Feld komplett neu angelegt und neu gepflegt. Gleiches verhalten.

**Comment by alnv** [comment]
Sollte in v1.31.27 behoben sein.

**Comment by m-knorr** [comment]
Scheint jetzt zu funktionieren. Vielen Dank! 👍
