### ISSUE TITLE
Eindeutige Bezeichnung in Datensatz nicht mehr editierbar

### ISSUE THREAD

**Issue by LarsLuz** [alnv/catalog-manager#243]
Innerhalb eines angelegten Backend-Moduls wurden verschiedene Datensätze erstellt. Das Feld für die eindeutige Bezeichnung innerhalb eines solchen Datensatzes ist zwar via Formular editierbar, aber sobald es abgeschickt wird werden die Eingaben nicht übernommen. Nach dem Neuladen steht der alte Wert wieder im Formular. Alle anderen Felder sind normal editier- und speicherbar.

Wir haben schon auf die neuste Version per Composer geupdated

**Comment by alnv** [comment]
Vermutlich wurde unter Catalog Einstellung (Be-Modul) > Feld-Einstellung (Palette) >  Dynamischer-Wert für eindeutige Bezeichnung (Eingabefeld) ein Wert deklariert. 

Wenn ja, kannst es rausmachen, dann sollte es gehen.

**Comment by LarsLuz** [comment]
Vielen lieben Dank, wir probieren das morgen direkt aus!

**Comment by LarsLuz** [comment]
VIelen Dank, dass hat das Problem gelöst.
