### ISSUE TITLE
Spacing in masterurl 

### ISSUE THREAD

**Issue by Messa1** [alnv/catalog-manager#244]
I have set up a frontend-modul do show categories and i set up a individuell page for showing details. When i checkt the frontend it change the masterurl but false.

`<?= $this->masterUrl ?>`

**dienstleistungen/%20/geschaeftskunden.html**
should be 
**dienstleistungen/geschaeftskunden.html**

![Bildschirmfoto 2020-04-27 um 11 50 14](https://user-images.githubusercontent.com/3908658/80359108-a9d7c080-887d-11ea-918f-8d7a5697c2d3.png)

Best Regards
Matthias

**Comment by Messa1** [comment]
after creating a new site an setting up again, the bug i gone.

**Comment by Messa1** [comment]
Ah oky, i know now how to reproduce the error.

![Bildschirmfoto 2020-04-27 um 14 17 49](https://user-images.githubusercontent.com/3908658/80371263-e7464900-8891-11ea-84f5-249aac3b4dfd.png)

If i set up masterpage and use it also for routing the taxonomie.
Is that something i can do like i show here?

At the moment i get no results.
I want to show taxonomie (image and description) and all "dienstleistungen" that are in this category. Also auto_item for "dienstleistungen".

So the final result should be:

dienstleistungen/geschaeftskunden.html - View with image / description and all dienstleistungen

dienstleistungen/geschaeftskunden/dienstleistung.html - Details View of the "dienstleitung"

**Comment by alnv** [comment]
- Your category should be a required field so that no empty aliases are generated.
- You can access the routing values with {{ CTLG_ACTIVE::fieldname }}. Just like a normal filter form

**Comment by Messa1** [comment]
Category is required at "Dienstleitungen".
![Bildschirmfoto 2020-04-27 um 19 56 56](https://user-images.githubusercontent.com/3908658/80404371-61da8d00-88c1-11ea-9830-20557f6cf634.png)

Dienstleistung-Kateforien
![Bildschirmfoto 2020-04-27 um 19 58 05](https://user-images.githubusercontent.com/3908658/80404427-7585f380-88c1-11ea-9eba-744b2a3a3942.png)

I don't hava a single view routing page for "Dienstleistungen" alone.

I try to set it up like that.
dienstleistungen/categorie.html
dienstleistungen/categorie/item.html

dienstleistungen is a page in contao with the settings in my post before.

**Comment by Messa1** [comment]
Oky, if found the "problem" If i turn off the module to show category infos it woks.
I thought i could get category image, headline and description with a new module.

But i think i need another way to access to this infos.

![Bildschirmfoto 2020-04-28 um 11 22 56](https://user-images.githubusercontent.com/3908658/80470743-b4a85900-8942-11ea-897e-2799eb57f3cd.png)
![Bildschirmfoto 2020-04-28 um 11 22 41](https://user-images.githubusercontent.com/3908658/80470736-b2de9580-8942-11ea-9e21-05463957f421.png)
