### ISSUE TITLE
Filtergenerator mit Select-Menü - keine Ausgabe bei bestimmten Zeichen im Value-String

### ISSUE THREAD

**Issue by herrrilke** [alnv/catalog-manager#245]
hallo und guten morgen,

mit
Contao: 4.9.2
Catalog Manager: v1.31.27

erstelle ich einen katalog für installationsbedarf.
dabei soll nach terms wie diesem gefiltert werden:  
`Waschtisch mit Absperrung Grohe 1/2" KW+WW, Wasserzähler Ista 1/2" KW+WW`

CM findet aber die datensätze nicht, wenn ein komma (",") im string ist.
und die anführungszeichen konnte ich nur unschädlich machen, indem ich im template die ausgabe in hochkommata gesetzt habe.

aber ist es nicht das problem, das der string nicht richtig escaped wird?
und was mache ich mit meinen kommata in den feldern?

hier mein setting:

![Screenshot_2020-04-30Filtergenerator](https://user-images.githubusercontent.com/791989/80698690-22878880-8adb-11ea-8a08-553c1720e457.png)

dir vorab schon mal auf diesem wege vielen dank für die erweiterung!

**Comment by alnv** [comment]
Wenn in einem Filterwert ein Komma vorkommt, wird daraus ein Array (Mehrfach-Abfrage). Daher gibt es dazu keine Ergebnisse. Du kannst es mit dem REGEXP Operator versuchen, allerdings kommen vermutlich keine genauen Ergebnisse.

Allgemein sollte die Textsuche nur ein Begriff umfassen, zumindest ist es daraus ausgelegt.
