### ISSUE TITLE
FR: Catalog-Listensicht: URLs in Link umwandeln

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#25]
Wenn eine Tabelle URL-Felder enthält, würde ich die in der Listenansicht gerne als anklickbaren Link ausgeben, entweder mit einem Linktext wie "Link" oder "Click here" oder mit dem Inhalt eines Feldes "link_text".

(Im Template für die Detailansicht bekomme ich das mit meinen rudimentären Kenntnissen hin, leider aber nicht im Template ctlg_view_table.html5.)

**Comment by alnv** [comment]
Kannst du mir den Code von dem Detailansicht Template hier posten? Also nur den Teil mit der  URL…

**Comment by Anke** [comment]
```
<?php if( $this->club_url ): ?>
  <a href="<?= $this->club_url; ?>" target="_blank">Click to visit Club's website</a>
<?php endif; ?>
```

In deiner Demo hast du für das Bild (Vereinslogo) in der Tabelle Felder wie img_alt, img_title, img_desc angelegt. Das geht ja mit Links genauso gut mit Feldern wie link_url, link_text, link_target usw, so dass man die Variablen ins Template der Detailansicht übernehmen kann. Aber in der Listenansicht?

**Comment by alnv** [comment]
Öffne das _ctlg_view_table_ Template und füge in die erste _foreach_ Schleife ganz oben (Zeile 5) folgenden code ein:
```
<?php if( $strColumnName == 'club_url' ): ?>
   <td><a href="<?= $this->club_url; ?>" target="_blank">Click to visit Club's website</a></td>
   <?php continue; ?>
<?php endif; ?>
```
Selbstverständlich sollte "club_url" Feld in der Tabelle angezeigt werden. Mit dem Code oben, überschreibst du die Standard Ausgabe.

**Comment by Anke** [comment]
Super, herzlichen Dank! 
Allerdings - wenn das Feld club_url leer ist, wird trotzdem ein Link (mit der eigenen URL) generiert. Würdest du mir da noch mal helfen, als zweite Bedingung "wenn Feld nicht leer" hinzuzufügen?

**Comment by alnv** [comment]
So in etwa sollte es aussehen (nicht auf Syntax Fehler geprüft):
```
<?php if( $strColumnName == 'club_url' ): ?>
   <td>
      <?php if( $this->club_url ): ?>
         <a href="<?= $this->club_url; ?>" target="_blank">Click to visit Club's website</a>
      <?php endif; ?>
   </td>
   <?php continue; ?>
<?php endif; ?>
```
