### ISSUE TITLE
Upgrade 4.4.39 > 4.9.3: Fehlermeldung bei Verwendung des Modifizierer-Moduls

### ISSUE THREAD

**Issue by CONTEGRA** [alnv/catalog-manager#251]
Contao 4.4.39 | CM 1.20 > Contao 4.9.3 | CM 1.31

Hallo Alexander,

Events wird per Modifizierer erweitert. Nach dem Upgrade wird bei Events und in den Eingabefeldern des Modifizierer-Moduls folgender Fehler angezeigt:

_Table 'tl_content' can not be used as relation. Please delete all rows or create valid pid value._

Als Tabellenname des Modifizierers ist tl_calendar_events und als Elterntabelle tl_calendar ausgewählt.

Bisher scheint das FE und BE nicht beeinflusst zu sein aber kann es zu Problemen kommen und wie ließe sich der Fehler korrigieren?

**Comment by alnv** [comment]
Trage mal in deine dcaconfig.php (system/config/dcaconfig.php) 
`$GLOBALS['TL_DCA']['tl_content']['config']['dynamicPtable'] = true;`
ein. Bei mir hat es geholfen.

**Comment by CONTEGRA** [comment]
Danke, es hat funktioniert!

Allerdings nicht der neue Weg über /contao/dca/tl_config.php.

**Comment by eiswurm** [comment]
Wir haben exakt das gleiche Problem. Bei uns läuft Contao 4.10 und der CM 1.31.35. Auch wir haben, wie CONTEGRA die tl_calendar_events modifiziert. Änderungen in der dcaconfig.php haben nur zu noch mehr Fehlermeldungen geführt. @CONTEGRA wie habt ihr das Problem gelöst?

**Comment by CONTEGRA** [comment]
Ich habe es wie Alexander in seiner Antwort geschrieben hat, klassisch unter system/config/dcaconfig.php eingetragen.

**Comment by eiswurm** [comment]
<?php 

...vergessen
jetzt geht es :-)
