### ISSUE TITLE
Backend: List view - Taxonomy - Inserttags

### ISSUE THREAD

**Issue by daniel-nemeth** [alnv/catalog-manager#254]
Hallo Alexander!
Gibt es eine Möglichkeit, im Backend Listenmodul unter Taxonomy die Contao Inserttags mitzuverwenden? 

Als Beispiel: Ich möchte im FE eine Liste ausgeben, welche nur Einträge aus dem aktuellen Jahr anzeigt. Dazu lege ich in der Taxonomy das Feld an, setze auf equal und gebe als wert {{date::Y}} ein. Somit wäre die Filterung nur für das aktuelle Jahr. Leider funktioniert es nur wenn ich als Wert 2020 angebe.

Ein anderes Beispiel wäre: ich möchte eine Liste mit Einträgen ausgeben, welche nur zum aktuellen eingeloggten Mitglied gehören. Da wäre der pid Filter auf equal und der Wert {{user::id}}.

Vielen Dank,
LG Daniel

**Comment by alnv** [comment]
Hallo Daniel,

die Inserttags kannst problemlos verwenden. 
- Für das Datum existiert ein anderes Inserttag. Siehe https://catalog-manager.org/dokumentation/mit-datum-arbeiten.html. 
- {{user::id}} sollte funktionieren: https://github.com/alnv/catalog-manager/issues/1

**Comment by daniel-nemeth** [comment]
Hallo und danke für das rasche Feedback. Geht das Timestamp Inserttag auch, wenn man ein Feld hat, in dem nur das Jahr gespeichert wird und ein Feld, in dem nur das Monat?

**Comment by alnv** [comment]
Es läuft alles über den UNIX Timestamp. Wenn das Jahr/Monat ausgeschrieben steht wird es damit nicht funktionieren.

**Comment by daniel-nemeth** [comment]
Darf ich nun nochmal nachfragen.
Ich habe nun den Catalog angepasst und neben dem Monat und Jahr gibt es nun ein Feld, welches den Timestamp zusätzlich mit dem 15. des Monats abspeichert (z.B. 06/2020 -> 15.06.2020 - 10 Uhr). 

Wie kann ich nun die Datensätze filtern via Taxonomy, welche im heutigen Monat und Jahr den Timestamp haben?

Vielen Dank

**Comment by alnv** [comment]
was das Jahr angeht, könntest du es eventuell damit versuchen: 
{{CTLG_TIMESTAMP::?::yearBegin}} Between {{CTLG_TIMESTAMP::?::yearEnd}}

Für 15. des Montags fehlt mir keine Lösung zumindest keine die Konfigurierbare wäre. Was ein Versuch wäre das ganze zusammenzurechen:  {{CTLG_TIMESTAMP::?add=1296000::monthBegin}}… hab's nicht getestet.

**Comment by daniel-nemeth** [comment]
Hi. Vielen Dank!!

Brauche die Filterung nur für das jetzige Jahr und das jetzige Monat. Der Tag ist nicht wichtig.

{{CTLG_TIMESTAMP::?::yearBegin}} Between {{CTLG_TIMESTAMP::?::yearEnd}}

{{CTLG_TIMESTAMP::?::monthBegin}} Between {{CTLG_TIMESTAMP::?::monthEnd}}

Werde es nun so versuchen. Einen Hook gibt es ja nicht um den {{date::}} Inserttag einzubinden, oder?

Am einfachsten wäre die Taxonomy-Filterung mit:
Field1 equal {{date::m}} und Field2 equal {{date::Y}}

**Comment by daniel-nemeth** [comment]
Vielen Dank Alexander, es funktioniert so einwandfrei!

LG Daniel
