### ISSUE TITLE
Änderung des Alias eines Eintrages nach speichern

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#255]
Hallo Alexander,

mir ist aufgefallen, dass sich manchmal, wenn ein Katalogeintrag im Frontend aufgerufen wird und ohne Änderung gespeichert wird, der Alias des Eintrages ändert. Es wird eine Zahl, wohl eine Versionsnummer angehangen. Öffnet man den Eintrag erneut und speichert wiederum, setzt sich der Alias zum Ursprung zurück. Das Verhalten wird deshalb zum Problem, weil die Seiten, welche sich aus dem Eintrag ergeben von Google indiziert werden und bei Abänderung nicht mehr Gültig sind.

Kann ich das Verhalten irgendwie vermeiden?

Beste Grüße

**Comment by hoaxone** [comment]
Nachtrag. 

Es scheint sich wie folgt zu verhalten. Ein Eintrag wird immer abwechselnd mit einer und dann wieder ohne eine Nummer im Alias gespeichert. Beim erstmaligen erzeugen ohne Nummer. Ab dahin abwechselnd mit und ohne. Die Fortlaufende Nummer schein Kataloggebunden zu sein. 

Neben dem Google Problem gibt es da auch noch ein paar mehr. Wird die Seite eines Eintrages in Bookmarks übernommen oder die Seite verlinkt kann sie bei jeder zweiten Änderung nicht mehr erreichbar sein.

Beste Grüße

**Comment by alnv** [comment]
Danke für die Zusammenfassung. Ich werde es versuchen zu reproduzieren.

**Comment by alnv** [comment]
Sollte in v1.31.35 behoben sein.

**Comment by hoaxone** [comment]
Supper! Vielen Dank!
