### ISSUE TITLE
Eingabeprüfung Alles außer "#&()/<=>"  greift nicht.

### ISSUE THREAD

**Issue by hoaxone** [alnv/catalog-manager#256]
Hallo Alexander,

es scheint, als ob die Eingabeprüfung "Alles außer "#&()/<=>" " nicht greift. Sowohl im Backend als auch im Frontend lässt sich ein "/" verwenden.

**Comment by alnv** [comment]
Die Validierungen sind ein Bestandteil des Contao Frameworks und mittlerweile heißt es Alles außer "#<>()\\=" … Ab welcher Contao Version das so ist, kann ich nicht sagen.

**Comment by hoaxone** [comment]
Ok Danke für die Info
