### ISSUE TITLE
Frontend: Anzeige des Listmoduls zur Kindtabelle und zusätzlich Anzeige des verwendeten Elternelementes

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#258]
Hallo an die Experten,
ich habe folgendes Problem. Ich habe eine Elterntabelle und eine Kindtabelle definiert.
Es geht um die Darstellung im Frontend.
Ich habe ein Modul zur Listanzeige des Elternelementes im Frontend definiert. Darin ist der Link auf die Kindseite mit Übergabe des Queryparameters „pid=##id##“ definiert. Für die Zielseite ist ein Listmodul für die Kindtabelle definiert. Dort ist der Filter „Elternelement PID = {{pid}} definiert. Das funktioniert problemlos.
Jetzt habe ich auf der Seite der Kindtabelle zusätzlich ein weiteres Listmodul der Elterntabelle definiert, um den ausgewählten Datensatz der Elterntabelle anzuzeigen. Dort hatte ich als Filter ID =  {{pid}} verwendet. Leider werden alle Datensätze angezeigt. Gebe ich für {{pid}} den tatsächlichen Wert ein, dann funktioniert es. Ergo kann der Filter des Listmoduls nicht auf den Wert der URL zugreifen.
Was kann ich tun?

**Comment by alnv** [comment]
Grundsätzlich muss der pid Attribute in der Url enthalten sein z.B mydomain.de?pid=123. Wenn es der Fall ist, kannst du es mit {{CLTG_ACTIVE::pid}} auslesen. Die {{pid}} Abfrage funktioniert nur beim Filtergenerator innerhalb der Eingabefelder.

Alternativ: Wenn man auf der Detailseite " Master verwenden" aktiviert, kann man auch {{CTLG_MASTER::pid}} verwenden.

**Comment by gfassben** [comment]
Erst einmal vielen Dank für die Rückmeldung. Aber irgendwo scheint der Wurm drin zu sein. 
Ausgangspunkt ist folgende Listanzeige:
 
![grafik](https://user-images.githubusercontent.com/60659770/91283449-e7e0e480-e78a-11ea-9f73-5a3fae0f4570.png)
![grafik](https://user-images.githubusercontent.com/60659770/91283493-f5966a00-e78a-11ea-9adf-d8eb533d10a5.png)
![grafik](https://user-images.githubusercontent.com/60659770/91283525-fd560e80-e78a-11ea-864a-198a1f0efa2e.png)
 
Daraus wird die definierte Seite „Anmeldungen“ mit der Listeanzeige der Kindtabelle aufgerufen. Dort habe ich folgende Taxonomie eingestellt:
 
![grafik](https://user-images.githubusercontent.com/60659770/91283545-047d1c80-e78b-11ea-9a9d-f19196501281.png)

Das funktioniert problemlos.
Zusätzlich soll auf der gleichen Seite eine Variante der Ausgangsliste angezeigt werden – eingeschränkt auf das Elternelement. 
Die URL mit Angabe der pid ist korrekt: „anmeldung.html?pid=28“
Die aufgerufene Liste hat folgende Einstellungen:

![grafik](https://user-images.githubusercontent.com/60659770/91283589-11017500-e78b-11ea-9e18-a06fd9b952bf.png)
 
Dabei habe ich {{CLTG_ACTIVE::pid}} testweise ersetzt durch {{CTLG_MASTER::pid}} und {{pid}}. Alle Varianten funktionieren nicht. Nur wenn der Wert für pid in der Taxonomie fest eingetragen wird, funktioniert es.
Für mich hat es den Eindruck als wenn dieser Filterzugriff nur auf Kindtabellen zulässig ist.

**Comment by robvis** [comment]
Hi Alexander,
For me the same question/issue.
I create a master (address) record en want to redirect to create the child table record (act123=create). For this I need the master_ID to be passed as PID to the child table. I don't see how to pass the just created Master_ID with the re-direction on create.

Gruesse,
Rob
