### ISSUE TITLE
beim Löschen von Inhaltselementen "Internal Server Error" - "The table name must not be empty"

### ISSUE THREAD

**Issue by smeyli** [alnv/catalog-manager#259]
Nachdem ich den Catalog Manager in einer Contao 4.9.4 installiert, konfigueriert und die angelegten Tabellen befüllt habe, kann ich kein weder Inhaltselemte, Seiten, Module oder Filter usw. löschen. 
Eine kurze Recherche ergab einen Treffer im Contao-Forum, dass bei jeder Angelegten Tabelle (Catalog) mindestens ein Feld angelegt sein muss - das habe ich getan, doch nach wie vor erscheint dieser Fehler beim Versuch, irgendetwas im Backend zu löschen.
Weiß jemand einen Ausweg?

**Comment by alnv** [comment]
Vermutlich gibt es innerhalb des Catalog Manager's einen Katalog mit einem undefinierten "Tabellennamen". Wenn es der Fall ist, kannst du z.B mit PHPMyAdmin den Eintrag in der tl_catalog Tabelle löschen.

Über's Backend löschen wird es vermutlich nicht funktionieren.

**Comment by smeyli** [comment]
Hallo Alexander,
vielen herzlichen Dank für diese schnelle und hilfreiche Information.
Genau daran hat es gelegen - Eintrag gelöscht und alles funktioniert, wie es soll.
Danke!
