### ISSUE TITLE
Duplikation von bestehenden Feldern

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#26]
Bei umfangreichen Masken ist es mühsam die Felder immer wieder neu anzulegen. Ich vermisse hier eine Möglichkeit bestehende Felder zu duplizieren.

**Comment by codiso** [comment]
<img width="1014" alt="catalog_manager_ _spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27586691-a7db3ae4-5b41-11e7-9528-1518f807b288.png">

**Comment by alnv** [comment]
Ich packe es in den v1.4 Branch.

**Comment by alnv** [comment]
Ist erledigt. Dieses Feature gibt es in der v1.4
