### ISSUE TITLE
automatische Feldvorbelegung in Abhängigkeit von Select-Menu

### ISSUE THREAD

**Issue by smeyli** [alnv/catalog-manager#260]
Ausgangsposition: 2 Tabellen
In der 1. Tabelle befinden sich Kategorien, in der 2. Tabelle Produkte

In der Tabelle Produkte wähle ich via Select-Menu die entsprechende Kategorie aus Tabelle 1.
Weiterhin existiert  in der Tabelle Produkte ein Feld, in welches andere Daten (z.B. der alias) aus der Tabelle Kategorie eingetragen werden sollen (natürlich in Abhängigkeit von der gewählten Kategorie). Das sollte am besten automatisch und versteckt funktionieren. 

Kurz und knapp: Bei Produkt 1 wird "Kategorie A" gewählt und in einem weiteren Feld soll der Alias von "Kategorie A" automatisch abgespeichert werden (Feld versteckt).

Kann man das mit Simple Tokens oder $this->tabelleField erreichen?
Erfolg hatte ich damit leider nicht.

**Comment by alnv** [comment]
Out of the box kann man keine versteckte Felder vor belegen oder automatisch ausfüllen. Das kann man aber mit einem eigen callback (hook) erreichen…
