### ISSUE TITLE
return to last listpage from detail / front-end editing

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#261]
Hallo ALexander,

When I use pagination in the list view, I always return to page 1 of the list view after detail view/front-end editing or other subsequent pages.
I like to return/goback to my last viewed/visited page (e.g. page 4) to go on with viewing following list pages.
How can I return to my last(left) page?

Thanks,
Rob

**Comment by alnv** [comment]
The page numbering is captured via the "page_e<moduleId>=<page-number>" parameter, i.e. this parameter must be passed to the detail page and from the detail page to the back-link.

Alternatively you can also use: <a title="Zurück" href="javascript:history.go(-1)">

**Comment by robvis** [comment]
Hallo Alexander,
Ich habe die Lösung für detail Pagina gefunden mit Hilfe $_SYSTEM['HTTP_REFERER"] und eigene Inserttags.
Aber jetzt nog die FrondendPage.
Das gibt ein Problem. 
- Die Query-Parameter beim Weiterleitung akzeptiert keine Inserttags.
Ich mache die Weiterleitung Pagina meine original Pagina
- When ich "catalogFormRedirectParameter" im "catalog_default.html5" ändere mit aktuelle filter Werten gescheht auch nichts.
Aber when Ich die werten hard im Query-Parameter eingebe, geht das gut.
Wie kann Ich die Rückleitung mache, dass Ich die gleiche original "inhalt" Pagina wieder bekomme?

Grüssen,
Rob Vis
