### ISSUE TITLE
RTE verhindert Filterbarkeit

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#265]
Hallo Alexander,

wenn ich einer Textarea einen RTE zuweise (in meinem Fall TinyMCE), dann ist es unter den Taxonomieeinstellungen in der Listenansicht nicht auswählbar. Grade für so etwas wie eine Wortsuche in Beschreibungstexten ist das dann ein Problem.

LG
Florin

**Comment by alnv** [comment]
Haben wir bewusst darauf verzichtet, weil das eingebettete HTML die Suchergebnisse verzerrt.
