### ISSUE TITLE
Feld automatisch mit Upper-Case

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#267]
Hallo Alexander,

ist es möglich, einem Feld einen dynamischen Wert zuzuweisen und diesen automatisch im Upper-Case zu schreiben?
In meinem Beispiel bräuchte ich das für eine Gruppierung nach Anfangsbuchstabe, wobei manche Namen teils mit lower-case geschrieben sind.

Oder gibt es schon eine Funktion zum Gruppieren nach Buchstaben, die ich einfach noch nicht kenne?

Beste Grüße,
Florin

**Comment by alnv** [comment]
Leider nicht, aber eine Gruppier-Funktion gibt es in der Listenansicht (Sortierungseinstellungen > Gruppieren)
