### ISSUE TITLE
Bei Checkbox über Datenbank Auswahlliste nur der erste Eintrag als Feld

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#268]
Hallo Alexander,

ich habe gerade eine Checkbox-Liste als BE-Feld für ein Modul eingerichtet, welches die Daten aus einem anderen Modul per Datenbank Auswahlliste übernimmt. Allerdings wird dabei nur der alphabetisch erste Eintrag angezeigt...
Das Feld hat außer der Liste keine besonderen Einstellungen.
Sowohl bei Radio-Buttons als auch bei Select-Felder funktioniert es ohne Probleme.

LG
Florin

**Comment by alnv** [comment]
Vermutlich sind die Daten in der Wertspalte identisch, sodass am Ende nur einer bleibt. Kannst du ein Screenshot von deiner Konfiguration posten?

**Comment by FlorinvV** [comment]
Okay, ich habe rausgefunden, was das Problem ist: Als ich vom Select-Menü zurückgeschalten habe, war Mehrfachauswahl aktiviert. Diese gibt es auch bei Checkboxen und wenn man sie nicht aktiviert, wird auch nur ein Eintrag angezeigt. Gleiches passiert auch bei normaler Auswahlliste und wahrscheinlich auch beim Fremdschlüssel.
