### ISSUE TITLE
Mehrere bearbeiten … bei Feldern

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#27]
Möchte man mehrere Felder nachträglich z.B. im Datentyp ändern, so ist das sehr mühsam, dies bei jedem Feld zu tun. Die gewohnte Funktionalität des Mehrfachbearbeitens sollte auch integriert werden!

<img width="1030" alt="catalog_manager_ _spangler____reisen_-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27587083-41cd7a94-5b43-11e7-82b1-f530fdf01b0a.png">

**Comment by Anke** [comment]
siehe https://github.com/alnv/catalog-manager/issues/6

**Comment by codiso** [comment]
Danke hatte ich nicht wahrgenommen ?!?

**Comment by alnv** [comment]
=> #6
