### ISSUE TITLE
Array in Backend-Ansicht

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#270]
Hallo Alexander,
in der Backend-Ansicht eines Backend-Moduls erscheint `Array` wenn ich in der Darstellungsansicht des Backend-Moduls etwas anderes als `Eindeutige Bezeichnung` und` Sortierung nach einem festen Feld` eingebe. Operatoren sind `Verschieben`, `Duplizieren` `Aus/Einblenden` aktiviert.

Ich benötige ja ein Datenbankfeld (in meinem Fall `Sortierindex`) um die Einträge überhaupt zu sortieren.

Listenansicht:
![listenansicht](https://user-images.githubusercontent.com/8830861/95990364-b3ed7b80-0e2b-11eb-8aec-1bd891ad520f.PNG)

Catalog Manger:
![Inkedscrnli_14-10-2020_14-37-29_LI](https://user-images.githubusercontent.com/8830861/95990661-1777a900-0e2c-11eb-9651-d31d73180624.jpg)

Contao 4.9.8
Catalog Manager 1.31.36

**Comment by alnv** [comment]
Should be fixed in 1.31.37
