### ISSUE TITLE
Alternative zu Google Maps wegen Datenschutz

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#271]
Hallo Alexander,

ich weiß, es wurde schon öfter nach einer Alternative zu Google-Maps gefragt, allerdings gerät GM jetzt wegen dem Fall von Privacy Shield zunehmends datenschutztechnisch in eine schwierige Lage...
Meine Agentur unterhält bereits einige CM-Installationen, gerade auch wegen der Kartenfunktion, welche ich jetzt eigentlich nicht mehr benutzen darf...

Bleibt es hinsichtlich auf die problematische DSGVO-Situation bei einem klaren "Nein" zu einer GM-Alternative?

Beste Grüße und tut mir Leid wegen der vielleicht nervigen Frage 😅 
Florin

**Comment by alnv** [comment]
Bisher habe ich keinen vergleichbaren Kartendienst Anbieter gefunden (im Bezug auf Server/GeoCoding/Umkreissuche).

**Comment by FlorinvV** [comment]
Ich könnte mich jetzt irren, aber hat Leaflet als Basis nicht auch eine Möglichkeit zum Geocoding und Umkreissuche?
