### ISSUE TITLE
tl_page modifizieren

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#272]
Hallo Alexander,
wenn man versucht die tl_page zu modifizieren (inkl. Catalog Einstellungen mit den originalen Einstellungen überschreiben), also z.B. mit einer Checkbox zu versehen, dann erscheint diese nicht in der Seitenstruktur der Seite (also in der Übersicht einer beliebigen Seite).

**Catalog Manager:**
![scrnli_29-10-2020_11-47-36](https://user-images.githubusercontent.com/8830861/97558925-11152f80-19dd-11eb-9e1e-5e81d7cd9789.png)

**beliebiges Feld in der tl_page:**
![scrnli_29-10-2020_11-52-412](https://user-images.githubusercontent.com/8830861/97559119-4faaea00-19dd-11eb-82b5-5a7cd49ac095.png)

**Seitenstruktur**
![scrnli_29-10-2020_11-51-432](https://user-images.githubusercontent.com/8830861/97558973-2722f000-19dd-11eb-8a13-954963a443fd.png)
Die Checkbox/EIngabefeld müsste doch hier eigentlich zu sehen sein?

C 4.10.3
Catalog Manager v1.31.36

**Comment by alnv** [comment]
Kommt darauf an ob sich das Feld in der Richtigen Palette befindet. Was hast du beim Feld Picker ausgewählt?

**Comment by akroii** [comment]
Welches Feld meinst du? Meinst du meine custom angelegte Checkbox?
