### ISSUE TITLE
Masterview funktioniert nicht mit tl_member

### ISSUE THREAD

**Issue by daniel-nemeth** [alnv/catalog-manager#273]
Hallo!
Ich habe für die tl_member einige Felder hinzugefügt. Weiters eine Kindtabelle namens "buchungen". Nun habe ich ein Listenmodul erstellt, welche mir die tl_member Einträge ordnungsgemäßg anzeigt. Die masterurl zeigt auf eine andere Unterseite, auf der ich ein masterview-modul angelegt habe.

Nun habe ich dass Problem, dass im Listenmodul die $this->masterUrl nur mitarbeiter/buchungen.html ausgibt, jedoch ohne auto_item. Woran kann das liegen?

Vielen Dank!

**Comment by alnv** [comment]
Überprüfe ob deine Buchungen über einen Alias verfügen und ob die Detailseite richtig eingestellt. So auf Anhieb kann ich dir nicht sagen, wieso der Alias nicht ausgegeben wird.
