### ISSUE TITLE
Bildgröße an Ausgabe-Modul koppeln

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#276]
Hallo Alexander,

ich arbeite gerade an einer Installation, in der ein CM-Modul in 4 verschiedenen Listen ausgegeben wird.
Jetzt brauchen die Elemente ein Bild, welches je nach Liste ein anderes Seitenverhältnis haben soll.

Bisher ist es so, dass ja die Bildgröße für das Bild im Uploadfeld des Elements bestimmt wird, sodass ich im Prinzip 4-Mal das Bild auswählen muss um es in 4 verschiedenen Bildgrößen ausgeben zu lassen. 
Geht das auch anders herum? Dass ich z.B. in einem Listenmodul die Möglichkeit habe, ein im Element ausgewähltes Bild z.B. in einem Select-Menü auszuwählen, welches dann über die normale Bildgrößen-Maske angepasst wird.

Wäre es denkbar das umzusetzen oder spricht da etwas Entscheidendes dagegen? (Ich meine, es wird ja einen Grund geben das du es auf diese Weise gelöst hast wie du es gelöst hast)

LG Florin

**Comment by fritzmg** [comment]
I agree, the image size should be set in the module (or should be overridable in the module at least), so that you can have different image size settings for the list (e.g. small thumbnail) and the detail page (e.g. large image).

**Comment by fritzmg** [comment]
PR: https://github.com/alnv/catalog-manager/pull/324
