### ISSUE TITLE
Fine-Uploader: Limit Dateigröße greift nicht

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#278]
Hallo Alex,

Damit über das Frontend-Editing ein User mehrere Bilder hochladen kann, verwende ich den "Fine-Uploader".
Ich möchte gerne die max. Dateigröße des Uploads limitieren (z.B. auf 3 MB pro File).
Leider werden Eingaben, die ich im Feld "Maximale Eingabelänge" mache, nicht berücksichtigt.
Es werden auch Files > der maximalen Eingabelänge hochgeladen.

Hab das Eingabefeld lt. screenshots angelegt.
Verwende Contao 4.10.4 mit der aktuellen Version 1.31.39 des Catalog Managers.

![fine_uploader_screenshot1](https://user-images.githubusercontent.com/60215157/100638677-94a3a280-3334-11eb-9c20-0dcd9cf35c1b.jpg)
![fine_uploader_screenshot2](https://user-images.githubusercontent.com/60215157/100638691-9b321a00-3334-11eb-8aab-5d45b61e97e0.jpg)
![fine_uploader_screenshot3](https://user-images.githubusercontent.com/60215157/100638716-9ff6ce00-3334-11eb-82b5-e95e4f30b9c7.jpg)

**Comment by alnv** [comment]
Should fixed in v1.31.40

**Comment by jochi44** [comment]
Is fixed!
Thanks for your great work, Alex!
