### ISSUE TITLE
DB-Tabelle Typ und Kollation

### ISSUE THREAD

**Issue by landzone21** [alnv/catalog-manager#279]
Ich erstelle ein Modul und lege damit eine neue Tabelle in der Datenbank an. Diese Tabelle erhält automatisch den Typ MyISAM und die Kollation utf8_general_ci.
Ich Contao 4.9 haben alle anderen Tabellen aber den Typ InnoDB und die Kollation utf8mb4_unicode_ci.
Kann ich das beim Erstellen des Moduls beeinflussen?

**Comment by alnv** [comment]
Im Contao/CM kann man es momentan nirgends einstellen. Wir schauen, ob es möglich ist, das noch einzubauen.
