### ISSUE TITLE
FE-Editing - Weiterleitung funktioniert nicht

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#28]
Wenn man im FE einen Datensatz ändert und auf Speichern klickt, bleibt man in der Editiermaske. (Habe übers Template schon einen Button Abbrechen/Zurück hinzugefügt.)

Im FE-Modul Catalog-Listenansicht gibt es unter Frontend-Einstellungen die Möglichkeit, eine Weiterleitungsseite auszuwählen. Hier habe ich eine extra Seite "Änderungen wurden gespeichert" ausgewählt, aber es erfolgt keine Weiterleitung (auch keine Fehlermeldung).

**Comment by alnv** [comment]
Das Ding kommt mit dem nächsten Update. Nach editieren/anlegen oder löschen wird
- ein text angezeigt (z.B Ihr Datensatz wurde gespeichert.)
- oder mann kann eine Weiterleitungsseite bestimmen.
Ist schon alles implementiert. Update sollte auch schon zeitnah rauskommen :)

**Comment by alnv** [comment]
Alles klar die 1.3 Version ist online. Damit sollte die Weiterleitung funktionieren.
