### ISSUE TITLE
{{CTLG_MASTER::*}} gibt bei 10% der Datensätze falsche Werte aus

### ISSUE THREAD

**Issue by smeyli** [alnv/catalog-manager#280]
**Ausgangssituation:**
In der Datenbank befinden sich über 1800 Datensätze mit Druckermodellen.
Es gibt eine Herstellertabelle, Typ-Tabelle und eine Produkt-Tabelle.
Die Datensätze sind sauber und fehlerfrei - alles mehrfach von verschiedenen Personen kontrolliert.

**die Konfiguration**
Es gibt 2 Ansichten - Liste + Details
Die Listenansicht ist elegant filterbar - funktioniert alles bestens.
Das URL-building der Detailseite funktioniert auch bestens: .../Hersteller/Produkt-Typ/(auto_item)
Im Seitenbaum wurde die Produkt-Tabelle als Master und auch als Routing-Tabelle angegeben.

**Die Detailansicht**
Für die Detailansicht gibt es keine separate Seite, nur ein separates Template (also nix besonderes)
Zusätzlich gibt es noch einen Seitenkopf-Bereich (Standard-Inhaltselemte) + einen Text-Bereich (auch Standard-Inhaltselemente)
Im Seitenkopf-Bereich werden {{CTLG_ACTIVE::manufacturer}} {{CTLG_ACTIVE::product_type}} fehlerfrei ausgegeben.
Zusätzlich soll in diesen beiden Inhaltselementen zum jeweiligen Produkt auch der Preis und der Titel ausgegeben werden.
Da die Produkt-Tabelle als Master-Tabelle fungiert, sollte das ja kein Problem darstellen, einfach {{CTLG_MASTER::title}} und {{CTLG_MASTER::price}} auslesen und fertig.

**Das Problem**
Diese beiden Inserttags {{CTLG_MASTER::title}} und {{CTLG_MASTER::price}} erledigen diese Arbeit bei etwa 90% der Produkte. Bei den anderen 10% werden falsche Daten ausgegeben - jedes mal die gleichen falschen Daten von anderen Produkten - ein Schma ist nicht erkennbar.
Auch wenn ich mit dem Master-Inserttag den Alias oder irgendwas anderes ausgebe, erscheinen falsche Daten, obwohl das URL-Building korrekt ist.
Ich habe schon mehrfach die Datensätze miteinander verglichen und keine Fehler, Unregelmäßigkeiten, Besonderheiten usw. entdeckt. Dieses Phänomen tritt plötzlich von einem zum nächsten Datensatz auf.

Na klar, ich könnte das Problem umgehen, indem ich alle Daten fein im Template ausgeben, doch dann ist der Seitenaufbau nicht mehr so flexibel - da ich gern im Header den Hersteller, den Typ und das Druckermodell + Preis ausgeben möchte und zusätzlich einen Fließtext mit entsprechenden Platzhaltern (Inserttags). Und dafür ist ja schließlich das Master-Insert-Tag da.

Seit vielen Tagen bin ich (sind wir) schon auf Fehlersuche und noch keinen Schritt weiter.
Selbst, wenn ich das Produkt, von welchem fälschlicherweise Daten angezeigt werden, deaktiviere oder dessen Daten ändere,  werden Daten von diesem Produkt trotzdem weiterhin angezeigt.

**Comment by alnv** [comment]
Kannst du 2-3 Aliase von den betroffenen Datensätzen posten?

**Comment by smeyli** [comment]
Diese Aliase (alles von  Hersteller Kyocera - insgesamt 29 Datensätze) zeigen Daten vom Datensatz (Brother) mit dem Alias **dr-1030** (Das ist der erste Datensatz überhaupt)
1t02m70nxv
1t05jk0nl0
1t05jkcnl0
1t05jkbnl0
1t05jkanl0
...

**Aliase** von Lexmark
24b6008
24b6010
24b6009
24b6011
24b7182
24b7183
24b7184
24b7185
24...
...
zeigen Daten vom Datensatz mit dem Alias tn-2310 (wieder Brother)

**Aliase** (alles Lexmark)
50f0ua0
50f2000
50f2h00
50f0ha0
50...
...
zeigen Daten vom Datensatz mit dem Alias tn-320bk (Brother)

51f0ha0
51f2h00
51f2h0e
51...
...
zeigen Daten vom Datensatz mit dem Alias tn-320c (Brother)

56f2000
56f2h00
56f2x00
56...
...
zeigen Daten vom Datensatz mit dem Alias tn-320m (Brother)


63b2000
63b2h00
63b2x00
zeigen Daten vom Datensatz mit dem Alias tn-326c (Brother)

**und bei diesen Aliasen (auch Lexmark) stimmt die Ausgabe wieder**
64004he
64016he


bei den danach angezeigten Herstellern (alle alphabetisch) ist alles wieder gut und ab Toshiba geht es wieder los

hier mal Xerox-Aliase

006r01395
006r01396
006r01397
006...
...
zeigen Daten vom Datensatz mit dem Alias dr-241cl (Brother)

usw.

Ich habe alle Daten als CSV exportiert und in Excel die Zusammenhänge farblich markiert. Ich sehe dabei irgendwie keine Zusammenhänge, außer, dass die falschen Daten immer vom Hersteller Brother kommen.

**Comment by alnv** [comment]
Kannst du testweise bei einigen betroffenen Aliasen ein "id_" Präfix hinzufügen? Z.b "id_ 56f2000" und testen ob es so funktioniert. Aus welchem Feld wird der Alias generiert, das sieht nicht nach dem title aus?

**Comment by smeyli** [comment]
Hallo Alex,
das habe ich schon probiert und jetzt auch nochmal bei anderen Datensätzen - das Ergebnis bleibt das gleiche.
Ebenso habe ich den Alias bei dem fälschlicherweise angezeigten Artikel geändert. Trotzdem werden dessen Daten angezeigt.

Die Daten werden nicht in Contao angelegt, sondern direkt in MySQL importiert.
Der Alias unterscheidet sich bei einigen Datensätzen vom Titel und ist beim Import schon vorgegeben.
Bei den betroffenen Datensätzen ist aber alles dabei Alias = Titel und Alias anders als Titel.
Ebenso funktioniert es bei etwa 90% der Datensätze (auch manchmal Alias = Titel und manchmal eben nicht)

**Comment by smeyli** [comment]
noch ein anderer Test:
direkt im Backend habe ich einen betroffenen Datensatz dupliziert, komplett anderen Alias vergeben und noch ein paar andere Daten angepasst - und es werden trotzdem die gleichen falsche Daten über den Master "gezogen" wie beim Ursprungs-Datensatz.

**Comment by alnv** [comment]
In v1.31.41 sollte es gefixt sein.

**Comment by smeyli** [comment]
Also brauche ich jetzt nicht weiter Analyse zu betreiben.
Kannst Du schon etwas dazu sagen, wann diese Version verfügbar sein wird?

Vielen Dank für Deinen netten und super schnellen Support!!!

**Comment by smeyli** [comment]
Ich habe gerade gesehen, dass die neue Version schon verfügbar ist - gleich installiert...

JETZT FUNKTIONIERT ALLES SUPER - DANKE!!!
