### ISSUE TITLE
CTLG_TIMESTAMP formatieren

### ISSUE THREAD

**Issue by landzone21** [alnv/catalog-manager#281]
Gibt es die Möglichkeit, den Inserttag direkt im Backend als Datum formatiert auszugeben?
Ich würde gern im Filtergenerator den Standardwert eines Textfeldes vorbelegen mit { { CTLG_TIMESTAMP::?add=604800 } }. Damit wird aber der Timestamp im Frontend vorbelegt, diesen möchte ich als als Datum formatiert ausgeben.

**Comment by alnv** [comment]
Das CTLG_TIMESTAMP ist dafür nicht ausgelegt. Damit lässt sich nur der Timestamp ausgeben. 
Aber vllt. ist es so möglich:
<?= date('d.m.Y', time()+ 604800) ?>

**Comment by landzone21** [comment]
Danke, aber wie ist es möglich? Der Vorschlag wird leider nicht angezeigt....

**Comment by landzone21** [comment]
Ich möchte die Frage nochmals hervorholen, da ich noch keine Lösung gefunden habe:
Ein Filterformular mit Datepicker enthält die Datenfelder 'von' und 'bis', diese sollen bei Seitenaufruf vorbelegt sein. Im Backend kann ich im Filterformular den { { CTLG_TIMESTAMP::?add=604800 } } als Standardwert eingeben, aber nicht als Datum formatieren. Mit dem normalen Inserttag {{date}} kann ich unter Contao 4.9 aber keine Berechnungen mit dem Datum vornehmen. Was könnte ich noch tun? Danke für die Hilfe.
