### ISSUE TITLE
Feature: Fine-Uploader Frontend-Editing -> Begrenzung der Anzahl der hochzuladenden Dateien

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#282]
Hi Alex,

der Contao Fine-Uploader bietet, soweit ich das sehe, über die Option "'uploaderLimit'" die Möglichkeit, die Höchstanzahl der hochzuladenden Dateien zu begrenzen.
Wäre toll, wenn man das über ein Feld im Backend im Catalog Manager auch definieren könnte.

**Comment by alnv** [comment]
Serverseitig ist es nicht implementiert, idealerweise sollten es beides unterstützen. Es kann gut sein, dass der Fine Uploader noch ersetzt wird, da dieser nicht weiter entwickelt wird.
