### ISSUE TITLE
Cookies ctlg_FEE_MessageXY -> Firefox-Warnings

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#283]
Hallo Alex,

in der Firefox-Konsole werden Meldungen dieser Art ausgegeben (Loglevel: Warning) bei Aufruf einer Seite, auf der der CM installiert ist:

`Das Cookie "ctlg_FEE_Message54" wurde abgelehnt, da es bereits abgelaufen ist.`
`Das Cookie "ctlg_FEE_Message45" wurde abgelehnt, da es bereits abgelaufen ist.`
`Das Cookie "ctlg_FEE_Message56" wurde abgelehnt, da es bereits abgelaufen ist.`
`Das Cookie "ctlg_FEE_Message60" wurde abgelehnt, da es bereits abgelaufen ist.`
`Das Cookie "ctlg_FEE_Message95" wurde abgelehnt, da es bereits abgelaufen ist.`

Könnte man das irgendwie bereinigen, sodass diese Warnungen nicht mehr angezeigt werden?

**Comment by grummbeer** [comment]
Die cookies betreffen das Bearbeiten per Frontend, oder? Vielleicht könnte man auf das Setzen ganz verzichten wenn FEE nicht benutzt wird? Das würde auch helfen beim caching von contao.

**Comment by alnv** [comment]
ja, genau diese werden nur beim FE-Editing gesetzt. Ich denke, da ist nur die Lebensdauer auf zu lang eingestellt.

**Comment by grummbeer** [comment]
Wäre das im Ergebnis so, dass die cookies gar nicht erst in der Serverantwort auftauchen?

Mir geht es um das caching in contao. Hier wird’s "private" wegen dem response-cookie "ctlg_FEE_MessageXX" und dem session-cookie. Hast Du Dich dem Thema schon gewidmet? Beim Rumprobieren habe ich zwei Stellen modifiziert und das caching funktioniert so für mich damit.

**1. FEE-cookies**

Auskommentieren der beiden Zeilen `System::setCookie()` in "CatalogMessage" [hier](https://github.com/alnv/catalog-manager/blob/fee84220bd1bdb9a0503bdedc1e46416a6dde095/library/alnv/CatalogMessage.php#L33) und [hier](https://github.com/alnv/catalog-manager/blob/fee84220bd1bdb9a0503bdedc1e46416a6dde095/library/alnv/CatalogMessage.php#L46)

Lösung: Cookies nur setzen wenn FEE überhaupt aktiv?


**2. Session**

Die Session wird in der "[CatalogInput](https://github.com/alnv/catalog-manager/blob/fee84220bd1bdb9a0503bdedc1e46416a6dde095/library/alnv/CatalogInput.php#L22)" aufgemacht? Das habe ich mit `if (TL_MODE === 'FE') { return '';}` überbrückt.  Leider weiß ich nicht wo das benötigt wird oder ob ich damit das Backend störe. 

Lösung: Vielleicht die Sitzung erst bei einem POST bzw. wenn sie tatsächlich gebraucht wird aufmachen?

Keine Ahnung ob es da noch mehr gibt oder so, sieht aber doch vielversprechend aus, oder ist das bereits obsolet?

**Comment by jochi44** [comment]
Hi Alex,

any news on this topic?

**Comment by nano-67** [comment]
Hallo Alex, 
es werden immer noch Cookies gesetzt, obwohl das FE-Editing nicht aktiviert ist (Contao 4.13, CM 1.32.29). Das Auskommentieren der Zeilen 33 und 46, wie von grummbeer beschrieben, hilft.
Ich würde gerne die CM-Listenansicht ohne Cookies einsetzen. Gibt es dafür eine updatesichere Lösung?

**Comment by marcelgit2** [comment]
> Hallo Alex, es werden immer noch Cookies gesetzt, obwohl das FE-Editing nicht aktiviert ist (Contao 4.13, CM 1.32.29). Das Auskommentieren der Zeilen 33 und 46, wie von grummbeer beschrieben, hilft. Ich würde gerne die CM-Listenansicht ohne Cookies einsetzen. Gibt es dafür eine updatesichere Lösung?

Dieser Frage möchte ich mich anschließen.
