### ISSUE TITLE
tl_module fields

### ISSUE THREAD

**Issue by daniel-nemeth** [alnv/catalog-manager#284]
Hi.
I have extended the tl_module fields via an Catalog Modifier. 
Can you please tell me how to access now this fields within the template? With $this->showTemplateVars(); i'm not able to find the fields.

Cheers

**Comment by alnv** [comment]
Use the arrow operator to access the value. For example $this->*myfieldname*. One thing must be noted. Not every module passes the variables to the template. You can still get them with your own DB query.

``` php
// not tested
$objModule = \Database::getInstance()->prepare('SELECT * FROM tl_module WHERE id=?')->exceute($this->id);
<?= $objModule->myfieldname ?>
```

**Comment by daniel-nemeth** [comment]
I tried it with $this->field but it seems the catalog list and masterview module are not passing the fields to template. Cheers for help.
