### ISSUE TITLE
tl_catalog.cTables - varchar(255) to short

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#285]
Hi!

I have extended the tl_member with 8 subtables. Now I have the problem that I'm not able to store the value of the field cTables, because the field is a varchar(255). It should be changed to TEXT to allow enough subtables for storage.

Cheers

**Comment by alnv** [comment]
You can extend the field in your config file. For Example
app/Resources/contao/dca/tl_catalog.php:
$GLOBALS['TL_DCA']['tl_catalog']['fields']['cTables']['sql'] = 'text NULL';
