### ISSUE TITLE
Format in view settings

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#286]
Hi.
The catalog manager changes the format field in view settings for a catalog from %s to %p from time to time. But i am not able to find what is triggering this behaviour. After the change to %p the title is not shown anymore.

**Comment by daniel-berger-nemeth** [comment]
Are there any update on this please?

**Comment by alnv** [comment]
> The catalog manager changes the format field in view settings for a catalog from %s to %p from time to time. 

What settings do you mean?

**Comment by daniel-berger-nemeth** [comment]
![image](https://user-images.githubusercontent.com/5083254/108604338-9322cd00-73ad-11eb-8066-dea5144bf8cc.png)

The view settings have a field named _Format_. Regulary sprintf works with the _%s_, Catalog Manager is switching this to _%p_ when opening it.
