### ISSUE TITLE
Einsatz von MultiColumnWizard

### ISSUE THREAD

**Issue by landzone21** [alnv/catalog-manager#287]
Ich erweitere mittels CM die Events und möchte für das Backend eine Eingabe erstellen, die sowohl ein Select-Menü als auch ein zugehöriges Textfeld beinhaltet und dieses als BLOB in der DB abspeichern. 
Das ganze sieht so aus:
![multicolumnwizard](https://user-images.githubusercontent.com/40214527/103627583-20b17700-4f3e-11eb-9602-99c815fb9c17.png)

Dazu möchte ich den MultiColumnWizard nutzen. Kann man den in den CM integrieren? Wie würde das konkret aussehen? Oder gibt es noch einen anderen Weg, das zu lösen?

**Comment by alnv** [comment]
Siehe #142
