### ISSUE TITLE
Nutzung von versteckten Feldern

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#288]
Ich nutze derzeit versteckte Felder zur automatischen Belegung des Feldes "Autor" aus dem Frontend heraus. Dabei wird als Standardwert {{user::id}} eingetragen. Das funktioniert gut.

Ich habe eine Verknüpfung von zwei Tabellen nach Ihre [Beschreibung](https://catalog-manager.org/dokumentation/catalog-manager-joins.html) eingerichtet. Ich kann nachvollziehen, dass die Werte in der Tabelle zur Verfügung als "tablenameFeldname".

In der Frontenderfassung soll nach der Auswahl eines Wertes aus der verknüpften Tabelle (Wert = ID) ein anderer Spaltenwert automatisch gezogen werden.

Kann ich diese Information auch für die Erfassung der Daten nutzen? Meine Versuche mit {{ctlg_tabellenname::feldname}} führten lediglich dazu, dass das Feld mit dem Wert "-3600" belegt wird.

**Comment by alnv** [comment]
> Kann ich diese Information auch für die Erfassung der Daten nutzen? Meine Versuche mit {{ctlg_tabellenname::feldname}} führten lediglich dazu, dass das Feld mit dem Wert "-3600" belegt wird.
Dieses Inserttag existiert nicht daher der Wert.

> In der Frontenderfassung soll nach der Auswahl eines Wertes aus der verknüpften Tabelle (Wert = ID) ein anderer Spaltenwert automatisch gezogen werden.
Wenn sich das Formular auf einer Detailseite befindet, könnte es mit dem Master IT gehen z.B
{{CTLG_MASTER::my_tableMyfield::?joinFields=1}} oder wenn es eine Elterntabelle ist {{CTLG_MASTER::my_tableMyfield::?joinParent=1}}

Ansonsten wäre ein eigener Inserttag notwendig: https://docs.contao.org/dev/framework/insert-tags/
