### ISSUE TITLE
Filter auf Kundentabelle funktioniert nicht

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#289]
Hallo,

ich habe zunächst eine Erweiterung der Tabelle tl_member angelegt.

Mit einer Listanzeige zeige ich ausgewählte Kundendaten (Member) als Liste an. Nun möchte ich diese Liste optional nach Nachname filtern.

Dazu habe ich über den Filtergenerator einen Filter angelegt: Feldbezeichnung = Nachname; Feldname = lastname . Das Filterformular ist im Artikel eingebunden.

Im Listmodul habe ich eine Taxonomie mit der Bedingung:
Feld = Nachname (lastname)
Operator = IN
Wert = { { CTLG_ACTIVE::lastname} }
eingerichtet. Das Ergebnis ist leider unbefriedigend. es werden keine Werte angezeigt. Auch Veränderungen des Operators brachten kein Ergebnis.

Ihre Beschreibung in der Doku ist hier nicht detailliert genug. Insbsondere vermisse ich die konkrete Beschreibung der Verbindung der Parameter und der damit verbundenen Vorgaben.

**Comment by alnv** [comment]
> Operator = IN

REGEXP wäre die besser Wahl

> Wert = { { CTLG_ACTIVE::lastname} }

Überprüfe ob das Insertag einen Wert zurückgibt (Inserttag's können überall auf der Seite platziert werden). 
Leerzeichen zwischen den Klammern sind nicht erlaubt (in der Doku ist es nur so, damit Contao diese nicht wegrendert). So sollte es gehen: {{CTLG_ACTIVE::lastname}}

> Ihre Beschreibung in der Doku ist hier nicht detailliert genug. Insbsondere vermisse ich die konkrete Beschreibung der Verbindung der Parameter und der damit verbundenen Vorgaben.

Das CTLG_ACTIVE Inserttag ist im Grunde eine abgewandelte Form der $_GET/$_POST Variable in PHP.

**Comment by gfassben** [comment]
Vielen Dank, die Leerzeichen waren das Problem.
