### ISSUE TITLE
Speichern + Duplizieren bei Feldern führt zu einem Contao Fehler

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#29]
Nutzt man "Speichern + Duplizieren" so schmeißt Contao einen internen Fehler ?!?

<img width="571" alt="catalog_manager_ _spangler____reisen_ _eingabefeld_mit_der_id_120_bearbeiten__-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27595482-170d913a-5b5d-11e7-913d-f359a7736e93.png">

**Comment by alnv** [comment]
Die Spaltennamen werden nicht escaped… Zudem darf die Option "Speichern und duplizieren" gar nicht angezeigt werden, da das duplizieren nicht aktiviert ist. Unter Contao 3.5 verhält es sich Richtig. Mal schauen wo der Wurm ist. Danke für den Hinweis.

Die Duplizieren-Funktion kommt noch nach… siehe #6 #26

**Comment by alnv** [comment]
Fehler wurde in der v1.3 behoben. Allerdings müssen alle "einzigartigen" Eingabefelder neu eingestellt werden. Siehe [Änderungsprotokoll](https://catalog-manager.alexandernaumov.de/anderungsprotokoll.html).
