### ISSUE TITLE
Beschreibung der Wizards zu den Modulen

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#290]
Hallo,

zu den angelegten Modulen im CM kann man Wizards anlegen. Ich finde leider keinerlei Beschreibung zu dieser Funktion.

Vielen Dank im voraus.

**Comment by alnv** [comment]
Das ganze ist ein Bestandteil der Wizard-Erweiterung für CM: https://github.com/alnv/catalog-manager-wizards

Diese wird nicht mehr Aktiv weiterentwickelt (ist eine Erweiterung für einen Kunden gewesen und darüber hinaus nie weiter entwickelt). Eine Doku wurde nicht erstellt.

**Comment by gfassben** [comment]
Klare Ansage - nicht verwenden. Danke für die Info.
