### ISSUE TITLE
Listanzeige verbundener Tabellen

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#292]
Hallo,

ich möchte in einer tabellarischen Liste die Daten der dem Listmodul zugeordneten Tabelle und die Daten der referenzierten Tabellen (Elterntabelle oder Mastertabelle) anzeigen.

Wenn ich das richtig sehe, gibt es folgende relevante Templates:

ctlg_view_master 
mod_catalog_table
ctlg_view_table

Wo wird angesetzt? Was ist wo genau zu tun? Die einfache Angabe mit "... Ausgabe mit this..." hilft mir nicht so recht weiter. Über eine Art "Kochrezept" würde ich mich sehr freuen.

Ist eine zusätzliche Funktionsumfang denkbar, dass man in der Listdefinition, die Felder der mit Beziehungen verbundenen Tabellen mit auswählt?

**Comment by gfassben** [comment]
Kleine Ergänzung: Contao Release 4.9.10, Catalog Manager 1.31.41

**Comment by alnv** [comment]
Momentan existiert nur die Möglichkeit die Daten aus referenzierten Tabellen über den `$this->tableFieldname` auszugeben. 
So kannst du alle verfügbaren Variablen in einem Template ausgeben:
<?php $this->showTemplateVars(); ?>

> Ist eine zusätzliche Funktionsumfang denkbar, dass man in der Listdefinition, die Felder der mit Beziehungen verbundenen Tabellen mit auswählt?

Ist derzeit nicht geplant

**Comment by gfassben** [comment]
Das ist Schade. Aus meiner sicht wäre das ein wichtiger Schritt für das Produkt, wenn man gerade an der Stelle mit weniger Programmierkenntnissen auskommt. 

Alternativ bin ich dann noch immer am sogenannten "Kochrezept" oder auch "How to" interessiert.
