### ISSUE TITLE
Frontend-Editing: Duplizieren von Einträgen -> DB-Feld "tstamp" (attribut "start") wird nicht befüllt

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#293]
Hallo Alex,

beim "Duplizieren" von Einträgen im Frontend-Editing wird das Attribut "start", also das "Anzeigen ab"-Datum nicht mit dupliziert. In der DB-Spalte "tstamp" wird der Wert "0" gespeichert.
Der duplizierte Eintrag wird in Folge in der Listenansicht nicht angezeigt.
Speichere ich den duplizierten Datensatz im Backend erneut ab, wird das Start-Datum befüllt und der Eintrag ist in der Listenansicht sichtbar.

**Comment by alnv** [comment]
Das ist so korrekt, ansonsten besteht die Gefahr, dass die Elemente sofort sichtbar sind (z.B in irgendwelchen Listen).

**Comment by jochi44** [comment]
Genau das möchte ich aber. Das im Frontend duplizierte Element soll sofort sichtbar sein.
Sonst muss ich ja als Seitenbetreiber immer schauen, ob neue Einträge da sind und die dann manuell sozusagen freischalten.
Hab ich eine Möglichkeit, das irgendwo zu definieren (tstamp soll befüllt werden)?
Sonst muss ich wohl die "Duplizieren"-Funktion ausblenden (was schade wäre, da ich die Funktion gut finde).
