### ISSUE TITLE
Nach Bearbeitung der Daten im FE wird der Filter zurückgesetzt.

### ISSUE THREAD

**Issue by gfassben** [alnv/catalog-manager#297]
Hallo,

eine Liste ist zur Bearbeitung im Frontend vorgesehen.

Über einen Filter werden die zu bearbeitenden Datensätze selektiert. Das funktioniert gut.

Wird die Bearbeitung eines Datensatzes durchgeführt, landet man gemß Definition wieder auf der Liste - leider ist dann der Filter wieder zurückgesetzt, so dass man die Filterkriterien nach jeder Bearbeitung wieder neu erfassen muss. 

Gibt es eine Möglichkeit, das zu verhindern?

**Comment by alnv** [comment]
Out of the box ist es nicht möglich.  

Eine mögliche Lösung (Programmierkenntnisse erforderlich):
Man könnte die GET-Parameter zwischen speichern (oder an "create-link" anhängen) und dann an die Weiterleitung übergeben (via "catalogManagerFrontendEditingRedirect"-Hook).
