### ISSUE TITLE
Listenansicht - Filter mit Jahreszahl

### ISSUE THREAD

**Issue by RoToK4** [alnv/catalog-manager#298]
Hallo, ich habe folgendes Anliegen!

Ich habe einen Select-Filter aus einer DB-Spalte erstellt (Datum)
Im Select wird das Jahr dargestellt, aber die Value ist natürlich der Timestamp aus der Datenbank.
Nach select gibt es einen GET-Parameter "fjahr" mit dem Timestamp aus der DB (zum Beispiel fjahr=1072911600 für 2004)

![Bildschirmfoto 2021-02-11 um 14 21 58](https://user-images.githubusercontent.com/78913204/107642074-ada1cb80-6c74-11eb-95a8-26d110b5b645.png)
![Bildschirmfoto 2021-02-11 um 14 22 28](https://user-images.githubusercontent.com/78913204/107642201-d88c1f80-6c74-11eb-8ac9-92919158955e.png)

Nun möchte ich die Liste nach Jahr filtern, sobald ein Jahr im Select ausgewählt wird.
Ich habe schon ein paar Ansätze hier gefunden, aber leider funktioniert keiner davon.

{{CTLG_ACTIVE::fjahr::year}}

{{CTLG_ACTIVE::fjahr::yearBegin}}
{{CTLG_ACTIVE::fjahr::yearEnd}}

Wie kann ich das lösen?

**Comment by alnv** [comment]
Die korrekte Syntax für die Inserttags wäre:

{{CTLG_ACTIVE::fjahr::?isDate=1&dateMethod=yearBegin}}
{{CTLG_ACTIVE::fjahr::?isDate=1&dateMethod=yearEnd}}

**Comment by RoToK4** [comment]
Super, genau das war!!
DANKE!!
