### ISSUE TITLE
Fehlermeldung in Verbindung mit rocksolid_custom_elements

### ISSUE THREAD

**Issue by mj1985** [alnv/catalog-manager#30]
Unter Contao 3.5 bekomme ich neuerdings folgende Fehlermeldung, wenn ich meine Rocksolid Custom Elements bzw. das Inhaltselement bearbeiten möchte:
```
Warning: Illegal string offset 'permission' in system/modules/catalog-manager/library/alnv/UserPermissionExtension.php on line 64

#0 system/modules/catalog-manager/library/alnv/UserPermissionExtension.php(64): __error(2, 'Illegal string ...', '/var/www/vhosts...', 64, Array)
#1 system/modules/catalog-manager/library/alnv/UserPermissionExtension.php(25): CatalogManager\UserPermissionExtension->extendUserAndUserGroupDCA('ads_news', 'tl_user')
#2 system/modules/core/library/Contao/DcaLoader.php(97): CatalogManager\UserPermissionExtension->initialize('tl_user')
#3 system/modules/core/library/Contao/Controller.php(1313): Contao\DcaLoader->load(false)
#4 system/modules/core/library/Contao/DcaExtractor.php(382): Contao\Controller::loadDataContainer('tl_user')
#5 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#6 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_user')
#7 system/modules/core/library/Contao/Model/QueryBuilder.php(52): Contao\DcaExtractor::getInstance('tl_user')
#8 system/modules/core/library/Contao/Model.php(1233): Contao\Model\QueryBuilder::find(Array)
#9 system/modules/core/library/Contao/Model.php(1068): Contao\Model::buildFindQuery(Array)
#10 system/modules/core/library/Contao/Model.php(796): Contao\Model::find(Array)
#11 system/modules/core/controllers/BackendMain.php(268): Contao\Model::findByPk('23')
#12 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}
```

Die normalen Contao-Elemente werfen **keine** Fehlermeldung.
Folgende Versionen sind installiert (über Composer):
alnv/catalog-manager v1.2.11
madeyourday/contao-rocksolid-custom-elements v1.3.11

Hat jemand eine Idee?

**Comment by alnv** [comment]
Das Modul Rocksolid Custom Elements wurde noch nicht getestet. Das werde ich demnächst machen und dir das Ergebnis mitteilen bzw. den Patch. 

Sonst würde ich das Install Tool ( _contao/install.php_ ) aufrufen und prüfen ob die "ads_news" Spalte auch angelegt ist. Gegebenenfalls auch manuell anlegen…

**Comment by mj1985** [comment]
Ich habe gerade über phpmyadmin geschaut, die Spalten existieren, das Install-Tool meldet auch keine Updates.
Falls du einen ersten Patch, die Lösung, hast - gerne vorab schicken. Wir nutzen RSCE recht viel und ich könnte schnell ein paar Dinge testen und Rückmeldung geben.

**Comment by alnv** [comment]
Ich konnte kein Fehler feststellen. Allerdings sollte ab der Version 1.3 folgender Fehler nicht mehr passieren:
`Warning: Illegal string offset 'permission' in system/modules/catalog-manager/library/alnv/UserPermissionExtension.php on line 64`

Das Update ist online. Versuche es mal damit. Sonst kannst du mir mal die Config & Template Datei von deinem Custom Element schicken…

**Comment by mj1985** [comment]
Update ist erfolgt, Fehlermeldung weiter vorhanden. Allerdings konnte ich das Problem in einer anderen Installation mit dem RSCE Template nicht reproduzieren.
Deshalb werde ich erstmal selbst weiter suchen.

**Comment by mj1985** [comment]
Ich konnte den Fehler nun in einer neuen Installation reproduzieren.
Hier habe ich die Tabelle neu angelegt und den Haken bei "Backend Modul einblenden" aktiviert, schon bekam ich wieder die Fehlermeldung von oben.
Ist der Haken raus, bleibt auch die Fehlermeldung aus.

**Comment by alnv** [comment]
Kommt immer noch die selbe Fehlermeldung?
? => `Warning: Illegal string offset 'permission' in system/modules/catalog-manager/library/alnv/UserPermissionExtension.php on line 64`

Ich verstehe überhaupt nicht wieso er beim Inhaltselement (tl_content), die Benutzer Table (tl_user) aufruft? Sehr seltsam… 

> Hier habe ich die Tabelle neu angelegt und den Haken bei "Backend Modul einblenden" aktiviert, schon bekam ich wieder die Fehlermeldung von oben.

Wenn die Tabelle nicht als BE Modul eingebunden ist, kannst du auch die Inhaltselemente nicht aufrufen, es seit den es handelt sich um eine Kind Tabelle. Daher kein Fehler.

Bei mir passiert immer noch nichts… kann einfach den Fehler nicht reproduzieren.

**Comment by mj1985** [comment]
Fehlermeldung:
```
Warning: Illegal string offset 'permission' in system/modules/catalog-manager/library/alnv/UserPermissionExtension.php on line 100

#0 system/modules/catalog-manager/library/alnv/UserPermissionExtension.php(100): __error(2, 'Illegal string ...', '/var/www/vhosts...', 100, Array)
#1 system/modules/catalog-manager/library/alnv/UserPermissionExtension.php(64): CatalogManager\UserPermissionExtension->getPermissionLabel()
#2 system/modules/catalog-manager/library/alnv/UserPermissionExtension.php(25): CatalogManager\UserPermissionExtension->extendUserAndUserGroupDCA('ads_employee', 'tl_user')
#3 system/modules/core/library/Contao/DcaLoader.php(97): CatalogManager\UserPermissionExtension->initialize('tl_user')
#4 system/modules/core/library/Contao/Controller.php(1319): Contao\DcaLoader->load(false)
#5 system/modules/core/library/Contao/DcaExtractor.php(382): Contao\Controller::loadDataContainer('tl_user')
#6 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#7 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_user')
#8 system/modules/core/library/Contao/Model/QueryBuilder.php(52): Contao\DcaExtractor::getInstance('tl_user')
#9 system/modules/core/library/Contao/Model.php(1233): Contao\Model\QueryBuilder::find(Array)
#10 system/modules/core/library/Contao/Model.php(1068): Contao\Model::buildFindQuery(Array)
#11 system/modules/core/library/Contao/Model.php(796): Contao\Model::find(Array)
#12 system/modules/core/controllers/BackendMain.php(268): Contao\Model::findByPk('23')
#13 system/modules/core/controllers/BackendMain.php(135): Contao\BackendMain->output()
#14 contao/main.php(20): Contao\BackendMain->run()
#15 {main}
```

Diese kommt, wenn ich das **RockSolid-Element bearbeiten möchte** und auch nur da. Bei den Contao-Standard-Elementen ist alles gut.

Sobald der Haken bei der Anzeigen als Modul im Catalog draußen ist, ist auch die Fehlermeldung weg.

**Comment by alnv** [comment]
Ich habe da eine Idee :)

Öffne die config.php in dem Catalog Manager Modul (`system/modules/catalog-manager/config/config.php`) und füge in der letzten Zeile folgende Variable ein:

`$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER'] = [];`

und sage mir ob der Fehler noch da ist. Wenn der Fehler noch da ist, versuche es mal damit:

`$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['permission'] = '';`

**Comment by mj1985** [comment]
Habe die beiden Zeilen an das Ende hinzugefügt. Die Fehlermeldung erscheint weiterhin. 
Bei den Rechten in den Benutzergruppen habe ich auch noch freie Felder:
![grafik](https://user-images.githubusercontent.com/5830093/27686659-09a9f6a0-5cd4-11e7-804c-57a555fbcf1e.png)

Ich kann dir gerne Zugangsdaten schicken, falls es dir weiterhilft.

**Comment by alnv** [comment]
Ja, kannst gerne mache => me@alexandernaumov.de

**Comment by alnv** [comment]
Bei dir werden die globalen Variablen nicht geladen. Betroffen sind:
`$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']`
`$GLOBALS['TL_LANG']['catalog_manager']`

Irgendwie wird `tl_user` Data-Container-Array vorzeitig geladen.

**Comment by mj1985** [comment]
Das war's. Besten Dank, nun ist die Fehlermeldung weg
