### ISSUE TITLE
Table like input

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#300]
Hi Alexander,
Gibt es eine möglichkeit wie eine Tabelle die Eintragen zu machen/ändern?
Also, mit CatalogListenansicht eine Liste machen und dann eine oder mehrere spalten mutieren. Keine neue Reihe.
Ich weiss, dass es eine möglichkeit gibt mit Wünschliste, aber dass ist für andere Anwendugen and ist Session abhängig.

Danke.

**Comment by alnv** [comment]
Hast du ein Beispiel? Meinst du es wie die Tabelle im Backend?

**Comment by robvis** [comment]
Ich meine in der Listenansicht.
Zum Beispeil die "Hvh" spalte Eintrage fähig machen.
Und am schönsten mit Hilfe +/- Tasten beim Nummerisch, wie im Frontend editing Display.
![image](https://user-images.githubusercontent.com/32883690/108629347-b4dc8c80-745f-11eb-82c2-3c9f7b75ac0e.png)

**Comment by robvis** [comment]
Hallo Alexander,
Haben Sie schon eine Hinweis?
Danke und Grüsse,
Rob
