### ISSUE TITLE
XML-Sitemap erstellen

### ISSUE THREAD

**Issue by FlorinvV** [alnv/catalog-manager#302]
Hallo Alexander,
aus irgendeinem Grund werden die Detailseiten nicht in die XML-Sitemap geschrieben, obwohl die Detailseite im Listenmodul ausgewählt ist, wie auf dem Screenshot auf der CM-Seite beschrieben. Das speichern in der Sitemap ist dort auf Standard gestellt. Die Seiten tauchen trotzdem nicht auf...
Gibt es da noch andere Dinge auf die ich achten muss?

Vielen Dank schonmal
Beste Grüße
Florin

**Comment by alnv** [comment]
Sobald in der Listenansicht eine Detailseite  unter "Detailansichtsseite festlegen" ausgewählt ist, sollten die URLs in die XML geschrieben werden. Es kann durch die Sitemap-Einstellung oder Filterung-Einstellungen verhindert werden, sonst sollte es immer funktionieren. Ich konnte jetzt auch kein Fehler feststellen.

**Comment by FlorinvV** [comment]
Hier die Screenshots:
Außer den Einstellungen die du hier siehst ist alles andere deaktiviert.
Ich habe auch am Template geschraubt, falls das noch interessant sein sollte.
<img width="1340" alt="Bildschirmfoto 2021-10-15 um 08 16 27" src="https://user-images.githubusercontent.com/57443264/137441366-98a1d7a9-318c-477a-ac90-5d5905085707.png"
<img width="1340" alt="Bildschirmfoto 2021-10-15 um 08 17 45" src="https://user-images.githubusercontent.com/57443264/137441381-5a24c420-859c-4d8b-93db-569d31c3bfd7.png">
<img width="1340" alt="Bildschirmfoto 2021-10-15 um 08 18 10" src="https://user-images.githubusercontent.com/57443264/137441392-6258569b-728f-47c6-bf5c-4476b420f960.png">
>

**Comment by FlorinvV** [comment]
Hey, irgendwie ist die Sache hier ein bisschen eingeschlafen...

Das Problem ist aber leider immer noch da... 

Ich habe die Einstellungen jetzt auch mit der der Demo verglichen, leider ohne Erfolg
Konntest du an den Einstellungen etwas festmachen? Oder kann es an Änderungen am Template liegen?

Es scheint auch nur bei dieser einen Installation zu passieren..

**Comment by alnv** [comment]
Ich kann es leider nicht reproduzieren. Vermutlich ist irgendwo in der Konfiguration was schief gelaufen. Wenn du magst, kannst du ein Support Ticket aufmachen: https://catalog-manager.org/support-ticket.html (um das Problem zu analysieren benötigen wir einen Contao Zugang)
