### ISSUE TITLE
Bild/Image im Taxonomie-Baum

### ISSUE THREAD

**Issue by smeyli** [alnv/catalog-manager#304]
Ausgangssituation:
Tabelle 1: Kategorien (mit Name und Bild)
Tabelle 2: Artikel

Über Tabelle 1 habe ich einen Taxonomie-Baum ausgegeben, über den man die Artikel erreicht - soweit ganz simple.
Ich möchte jedoch auch das zugehörige Bild der Kategorie mit ausgeben. 
Bei der Ausgabe der Template-Variablen für "ctlg_taxonomy_nav" finde ich leider nichts für das Bild.

Vielleicht ist mein Denkansatz auch in die verkehrte Richtung gegangen...

**Comment by alnv** [comment]
Du kannst mal auf "<?php var_dump($arrItem ) ?>" ausführen und schauen, was in der Variablen drin steckt. Es ist gut möglich, dass da die Bild Variable drin steckt. 

Falls, kein Debugtool installiert ist:
<?php echo $this->dumpTemplateVars() ?>
Damit werden alle Variablen im Template ausgegeben.
