### ISSUE TITLE
Problem Aliasgenerierung

### ISSUE THREAD

**Issue by TTenbergen-dev** [alnv/catalog-manager#305]
Hallo, 
ist es möglich den Alias im Feld Dynamischer-Wert so erzeugen zu lassen, dass nicht-URL-taugliche Zeichen entfernt oder in Unterstriche umgewandelt werden?

Das Umwandeln von Leerzeichen aus einem mit "Short Token" geholten Feld scheint auch nicht zu funktionieren!

Ist es eigentlich möglich im Feld Dynamischer-Wert auch Rechenoperationen mit den Werten anderer Felder durchzuführen? Das wäre auch sehr praktisch und hilfreich. In der Dokumentation steht zur Handhabung Dynamischer-Wert leider nicht so viel drin.

Vielen Dank für eine kompetente Antwort!

**Comment by alnv** [comment]
Hallo,

Es ist nur möglich mehrere Felder zu kombinieren. Rechenoperationen usw. sind nicht konfigurierbar.

> Das Umwandeln von Leerzeichen aus einem mit "Short Token" geholten Feld scheint auch nicht zu funktionieren!

Welche Funktion ist damit gemeint?
