### ISSUE TITLE
Frontend-Sortierung (Datum, Preis ...)

### ISSUE THREAD

**Issue by smeyli** [alnv/catalog-manager#306]
Ich würde sehr gern Datensätze im Frontend sortierbar machen. Anfangs dachte ich, dass es eher Standard-Funktionalitäten sind, doch es hat sich herausgestellt, dass es doch nicht so einfach geht.

In einem alten Support-Beitrag [https://catalog-manager.org/feedback/sortieren-nach-im-frontend.html](url) habe ich einen Ansatz gefunden, doch leider ist das angegebene Beispiel nicht mehr online, da die Demo-Seite mal mehr und mal weniger weniger kaputt gespielt wird ;-)

Wie kann man diese Frontend-Sortierung umsetzen? Das müsste doch mega viele Erweiterungsnutzer interessieren.

Vielen Dank schonmal für die Infos.

**Comment by alnv** [comment]
Das kann man mit dem Filtergenerator lösen. Dazu benötigst du 2 Eingabefelder (Feldauswahl & Reihenfolge). Siehe

Beispiel Konfiguration "Feldauswahl":
<img width="595" alt="screenshot" src="https://user-images.githubusercontent.com/1732915/120780143-11078000-c528-11eb-89cc-25c8ef0b9b67.png">

Beispiel Konfiguration "Reihenfolge":
