### ISSUE TITLE
Aus-/Einblendungs Auge wird nicht angezeigt / funktioniert nicht

### ISSUE THREAD

**Issue by martin-netprofit** [alnv/catalog-manager#307]
Hallo,

aktuell hab ich das Problem, das die Ein-/Ausblendungs Option (grünes Auge) in der Übersicht einfach nicht angezeigt wird. Die Dokumentation hat mir hier leider nicht weiterhelfen können oder hab ich hier etwas übersehen?
Ist das ein Bug oder mache ich hier noch etwas falsch?

**Einstellungen für diese Option:**
![Bildschirmfoto 2021-06-07 um 16 42 32](https://user-images.githubusercontent.com/25613502/121037500-c861f800-c7af-11eb-99a4-fa9a7e5bfa68.jpg)

**Übersicht:**
![Bildschirmfoto 2021-06-07 um 16 44 17](https://user-images.githubusercontent.com/25613502/121037771-052def00-c7b0-11eb-8134-c4000b3b92fc.jpg)

**Aktuelle Umgebung:**
Contao 4.9.13
Catalog-Manager: v1.31.50
PHP: 7.3

**Comment by alnv** [comment]
Sollte in v1.31.51 behoben sein. Allerdings musst du noch einmal die Katalog-Einstellungen abspeichern (Aus/Einblenden auswählen und dann speichern).

**Comment by martin-netprofit** [comment]
Top, hat funktioniert 👍
