### ISSUE TITLE
Sorting der Hauptsprache wird nicht übernommen bei übersetzten Einträgen

### ISSUE THREAD

**Issue by trilobit-gmbh** [alnv/catalog-manager#308]
Bspl:

- Katalog
  - Mitarbeiter Katalog
  - manuelle Sortierung ist eingestellt. Mitarbeiter lassen sich im Backend sortiert ausgeben
  - Übersetzung zu jedem Mitarbeiter anlegen

- Lister-Modul
  - Auswahl Mitarbeiter-Katalog
  - Taxonimie-Filter auf die aktuelle Sprache
  - Sortierung der Liste nach dem Sortierindex

- Frontend-Ausgabe
  - Hauptsprache: OK; Sortierung passt
  - andere Sprache: der Filter gibt die korrekten Items zurück; der Sortierindex ist jedoch immer '0', die Sortierung ist dann nach ID aufsteigend

Bei Fragen bitte PM

Viele Grüße
Peter

peter.adelmann@trilobit.de

**Comment by alnv** [comment]
Sollte mit v1.31.52 gefixt sein.

**Comment by trilobit-gmbh** [comment]
Hallo Alex,
der Kunde hat das getestet und es funktioniert. Vielen Dank!
Gruß
Peter
