### ISSUE TITLE
CM-Tabellen werden gelöscht bei Upgrade auf Contao 4.11.x

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#309]
Ist der Catalog Manager kompatibel mit Contao 4.11.x?

Wollte heute eine Contao 4.10.7-Installation (mit Catalog Manager) auf 4.11.4 upgraden.
Dabei werden alle Catalog Manager-Tabellen (unsere beginnen mit cm_*) gelöscht!

Hab keine Contao 4.9-longterm installiert, bei der ich das testen kann, nehme an, das Verhalten ist da gleich.
Bitte um Feedback.

**Comment by alnv** [comment]
Mit v1.31.52 wird das löschen von CM Tabellen verhindert.
