### ISSUE TITLE
Auswahlliste mit eigenen Werten

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#31]
Nutzt man Auswahllisten, die man durch eigen Werte bestückt, so findet man folgende Eingabemethodik vor:

<img width="463" alt="catalog_manager_ _spangler____reisen_ _eingabefeld_mit_der_id_136_bearbeiten__-_contao_open_source_cms" src="https://user-images.githubusercontent.com/2002902/27648943-7e269a50-5c30-11e7-8a8a-67af19c5bfb5.png">

Ich hatte zu Anfang unter Schlüssel "Sommer" und "Winter" eingetragen und unter Wert das eingetragen was in das Feld laufen soll. Überraschenderweise habe ich aber in meinem Select-Feld die Werte gesehen, die als Feldwert gedacht waren. Ich musste also die Eingabe umkehren um die richtige Darstellung zu bekommen.

<img width="330" alt="bildschirmfoto_2017-06-28_um_18_26_50" src="https://user-images.githubusercontent.com/2002902/27649099-0bb06162-5c31-11e7-9b0a-ac89abc62841.png">

Ist für mich nicht konsistent gelöst …

**Comment by alnv** [comment]
Ich habe die Labels umbenannt.
Schlüssel => Wert
Wert => Text
Da es ein Contao-Core Widget ist, habe ich es gar nicht wahrgenommen :) Danke für den Hinweis.

**Comment by codiso** [comment]
Gerne :-D
