### ISSUE TITLE
Datei-Upload / Erlaubte Dateitypen, Begrenzung auf 255 Zeichen

### ISSUE THREAD

**Issue by bogensee** [alnv/catalog-manager#310]
Wir haben den Catalog Manager bei einem Sprachdienstleister im Einsatz. Dieser benötigt mittlerweile zahlreiche Dateiformate für den Dateiupload, welche jetzt über die Grenze von 255 Zeichen hinausgehen.

Es wäre gut, wenn im Eingabefeld für die erlaubten Dateiendungen mehr als 255 Zeichen möglich wären.

**Comment by alnv** [comment]
Das kann man über die dcaconfig.php (oder app/Resources/contao/dca/tl_catalog_fields) anpassen:

$GLOBALS['TL_DCA']['tl_catalog_fields']['fields']['extensions']['sql'] = 'text NULL';

Danach Cache leeren und Install Tool ausführen.

**Comment by bogensee** [comment]
Danke Alexander! Die Lösung reicht für uns.
