### ISSUE TITLE
Bei Nutzung Filtergenerator Select Menü ( Auto Submit )

### ISSUE THREAD

**Issue by netSpeedyTV** [alnv/catalog-manager#312]
Hallo,

vielleicht sehe ich die Option nicht aber wenn ich den Filtergenerator nutze und z.B. Umkreissuche per Select Menü erstellt habe. Beim Suchen macht er Automatisch das (Filter) "Submit" wie oder wo kann man das Ausschalten.

**Comment by alnv** [comment]
Diese Einstellung findest du bei dem jeweiligen Eingabefeld. Siehe Allgemeine-Einstellungen > "Submit on change"

**Comment by netSpeedyTV** [comment]
Vielen dank für diese schneller Hilfe, dann muss ich jetzt noch 2 Sachen hinbekommen dann kann die Lizenz gekauft werden.
