### ISSUE TITLE
SQL data type changed to "unknown option"

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#313]
Hi Alexander>
I'm entering an new field type "checkbox menu" with SQL_data_type VARCHAR (32) and Evaluations setting "multiple".
When I save the field everything is fine.
Using these setting every thing is fine in the database field data is saved as comma separator, showing the front-end the check boxes are fine as well.
When I recall the catalog field definition the SQL_data_type changed from VARCHAR (32) to **"unknown option"**.
Please could you have a look at this?
thanks.
Rob

**Comment by alnv** [comment]
I guess the character length of 32 is too small for multiple selection. Try it with "blob NULL
