### ISSUE TITLE
changing language with module type "catalog master view"

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#314]
Hi Alexander,
I'm using the Terminal42 Changelanguage extention.
This works very good with Catalog-Manager.
I have 1 issue:
When changing language on a page with a "catalog master view" module, the "catalog master view" disappears.
All other page modules are shown and translated.
See my pictures before and after change language.
Hope you can explain and/or solve the issue.

**BEFORE change language**
![before_change_lang](https://user-images.githubusercontent.com/32883690/124272372-ea486380-db3e-11eb-9691-b6502d760252.png)

**AFTER change language**
![after_change_lang](https://user-images.githubusercontent.com/32883690/124272397-f2080800-db3e-11eb-9812-8e5bf6c0b412.png)

**Comment by alnv** [comment]
Make sure that the detail page is available and included in the appropriate language. Normally, no frontend module should disappear when it is included. Furthermore, there should be a record in the selected language.
