### ISSUE TITLE
Language change on "master view" request

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#315]
Hi Alexander,
When using the "select detail view page" the used page language is changed to the page language in the "select detail view page" and not the page language of the "root / calling" page.
So the language "select detail view page" is static the one choosen.
Please could you have a look at this issue?
thanks,
Rob Vis

![ScreenHunter 212](https://user-images.githubusercontent.com/32883690/124273478-58415a80-db40-11eb-8fc9-b281096d5ec3.png)

**Comment by alnv** [comment]
You need one frontend module (detail view) per language with corresponding selected detail page.
