### ISSUE TITLE
Catalob database structure update

### ISSUE THREAD

**Issue by robvis** [alnv/catalog-manager#316]
Hi Alexander,
I'm using Synccto from Menatwork, great tool!
When not syncing the database content, the table/column structure is not updated.
So, do you know a trick to update the DB table/column structure from catalog-manager?

I'm now writing down my changes and touch the change in catalog-manage again, than the db column is updated/added.
But this is very time consuming and when I forget to write down the change it gives issues.

Thanks in advance.

Best regards,
Rob

**Comment by alnv** [comment]
Sorry but I have no experience with the SyncTo module so far. 

Presumably the extension requires a DCA for the table, which Catalog Manager does not provide. Therefore it will probably not work with SyncTo.
