### ISSUE TITLE
Rechnen mit Timestamp liefert falsche Ergebnisse

### ISSUE THREAD

**Issue by cjlisten** [alnv/catalog-manager#318]
Hallo Alexander,
ich verwende **{{CTLG_TIMESTAMP::?add=7862400}}** als Standardwert, um zu einem gegebenen Datum 91 Tage hinzuzufügen (24 x 3600 x 91). Catalog-Manager liefert mir aber immer nur ein Datum einen Monat später. 
Mache ich was falsch oder kann die Funktion nur maximal 30 Tage addieren?

**Comment by alnv** [comment]
Hallo,

welchen "SQL Datentyp" hast du für das Feld ausgewählt?

Es gibt keine Obergrenze, habe es nochmal nachkontrolliert. Wenn mann den Inserttag ausgibt, wird der Richtige Zeitstempel angezeigt.

**Comment by cjlisten** [comment]
Hallo Alexander,

danke fürs Nachkontrollieren. Dachte mir schon, dass es mein Fehler ist. ;-))

Der Datentyp ist varchar(32) NOT NULL default, das Feld in der Catalog-Manager-Tabelle fürs Backend ist als Datumsfeld angelegt. 

Dank deinem Hinweis habe ich den Fehler inzwischen gefunden: Ich hatte im Formular, aus dem die Tabelle ihre Daten erhält, die falsche Zahl zum Zeitstempel hinzuaddiert. Sorry, an die Fehlerquelle hatte ich nicht gedacht!

Vielen Dank für deine Hilfe,
Claus
