### ISSUE TITLE
Listenansicht: Gruppierte Ausgabe der Eltern- und Kindelemente 

### ISSUE THREAD

**Issue by landzone21** [alnv/catalog-manager#319]
Ich erstelle eine Listenansicht der Kindtabelle und gruppiere die Ausgabe nach der pid. 
Im Frontend möchte ich anstelle der dargestellten PID andere Spalten aus der Elterntabelle ausgeben. Ist das möglich und wie kann ich diese Elemente ansprechen?
Danke

**Comment by landzone21** [comment]
Bedeutet das, dass die Listenansicht nicht "out of the box" funktioniert? Wenn man die Option "Gruppierung" aktiviert und die Option "Als Array ausgeben", dann ist die erste Option außer Kraft gesetzt, obwohl sie im FE-Modul aktiviert ist?

**Comment by alnv** [comment]
ja, genau. Wenn man die Daten als Array ausgibt werden die Template Einstellungen nicht berücksichtigt.

Es besteht auch die Möglichkeit mit einer DB-Abfrage, wenn der Gruppenwert eindeutig ist, das Element anzusprechen. Zum Beispiel so:

Siehe mod_catalog_universal Template
``` php
 <?php if ( $this->showAsGroup ):?>
      <?php foreach( $this->data as $strGroup => $arrOutput ): ?>
         <div class="group">
         	<?php 
                         // Meine DB-Abfrage
         		$objEntity = \Database::getInstance()->prepare('SELECT * FROM my_table WHERE field=?')->execute($strGroup);
         	?>
            <div class="group_headline foobar"><<?= $this->catalogGroupHeadlineTag; ?>><?= $objEntity->my_field; ?></<?= $this->catalogGroupHeadlineTag; ?>></div>
            <div class="group_content"><?= join( $arrOutput ); ?></div>
         </div>
      <?php endforeach; ?>
   <?php else: ?>
```

**Comment by landzone21** [comment]
Wunderbar, diese 2. Option war das, was ich suchte. 
Vielen Dank!
