### ISSUE TITLE
Feld Upload mit Option Galerie speichert keine Bilder

### ISSUE THREAD

**Issue by planepix** [alnv/catalog-manager#32]
Hallo Alex,

mit der aktuellen Contao 4.4.0 und dem neuesten Release des CM lassen sich Bilder in einem Eingabefeld „Galerie” auswählen, werden aber nicht gespeichert.

Eben auch in der Demo versucht. Nach dem Speichern ist die Liste der gewählten Bilder wieder leer.

Beste Grüße
Thomas

**Comment by alnv** [comment]
Hi Thomas,

der _SQL Datentyp_ ist zu klein. Wenn du es auf _blob NULL_ umstellst, sollte der upload wieder funktionieren.
![upload image sql data type](https://catalog-manager.alexandernaumov.de/files/theme/media/github/upload-sql-data-type.png)

Es kann passieren, wenn du den SQL Typ änderst, dass es zu einem Fehler kommt. Wenn dieser Fall Eintritt sollst du alle Spaltenwerte in der Galerie löschen. 

Ich prüfe gerade ob ich den Blob NULL Datentyp generell für Bilder verwende.

**Comment by planepix** [comment]
Besten Dank Alex,
genau das wars. Dann kann ich weiter testen.
