### ISSUE TITLE
Filterform Reset Text ändern

### ISSUE THREAD

**Issue by Fanni-Portier** [alnv/catalog-manager#323]
Hallo!

Ich möchte im Template "ce_catalog_filterform.html5" den Text für den Reset Link ändern.
Derzeit "Alle Filtereinstellungen zurücksetzen.".

Wie kann ich das machen?

**Comment by alnv** [comment]
Hierzu kannst du die Globale Variable in der default.php (oder langconfig.php) anpassen:

`$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['resetForm'] = 'Filtereinstellungen zurücksetzen';`
