### ISSUE TITLE
Canonical Tag in Catalog Detailansicht

### ISSUE THREAD

**Issue by Fanni-Portier** [alnv/catalog-manager#325]
Gibt es eine Möglichkeit ein Canonical Tag für den Modultyp "Catalog Detailansicht" zu definieren?

Besonders schön fände ich eine Möglichkeit das Canonical Tag direkt im Modul zu definieren.
So wie man es bei den Meta Tags kann.

Für die anderen Seiten verwende ich die Erweiterung "rel-canonical".
Da kann in der Seitenstruktur eine Seite für den Canonical Tag ausgewählt werden.
Kann ich da zum Beispiel auf ein Feld aus dem Catalog Manager zugreifen?

**Comment by alnv** [comment]
Ein Canonical-Tag Integration ist nicht vorhanden, auch nicht geplant. Grundsätzlich kannst du ja dafür ein eigenes Eingabefeld anlegen und dann im jeweiligen Template die passenden URLS ausgeben.

``` php
<?php 
$GLOBALS['TL_HEAD'][] = '<link rel="canonical" href="'.$this->myUrl.'" />';

```

**Comment by Fanni-Portier** [comment]
Vielen Dank!

**Comment by Fanni-Portier** [comment]
Jetzt muss ich doch nochmal fragen.
Ich weiß, dass das vermutlich nicht's mit dem Catalog Manager zu tun hat. Vielleicht bekomm ich aber trotzdem eine Antwort?

Ich habe für das Canonical Tag jetzt ein Textfeld mit Page Picker angelegt.
Wenn ich den Wert in den canonical Link übernehmen möchte wird aber das Inserttag nicht interpretiert. Sondern einfach so ausgegeben {{link_url::1}}.

**Comment by alnv** [comment]
Damit kannst du den InsertTag parsen: <?= \Controller::replaceInsertTags('{{link_url::1}}') ?>

**Comment by Fanni-Portier** [comment]
Danke - mit dem Wort parsen hab ich's dann gefunden ;)
$this->replaceInsertTags();
