### ISSUE TITLE
404 bei geschütztem Detailansichtelement

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#327]
Hallo Alexander,
wenn man auf deiner Detailansicht das Detailansicht-Modul mit einer Gruppe für Mitglieder schützt, bekommt man ein 404. Ich habe an dieser Stelle nur das Modul und nciht die gesamte Seite geschützt. Stattdessen sollte hier eine leere Seite erscheinen.
Logge ich mich dagegen im Frontend ein und rufe dann die Detailansicht auf, so funktioniert es.

Genaues Setup:
Modul Listenansicht (nicht geschützt) -> Weiterleitung zu Modul Detailansicht (FE-Mitglieder geschützt)

Contao 4.9.20
Catalog Manager: v1.31.58

**Comment by alnv** [comment]
Hi,

Sobald ein Alias gesetzt ist, gibt es eine 404 Fehlermeldung. Diese kommt auch nicht von der Detailansicht (ist ja deaktiviert). Wenn man angemeldet ist, dann wird die Detailansicht auch generiert und es gibt keine 404 Meldung. Das ist korrekt so.

Wenn du 404 Meldung deaktivieren willst, musst du irgendwo im template `\Input::get('auto_item')` aufrufen…
