### ISSUE TITLE
Filtergenerator // leere Filter nicht anzeigen

### ISSUE THREAD

**Issue by Fanni-Portier** [alnv/catalog-manager#328]
Hallo!

Ich habe im Filtergenerator einen Feldtyp "Radio-Menü" angelegt.
Im Frontend möchte ich verhindern, dass Filter angezeigt werden, die kein Ergebnis finden.

Ist das irgendwie möglich?

**Comment by alnv** [comment]
Siehe hier https://catalog-manager.org/dokumentation/catalog-manager-filter-generator.html > Schritt 6
