### ISSUE TITLE
HTML-Tags bei tinyMCE-Feldern im Frontend sichtbar

### ISSUE THREAD

**Issue by dive13** [alnv/catalog-manager#330]
Mir fällt nach einem Update plötzlich auf, dass die Inhalte aus Textareas mit TinyMCE im Frontend inkl. HTML-tags ausgegeben werden. Tritt bei bestehenden aber auch neuen Feldern auf, sobald neu gespeichert wird. Als SQL-Datentyp habe ich seit jeher text NULL eingestellt. Ich verwende auch kein eigenes bzw. angepasstes tinyMCE-template. Fehlerhafte oder überflüssige Formatierungen bei der Eingabe im tinyMCE kann ich ebenfalls ausschließen.

Catalog Manager 1.31.58
Contao 4.9.22

**Comment by alnv** [comment]
Damit kannst du die HTML-Entities umwandeln: <?= \StringUtil::decodeEntities($this->myFieldname); ?>

Das kannst du direkt im Template aufrufen.
