### ISSUE TITLE
Probleme beim Duplizieren Frontendbearbeitung

### ISSUE THREAD

**Issue by Veronikas** [alnv/catalog-manager#333]
Datensätze, die bei der Frontendbearbeitung dupliziert werden, werden im Frontend nicht angezeigt, auch wenn bei der Berechtigungsart Standard ausgewählt ist (also kein explizites Freischalten). Im Backend werden sie indessen als freigeschaltet angezeigt: _Datensatz verstecken nein_ 

Wenn man in der Frontendbearbeitung _Sichtbarkeit ignorieren_ wählt, kann man sich die duplizierten Datensätze zwar anzeigen lassen, wenn man sie jedoch dann im Frontend bearbeiten möchte, wird ein leerer Datensatz ausgegeben.

Nur wenn man die Duplikate im Backenend einmal öffnet und speichert, werden sie regulär ausgegeben.

Catalog Manager 1.31.60
Contao 4.9.24

**Comment by alnv** [comment]
Ist behoben in v1.31.61

**Comment by Veronikas** [comment]
Sehr schön. Danke!
