### ISSUE TITLE
Taxonomies/Filterung

### ISSUE THREAD

**Issue by ngdot** [alnv/catalog-manager#335]
Unter Contao 4.9.24 und der aktuellste Catalog Manager Version 1.31.61 gibt es Probleme mit den Filtern innerhalb eines Moduls.
Ich aktiviere die Checkbox "Taxonomies/Filterung aktivieren", aber ich kann einfach keine hinzufügen. Nach dem Klick auf das grüne "+" passiert einfach nichts. Komisch ist, wenn ich das Modul via einem Content Element Module Include über die Lightbox editiere, klappt das hinzufügen der Filter ganz normal und die vorhanden Filter werden angezeigt. Wenn ich aber über Themes => Theme => Module rein gehe, werden einfach keine Filter angezeigt und ich kann auch keine ergänzen.

**Comment by akroii** [comment]
Zeigt die Browser-Konsole etwas an, während du versuchts auf das grüne Plus zu klicken?

**Comment by herrrilke** [comment]
so, und jetzt wird's spannend:

ich habe eine andere installation - contao 4.9.24 und CM 1.31.61 (gleiche versionen wie ngdot) - da funktioniert es.

was jetzt ?!

**Comment by akroii** [comment]
Kann evtl. eine Extension dazwischenfunken? Wie sieht deine Composer.json aus?

**Comment by herrrilke** [comment]
ich nehm's fast an...

das ist die json der  "defekten" installation:

`{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Managed Edition",
    "license": "LGPL-3.0-or-later",
    "require": {
        "alnv/catalog-manager": "^1.31",
        "alpdesk/alpdesk-parallax": "^1.0",
        "clickpress/contao-clickpress-grid": "^1.0",
        "codefog/contao-mobile_menu": "^2.7",
        "contao/calendar-bundle": "4.13.*",
        "contao/conflicts": "*@dev",
        "contao/listing-bundle": "4.13.*",
        "contao/manager-bundle": "4.13.*",
        "contao/news-bundle": "4.13.*",
        "craffft/css-style-selector-bundle": "^1.6",
        "do-while/contao-backupdb-bundle": "^1.5",
        "heimrichhannot/contao-slick-bundle": "^1.6",
        "jrgregory/m17-sticky-backend-footer": "^2.0.9",
        "madeyourday/contao-rocksolid-custom-elements": "^2.1",
        "madeyourday/contao-rocksolid-icon-picker": "^2.0",
        "omosde/contao-om-backend": "^1.7",
        "oveleon/contao-component-style-manager": "^2.5",
        "oveleon/contao-cookiebar": "^1.7",
        "terminal42/contao-leads": "^1.4",
        "terminal42/notification_center": "^1.6"
    },
    "conflict": {
        "contao-components/installer": "<1.3"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}
`

ich habe einen diff gemacht.
dies sind die erweiterungen, die nicht in der funktionierenden installation sind:

 `
"alpdesk/alpdesk-parallax": "^1.0",
"heimrichhannot/contao-slick-bundle": "^1.6", 
"oveleon/contao-component-style-manager": "^2.5", 
"terminal42/contao-leads": "^1.4",
"terminal42/notification_center": "^1.6"
`

ich tippe ja mal gleich auf die erste, weil die auch eintragungen in den seiteneinstellungen vornimmt.
... mh, componsten-style manager auch ...
teste ich mal aus.

**Comment by herrrilke** [comment]
AAAAAND the winner is ....

"oveleon/contao-component-style-manager": "^2.5", 

den habe ich deinstalliert - seitdem läuft's.
sehr schade, denn er ist mir sehr an's herz gewachsen und jetzt bin ich stil-los  :(

**Comment by akroii** [comment]
Du kannst den Leuten von oveleon auch gerne mal ein Ticket aufmachen. Die freuen sich bestimmt über Verbesserungsvorschläge. Brauchst aber eine Stacktrace. Hast du eigentlich mal den Debugmode im Backend aktiviert und mal geguggt ob irgendwas kommt?

**Comment by herrrilke** [comment]
nee, das wär' schlau gewesen, hab ich aber nicht gemacht & also kein stacktrace ...
