### ISSUE TITLE
natcasesort für IDs

### ISSUE THREAD

**Issue by akroii** [alnv/catalog-manager#336]
Hallo Alexander,
ist es möglich in dem Frontend-Modul eine weitere SortierungsMethode für Listenelemente auszugeben?
Bisher kann ich "nur" Aufsteigend oder Absteigend sortieren.
Bei numerischen IDs kommt es dabei zu unerwünschten (oder besser gesagt zu einer unnatürlichen Reihenfolge).
Aufsteigend wird wier folgt sortiert:
`ID: 10,11,20,4`
sollte eigentlich
`ID: 4,10,11,20`
sortiert werden.

Kann man [https://www.php.net/manual/en/function.natcasesort.php](https://www.php.net/manual/en/function.natcasesort.php) für IDs implementieren? Oder vlt sowas ähnliches?
[https://3v4l.org/RKj9r](https://3v4l.org/RKj9r) (thanks to fritzmg)
[https://contao.slack.com/archives/CK4J0KNDB/p1642060618082400](https://contao.slack.com/archives/CK4J0KNDB/p1642060618082400)

**Comment by fritzmg** [comment]
As already explained in Slack, you do not need natural sorting in order to sort numeric values.

**Comment by alnv** [comment]
Die Reihenfolge hängt auch vom Datentyp ab (SQL) z.B.
varchar sortiert ID: 10,11,20,4
int sortiert ID: 4,10,11,20
Vermutlich hast du für die IDs varchar als Datentyp gewählt, wenn du es auch int umstellst, sollte es mit der Reihenfolge klappen.
