### ISSUE TITLE
Bilder/Dateien ohne Vorgabe rendern

### ISSUE THREAD

**Issue by madi84** [alnv/catalog-manager#34]
Das Dabenbankfeld "disableFileRendering" und "disableImageRendering" scheint gedroppt worden zu sein. Im Backend finde ich die Option auch nicht mehr. Wurde die Funktion rausgenommen? 

Habe das an vielen Stellen benutzt. Man will ja den Link auch mal um was anderes legen, z.B.  den Titel oder ein Bild. So ist man immer auf die eine Ausgabe beschränkt:

`<a href="de/test.html?file=files/datei.pdf" title="Die Datei datei.pdf herunterladen">datei.pdf <span class="size">(2,9 MiB)</span></a>`

Statt der Option im Backend könnte man doch neben dem gerenderten Link einfach noch die einzelnen Daten zusätzlich als Variable anbieten?

**Comment by alnv** [comment]
So eine Funktion existiert bereits für die Bilder Galerie. Dort lässt sich die Galerie als ein Array ausgeben. Damit kann man auf spezielle Attribute zugreifen z.B $this->myGallery[0][0]->src
![Galerie als Array ausgeben](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Bilder-Galerie-als-Array.png)

Die gleiche Funktion könnte ich auch für einfache Bilder/Download/s implementieren.

Wäre das in Ordnung?

**Comment by madi84** [comment]
Klar, ein Array mit den Daten ist super. Die Funktion gabs schon mal für Dateien/Bilder, habe in den templates viel mit z.B. $this->file[href] gearbeitet. Vielleicht war das aber noch mit dem F-Modul.

**Comment by alnv** [comment]
Ist erledigt. Alle Upload Typen können als Array ausgegeben werden.

**Comment by madi84** [comment]
Super, funktioniert einwandfrei. Danke!
