### ISSUE TITLE
Make catalog-manager PHP 8.0/8.1 compatible

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#343]
The catalog-manager does not seem to be fully compatible with PHP 8.0 / PHP 8.1.
I updated one of my installations to Contao 4.13.2 and to PHP 8.0.16.

Already when only calling the backend I get a lot of php related errors in the error.log of the server.

Example:
```
2022/04/06 12:12:04 [error] 18846#18846: *609 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "MOD" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105
PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105PHP message: PHP Warning:  Undefined array key "design" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105PHP message: PHP Warning:  Undefined array key "catalog-manager-extensions" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105
PHP message: PHP Warning:  Undefined array key "accounts" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105
PHP message: PHP Warning:  Undefined array key "system" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105PHP message: PHP Warning:  Undefined array key "notification_center" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 105PHP message: PHP Warning:  Undefined array key "tl_class" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/CatalogFieldBuilder.php on line 155
PHP message: PHP Warning:  Undefined array key "label" in /var/www/clients/vendor/alnv/catalog-manager/library/alnv/C" while reading response header from upstream, client: 1.1.1.1, server: test.tld, request: "GET /contao/login?_hash=uFcPEe1TgbOPPg09xDDo%2FGN7Ou0TbgvyrNp36QYn5Jg%3D&redirect=https%3A%2F%2Ftest.tld%2Fcontao HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web50.s
```

**Comment by jochi44** [comment]
There are still some errors in the error.log of the server when running PHP 8.1.5:

`2022/04/29 16:40:22 [error] 8200#8200: *9 FastCGI sent in stderr: "v/CatalogDcExtractor.php on line 300" while reading response header from upstream, client: 11.111.111.11, server: test.tld, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web50.sock:", host: "test.tld"`

`2022/04/29 16:40:22 [error] 8200#8200: *9 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "flag" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/CatalogDcExtractor.php on line 300PHP message: PHP Warning:  Undefined array key "kz_kauf_miete" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/Fields/Radio.php on line 47PHP message: PHP Warning:  Undefined array key "title" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 80PHP message: PHP Warning:  Undefined array key "alt" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 91PHP message: PHP Warning:  Undefined array key "link" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 93PHP message: PHP Warning:  Undefined array key "caption" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 95PHP message: PHP Warning:  Undefined array key "title" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 80PHP message: PHP Warning:  Undefined array key "alt" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 91PHP message: PHP Warning:  Undefined array key "link" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 93PHP message: PHP Warning:  Undefined array key "caption" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 95PHP message: PHP Warning:  Undefined array key "title" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 80PHP message: PHP Warning:  Undefined array key "alt" in /var/www/clie`

`2022/04/29 16:41:29 [error] 8200#8200: *47 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "MOD" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Undefined array key "design" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Undefined array key "catalog-manager-extensions" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Undefined array key "accounts" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Undefined array key "system" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104PHP message: PHP Warning:  Undefined array key "notification_center" in /var/www/clients/web/test/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104" while reading response header from upstream, client: 11.111.111.11, server: test.tld, request: "POST /contao?do=wartung_unternehmen&ref=4J7VpS6y HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web50.sock:", host: "test.tld", referrer: "https://test.tld/"`

**Comment by akroii** [comment]
```
ErrorException:
Warning: Undefined array key "MOD"

  at vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php:105
  at CatalogManager\I18nCatalogTranslator->get()
     (vendor/alnv/catalog-manager/library/alnv/CatalogManagerInitializer.php:93)
  at CatalogManager\CatalogManagerInitializer->setNavigation()
     (vendor/alnv/catalog-manager/library/alnv/CatalogManagerInitializer.php:31)
  at CatalogManager\CatalogManagerInitializer->initialize()
     (vendor/contao/core-bundle/src/Framework/ContaoFramework.php:384)
  at Contao\CoreBundle\Framework\ContaoFramework->triggerInitializeSystemHook()
     (vendor/contao/core-bundle/src/Framework/ContaoFramework.php:286)
  at Contao\CoreBundle\Framework\ContaoFramework->initializeFramework()
     (vendor/contao/core-bundle/src/Framework/ContaoFramework.php:121)
  at Contao\CoreBundle\Framework\ContaoFramework->initialize()
     (vendor/contao/core-bundle/src/Security/User/ContaoUserProvider.php:68)
  at Contao\CoreBundle\Security\User\ContaoUserProvider->loadUserByIdentifier()
     (vendor/contao/core-bundle/src/Security/User/ContaoUserProvider.php:87)
  at Contao\CoreBundle\Security\User\ContaoUserProvider->refreshUser()
     (vendor/symfony/security-http/Firewall/ContextListener.php:236)
  at Symfony\Component\Security\Http\Firewall\ContextListener->refreshUser()
     (vendor/symfony/security-http/Firewall/ContextListener.php:137)
  at Symfony\Component\Security\Http\Firewall\ContextListener->authenticate()
     (vendor/symfony/security-bundle/Debug/WrappedLazyListener.php:49)
  at Symfony\Bundle\SecurityBundle\Debug\WrappedLazyListener->authenticate()
     (vendor/symfony/security-http/Firewall/AbstractListener.php:26)
  at Symfony\Component\Security\Http\Firewall\AbstractListener->__invoke()
     (vendor/symfony/security-bundle/Debug/TraceableFirewallListener.php:73)
  at Symfony\Bundle\SecurityBundle\Debug\TraceableFirewallListener->callListeners()
     (vendor/symfony/security-http/Firewall.php:92)
  at Symfony\Component\Security\Http\Firewall->onKernelRequest()
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (vendor/symfony/http-kernel/HttpKernel.php:128)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (web/index.php:44)
  at require('/srv/www/akroll/public/bw/web/index.php')
     (web/app.php:13)  
```

**Comment by akroii** [comment]
It seems to work in v1.32.5

**Comment by jochi44** [comment]
Contao v4.13.5
Catalog Manager v1.32.5
PHP v8.1.5

The following errors definitely occur when only calling the Contao backend at https://test.tld/contao:

`PHP message: PHP Warning:  Undefined array key "MOD" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Undefined array key "design" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Undefined array key "catalog-manager-extensions" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Undefined array key "accounts" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Undefined array key "system" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104`

`PHP message: PHP Warning:  Undefined array key "notification_center" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/I18nCatalogTranslator.php on line 104" while reading response header from upstream`

**Comment by jochi44** [comment]
Contao v4.13.5
Catalog Manager v1.32.5
PHP v8.1.5

The following errors occur when calling the frontend where some Catalog Manager modules are integrated (some may be specific to my installation):

```
PHP message: PHP Warning:  Undefined array key "Fleischfachmarkt" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Gärtnerei" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Baumschule" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Gas" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Gastrobedarf" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Gebrauchsgegenstände" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
PHP message: PHP Warning:  Undefined array key "Geschenke" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/Fields/Select.php on line 60
```

```
PHP Warning:  Undefined array key "caption" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 95
PHP message: PHP Warning:  Undefined array key "title" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 80
PHP message: PHP Warning:  Undefined array key "alt" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 91
PHP message: PHP Warning:  Undefined array key "link" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 93
PHP message: PHP Warning:  Undefined array key "caption" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 95
```

```PHP message: PHP Warning:  Undefined array key "link" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 348```

**Comment by jochi44** [comment]
Contao: 4.13.10
Catalog Manager v1.32.17
PHP 8.1.10
======================================================================

The following warnings still occur when running Catalog Manager v1.32.17 on PHP 8.1.10:

```
PHP message: PHP Warning:  Undefined array key "link" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 345
PHP message: PHP Warning:  Undefined array key "title" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 129
PHP message: PHP Warning:  Undefined array key "alt" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 140
PHP message: PHP Warning:  Undefined array key "link" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 142
PHP message: PHP Warning:  Undefined array key "caption" in /var/www/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 144
```

**Comment by jochi44** [comment]
Catalog Manager v1.32.18 fixed some of the php8.1 related issues.
These warnings are new:

```
PHP message: PHP Warning:  Undefined array key 1 in /var/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 319
PHP message: PHP Warning:  Undefined array key 2 in /var/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 319
PHP message: PHP Warning:  Undefined array key 3 in /var/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 319
PHP message: PHP Warning:  Undefined array key 4 in /var/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 319
PHP message: PHP Warning:  Undefined array key 5 in /var/web/vendor/alnv/catalog-manager/library/alnv/GalleryCreator.php on line 319

PHP message: PHP Warning:  Undefined property: stdClass::$addImage in /var/web/vendor/contao/core-bundle/src/Resources/contao/templates/gallery/gallery_default.html5 on line 5
PHP message: PHP Warning:  Undefined property: stdClass::$addImage in /var/web/vendor/contao/core-bundle/src/Resources/contao/templates/gallery/gallery_default.html5 on line 5

PHP message: PHP Warning:  Undefined array key kz_kauf_miete in /var/web/vendor/alnv/catalog-manager/librar/y/alnv/Fields/Radio.php on line 47

PHP message: PHP Warning:  Undefined array key model in /var/web/vendor/alnv/catalog-manager/library/alnv/Fields/Upload.php on line 36

PHP message: PHP Warning:  Array to string conversion in /var/web/vendor/contao/core-bundle/src/Resources/contao/templates/block/block_unsearchable.html5 on line 3
```

**Comment by alnv** [comment]
Die Warnings die den CM betreffen wurden in der v1.32.20 gefixt.
