### ISSUE TITLE
v1.32.4: php-error "array_filter() expects parameter 1 to be array, string given"

### ISSUE THREAD

**Issue by jochi44** [alnv/catalog-manager#347]
Contao: 4.13.4
PHP: 7.4.29

Yesterday's version update to v.1.32.4 seems to lead to a php-error (error.log on server):
`2022/05/19 11:44:06 [error] 20232#20232: *87682 FastCGI sent in stderr: "PHP message: PHP Warning:  array_filter() expects parameter 1 to be array, string given in /var/www/test/vendor/alnv/catalog-manager/library/alnv/CatalogView.php on line 1154`

**Comment by alnv** [comment]
Should fixed in v1.32.5

**Comment by jochi44** [comment]
I can confirm that the error is fixed with v1.32.5.
