### ISSUE TITLE
Probleme mit dem neuen Contao Manager

### ISSUE THREAD

**Issue by daniel-berger-nemeth** [alnv/catalog-manager#358]
Hi.
Contao Manager 1.6.0
Contao 4.13.8
Catalog Manager 1.32.15

Ich kann den Catalog Manager zwar anstandslos installieren, jedoch erkennt der neue Contao Manager anscheinend die Datenbanktabellen nicht bzw. kann ich die Datenbanktabellen für den Catalog Manager nicht installieren.

LG

**Comment by daniel-berger-nemeth** [comment]
Als zusätzliche Information. Ich habe lediglich Contao und den Catalog Manager installiert. Es sind keine anderen Erweiterungen installiert.

**Comment by Anke** [comment]
Der Catalog-Manager ist laut letztem Änderungsprotokoll nur für Contao 4.4 bzw. 4.9 konzipiert. 

Ferner habe ich die Info gefunden, dass Catalog-Manager Version 2 "auf Anfrage" und "unter bestimmten Voraussetzungen" über ein Support-Ticket bezogen werden kann. Was genau bedeutet das??? Dass ein Upgrade kostenpflichtig ist? Dass man es nicht mehr selbst installieren kann? Mit welcher Contao-Version ist Version 2 kompatibel? Gibt es ganz neue Features oder Strukturen und wenn ja, welche?

@alnv: Es wäre schön, wenn du uns aufklären würdest, wie es mit dem wunderbaren Catalog-Manager weitergeht.

**Comment by alnv** [comment]
Das wurde in v1.32.16 gelöst.

> Ferner habe ich die Info gefunden, dass Catalog-Manager Version 2 "auf Anfrage" und "unter bestimmten Voraussetzungen" über ein Support-Ticket bezogen werden kann. Was genau bedeutet das??? Dass ein Upgrade kostenpflichtig ist? Dass man es nicht mehr selbst installieren kann? Mit welcher Contao-Version ist Version 2 kompatibel? Gibt es ganz neue Features oder Strukturen und wenn ja, welche?

Bezieht es sich noch auf das obige Problem? Ansonsten würde ich das Issue schließen … 

Um deine Frage zu beantworten:

CM 2 ist bereits öffentlich zugänglich. Das kann jeder installieren und testen. Siehe https://extensions.contao.org/?q=catalog-manager-bund&pages=1&p=alnv%2Fcatalog-manager-bundle

Es gibt aber noch keine Dokumentation. Zudem fehlt noch Contao 5 und PHP 8 Unterstützung und ganz wichtig, CM 2 ist nicht Rückwärtskompatibel zu CM 1.

Mehr Informationen gerne über direkt Anfrage an: info@catalog-manager.org
