### ISSUE TITLE
Problems with other Extensions

### ISSUE THREAD

**Issue by JessesNei** [alnv/catalog-manager#359]
If I have installed the catalog Manager extensions and I install f.e. another extension like con4gis or Rocksolid slider the installation is successful but the extensions will not be shown in the backend.

Also in the contao manager the isn't shown that a DB Update would be needed but if I install the same extensions without catalog manager installed there is a DB update needed. ( I just learnd if i check via Installtool I can run the DB update)

If I have installed the Rocksolid slider before and add the catalog manager if I want to change a frontend module that I use as a slider template I can not see the fields to change the slider behavior anymore

Contao Manager 1.6.0
Contao 4.13.8
PHP 7.4

**Comment by alnv** [comment]
> If I have installed the catalog Manager extensions and I install f.e. another extension like con4gis or Rocksolid slider the installation is successful but the extensions will not be shown in the backend.
> 
> Also in the contao manager the isn't shown that a DB Update would be needed but if I install the same extensions without catalog manager installed there is a DB update needed. ( I just learnd if i check via Installtool I can run the DB update)
> 

this should fixed in v1.32.16
