### ISSUE TITLE
Taxonomies/Filter für Datenbank Auswahlliste erweitern

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#36]
Hallo,

ich würde gerne ein Eingabefeld mit dem Typ Select-Menü erstellen. Das Feld soll aus der Datenbank tl_member die Mitglieder auswählen können. Hierbei möchte ich aber nur bestimmte Mitglieder zur Auswahl anzeigen.
Besteht die Möglichkeit, die Datenbankfelder aus der Auswahltabelle, in dem Fall tl_member, ebenfalls für die Filterung freizuschalten?
So könnte dann z.B. alle Mitglieder von Firma "A", die noch aktive sind, auswählen.

VG
André

**Comment by alnv** [comment]
Ich werde es prüfen und gegebenenfalls im nächstem Update nachrüsten.

**Comment by andre5tz** [comment]
Das hört sich gut an, danke schon mal :-)

**Comment by alnv** [comment]
Alle core Module können ab v1.5 gefiltert werden.
