### ISSUE TITLE
Nach update sind meine Filteransichten kaputt - kann man das irgendwie leicht fixen?

### ISSUE THREAD

**Issue by HeinZHeinriCh** [alnv/catalog-manager#360]
Hallo nach update funktionieren die gefilterten Frontendansichten nicht mehr so wie zuvor ...

Diese sind als externe Verlinkung angelegt auf eine neue Seite:

Also nach folgenden Schema: 

- www.egal.de/kontakte/?department=32 >> für Abteilung A
- www.egal.de/kontakte/?department=33 >> für Abteilung B

Jemand ne Idee warum das nicht mehr funktioniert oder wie man das reparieren kann? Mit dem Filtergenerator bin ich da echt überfordert ...

Schon Mal vielen Dank

Mit freundlichen Grüßen

Heiner

**Comment by alnv** [comment]
Hallo,

Leider reicht die Beschreibung des Problems für die Fehlersuche nicht aus. Wir brauchen mehr Infos zur der ganzen Konfiguration.

Du kannst auch gerne hier ein https://catalog-manager.org/support-ticket.html Ticket erstellen.
