### ISSUE TITLE
Datenbankeinstellungen - Sortierungs-Felder und Anzeige-Felder - Start und Stop?

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#37]
Hallo,

in den Datenbankeinstellungen unter Sortierungsfeld/er und Anzeige-Felder können die entsprechenden Datenbankfelder ausgewählt werden. Es fehlen dabei die Felder Start und Stop, die ja eigentlich bei allen Tabellen automatisch mitangelegt werden.

Wenn es keinen Grund dafür gibt, dass die Felder nicht angezeigt werden, wäre es schön, wenn auch die beiden Felder bei der Auswahl erscheinen würden :-)

Vielen Dank schon mal und viele Grüße
André

**Comment by alnv** [comment]
Kommt mit dem nächstem Update. Danke für den Hinweis :)

**Comment by alnv** [comment]
Ist erledigt in v1.5
