### ISSUE TITLE
ID als Filterfeld nutzen?

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#38]
Hallo Alexander, ich habe es irgendwie nicht geschafft das Feld ID als Sortier- oder Filterfeld zu aktivieren? Was muss ich tun das das geht?

**Comment by alnv** [comment]
Um welche Einstellung handelt es sich?

**Comment by codiso** [comment]
Ich möchte die Panel Einstellung so haben, das nach ID sortiert werden kann.Am 17.07.2017 5:11 nachm. schrieb Alexander Naumov <notifications@github.com>:Um welche Einstellung handelt es sich?

**Comment by alnv** [comment]
Die Darstellung auf "Sortierung nach einem Variablen Feld" setzen.
![Sortierung nach einem Variablen Feld](https://catalog-manager.alexandernaumov.de/files/theme/media/github/BE-Darstellung.png)

Danach sollte es gehen. Vorausgesetzt ist die 1.4 Version.

**Comment by codiso** [comment]
Ich schaffe es nicht im Filter in der Liste die ID zu filter oder zu sortieren ?!?
Was mache ich falsch?

**Comment by alnv** [comment]
Wie beschrieben die **Darstellung** auf **Sortierung nach einem Variablen Feld** setzen und die entsprechende Felder im Panel aktivieren:
![Contao Panel Layout](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Panel-Layout.png)

Danach kann man die Backend Datensätze nach der **ID sortieren**.

Was die **Filterung** anbetrifft, diese muss in **dcaconfig.php** eingestellt werden.

_system/config/dcaconfig.php:_ 
`$GLOBALS['TL_DCA']['ctlg_mytable']['fields']['id']['filter'] = true;`

Übrigens in der dcaconfig können alle Einstellungen überschrieben werden. Wenn du z.B eine bestimmte Konfigurationsmöglichkeit nicht über den Catalog Manager einstellbar ist
