### ISSUE TITLE
Taxonomies mit Ganzzahlen: Vergleich funktioniert nicht korrekt

### ISSUE THREAD

**Issue by plorenz-etes** [alnv/catalog-manager#387]
In meinem Projekt werden Ferienunterkünfte vermietet. Dafür gibt es eine Liste von Ferienunterkünften, die filterbar ist, u.a. nach Preis, indem man einen Maximalpreis angeben kann.

Der Preis ist wie folgt in der Datenbank angelegt:

```
| rental_price               | int(10) unsigned | YES  |     | NULL    |                |
```

In der Catalog Listenansicht habe ich bei den Taxonomies folgendes eingetragen:

```
Anzeige Mietpreis ab [rental_price]        Kleiner gleich        {{CTLG_ACTIVE::rental_price}}
```

Leider funktioniert diese Filterung aber nicht richtig. Wenn ich als URL-Parameter den `rental_price` auf z.B. `5000` setze, werden sämtliche Ferienhäuser ausgeblendet, welche z.B. 590 € kosten. Sobald ich den URL-Parameter auf `6000` setze, werden auch die Ferienhäuser mit 590 € angezeigt.

Das Problem scheint auch nicht im CTLG_ACTIVE-InsertTag zu liegen, denn ich kann hier auch hardcoded z.B. 5000 eingeben und das selbe Phänomen auslösen.

Gibt es eine Möglichkeit, den Preis korrekt zu vergleichen? Ist das ggf. ein Fehler?

**Comment by alnv** [comment]
Versuch es mal mit der v1.32.45 Version.

**Comment by plorenz-etes** [comment]
> Versuch es mal mit der v1.32.45 Version.

Super, damit hat es nun funktioniert - danke!
