### ISSUE TITLE
Lister/Reader Verhalten wie bei News o. Ä.

### ISSUE THREAD

**Issue by m-knorr** [alnv/catalog-manager#39]
Hallo,

besteht die Möglichkeit ein Lister/Reader Verhalten mit auto_item zu erzeugen wie bei den integrierten Lösungen? (News, Events, ...)

Problem ist folgendes:

Wenn ich ein Auflistungsmodul erstelle für einen Katalog der auf tl_content zugreift, habe ich das Problem, dass in der Detailansicht das Markup des Auflistungsmodul bestehen bleibt.

Die könnte ich umgehen, wenn ich auf eine separate Reader Seite umleite. Dies möchte ich aber aus Gründen der URL-Struktur ungern machen.

Beispiel:

- www.foo.com/barlist/fooitem/ - fooitem als Detailansicht behält Wrapper Markup von barlist
- www.foo.com/bardetail/fooitem/ - fooitem als Detailansicht wie gewollt, aber bardetail hängt dazwischen und sollte eigentlich barlist sein.

Ich hoffe, dass das Problem verständlich ist und ich nur noch nicht gefunden habe wie ich die Settings entsprechend anlege!

Danke und Gruß! Martin

**Comment by alnv** [comment]
Hi, ich verstehe dein Anliegen nicht ganz. Wenn keine Detailseite definiert ist, wechselt die Listenansicht automatisch zur Detailansicht.

**Comment by m-knorr** [comment]
Hallo,

danke für deine Antwort!

Ok, ich glaube ich habe einen Denkfehler in meinem Vorgehen. Denn das System kann ja gar nicht die zusätzlichen Elemente im Artikel wo die "Liste" drin liegt entfernen.

Ist es denn möglich über das Routing mit einer eigenen Detailseite zu arbeiten und dort aber das *detail* zu entfernen?

aktuell: **foo.com/projects/detail/project-title**

ziel: foo.com/projects/project-title

Danke!

**Comment by alnv** [comment]
Im Contao ist es üblich eine Detailseite anzulegen. Wenn die Liste zeitgleich eine Detailseite ist, kann man das Problem umgehen. Nachteil ist das bestehende Markup…
Mir fällt keine bessere Lösung ein.

Ich lasse den Task für Diskussionen offen.

**Comment by alnv** [comment]
Ab Contao 4.5 können Detailseiten festgelegt werden. Wenn kein Element (auto_item) gesetzt ist, gibt es automatisch eine 404 Fehlermeldung.
