### ISSUE TITLE
FR: Eigene Navigationsbereiche erstellen unter "Backend Modul einblenden"

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#40]
Hallo,

nach den ersten "Testläufen" mit dem Catalog Manager bin ich echt begeistert, was Du da auf die Beine gestellt hast. Wirklich TOP!!! Da die Anwendungsmöglichkeiten so riesig sind habe ich noch einen Vorschlag. Zu dem Thema habe ich hier keine Diskussioin und keinen FR gefunden.

Was ich zur besseren Übersicht vermisse, ist eine Möglichkeit, eigene Navigationspunkte im Backend zu erstellen, in die man dann die Catalog Manager Module einbinden kann.
Aktuell muss ich mich mit den vorhanenden Navigationspunkten im Backend zufrieden geben.
![navigationsbereiche erweitern](https://user-images.githubusercontent.com/2168409/28356350-05e2e43e-6c68-11e7-9f78-67efbed11a9a.jpg)

Würde mich freuen, wenn in der Richtung noch was möglich wäre und wir in Zukunft über den Catalog Manager auch eigene Hauptnavigationspunkte im Backend erstellen könnten :-)

Viele Grüße
André

**Comment by alnv** [comment]
Hi, danke für dein Feedback :) Dafür gibt es bereits eine Lösung. Du kannst einfach die _$GLOBALS['BE_MOD']_ Variable erweitern…

/system/config/**dcaconfig**.php
``` php
array_insert(  $GLOBALS['BE_MOD'], 0, [

        "myNewNavPoint" => []
]);
```
/system/config/**langconfig**.php:

`$GLOBALS['TL_LANG']['MOD']['myNewNavPoint'] = "Hier kommt die Übersetzung";`

**Comment by andre5tz** [comment]
Hi, danke für die Antwort. 
Ich werde mal testen, ob ich das hinbekomme. 
Per Mausklick im Backend wäre nunmal schöner/leichter.

**Comment by alnv** [comment]
Siehe #60

**Comment by mlwebworker** [comment]
In welche Datei muss das, wenn man für Contao 4 die "neue Variante" der Konfiguration nutzen möchte?

**Comment by ricowe** [comment]
Sehr geehrte Damen und Herren,
vielen Dank für Ihre Nachricht.

ich bin vom 19.07. bis 05.08.2019 im Urlaub.
Ihre Nachricht wird in dieser Zeit nicht gelesen oder bearbeitet.

Ab dem 05.08.2019 bin ich wieder für Sie da und werden Ihr Anliegen bearbeiten.

In dringenden Anliegen erreichen Sie meinen Kollegen Lars Drünkler 
telefonisch unter der Nummer: 0331/27976100

Mit freundlichen Grüßen
Enrico Wendt

**Comment by alnv** [comment]
Unter Contao 4 ist es genauso möglich. Die dcaconfig.php kann im selbem Ordner erstellt werden.

**Comment by mlwebworker** [comment]
Funktioniert wäre aber nicht der moderne Weg.
