### ISSUE TITLE
Sonderzeichen in <?= $this->masterUrl; ?> und title="<?= $this->title; ?>

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#41]
Hallo Alex,

beim Aufbau mit Detailseiten habe ich festgestellt, dass bei mir in der URL zur Detailseite die Sonderzeichen nicht sauber umgeschrieben werden.

In der erzeugten URL sind Leerzeichen " " und Umlaute enthalten. Dazu werden im title der URL Anführungszeichen nicht entfernt.

Folgender Code im Template (z. B. ctlg_view_table, ctlg_view_teaser)
`<a href="<?= $this->masterUrl; ?>" title="<?= $this->title; ?>">Details`

Bsp. mit "ü" und Anführungszeichen im title:
> <a href="xxx/xxx**ü**xxx/xxx-xxx.html" title="xxx **"xxx"**">
![url](https://user-images.githubusercontent.com/2168409/28543266-86fc00ea-70bf-11e7-87ef-47dcffe64fc0.PNG)

Bsp. mit Leerzeichen, hier wäre ein "_" sicher besser:
> `<a href="xxx/xxx xxx/xxx.html" title="xxx">`
![url2](https://user-images.githubusercontent.com/2168409/28543385-dc50f92e-70bf-11e7-986e-42b42e7b9ac2.PNG)

Muss ich eine Einstellung vornehmen, damit die Sonderzeichen escaped werden?

Für den Fall, dass nicht ich als Anwender das Problem bin, wäre es klasse, wenn Du hier schnell eine saubere Lösung findest.

Viele Grüße
André

**Comment by andre5tz** [comment]
Morgen,

teil eins konnte ich heute Morgen selbst lösen. 
Bei den Einstellungen hatte ich in der Wertspalte den Titel ausgewählt. Hier auf den Alias umgestellt führt zum gewünschten Ergebnis. Anscheinend wird für die URL die Wertspalte genutzt.
**So funktioniert es mit der masterUrl.**
![sonderzeichen_in_url](https://user-images.githubusercontent.com/2168409/28559508-190215e0-7117-11e7-8efa-920f5f525383.JPG)

Jetzt muss ich nur noch die Lösung für die Anführungszeichen im Titel finden.

Viele Grüße
André

**Comment by andre5tz** [comment]
Lösung für die Anführungszeichen habe ich für meinen Bedarf jetzt auch gefunden.

Den Titel-Tag im Template habe ich jetzt ein secialchars hinzugefügt. 
Siehe ([https://docs.contao.org/books/manual/3.4/de/04-inhalte-verwalten/inserttags.html])
title="<?= **specialchars**($this->title); ?>">

Ich denke, damit kann ich das Thema auch geschlossen werden.
Sorry, dass ich nicht erst vernünftig gesucht habe, aber vielleicht hilft es ja noch jemandem.
Evtl. kannst Du ja auch mal prüfen, ob es sinnvoll wäre, in den Standard-Templates eine passende Lösung einzubauen.

VG
André

**Comment by alnv** [comment]
Contao 4.4 unterstützt sämtliche Sonderzeichen und kann den 
Seitenalias entsprechend auflösen. Ich will da nichts einschränken. Deine Lösung ist Optimal. Danke 👍
