### ISSUE TITLE
Leerzeichen im array einfügen - nach einem Komma <?= implode( ', ', $this->{$strColumnName} ); ?>

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#42]
Hallo,

ich habe noch einen banalen Änderungsvorschlag.
Im **Template ctlg_view_table.html5** wird bei einem array mit "impolode( **','**" ein Komma zwischen die Einträge gesetzt. 
Dazu sollte nach dem Komma noch ein Leerzeichen eingefügt werden, sonst sieht es unschön aus. 
Oder gibt es sinnvolle Anwendungsbeispiele, bei denen die Einträge direkt ohne Leerzeichen hintereinander geschrieben werden?
```
<?php if ( is_array( $this->{$strColumnName} ) ): ?>
         <td><?= implode( ', ', $this->{$strColumnName} ); ?></td>
         <?php continue; ?>
      <?php endif; ?>
```
Keine Ahnung, ob das noch an weiteren Stellen auftaucht.

Viele Grüße
André

**Comment by alnv** [comment]
Kann man machen. Das packe ich in den v1.5 Branch.

**Comment by alnv** [comment]
Catalog Manager v1.5 ist nun verfügbar.
