### ISSUE TITLE
Obgligates title-Feld im BE filtern/sortieren/suchen

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#44]
Mache ich einen Denkfehler oder hat man keine Möglichkeit, zum title-Feld "Panel Layout-Einstellungen" festzulegen? Sollten die Filterung, Sortierung und Suche dann nicht standardmäßig aktiviert sein? 

Ich kann die Sortierung im CM zwar festlegen, dann aber in der Datensatzliste auch nicht ändern, und wenn man lange Listen hat, wären Suche und Filterung schon hilfreich.

**Comment by alnv** [comment]
Titel & Alias kann ich standardmässig in die Suche aufnehmen.
Sortierung in der BE-Datensatzliste kannst du nur beeinflußen, wenn du bei der Darstellung "Sortierung nach einem variablen Feld" ausgewählt hast.
![](https://catalog-manager.alexandernaumov.de/files/theme/media/github/BE-Darstellung.png)

**Comment by alnv** [comment]
Neu in v1.5 => Alias und Titel sind nun standardmässig in der Suche drin.

**Comment by alnv** [comment]
Hier gibt es noch ein Issue zur Sortierung => #52
