### ISSUE TITLE
Template für CE Catalog Filterformular anpassen

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#45]
Hallo,

ich habe mich nun daran gewagt, einen Filter über den Filtergenerator zu erstellen. Bei der Anpassung der Ausgabe mit css habe ich jetzt ein kleines Problem mit der Ausgabe der Checkboxen.

Aktuell kommt zuerst der Text und dann die Checkbox in **catalog-manager/templates/ctlg_form_field_checkbox.html5**:
````
<?php foreach( $this->options as $strKey => $strTitle ): ?>
      <div class="checkbox_container">
         <label for="id_form_<?= $this->name ?>_<?= $intIndex ?>"><?= $strTitle ?></label>
         <input type="checkbox" id="id_form_<?= $this->name ?>_<?= $intIndex ?>" name="<?= $this->name ?>[]" value="<?= $strKey ?>" <?= ( !empty( $this->value ) && in_array( $strKey, $this->value ) ? 'checked' : '' ) ?> <?= $this->onchange ?>>
      </div>
      <?php $intIndex++; ?>
<?php endforeach; ?>
````

**Wäre es nicht besser, wenn label mit input getauscht wird, damit zuerst die Checkbox kommt und dann der Text?**

```
<input type="checkbox" id="id_form_<?= $this->name ?>_<?= $intIndex ?>" name="<?= $this->name ?>[]" value="<?= $strKey ?>" <?= ( !empty( $this->value ) && in_array( $strKey, $this->value ) ? 'checked' : '' ) ?> <?= $this->onchange ?>>
         <label for="id_form_<?= $this->name ?>_<?= $intIndex ?>"><?= $strTitle ?></label>

```
Gleiches im Template **catalog-manager/templates/ctlg_form_field_radio.html5**.

Ich habe erst kurz versucht, das ganze mit float zu lösen, aber danach verrutscht die Textbox in er Höhe zum Text, sieht nicht schön aus. 

VG
André

**Comment by alnv** [comment]
Geht klar. Sollte ab v1.5 implementier sein.

**Comment by andre5tz** [comment]
In Contao 4.4 ist die Checkbox im Template form_checkbox.html5 übrigens so gelöst.
```
      <?php if ($option['type'] == 'option'): ?>
        <span><input type="checkbox" name="<?= $option['name'] ?>" id="opt_<?= $option['id'] ?>" class="checkbox" value="<?= $option['value'] ?>"<?= $option['checked'] ?><?= $option['attributes'] ?>> <label id="lbl_<?= $option['id'] ?>" for="opt_<?= $option['id'] ?>"><?= $option['label'] ?></label></span>
      <?php endif; ?>
```

**Comment by alnv** [comment]
Ist erledigt in v1.5

**Comment by alnv** [comment]
Das mit dem zusätzlichem span-Tag ist jedem selbst überlassen. Persönlich war ich nie Fan davon. Aber eventuell gibt es einen praktischen Grund dafür den ich nicht kenne ;)
