### ISSUE TITLE
Liste in Seite filtern

### ISSUE THREAD

**Issue by madi84** [alnv/catalog-manager#46]
Beim fmodule gab es die Möglichkeit in den Seiteneinstellung zu filten, dadurch sparte man sich für jede Seite ein eigenes Modul anzulegen. Habe ich für Kategorieseiten genutzt, gibt es so eine Funktion noch?

**Comment by alnv** [comment]
Mit dem Catalog Manager ist es nicht möglich, da die Filterung ganz anders funktioniert. Hier bräuchten wir eine andere Lösung…

**Comment by madi84** [comment]
Vielleicht könnte man standardmäßig den Seiten Alias auslesen, den man dann in der Liste via Variable bsp. {{CTLG_ACTIVE::pagealias}} filtern kann. Setzt lediglich vorraus, dass man eine Auswahlliste mit genau den gleichen Namen erstellt.

**Comment by alnv** [comment]
Dafür hast du ja schon ein InsertTag {{page::*}} Damit kannst du alles Mögliche auslesen.

{{CTLG_ACTIVE::*}} funktioniert nur bei GET/POST Parametern.

**Comment by madi84** [comment]
Stimmt, leider komme ich damit nur an den vollständigen Alias z.B. produkte/xyz , obwohl ich nur xyz brauche. Aber die Idee ist gut, vielleicht kann ich das irgendwie über einen eigenen Insert-Tag lösen indem ich den Alias aufsplitte.

**Comment by alnv** [comment]
Du könntest für deine Seite ein neues Eingabefeld erstellen, wo du diverse Werte (tags) hinterlegst. Mit dem {{page::*}} InsertTag kannst du auf die Tags zugreifen und dementsprechend deine Listenansicht filtern.

**Comment by alnv** [comment]
Mit dem Catalog Modifizierer kannst du jetzt die Seitenstruktur entsprechend erweitern und die Listenansicht über {{page::*}} Inserttag steuern.
