### ISSUE TITLE
Das title-Feld

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#47]
Hallöchen,

ich habe immer noch Probleme mit dem praktischen Einsatz des title-Feldes. 

Beispiel: In einem Formular sollen die Anwender unter "Titel" den Vereinsnamen eingeben, in einem anderen eine Disziplinarstrafe und in einem dritten Formular für geahndete Fouls den Nachnamen des Spielers. In letzterem Fall hätte ein Schiedsrichter etwa folgende Felder in dieser Reihenfolge auszufüllen:

Titel: ...
Liga: ...
Spielstätte: ...
Vorname des Spielers: ...
Verein des Spielers: ...
Gegnerischer Verein: ...

Da muss man einem x-beliebigen Schiri erstmal beibringen, dass der Nachname des geahndeten Spielers ins Feld Titel eingegeben werden muss, der dazugehörige Vorname irgendwo weiter unten.

Auch in den FE-Tabellen ist es suboptimal, wenn in einer Kopfzeile "Titel - Vorname" oder "Logo - Titel - Adresse" o.ä. steht. 
Versuche der Label-Korrektur in Formularen, FE-Tabellen und Backend-Optionen via langconfig und dcaconfig waren nicht sonderlich erfolgreich (siehe https://github.com/alnv/catalog-manager/issues/18#issuecomment-311026129). 
Natürlich gäbe es noch die Möglichkeit, dem Kunden zu erklären, dass er einen Nachnamen z.B. zweimal eingeben muss, einmal ins title-Feld und einmal ins Feld Nachname - auch eher wenig sinnvoll. 

Wenn pro Datentabelle ein title-Feld obligatorisch ist, gäbe es da nicht vielleicht eine Möglichkeit, selbst zu bestimmen, welches Textfeld als title-Feld herhalten soll? 

Was wäre,
a) wenn wir für jede Datentabelle selbst ein Pflicht-Textfeld mit Namen "title" anlegen müssten?
b) wenn ich alle meine Felder anlegen würde und dann noch mal in die Modulsteuerung ginge, wo meine zuvor angelegten Textfelder in einem Selectmenü erscheinen, in dem ich auswählen könnte, welches als title-Feld dienen soll - und wenn der Catalog Manager dann den Feldnamen in 'title' ändert und ein Pflichtfeld daraus macht?
Damit könnten wir andere Einstellungen wie Feldbezeichnung, Feldlänge usw. selbst definieren. Wäre etwas in dieser Art realisierbar?

b) Nehmen wir an, ich würde alle meine Felder anlegen und dann auswählen, welches Feld als title-Feld genutzt werden soll, und nehmen wir ferner an ... ginge dann noch mal in die Modulsteuerung rein, wo meine zuvor angelegten Textfelder in einem Selectmenü erscheinen, in dem ich auswählen könnte, welches als title-Feld dienen soll. Der Catalog Manager könnte den Feldnamen in 'title' umbenennen und ein Pflichtfeld daraus machen, aber andere Einstellungen wie Feldbezeichnung, Feldlänge usw. könnte ich selbst definieren. Wäre etwas in dieser Art realisierbar?

**Comment by alnv** [comment]
Ein paar Worte zum Titel-Eingabefeld:

Der Titel fungiert in erster Linie als Beschreibung des Datensatzes. Dieser soll möglichst einzigartig sein und am besten einer Konvention folgen. Spätestens wenn der Titel mehrfach in einer Tabelle vorkommt, wird es schwer die Datensätze voneinander zu unterscheiden. Bei einem Nachnamen o.ä ist es nur Frage der Zeit wann es passiert. 

Ein Titel könnte so aussehen: <_Spielstättekürzel_> <_Vereinskürzel_> <_Nachname_> 
**=>** _SFA - SF - Müller_

Damit wäre der Datensatz strukturiert und auffindbar. Es wäre sogar möglich mit solidem PHP Basiswissen, das ganze zu automatisieren. #todo :)

Aber das ganze nur als Empfehlung.

Eine Modifizierung des Titels ist auch möglich. Wir können auf den Data-Container Array zugreifen und die Optionen überschreiben bzw. ergänzen.

Als erstes überschreiben wir das label Attribute in der dcaconfig.php:
`$GLOBALS['TL_DCA']['ctlg_mytable']['fields']['title']['label'] = $GLOBALS['TL_LANG']['ctlg_mytable']['title'];`

Danach fügen wir unsere _neue Bezeichnung_ in die _langconfig.php_ ein:
```php
if ( $GLOBALS['TL_LANGUAGE'] == 'de' ) {

	$GLOBALS['TL_LANG']['ctlg_mytable']['title'] = [ 'Nachname', 'Bitte geben Sie einen Nachnamen ein.' ];	
}
```

und das war`s :)

Die Punkte A-C wären realisierbar. Mit der Realisierung könnte es aber noch dauern…

**Comment by Anke** [comment]
Guten Morgen!

> Der Titel fungiert in erster Linie als Beschreibung des Datensatzes. Dieser soll möglichst einzigartig sein und am besten einer Konvention folgen.
Ist das nicht eigentlich Aufgabe des Alias-Feldes? (Ich verstehe das ja auch lles einigermaßen, aber ich denke an die Leute mit ganz unterschiedlichem Bildungsstand und Verständnis, die die Daten eingeben sollen.)

**Comment by andre5tz** [comment]
Hallo,

da bin ich doch in die gleiche "Falle" getappt und habe den Titel mal so als Titel genutzt. 

Wäre es dann nicht besser, wenn der Titel umbenannt würde in z.B. "Eindeutige Bezeichnung".
Dazu noch Vorschlag b) von Anke berücksichtigen, so dass das Feld automatisch befüllt werden kann. 
Dann wäre der jetzige Titel die eindeutige "lesbare" Bezeichnung für den Datensatz und der alias wäre die "maschinenlesbare" Version.

Wichtig ist meiner Ansicht nach, dass die eindeutige Bezeichnung (aktuell Titel) automatisch befüllt wird, ohne dass der Benutzer dort was eintragen muss. Ich würde auch vorschlagen, dass zu automatisieren, so dass z.B. das erste erstellte Feld für die eindeutige Bezeichnung verwendet wird, was aber dann überschrieben bzw. ergänzt werden kann.

VG
André

**Comment by Anke** [comment]
> Der Titel fungiert in erster Linie als Beschreibung des Datensatzes. Dieser soll möglichst einzigartig sein und am besten einer Konvention folgen.

Jetzt muss ich da noch mal drauf zurückkommen. Sagen wir ich habe als Vereinsname "Turnerbund Hagnow 1899 e.v.". Diesen würde ich dann in der vollen Schreibweise ins Feld "club_name" schreiben und ins title-Feld lediglich eine eindeutige Kurzfassung wie "TB Hagenow". Die Templates und der Meta-Title werden aber aus dem title-Feld generiert, also meine eindeutige "Kurzfassung" ...? 

Der automatisch generierte, aber änderbare Alias würde lauten: "turnerbund-hagenow-1899-e-v". Kommt er zufällig mehrmals vor, wird (nach Core-Konventionen) automatisch eine Zahl hinten angehängt, und er dient meist als URL für Detailseiten. 

Als Webentwickler könnte ich mich durchaus damit anfreunden, wenn es heißen würde: Für jede Tabelle _kann_ ein Feld namens "meta_title" und ein Feld "meta_desc" angelegt werden. Wurden diese angelegt (if), können sie als Meta-Daten eingesetzt werden.

**Comment by alnv** [comment]
In der v1.5 werde ich die Bezeichnung ändern zu "Eindeutige Bezeichnung" o.ä statt Titel. Alias bleibt erstmal unberührt. Diesen brauche ich für SEO/ältere Browser und Contao 3.

> Wichtig ist meiner Ansicht nach, dass die eindeutige Bezeichnung (aktuell Titel) automatisch befüllt wird, ohne dass der Benutzer dort was eintragen muss.

Feature ist geplant.

Sonst, wie oben beschrieben alle Felder lassen sich per dcaconfig ändern, wenn es nicht anders geht. Alles andere wäre momentan zu hoher Zeitaufwand.

**Comment by Anke** [comment]
Ist okay. Es scheint momentan nicht mal zu stören, wenn das Titel-Feld leer bleibt. Mir ist aufgefallen, dass das Alias-Feld automatisch durchnummeriert ("_3") zu werden scheint. 
Im Core wird ja i.d.R. der Titel als Alias übernommen. Kannst du die Funktion vllt übernehmen, wenn man z.B. im Catalog-Modul (DB-Einstellungen) angeben würde, welches Feld als Titel/Alias dienen soll?

**Comment by alnv** [comment]
Neu in v1.5 Titel wurde unbenannt.

> Kannst du die Funktion vllt übernehmen, wenn man z.B. im Catalog-Modul (DB-Einstellungen) angeben würde, welches Feld als Titel/Alias dienen soll?

Werde ich prüfen und gegebenenfalls bis zum nächstem release umsetzen.

> Mir ist aufgefallen, dass das Alias-Feld automatisch durchnummeriert ("_3") zu werden scheint.

Wenn die eindeutige Bezeichnung fällt oder bereits existiert wird die **id** des **Datensatzes** für den Alias verwendet. Bei core Modulen ist es nicht anders.

**Comment by alnv** [comment]
Ich schließe den Task. Hier geht es weiter #55 #56
