### ISSUE TITLE
Frage: Format/HTML-Zeichenkette zur Formatierung der angezeigten Felder

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#48]
Vielleicht eine dumme Frage, aber kann leider in Demo und Doku nichts finden. Was kann man hier zB eintragen?

**Comment by alnv** [comment]
Du kannst z.B den _Titel_ mit einem _strong_ Tag umschließen: z.B `<strong>%s</strong>`

**Comment by Anke** [comment]
Danke.

Übrigens will ich an dieser Stelle mal sagen, dass der Catalog Manager einfach Klasse ist, der Support kaum zu toppen - und es macht richtig Spaß, damit zu arbeiten!!!

**Comment by alnv** [comment]
Danke. Das freut mich zu hören 👍

**Comment by kissinger999** [comment]
> Du kannst z.B den Titel mit einem strong Tag umschließen: z.B <strong>%s</strong>

Hallo!
Alex, kannst du bitte etwas näher erklären. 
Danke!
