### ISSUE TITLE
Sortierung über den Filtergenerator

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#49]
Hallo,

ich hatte bereits eine Frage zur Sortierung gestellt. [https://catalog-manager.alexandernaumov.de/feedback/frage-sortierung-uber-den-filtergenerator.html](url)

Leider kann ich das Ergebnis nicht verstehen.
Oben, Sortierung beim Catalog Filterformular, unten die Sortierung aus dem Modul Catalog Filterformular.
![sortierung filter vs bemodul](https://user-images.githubusercontent.com/2168409/28728671-cb31bd10-73c9-11e7-8c32-4811e6cf120f.PNG)

Sollte die Sortierung nicht bei beiden gleich sein? Richtig sortiert das Modul, falsch die Filter aus dem Filtergenerator.

Da ich im Feedback-Formular nicht antworten kann und ich das Ergebnis nicht nachvollziehen kann, hier nochmal meine Mitteilung.

Viele Grüße
André

**Comment by alnv** [comment]
Es kommt darauf an aus welcher Tabelle die Daten gezogen werden. Es kann gut sein, dass es zwei verschiedene Tabellen sind.

Bei dem Filtergenerator gibt es mehrere Möglichkeiten die Daten zu beziehen z.B
- Auswahlliste
- Datenbank
- Datenbank (zugewiesen)

während das FE Modul alle Daten aus der Referenzierten Tabelle zieht.

Wie beziehst du die Daten bei Filtergenerator?

**Comment by andre5tz** [comment]
Eingestellt ist Datenbank (zugewiesen). Ein Umstellen auf Datenbank ändert aber auch nichts an der Sortierung im Frontend. Wenn Du möchtest kann ich Dir gerne Backendzugang geben.

Grundsätzlich würde ich es klasse finden, wenn im Filtergenerator eine Sortierung eingestellt werden könnte.

**Comment by alnv** [comment]
Schicke mir mal ein BE-Zugang per E-Mail

**Comment by alnv** [comment]
Wie vermutet, es sind zwei verschiedene Tabellen.

Falls jemand ein ähnliches Problem hat:
_Es wird immer nach der ausgewählten Tabelle sortiert. Tabellen die nach einem variablen Feld sortiert werden, werden gänzlich von der Sortierung ausgenommen. Spalten die nicht atomar sind, das bedeutet mehr als ein Wert gespeichert haben (z.B eine Mehrfachauswahl) können auch nicht sortiert werden. Hier ist die Sortierung nur über das Template möglich (PHP-Sortierung)._

Eine manuelle Sortierung ist grundsätzlich möglich, eine Implementierung ist im Planung.
