### ISSUE TITLE
BE-Eingabemaske zeigt Feldname statt Bezeichnung

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#50]
Nicht sehr dreamatisch, aber seltsam: 

3 Textareas, 2 davon als Pflichtfelder, ansonsten alle Einstellungen gleich, aber bei 2 Feldern wird die Feldbezeichnung angezeigt, beim dritten der Feldname ("remarks" statt "Any further information").

![cm_textarea](https://user-images.githubusercontent.com/1300920/28757715-60a6a6a6-7589-11e7-92ee-58a222f9d522.jpg)

Das dritte Feld auch zum Pflichtfeld machen, ändert nichts.
Im FE stimmt die Anzeige.

**Comment by alnv** [comment]
Ist die Webseite Mehrsprachig?

**Comment by Anke** [comment]
Nein, einsprachig englisch.

**Comment by Anke** [comment]
Hat sich erldeigt - statt "remarks" steht da jetzt wie gewünscht "Further information" ...
