### ISSUE TITLE
Neuer ungespeicherter Datensatz wird im FE angezeigt

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#51]
Sobald man im BE auf "Datensatz anlegen" klickt, wird bereits ein leerer Datensatz im Frontend angezeigt. Das lässt sich hoffentlich bis zum Speichern unterbinden ...?

**Comment by alnv** [comment]
Eine Contao Spezialität :) Wird behoben in v1.5…

**Comment by alnv** [comment]
Ist behoben in v1.5

**Comment by ricowe** [comment]
Wenn ich einen Datensazu anlege (Backend-Formular mit abhängigen Selects) wird bei der Auswahl der abhängigen Selects der Datensatz gespeichert, obwohl er noch ncith fertig ausgefüllt ist. Mir ist klar, dass es durch "Submit on change" nicht anders möglich ist. 

Könnte man nicht zur Abhilfe die Checkbox "Datensatz verstecken" automatisch aktivieren, bis man den Datensatz fertig speichert?
