### ISSUE TITLE
Backend Sortierung nach Datum

### ISSUE THREAD

**Issue by alnv** [alnv/catalog-manager#52]
**Variante 1:**
Sortieren nach einem festen Wert.

![Contao Backend Sortierung mit Catalog Manager](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Sortierung-Fest.png)

**Variante 2:**
Sortieren nach einem variablen Wert.

_Schritt 1_: Die richtige Darstellung wählen.
![Contao Backend Sortierung mit Catalog Manager](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Sortierung-Variable.png)

_Schritt 2_: Die Sortierung im Eingabefeld festlegen
![Contao Backend Sortierung mit Catalog Manager](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Sortierung-Feld.png)

_Schritt 3_: Sortieren. Anders als bei einer festen Sortierung müssen wir zuerst auf "sortieren" klicken.
![Contao Backend Sortierung mit Catalog Manager](https://catalog-manager.alexandernaumov.de/files/theme/media/github/Sortierung-Panel.png)

**Comment by Anke** [comment]
Obwohl bei der variablen Sortierung als Sortierfeld (ausschließlich) "verfügbar" angeklickt und beim Feld auf/absteigend ausgewählt wurde, müssen wir in der BE-Ansicht noch mal auf Sortieren klicken?

**Comment by alnv** [comment]
So will es das Contao Framework :)
