### ISSUE TITLE
Tabellenname kann nicht nachträglich geändert werden.

### ISSUE THREAD

**Issue by liindex** [alnv/catalog-manager#53]
Hallo,

der Name einer Tabelle kann nicht nachträglich geändert werden.

Beispiel:
- Modul mit Tabellenname **testtabelle** erstellt. (im Backend anzeigen)
- Tabellenname auf **testtabelle_1** geändert.

1. In der Datenbank wird der neue Name übernommen. 
2. Bei Contao kommt folgende Fehlermeldung: _An exception occurred while executing 'SHOW FULL COLUMNS FROM testtabelle': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx_db1.testtabelle' doesn't exist_
3. Das Backend Modul versucht immer noch auf die alte Tabelle zuzugreifen: _Back end module "testtabelle" is not defined in the BE_MOD array_

MfG
Chris

PS: Catalog Manager in meiner Testphase...

**Comment by alnv** [comment]
Ist gefixt in v1.4.4

**Comment by alnv** [comment]
Ebenfalls behoben in v1.5

**Comment by liindex** [comment]
Vielen Dank.

Die Änderung des Tabellennamens funktioniert jetzt. Allerdings nur solange kein **tl_** vor den Tabellennamen gestellt wird.

Fehlermeldung beim Aufruf des erstellten Backend-Moduls:
> User Error: Could not create a data container object

**Comment by alnv** [comment]
Tabellen mit **tl_** Prefix sind nicht erlaubt! @todo an mich => Einen Validator implementieren.

**Comment by alnv** [comment]
Validator wurde implementiert.
