### ISSUE TITLE
Freie alias Auswahl.

### ISSUE THREAD

**Issue by alnv** [alnv/catalog-manager#55]
Der Backend User darf selber bestimmen, welches seiner Felder als Alias fungieren soll.

**Comment by alnv** [comment]
siehe #47

**Comment by Schmidty2** [comment]
Es wäre schön, wenn man den Alias optional auch aus mehreren Datenfeldern bilden und auf Wunsch auch einen Timestamp mit verwenden könnte. Beispiele:

FamiliennameVornameGebutsdatum = MustermannHans1501683093
Artikelbezeichnung-Datum der (ersten) Erstellung des Datensatzes = Kugelschreiber-1501683211

Dadurch erreicht man auf jeden Fall eine Eindeutigkeit.

**Comment by alnv** [comment]
-> wird auf Catalog Manager 2.0 verschoben. Jetzt nicht realisierbar.
