### ISSUE TITLE
Auto-Generierung für eindeutige Bezeichnung 

### ISSUE THREAD

**Issue by alnv** [alnv/catalog-manager#56]
siehe #47

**Comment by Anke** [comment]
Ist das hier jetzt noch im Todo-Modus? Jetzt haben wir also das Titel-Feld als "Eindeutige Bezeichnung", aber von Efitoren eingegebene Leerzeichen etc. werden nicht encodiert. Mich störts bis jetzt nicht, könnte aber vielleicht mal problematisch sein ...?

**Comment by alnv** [comment]
Ist implementiert in v1.17.beta1. Siehe Screenshot:

![](https://catalog-manager.alexandernaumov.de/files/theme/media/github/dyn-value-title.png)

Du kannst die Simple Tokens von Contao verwenden um auf die Feldwerte zuzugreifen z.B 
**##id## ##tstamp## ##my_fieldnam##**

**Comment by Anke** [comment]
Simple Tokens von Contao? Gelten die nicht nur für die Mails im Newsletter-Modul? 

Jedenfalls wird ##tstamp## nicht geparst. Es wäre aber schon praktisch, die Datensatz-ID und/oder den Timestamp in der dynamischen Vorbelegung der eindeutigen Bezeichnung verwenden zu können, da diese Felder standardmäßig vorhanden sind. Oder muss ich wirklich ein zweites, eigenes Timestamp-Feld erstellen, um einen Simple Token dafür zu generieren?

**Comment by alnv** [comment]
Welches Newsletter Modul meinst du?

**Comment by Anke** [comment]
Das im Core integrierte Newsletter-Modul.

**Comment by alnv** [comment]
Simple Tokens ist eine Contao Core Funktion, theoretisch überall einsetzbar. 

Generell wird nur der tatsächliche Wert aus der Datenbank ausgeben. Auch mit einem anderen Datum-Feld sollte das Ergebnis gleich sein. Es seiden man verwendet ein Textfeld…

**Comment by Anke** [comment]
Theoretisch mag das sein. Jedenfalls, wenn ich ##tstamp## angebe, wird kein Feldwert ausgegeben, sondern "##tstamp##".

**Comment by alnv** [comment]
Ich kann es nicht reproduzieren. Bei mir wird ##tstamp## gesetzt. Siehe > [Demo](https://demo.catalog-manager.org/contao) > Immobilien.

**Comment by keckmoritz** [comment]
bei mir geht es auch im Backend, aber nicht im Frontend-Editing (mit ##id##)

**Comment by alnv** [comment]
Die ID wird im FE nach dem speichern erzeugt, wie #170 beschrieben.
