### ISSUE TITLE
Timestamp im Frontend Editing

### ISSUE THREAD

**Issue by mgsoftThomas** [alnv/catalog-manager#57]
Ich weiß nicht ob es Bug ist oder ob ich nur noch nicht die richtige Konfiguration gefunden habe. Ich habe im Modul ein verstecktes Feld [int(10) unsigned NOT NULL default '0'] angelegt, Häkchen bei Zeitstempel, um das Änderungsdatum der letzten Bearbeitung zu erfassen und im Frontend auszugeben. Es werden beim Frontend Editing jedoch keine Werte in dieses Feld geschrieben. Auch ein Versuch mit einem Datumsfeld (gleiche Einstellungen) bleibt ohne Werte. Man kann zwar ein Datum im Frontend eingeben, Änderungen werden jedoch nicht übernommen. Im Backend funktioniert das Ganze. Das gleiche passiert mit dem standardmäßig angelegten tstamp Feld. Das Datum wird nur aktualisiert, wenn ich den Datensatz im Backend speichere. Gibt es dazu einen Lösungsansatz? Diese Funktion ist zwingend im Projekt vorgesehen, um in einer recht großen Liste den Überblick über den letzten Bearbeitungsstand zu behalten bzw. auch danach zu sortieren.

**Comment by alnv** [comment]
Das Problem mit dem Timestamp wurde in der v1.5.2 behoben. Timestamp wird nun korrekt im BE und FE gesetzt.

> Ich habe im Modul ein verstecktes Feld [int(10) unsigned NOT NULL default '0'] angelegt, Häkchen bei Zeitstempel, um das Änderungsdatum der letzten Bearbeitung zu erfassen und im Frontend auszugeben.

Der Zeitstempel wird hierbei als Standardwert gesetzt, wenn nichts anderes definiert ist. Also eine "letzte Änderung" Funktion ist hier nicht möglich.

Da bei dem Datentyp [ `int(10) unsigned NOT NULL default '0'` ] bereits ein Standardwert festgelegt ist, funktioniert hier das Timestamp nicht.

> Diese Funktion ist zwingend im Projekt vorgesehen, um in einer recht großen Liste den Überblick über den letzten Bearbeitungsstand zu behalten bzw. auch danach zu sortieren.

Ich denke, wenn der Standard Timestamp richtig funktioniert wird kein weiteres Eingabefeld mehr benötigt, oder?

**Comment by mgsoftThomas** [comment]
Habe das Update gerade eingespielt und der Standard Timestamp wird jetzt auch im Frontend Editing gespeichert. Somit ist kein separates (verstecktes) Feld dafür mehr nötig.
Super! Danke!

**Comment by mgsoftThomas** [comment]
Nach dem Update funktioniert nun aber leider das eingerichtete Filtermodul nicht mehr.

**Comment by alnv** [comment]
Bitte dafür ein neues Ticket erstellen mit möglichst genauen Beschreibung des Problems.
