### ISSUE TITLE
Filtermodul funktioniert nicht mehr

### ISSUE THREAD

**Issue by mgsoftThomas** [alnv/catalog-manager#59]
Nach dem Einspielen des heutigen Updates (1.5.0 Build 7) funktioniert das Frontend Filtermodul nicht mehr. Ich habe einen vorher funktionierenden Filter (form_radio), der eine Liste nach verschiedenen Statis eingrenzen sollte.
Selbst ein komplettes Löschen und Neuanlegen des Statusfeldes und der zugehörigen Werte in den Datensätzen brachte keine Erfolg.
Im Backend funktioniert die Filterung in der Listenansicht.

**Comment by alnv** [comment]
Ich kann den Fehler nicht reproduzieren. Bei mir laufen alle Filter einwandfrei. Auch auf der Demoseite funktionieren die Filter. Egal ob Filtergenerator oder FE-Filterformular. 

Eventuell stimmt etwas nicht mit der Konfiguration? Auf der Demoseite gibt es einen Beispiel Filter siehe [Immobilien Modul](http://catalog-manager-demo.alexandernaumov.de/immobilien.html).  

Welche Contao und PHP Version läuft auf deinem Server?

**Comment by alnv** [comment]
Eine Sache noch. 
Die Filterformulare erzeugen nur die GET/POST Parameter. Die eigentliche Filterung geschieht in der Listenansicht. Wenn es um Fehlersuche geht immer erst die Listenansicht überprüfen.
Dabei spielen die **{ { CTLG_ACTIVE::* } }** InsertTags die wesentliche Rolle. Diese lesen die GET/POST parameter aus. Weiter sind die Einstellungen im **Taxonomies/Filter** ganz wichtig.

**Comment by mgsoftThomas** [comment]
Habe das Ganze noch einmal in einer lokalen Version mit Composer getestet (Version 1.5.2), dort funktioniert der Filter. In zweiten Version per ER installiert (1.5.0) funktioniert nicht. Kann es sein, dass es an der Aktivierung der Option "Master verwenden" in der Seiteneinstellung der Listenseite zusammenhängt? Das ist für mich der einzige Unterschied zur lokalen Installation, da ich die Einstellung für die Ausgabe von Feldwerten auf der Bearbeiten-Seite, was auch funktioniert.

**Comment by alnv** [comment]
Schau mal ob bei dir die Einstellung "Filter verstecken" aktiviert ist.
![Filter verstecken](https://catalog-manager.alexandernaumov.de/files/theme/media/github/hidden-form.png)

Wird bei dir das Filtermodul angezeigt?

**Comment by mgsoftThomas** [comment]
Die Option "Filter verstecken" ist bei mir aktiviert. Der Filter selbst wird auf der Listenseite angezeigt, in der Bearbeiten Ansicht ist er dann weg. So habe ich diese Einstellung auch verstanden. Ein entfernen des Häkchens bringt auch keine Änderung, nur das der Filter auf der Bearbeiten-Seite angezeigt wird.
Ich habe alternativ versucht den Filter über den Filtergenerator umzusetzen, so wie im Immobilien-Besispiel. Dort bekomme ich aber im Bezugsfeld keine Auswahlmöglichkeit, obwohl ich die Datenbank und auch das entsprechende Feld für den Filterwert darunter eingestellt habe.

**Comment by mgsoftThomas** [comment]
Bei Bedarf könnte ich auch einen Zugang auf die Testumgebung einrichten, wenn das weiterhilft?

**Comment by alnv** [comment]
Der Bezugsfeld ist nur für das ein/ausblenden verantwortlich, wenn im "Bezugsfeld" ein Wert eingetragen/ausgewählt worden ist. Wenn du z.B nur ein Feld im Formular hast, werden auch keine Auswahlmöglichkeiten angezeigt.

Wie gesagt, ich kann den Fehler nicht reproduzieren. Ich vermute, dass die Konfiguration nicht ganz stimmt. Ohne zugriff auf's Backend kann ich dir nicht weiter helfen.

Wenn Filterformular angezeigt wird und dieser GET Parameter in die URL übergibt bzw. POST Parameter in den Header-Body, so funktioniert alles wie erwartet. Ob es der Fall ist kannst du überprüfen, wenn du den { { CTLG_ACTIVE::meinFeldname } } auf der Seite ausgibst.

Wenn die Liste nicht gefiltert wird, liegt es an der Listenansicht.

**Comment by alnv** [comment]
Zugang kannst du mir per E-Mail schicken.

**Comment by mgsoftThomas** [comment]
Mail ist unterwegs.

**Comment by alnv** [comment]
Die Filtereinstellung in der Listenansicht war falsch. Die Abfragen waren auf "ODER" gestellt. Unter v1.4 war das icon irreführend, wahrscheinlich hast du gedacht es wäre für das duplizieren da :)

Mittlerweile ist das icon eindeutig.
![Catalog Manager OR-Abfrage](https://catalog-manager.alexandernaumov.de/files/theme/media/github/OR-Icon.png)

**Comment by mgsoftThomas** [comment]
Der Teufel steckt im Detail ;-).
Das ist korrekt. Ich hatte den zweiten Filterwert durch "duplizieren" des ersten erzeugt. In der vorherigen Version stand da tatsächlich noch kein "OR". Das ist mir aber erst jetzt aufgefallen und geht auch so nicht eindeutig aus den Hilfetexten hervor. Ich habe angenommen, dass alle angelegten Filterfelder mit OR verknüpft sind, da das ja jeweils dahinter steht. Aber wenn man es weiß, leuchtet es ein.
