### ISSUE TITLE
FR: Mehrere Felder bearbeiten

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#6]
In der Feldliste im BE wäre die Option "Mehrere bearbeiten" sehr wünschenswert, gerade wenn man größere Tabellen hat. Ist das irgendwann machbar?

**Comment by alnv** [comment]
Dieses Feature wäre etwas aufwendig zeitnah zu realisieren. Daher prüfe ich es erstmal auf machbarkeit. Ich melde mich diesbezüglich noch…

**Comment by codiso** [comment]
👍

**Comment by alnv** [comment]
Dieses Feature packe ich in den v1.4 Branch.

**Comment by alnv** [comment]
Ist erledigt in v1.4.1.
