### ISSUE TITLE
Eigener Bereich in der Backend-Navigation

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#60]
Bei der Zuordnung der Tabellen in der Backend-Navigation kann bei der Checkbox "Backendmodul einblenden ==> Navigationsbereich" ein vorhandener Backend-Bereich ausgewählt werden.

Kann hier die Funktion hinzugefügt werden, optional einen neuen, eigenen Backendbereich zu erstellen und in diesem Bereich die Zuordnung vorzunehmen.

**Comment by alnv** [comment]
Siehe #40 

Eine eigene Eingabemaske ist in Planung.

**Comment by alnv** [comment]
Ist erledigt. Siehe unter System > Einstellungen > Catalog Manager-Einstellungen > Navigationsbereiche

**Comment by Anke** [comment]
Das ist ja klasse!

Allerdings habe ich 11 Module. Meine Anordnung war okay, solange ich 10 Module unter meinem Navigationsbereich angelegt habe. Als das 11. dazu kam (mit Sortierungsnummer 10) , wurde das an die 5. Position gerückt. Und dort bleibt es auch, wenn ich eine höhere Sortierungsnummer wähle.
 
Außerdem habe ich das Modul umbenannt, aber der neue Name wird ignoriert, und wenn ich das Modul aufrufe, um den Namen noch einmal zu ändern, steht da im Feld Modulname der aus dem Feld Name wohl automatisch übernommene Name, aber in Kleinschreibung und mit Bindestrichen - wie ein Alias -, aber eben nicht ein von mir fürs Backend-Menü eingegebener Name.

Kann das Problem jemand reproduzieren, oder ist in meiner DB was durcheinander geraten? Systemwartung hat daran nichts geändert.
