### ISSUE TITLE
Keine Weiterleitung auf Fallback mit changelanguage

### ISSUE THREAD

**Issue by madi84** [alnv/catalog-manager#61]
Bin nach der Anleitung auf https://catalog-manager.alexandernaumov.de/dokumentation/catalog-manager-mehrsprachigkeit.html vorgegangen. Hat sich an der Vorgehensweise etwas geändert? Klickt man auf der Detailseite den Sprachwechsler wird nicht korrekt weitergeleitet. Anscheinend geht der Alias verloren. z.B.: de/produkt/xyz.html -> en/product.html

**Comment by alnv** [comment]
Die Vorgehensweise ist die selbe geblieben. Wahrscheinlich ist der Fallback Datensatz nicht gesetzt. Auf der Demoseite läuft alles, daher vermute ich falsche Konfiguration.

**Comment by madi84** [comment]
Danke, hab meinen Fehler gefunden: Der Eintrag in der Hauptsprache muss als Fallback auch auf sich selbst verweisen. Dachte das wird wie im Fall der Seitenstuktur bei Contao automatisch verknüpft.
