### ISSUE TITLE
Timestamp auf Catalog Detailseite nicht verfügbar

### ISSUE THREAD

**Issue by mgsoftThomas** [alnv/catalog-manager#62]
Obwohl ich das tstamp Feld für die Anzeige auf der Catalog Detailseite angehakt habe, wird mir dieses dort nicht angezeigt.
Eine manuelle Einbindung über den Tag {{CTLG_MASTER::tstamp}} bringt mir nur den int-Wert (z.B. 1501752158) aus der Datenbank.
Auch ein hinzufügen in der Contao dca-config.php ($GLOBALS['TL_DCA']['ctlg_objekte']['fields']['tstamp']['eval']['rgxp'] = 'datim';) brachte nicht den gewünschten Erfolg.

**Comment by alnv** [comment]
Der `{{CTLG_MASTER::*}}` InsertTag liefert den tatsächlichen Wert aus der Datenbank aus. Daher ist es korrekt.

`$GLOBALS['TL_DCA']['ctlg_objekte']['fields']['tstamp']['eval']['rgxp'] = 'datim';`

Hier wird eine Validierung bei einer Benutzereingabe durchgeführt , da der Timestamp automatisch gesetzt wird, bringt es wenig. #17 

Du kannst den Timestamp im `ctlg_view_master` ausgeben:
`<?= $this->tstamp; ?>`

> Obwohl ich das tstamp Feld für die Anzeige auf der Catalog Detailseite angehakt habe, wird mir dieses dort nicht angezeigt

Welche Einstellung meinst du damit?

**Comment by mgsoftThomas** [comment]
Ich nutze für die Detailansicht nicht das Catalog Detail Modul sondern einen normalen Contao Artikel (Text) in dem ich alle Catalog Felder per Inserttags ausgebe (als Druckansicht für den Benutzer), da ich die Zusatztexte (Labels, Hinweise, Formatierungen usw.) damit gleich mit ausgeben kann ohne ein eigenes Template dafür zu schreiben. Funktioniert auch alles prima, bis auf den Timestamp. Daher wird mir auch der Einbau in das ctlg_view_master Template nichts bringen.

Das Häkchen was ich meine ist im Catalog Manager selbst. Dort kann ich ja die Anzeige-Felder auswählen, die sowohl in der Backend-Ansicht (Liste) als auch in der FE Detailansicht erscheinen. Zumindest konnte ich darüber die Felder steuern. Da mir die Ausgabe aber die Daten nur unformatiert lieferte (hier fehlt der Timestamp ganz), habe ich die oben beschriebene Vorgehensweise gewählt.

**Comment by alnv** [comment]
> Das Häkchen was ich meine ist im Catalog Manager selbst. Dort kann ich ja die Anzeige-Felder auswählen, die sowohl in der Backend-Ansicht (Liste) als auch in der FE Detailansicht erscheinen. 

Das hat keine Auswirkung auf die Detailansicht.

> Da mir die Ausgabe aber die Daten nur unformatiert lieferte (hier fehlt der Timestamp ganz), habe ich die oben beschriebene Vorgehensweise gewählt.

id, pid, sorting, tstamp und einige andere System Felder werde nicht ausgegeben. Aber man hat trotzdem Zugriff darauf z.B im ctlg_view_master oder ctlg_view_teaser Templates.
`<?= $this->tstamp; ?>`
`<?= $this->id; ?>`

Du hast sogar Zugriff auf die Feld Eigenschaften:
`$this->catalogFields['tstamp']` => `$this->catalogFields['tstamp']['title']`

Theoretisch brauchst du kein Conato Artikel, sondern du kannst alles im Template anzeigen. 

Alternativ geht das auch noch, wäre aber ein "eigenes" Template:

``` php
<?php $intTimestamp = \Controller::replaceInsertTags("{{CTLG_MASTER::tstamp}}");?>
<?php $objDate = new \Date( $intTimestamp ); ?>
<?= $objDate->datim; ?>
```

**Comment by mgsoftThomas** [comment]
Ich habe mir jetzt erstmal beholfen, indem ich den Quellcode aus dem Contao Artikel (mit den Inserttags) in ein eigenes ctlg_view_master Template kopiert habe und dort den Timestamp hinzugefügt. 
Funktioniert auch. Man muss nur dran denken, dass evtl. neue Felder dort auch händisch eingepflegt werden müssen. Da ich aber schnell ein Ergebnis brauche, ist das als Notbehelf ausreichend.
Trotzdem Danke!
