### ISSUE TITLE
Titel für Redakteure verschwunden

### ISSUE THREAD

**Issue by madi84** [alnv/catalog-manager#63]
Kann man das Feld "Eindeutige Bezeichnung", ehemalig Titel, für Redakteuere wieder sichtbar machen? Bzw. in die Gruppeneinstellung als Option mit aufnehmen.

**Comment by alnv** [comment]
Vielen Dank für den Hinweis. Die gesamten Rechten funktionieren nicht.

Ist behoben in v1.5.5
