### ISSUE TITLE
Palette: Konfiguration ob Palette hidden

### ISSUE THREAD

**Issue by tarun-uwe** [alnv/catalog-manager#64]
Hallo alvn,

es wäre toll, wenn es die Möglichkeit  bei den Paletten gäbe einzustellen,
ob diese "hidden" (zusammengeklappt) oder nicht zu sehen sind per default.

![image](https://user-images.githubusercontent.com/30664429/28932486-f023e1ac-7879-11e7-9672-6101a1aef45d.png)

viele Grüße
Uwe

**Comment by alnv** [comment]
Ist implementiert und kommt mit dem nächsten release.

**Comment by alnv** [comment]
Ist implementiert. Im Feldtyp **Palette öffnen** gibt es eine neue Checkbox **Palette einklappen**.
