### ISSUE TITLE
Palette: Schließen der Palette nicht möglich

### ISSUE THREAD

**Issue by tarun-uwe** [alnv/catalog-manager#65]
Hallo alnv,

es ist nicht möglich bestimmte Paletten zu schließen, da auf ein leeres Pflichtfeld hingewiesen wird.
Dies ist jedoch nicht bei allen Pflichtfeldern der Fall. Als Beispiel ist ein Video angefügt.

[Palette.mov.zip](https://github.com/alnv/catalog-manager/files/1197939/Palette.mov.zip)

viele Grüße
Uwe

**Comment by alnv** [comment]
Leere Eingabefelder mit einem [ required ] - Attribute verhindern das schließen der Palette. Das ist ein Bestandteil des Contao Cores. Siehe `AjaxRequest.toggleFieldset` Funktion. 

Daher ist es kein Bug.

Manchmal kommt es vor, dass die Palette trotzdem geschloßen wird wenn ein Eingabefeld ein Pflichtfeld ist aber über kein [ required ] Attribute verfügt. Das ist etwas inkonsequent von Contao gelöst. Aber das hängt nicht mit dem Catalog Manager Modul zusammen.
