### ISSUE TITLE
Galerie: Keine Übernahme der Bilder bei Nutzung "Zielverzeichnis"

### ISSUE THREAD

**Issue by tarun-uwe** [alnv/catalog-manager#66]
Hi alvn, 

seit der neuesten Version funktioniert die Übernahme von Bildern in die Galerie nicht mehr,
wenn die Funktion "Zielverzeichnis" zur Angabe des Pfades zur Bildauswahl genutzt wird.

viele Grüße
Uwe Tarun

Edited: GIF entfernt

**Comment by alnv** [comment]
Ich habe es mal ausprobiert und bin zum folgenden Ergebnis gekommen, wenn man den Schrägstrich ("/") vor dem "files" entfernt funktioniert alles wie es soll. 

Kannst du es bei dir ohne den Schrägstrich testen?

**Comment by alnv** [comment]
Ich werde eine zusätzliche Validierung implementieren.

**Comment by tarun-uwe** [comment]
Vielen Dank.
