### ISSUE TITLE
Anzeige von Anlagen im Backend

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#67]
Hallo Alex,

in einer Backendtabelle möchte ich in der Übersicht gerne sehen, ob Anlagen vorhanden sind. Das sieht bei mir so aus:
![anlagen1](https://user-images.githubusercontent.com/2168409/29185472-9dd90c66-7e09-11e7-9a28-d6c829a7822c.JPG)
![anlagen2](https://user-images.githubusercontent.com/2168409/29185492-a4a301dc-7e09-11e7-9296-cc09a60d117c.JPG)
Erwartet hätte ich jetzt ein Datei-Icon oder den Dateinamen :-) 
Habe ich was in den Einstellungen übersehen oder kannst Du da bitte nochmal nachschauen?

Viele Grüße und danke
André

**Comment by alnv** [comment]
Wie hast du die Anlagen im Backend ausgegeben? Mit welcher Einstellung?

**Comment by andre5tz** [comment]
"Als mehrspaltige Tabelle anzeigen" ist eingestellt, oder brauchst Du alle Einstellungen?

**Comment by alnv** [comment]
Mehrspaltige Tabelle kann man nicht steuern zumindest habe ich keine Möglichkeit entdeckt. 
Eine bessere alternative ist es das Label-Format von der normalen Darstellung zu überschreiben. Siehe Vereinsmodul.
![Contao Format überschreiben](https://catalog-manager.alexandernaumov.de/files/theme/media/github/BE-Format.png )

**Comment by andre5tz** [comment]
Danke für die Info, schade das die Anlagen nicht "sauber" in der Tabelle dargestellt werden können. 
Das mit dem überschreiben ist ja nicht das gleiche wie die Darstellung als Tabelle, oder ich habe es bei meinen Tests nicht richtig gelöst ... aber egal, mit der Info kann ich das entsprechend sinnvoll für mich umsetzen. 

Eine Frage noch dazu, gibt es für die Bearbeitungs-Icons 
![bearbeitungs-icons](https://user-images.githubusercontent.com/2168409/29305769-b04105f4-819a-11e7-868c-f75a0d64fe86.JPG)
 eigentlich auch einen Token?

Danke nochmal und viele Grüße
André

**Comment by alnv** [comment]
Was meinst du mit Token? Fallbeispiel?

**Comment by andre5tz** [comment]
##vereinslogo## ##title## ##Bearbeitungs-Icons##

**Comment by alnv** [comment]
Das ist nicht möglich. Die Bearbeitungs-Icons werden vom Contao core verwaltet und ausgegeben. Diese bleiben immer an der selben Stelle.

**Comment by andre5tz** [comment]
OK. Ich hatte am Wochennde mal Versucht, das ganze mit einer Tabelle nachzubauen, hat aber in dem Moment nicht so richtig geklappt, weil ich die Bearbeitungs-Icons da ja nicht mit rein bekomme ;-)
Danke nochmal, jetzt ist mir klar, wie ich damit umgehen kann.
