### ISSUE TITLE
Bei Feld Select-Menü den DB Eintrag nutzen.

### ISSUE THREAD

**Issue by tarun-uwe** [alnv/catalog-manager#68]
Hi Alex,

bei einem Select Feld gibt "<?= $this->feldname ?>" den in Contao hinterlegten Wert für die Anzeige im Backend zurück. 

Diesen kann man in der langconfig.php zwar für die verschiedenen Sprachen übersetzen, jedoch soll der DB Eintrag des Feldes auch als CSS class vergeben werden. Dies soll sprachunabhängig passieren.

Anbei ein Beispiel wie der aktuelle Stand ist.

viele Grüße
Uwe
P.S.: wäre vielleicht auch bei Checkboxen und Radios sinnvoll.

![image](https://user-images.githubusercontent.com/30664429/29213762-eec5a440-7ea4-11e7-89eb-96bc81c9d38c.png)

![image](https://user-images.githubusercontent.com/30664429/29213746-e21268dc-7ea4-11e7-844a-1835c68935c4.png)

**Comment by alnv** [comment]
Alles klar. Kommt auf die todo…

Bis dahin kannst du für das "Status" Select-Menü die "Mehrfachauswahl" aktivieren.  
Damit könntest du auf den DB-Wert zugreifen: `<?= array_keys( $this->status )[0] ?>`

**Comment by alnv** [comment]
Ist implementiert und kommt mit dem nächsten release.

**Comment by alnv** [comment]
Es gibt ein neues Attribute `origin`. Damit hast du Zugriff auf die hinterlegten Datenbank Werte.

z.B Öffne **ctlg_view_teaser** oder **ctlg_view_master** Template und gebe `<?= $this->origin['status']; ?>` aus.

**Comment by tarun-uwe** [comment]
Funktioniert super gut.

**Comment by Anke** [comment]
> z.B Öffne ctlg_view_teaser oder ctlg_view_master Template und gebe `<?= $this->origin['status']; ?>` aus.

Super! (Nach dieser Info habe ich allerdings lange suchen müssen.) Das löst meine FE-Ausgabe des Strings "Array" bei einem Checkbox-Feld, mit der ich nicht weiter wusste. 

Jetzt wäre es noch schön, wenn die Ausgabewerte (bei Mehrfachauswahl) durch Komma **+ Leerzeichen** getrennt würden.

**Comment by alnv** [comment]
$this->origin['status'] liefert den tatsächlichen Datenbankwert und dieser enthält keine Leerzeichen auch kann ich keine einfügen.

Das wäre demnach nur mir einem PHP Script möglich.

``` php
<?php $arrValues = explode( ',', $this->origin['key'] ); ?>
<?= implode( ',  ', $arrValues ); ?>
```
