### ISSUE TITLE
Verschieben von Datensätzen im Backend 

### ISSUE THREAD

**Issue by tarun-uwe** [alnv/catalog-manager#69]
Hi Alex,

ist es möglich auf der obersten Ebene eine Sortierung (Verschieben)
der Objekte zu haben?

Ziel ist es, dass die Datensätze in der Reihenfolge angezeigt werden, in welcher sie von einem
Mitarbeiter im Backend angelegt/angeordnet wurden.

Aktuell ist trotz Aktivieren der Operatoren kein Verschieben möglich.

![image](https://user-images.githubusercontent.com/30664429/29606755-892f4b50-87ef-11e7-9ce2-f4ecd970940c.png)
![image](https://user-images.githubusercontent.com/30664429/29606771-90c2feca-87ef-11e7-8ebe-350128290e2e.png)

**Comment by alnv** [comment]
Soweit ich jetzt testen konnte, gibt es keine Möglichkeit die oberste Tabelle individuell zu sortieren. Wenn es Contao nicht unterstützt, kann ich mit dem Catalog Manager wenig machen. 

Es seiden ich implementiere eine eigene Lösung. Aber das würde seine Zeit brauchen. Ob dieses Feature die Zeit Wert ist, muss ich noch prüfen…

**Comment by tarun-uwe** [comment]
Danke für die schnelle Rückmeldung. Wäre es vielleicht möglich das Feld "sorting" im Backend in einem einzelnen Datensatz Anzuzeigen und zu Ändern?

**Comment by alnv** [comment]
Ja, das würde gehen. Allerdings ist der Feldname "sorting" reserviert und in der obersten Ebene nicht relevant. Daher empfehle ich eine andere Bezeichnung.
