### ISSUE TITLE
Darstellungseinstellungen: Sortier- und Anzeigefelder

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#70]
Zu jeder Tabelle kann man im BE die Sortier- und die Anzeigefelder auswählen. Meines Erachtens sollte ein ausgewähltes (festes) Sortierfeld nicht automatisch in der Liste/Tabelle angezeigt werden. Wenn man das möchte, kann man es unter "Anzeige-Felder" auswählen.

**Comment by alnv** [comment]
Die Eingabemaske in der v1.6 wird etwas verbessert, sodass nur die Felder angezeigt werden, die auch für die Darstellung/Sortierung relevant sind.

**Comment by alnv** [comment]
Die Eingabemaske für Sortierung und Anzeige wurde in v1.6 verbessert.
