### ISSUE TITLE
Nur Filterergebnis anzeigen

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#71]
Hallo,
wenn man die Datensatz-Liste und einen dazugehörigen Filter auf einer Seite eingebunden hat, werden beim Aufruf der Seite zuerst immer alle Datensätze angezeigt, bis der Filter angewendet wird.

Kann eine Option hinzugefügt werden, so dass beim Aufruf der Seite keine Datensätze angezeigt werden (dafür aber ein Hinwies wie z.B.: Bitte Suchberiff eingeben oder Kein Suchergebnis) und erst nach Eingabe eines Suchbegriffs die gefilterten (auf den Suchbegriff passenden) Datensätze angezeigt werden.

**Comment by alnv** [comment]
Du kannst im Template (mod_catalog_universal) Abfragen ob ein Filterwert gesetzt ist.

Wenn kein Wert gesetzt ist, soll der output überschrieben werden z.B

``` php
<?php if( !\Input::get('myFilterValue') ): ?>
   <?php $this->output = 'Bitte geben Sie ein Suchbegriff ein.' ?>
<?php endif; ?>
```

Hilft es dir weiter?
