### ISSUE TITLE
Berechtigungsart festlegen - Auswirkung auf die Datenbank und das Installtool

### ISSUE THREAD

**Issue by andre5tz** [alnv/catalog-manager#72]
Hallo Alex,

ich hatte die Tage so meine Probleme mit meiner Contao 4.4 Installation. Nach einem Update über den Contao Manager wurde im Contao Installtool vorgeschlagen einige Spalten zu löschen.

- ALTER TABLE tl_member_group DROP ctlg_meinespaltep
- ALTER TABLE tl_member_group DROP ctlg_meinespalte
- ALTER TABLE tl_user DROP ctlg_meinespaltep
- ALTER TABLE tl_user_group DROP ctlg_meinespaltep
Dabei endete der Spaltenname 3x mit "p"?

Nach dem Löschen der Spalten im Installtool konnte ich mich dann mit meinem Account nicht mehr ins Backend einloggen.

Ich denke mal, dass hier ein Problem mit dem Installtool besteht, dass die Spalten nicht kennt und zum Löschen vorschlägt.

Nach etwas längerem Suchen habe ich dann festgestellt, dass ich in einem Catalog Modul unter **Berechtigungsart festlegen** auf **Standard** gestellt hatte. Nachdem ich das jetzt rausgenommen habe, klappt es wieder.

Mir ist zwar noch nicht klar, was die Berechtigungsarten machen und ich bin mir auch nicht sicher, ob ich hierbei das Problem bin, aber ich habe so das Gefühl, dass Du Dir das mal anschauen solltest.

Viele Grüße
André

**Comment by alnv** [comment]
Ich denke, es ist ein Cache Problem. Ist bei dir der "interne Cache" aktiviert?

**Comment by andre5tz** [comment]
Gute Frage, ob der "interne Cache" aktiviert ist. In Contao 4.4 finde ich unter System -> Einstellungen -> Globale Einstellung bzw. insgesamt keine Auswahl für einen "internen Cache". In der Seitenstruktur ist ein Cache eingestellt.
Scheinbar gibt es in Contao 4.4 Managed Edition keine Möglichkeit mehr, den "internen Cache" zu aktivieren bzw. auszuschalten???
Was und wo müsste ich löschen, damit das Problem zukünftig nicht mehr auftaucht?

**Comment by alnv** [comment]
Problem ist identifiziert. An einer Lösung bin ich dran.
Wer mit mit Contao 3.5 arbeitet, dem empfehle ich "internen Cache" zu deaktivieren. Ansonsten immer den Cache löschen, bevor man das Installtool aufruft.

Spalten für folgende Tabellen nicht löschen bis das Update kommt:
- tl_user
- tl_user_group
- tl_member_group

Anlegen ist erlaubt.

**Comment by Anke** [comment]
Ich habe das gerade mal probiert unter Contao 3.5.24: Egal, ob ich den Cache nur leere oder über die Einstellungen "umgehe" - beim Aktualisieren der DB werden die DROP-Befehle weiterhin angezeigt. Bei mir allerdings nur für die beiden User-Tabellen. Etliche Member-Rechte sind eingerichtet, falls diese Info wichtig für dich ist.

**Comment by alnv** [comment]
Der Fehler wurde behoben in v1.6. Unter Contao 3.5 läuft es nun stabil.

Mit Contao 4 kann es noch Probleme geben. Wenn man z.B die Datenbank überspielt kann es sein, dass die Berechtigungsfelder zum löschen Angeboten werden. Hier bitte erstmal **abwarten** und **nicht löschen**!
Workaround:
- Gehe zu _Catalog Manager_ und klicke auf _mehrere bearbeiten_ anschließend wähle alle Kataloge aus.
- Suche ein ru­di­men­täres Feld aus z.B _Name_
- Klicke auf _Weiter_ und danach auf _Speichern und schließen_
- Gehe zurück zu Install-Tool, wenn die Felder weiter zum löschen Angeboten werden, kannst du diese löschen

**Comment by alnv** [comment]
Ist gefixt in v1.17
