### ISSUE TITLE
FE-Berechtigungen - Duplizieren

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#73]
Nach einigem Probieren habe ich es hinbekommen, die Rechte richtig zu setzen, indem ich im FE-Modul die Rechte aktiviere (Anlegen - Bearbeiten - Löschen) und diese dann durch die Rechte in den Mitgliedergruppen nach Bedarf überschreibe. 

Schade nur, dass der Duplizieren-Llink nicht in den Mitgliedergruppen erscheint, im FE auch nicht mit Adminrechten. Umgekehrt, wenn ich Duplizieren im FE-Modul ebenfalls aktiviere, ist er auch sichtbar für FE-Editoren, die nicht duplizieren sollen. Kann das gelegentlich noch angepasst werden?

**Comment by alnv** [comment]
Duplizieren und anlegen sind aus Berechtigungssicht das gleiche. Eventuell kann man es besser lösen. Mal schauen was man hier machen kann.

**Comment by alnv** [comment]
Die Berechtigungen werden unter Catalog Manager 2.0 überarbeitet. Da würde ich es berücksichtigen.
