### ISSUE TITLE
Bitte um Hilfe mit tl_user/tl_user_group-Einträgen

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#74]
Ich glaube, ich hatte das oder ein ganz ähnliches Problem schon einmal, bekomme es aber mit dem Installtool nicht gelöst.

Wenn ich auf "Datenbank aktualisieren" klicke, will Contao in tl_user und tl_user_group alle Einträge löschen, die auf meine Catalog-Manager-Tabellen verweisen. Lösche ich sie tatsächlich, erhalte ich bei dem Versuch, im BE einzuloggen, haufenweise Fehlermeldungen, dass diese Felder fehlen. Ich habe den CM noch mal drüber installiert (repariert), aber an dem Problem hat sich nichts geändert.

Was kann ich tun?

**Comment by alnv** [comment]
Welche Contao/Catalog Manager Version hast du installiert? Problem ist mir bekannt. Bin gerade dabei es zu beheben. Siehe #72

**Comment by Anke** [comment]
Contao 3.5.24 und CM 1.5.8
