### ISSUE TITLE
Automatische Vorbelegung von Datenfeldern

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#75]
Hallo,
eine Funktion zur automatischen Vorbelegung von Datenfeldern ist sinnvoll.
Beispiel Flohmarktfunktion: Die Daten werden über Frontend-Editing eingegeben, sollen aber erst sichtbar sein, wenn ein Admin die Eingaben geprüft hat (Datensatz verstecken muss automatisch aktiviert sein). Außerdem soll der Datensatz nur eine bestimmte Zeit angezeigt werden (Anzeigen bis mit einem Datum vorbelegen) und der Datensatz soll einem bestimmten Frontend-Benutzer zugewiesen werden (User-ID in ein Datenfeld eintragen).
Alle diese Felder sollen im Frontend nicht sichtbar sein.

Aber auch andere (individuelle) Felder sollten mit bestimmten Werten z.B. aus Contao-Inserttags vorbelegt werden können.

**Comment by alnv** [comment]
Kann man machen.

**Comment by martin-hofmann-netprofit** [comment]
Wär klasse :)
Wie lange müsste man ungefähr warten bist dies umgesetzt wäre?

**Comment by alnv** [comment]
Zum zeitlichen Ablauf kann ich nichts sagen. Es ist auf jeden fall auf der todo Liste ;)

**Comment by alnv** [comment]
Vorab gibt es ein Hook. Dort können Standardwerte etc. definiert werden.

`$GLOBALS['TL_HOOKS']['catalogManagerFrontendEditingOnSave'] `

Als Parameter werden die Werte, Modus, Catalog-Einstellungen und Feld-Einstellungen übergeben.
Als Rückgabewert werden neue Werte erwartet.

config.php:
`$GLOBALS['TL_HOOKS']['catalogManagerFrontendEditingOnSave'][] = [ 'FrontendEditingOnSave', 'initialize' ];`

FrontendEditingOnSave.php:

``` php
class FrontendEditingOnSave extends \Frontend {
	
	
	public function initialize( $arrValues, $strAct, $arrCatalog, $arrCatalogFields ) {
		
                $arrValues['my_field']  = "Standardwert";

		return $arrValues;
	}
}
```

Dieser Hook kann in der neuesten Version genutzt werden. 

Eine Implementierung über das Contao Backend folgt nach…

**Comment by martin-hofmann-netprofit** [comment]
Klasse, hat funktioniert :)

**Comment by alnv** [comment]
Ist implementiert in v1.16-beta.
