### ISSUE TITLE
FE nach Update auf 1.6.0 Build 6: tstamp wird wieder im Unixformat angezeigt

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#76]
Im Frontend brauchen wir bei einer Tabelle das letzte Änderungsdatum (tstamp). 

Bisher wurde uns anzeigt "Revision date" und z.B. "14-09-2017 03:53". Nach dem Update lautet die Spaltenüberschrift "strColumnName" und das Datum erscheint in nicht-menschenlesbarem Format.

What can I do?

**Comment by alnv** [comment]
ups… da habe ich was übersehen. Ist behoben, ein Update genügt.

**Comment by Anke** [comment]
Dankeschön! Sehe gerade, dass im BE auch wieder der Timestamp steht statt lesbarem Datum ...

**Comment by alnv** [comment]
Dort musst du wie gehabt das tstamp Feld etwas anpassen.
dcaconfig.php => `$GLOBALS['TL_DCA']['meine_tabelle']['fields']['tstamp']['flag'] = 6;`

**Comment by Anke** [comment]
Merci.
