### ISSUE TITLE
Keine Inhaltselemente mehr in BE-Liste nach Update auf 1.6.0 Build 6

### ISSUE THREAD

**Issue by juju2** [alnv/catalog-manager#77]
Hallo,

seit heute werden nach dem Update des CatalogManagers keine Inhaltselemente mehr im BE-Modul aufgelistet.

Ich habe ein Backendmodul mit Wrapper und Kind-Datensätzen. Wenn ich die Inhaltselemente eines Kind-Datensatzes bearbeiten will, dann werden diese nicht mehr aufgelistet. Im Frontend sind alle Daten noch vorhanden.

Außerdem werden die Kinddatensätze nicht mehr wie vor dem Update nach Anfangsbuchstaben sortiert sondern offensichtlich nach "Eindeutiger Bezeichnung"; sprich jeder Eintrag hat sich selbst noch einmal als Gruppenüberschrift. 

Bitte um zeitnahe Behebung,

Vielen Dank.

juju

PS: Bei dem Update hat übrigens offensichtlich auch eine Benutzergruppe in den Einstellungen das Recht verloren, das Backend-Modul zu verwenden (Häkchen bei Modul verwenden war gelöst). Ich habe dies definitiv nicht geändert.

**Comment by alnv** [comment]
Update ist verfügbar. Siehe Build 12.

**Comment by alnv** [comment]
Was die Sortierung angeht. Diese kannst du bei den Catalog Einstellungen unter Sortierungseinstellungen ändern.

Was die Gruppenberechtigung angeht. Siehe #72

**Comment by juju2** [comment]
Danke für das schnelle Update - die Inhaltselemente werden jetzt wieder angezeigt.

Kannst Du mir das mit der Sortierung bitte etwas erläutern?

Ich habe keine Änderung an der BE-Sortierung vorgenommen und trotzdem werden die Kind-Datensätze plötzlich anders aufgelistet. Bis vor ein paar Tagen wurden die Datensätze gelistet wie gewünscht: Nachnamen, alphabetisch nach Anfangsbuchstabe sortiert und nach Buchstaben gruppiert. Jetzt gibt es für jeden Datensatz eine eigene Überschrift (offensichtlich die "Eindeutige Bezeichnung" und ich sehe nicht, wie ich das ändern soll, da es die Möglichkeiit nicht mehr zu geben scheint.

Danke, juju

**Comment by alnv** [comment]
Welche Darstellung hast du da ausgewählt? Sortierung nach variablen oder festen Wert?

**Comment by juju2** [comment]
Diese Möglichkeit existiert nicht. Ich kann in der Kind-Tabelle nur einstellen, wie Sie anhand der Elterntabelle sortiert werden soll.

**Comment by alnv** [comment]
Stimmt, bei "Darstellung der Kinddatensätze eines Elterndatensatzes" fehlen noch die Auswahlmöglichkeiten. Ist behoben!
