### ISSUE TITLE
Datenbankspalten werden umbenannt

### ISSUE THREAD

**Issue by juju2** [alnv/catalog-manager#78]
Hallo,
seit einer der letzten Versionen werden Datenbankspalten beim Speichern von Feld-Einstellungen umbenannt (=> lowercase).

Ich habe heute die Einstellungen an einem Galerie-Feld geändert und mich gewundert, warum die Galerie im FE nicht mehr angezeigt wurde. Nach einigem Suchen habe ich festgestellt, dass beim Speichern der Einstellungen der name (Bezeichnung für Datenbankspalte) vom System geändert wurde, wobei alle Großbuchstaben in kleine geändert wurden. So konnte im template nicht mehr auf die Variable zugegrigfen werden, da sich der Name ohne mein Wissen geändert hatte.

Ich bin ehrlich gesagt immer wieder erstaunt, wie labil dieses System ist und wie oft Einstellungen "vergessen" oder einfach überschrieben/ geändert werden. Auch wenn ich finde, dass Du einen schnellen und bemühten Service bietest, aber ich war in Contao noch nie so nervös bei Änderungen von Einstellungen oder vor Updates.

Danke für die Behebung, juju

**Comment by alnv** [comment]
> seit einer der letzten Versionen werden Datenbankspalten beim Speichern von Feld-Einstellungen umbenannt (=> lowercase).

MySQL akzeptiert nicht alle Zeichen und dieser Mechanismus dient als prevention vor fatalen Fehlern. 

> Ich bin ehrlich gesagt immer wieder erstaunt, wie labil dieses System ist und wie oft Einstellungen "vergessen" oder einfach überschrieben/ geändert werden. Auch wenn ich finde, dass Du einen schnellen und bemühten Service bietest, aber ich war in Contao noch nie so nervös bei Änderungen von Einstellungen oder vor Updates.

Zugegeben v1.6 beinhaltete sehr viele Änderungen. Leider ging es hier nicht anders. Tut mir leid für die Umstände.

**Comment by juju2** [comment]
Wäre es dann nicht besser, das wenigstens durch eine Prüfung beim Speichern samt Fehlermeldung umzusetzen, so dass man von der Änderung erfährt, da man den Feldnamen vor dem Speichern selber anpassen muss? So macht das System dies einfach und man wundert sich, warum irgendwas nicht mehr funktioniert.

Danke, juju

PS: Contao verwendet auch Groß/Kleinschreibung für Datenbankspalten (z.B. singleSRC)

**Comment by alnv** [comment]
Guter Einwand. Ist besser so. Groß/Kleinschreibung ist nicht das eigentliche Problem aber es ist einfacher eine feste Regel zu definieren anstatt einzelne Zeichen zu sperren.  In dem Fall handelt es sich um eine "snake_case" Syntax ohne Sonderzeichen… 

Wobei wenn du "singleSRC" oder "multiSRC" eingibst kann es bei Catalog Manager zu Problemen führen. Mit single_src oder singlesrc bist du auf der sicheren Seite.
