### ISSUE TITLE
Fehlermeldungen in Systemlogs wg. nicht gefundener Bilder im BE

### ISSUE THREAD

**Issue by juju2** [alnv/catalog-manager#79]
Hallo,

in meinem BE-Modul habe ich Wrapper und Kind-Datensätze. Die Kind-Datensätze haben in Ihren Eigenschaften ein Galeriefeld, bei denen ich wie in Contao gewohnt je nur den Bild-Ordner ausgewählt habe.

Immer nachdem ich im BE einen Wrapper öffne und die Kind-Datensätze aufgelistet werden, erscheint in den Systemlogs die Fehlermeldung, dass das Bild nicht gefunden werden kann. Hast Du eine Idee woran das liegen kann?

Hier einer der vielen Einträge in den Systemlogs:
> Image "files/pfad/zum/ordner" could not be processed: Directory "files/pfad/zum/ordner" is not a file

Wähle ich übrigens in den Einstellungen eines Datensatzes bei der Galerie nur Bilder und keinen Ordner, so erscheint dieser Datensatz nicht mehr in den Logs.

Danke, juju

**Comment by alnv** [comment]
Diesen Fehler konnte ich nicht reproduzieren. Unter welcher Contao/PHP Version kommt der Fehler?

**Comment by juju2** [comment]
Contao 3.5.28
PHP 7.0

**Comment by alnv** [comment]
Dieser Fehler kommt wenn sich in dem ausgewähltem Ordner unerlaubte Dateitypen befinden. Man muss entweder alles erlauben oder darauf achten, dass die Dateitypen stimmen.
