### ISSUE TITLE
Listenmodul: Option Kartenansicht aktivieren

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#8]
Hallo Alexander,

wenn es möglich wäre im Listenmodul unter "Kartenansicht aktivieren" im Feld "Adresse eingeben" statt einer statischen Adresse ein Feld aus der Datentabelle anzugeben, das z.B. den GoogleMaps-Link oder den GeoCode enthält, dann müsste es theoretisch möglich sein, für jeden Datensatz eine andere Karte anzuzeigen, oder?

Mein praktischer Gedanke: Ich habe eine Liste mit Cricketplätzen inkl. Adressen und - momentan externen - Links zu GoogleMaps. Deshalb meine Überlegung, die Maps gleich auf der Detailseite zu präsentieren.

Gruß,
Anke

**Comment by alnv** [comment]
Dafür gibt es ein Eingabefeld von Typ Kartenansicht. Leider gibt es momentan keine Dokumentation dafür aber es funktioniert ganz simpel.

- Du erstellst Felder für Lat und Long. 
- Danach aktivierst du unter der "Geo-Einstellungen" Palette Geo Coding für diese Felder.
- Als nächstes erstellst du ein Eingabefeld von Typ Kartenansicht.
- und weißt dem Kartenansicht Eingabefeld die Lat und Long Felder zu.
- danach braucht du nur paar Datensätze ein zu pflegen und die Kartenansicht im Template auszugeben. <?php $this->myFieldnameForMapView ?> o.Ä
