### ISSUE TITLE
Datei-Upload – Template Auswahl für Vorschaubild greift nicht (V1.6.8)

### ISSUE THREAD

**Issue by CONTEGRA** [alnv/catalog-manager#81]
Wenn man dem Vorschaubild für eine Galerie ein eigenes Template zuordnen will z.B. "ce_image_preview", so wird dieses zwar in der Auswahl angezeigt und gespeichert aber im FE wird es nicht übernommen.

Wenn das Template die Standardbezeichnung "ce_image" trägt gibt es keine Probleme.

**Comment by alnv** [comment]
Hallo, das werde ich mir noch genauer anschauen. Danke für den Hinweis

**Comment by alnv** [comment]
Ist gefixt.
