### ISSUE TITLE
Umkreissuche: mehrere Datensätze an einer Geoposition

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#83]
Wenn bei der Umkreissuche zwei oder mehrere Datensätze mit derselben Adresse (Geoposition) vorhanden sind, wird beim Überfahren des Markers in der Google Map im Popup-Fenster nur ein Datensatz angezeigt.

Bitte das Ganze so abändern, dass an einer Geoposition zwar ein Marker angezeigt wird, wenn man diesen mit der Maus überfährt, sollen aber alle Datensätze an dieser Geoposition in dem Popup aufgelistet werden.

**Comment by alnv** [comment]
Sorry für die späte Reaktion, dass wollte ich genauer prüfen. Jedenfalls wäre eine Umsetzung etwas problematisch. Grundsätzlich kann man allein mit den zur Verfügung stehenden Templates eine Lösung umsetzen aber da sind Javascript/Google Maps Kenntnisse erforderlich*. Eine genaue Anleitung wäre zeitaufwendig.

Aber das Issue ist berechtigt und ich werde es implementieren. Allerdings nicht zeitnah.

* Als erstes solltest du den Core-Code aus den jeweiligen Templates entfernen und erstmal die Geo-Koordinaten(lat,long) und die Info-Boxen in eine zwischen Variablen sammeln. Danach kannst du die Variable auslesen und alle Geo-Koordinaten die mehrmals vorkommen in eine Map ausgegeben - Ich hoffe, es hilft weiter.
