### ISSUE TITLE
Link zu Kindtabellen

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#84]
Wenn die Kindtabellen einer Elterntabelle im Frontend angezeigt werden sollen (Kind-Tabellen Weiterleitungsseiten), werden diese im Frontend in der Tabellenansicht in der Spalte Links als Linksymbol (grüner Ordner) angezeigt.
Kann das Ganze so erweitert werden, dass hier auch ein Textlink mit frei wählbarem Text verwendet werden kann bzw. dass die die Linksymbole zusätzlich beschriftet werden können?

**Comment by alnv** [comment]
Hier für steht dir die `$this->relations` Variable[array] zur verfügung. Diese Variable findest du bei folgenden Templates:

- ctlg_view_table
- ctlg_view_teaser

Meistens ganz unten…

So kannst du die Icons austauschen: [Eigene Icons / Standard Icons](https://catalog-manager.alexandernaumov.de/feedback/eigene-icons-standard-icons.html)

**Comment by alnv** [comment]
Ist
