### ISSUE TITLE
Umkreissuche: Alle Filtereinstellungen zurücksetzen

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#85]
Bei der Umkreissuche bleiben die Frontend-Eingaben solange erhalten, bis eine neue Suche eingegeben wird. Das führt teilweise zu Problemen. Deshalb wollte ich einen Link zum zürücksetzen der Filtereinstellungen einfügen.
Wenn man beim Filtergenerator im Filter einer Umkreissuche (Übertragungsmethode POST) den „Alle Filtereinstellungen zurücksetzen“-Link aktiviert, wird der Link im Frontend nicht angezeigt.
Wenn man GET als Übertragungsmethode ausgwählt, wird der Link angezeigt, aber er funktioniert nicht.

**Comment by 31er** [comment]
Contao 3.5.28 / CM 1.6.10
Ich wollte bei der Umkreissuche die eingegebene Postleitzahl und die bereits gefilterten Werte mit der Zusatzfunktion „Filtereinstellungen zurücksetzen erlauben“ verwenden.

Beim ersten anklicken werden die Marker in der Karte entfernt, die eingegebene Postleitzahl bleibt im Textfeld des Formulars stehen.
Beim zweiten Anklicken der Funktion „Alle Filtereinstellungen zurücksetzen“ erhalte ich folgende Fehlermeldung.

----------------------------------------
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* pi()/180) * COS(abs(latitude) * pi()/180) * POWER( SIN( (-longitude) * pi()/' at line 1 (SELECT *,3956 * 1.6 * 2 * ASIN(SQRT(POWER(SIN((-abs(latitude)) * pi()/180 / 2),2) + COS( * pi()/180) * COS(abs(latitude) * pi()/180) * POWER( SIN( (-longitude) * pi()/180 / 2 ), 2 ))) AS _distance FROM ctlg_spezialisten WHERE LOWER(CAST(ctlg_spezialisten.`tstamp` AS SIGNED)) > '0' AND( ctlg_spezialisten.`start` = '' OR LOWER(CAST(ctlg_spezialisten.`start` AS SIGNED)) <= 1506694560) AND( ctlg_spezialisten.`stop` = '' OR LOWER(CAST(ctlg_spezialisten.`stop` AS SIGNED)) > 1506694560) AND ctlg_spezialisten.`invisible` != '1' HAVING _distance < 50 LIMIT 0, 1000) thrown in system/modules/core/library/Contao/Database/Statement.php on line 295

#0 system/modules/core/library/Contao/Database/Statement.php(264): Contao\Database\Statement->query()
#1 system/modules/catalog-manager/library/alnv/SQLQueryBuilder.php(39): Contao\Database\Statement->execute(Array)
#2 system/modules/catalog-manager/library/alnv/CatalogView.php(460): CatalogManager\SQLQueryBuilder->execute(Array)
#3 system/modules/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(149): CatalogManager\CatalogView->getCatalogView(Array)
#4 system/modules/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(81): CatalogManager\ModuleUniversalView->determineCatalogView()
#5 system/modules/core/modules/Module.php(287): CatalogManager\ModuleUniversalView->compile()
#6 system/modules/catalog-manager/library/alnv/Modules/ModuleUniversalView.php(49): Contao\Module->generate()
#7 system/modules/core/elements/ContentModule.php(59): CatalogManager\ModuleUniversalView->generate()
#8 system/modules/core/library/Contao/Controller.php(484): Contao\ContentModule->generate()
#9 system/modules/core/modules/ModuleArticle.php(213): Contao\Controller::getContentElement(Object(Contao\ContentModel), 'main')
#10 system/modules/core/modules/Module.php(287): Contao\ModuleArticle->compile()
#11 system/modules/core/modules/ModuleArticle.php(67): Contao\Module->generate()
#12 system/modules/core/library/Contao/Controller.php(417): Contao\ModuleArticle->generate(false)
#13 system/modules/core/library/Contao/Controller.php(277): Contao\Controller::getArticle(Object(Contao\ArticleModel), false, false, 'main')
#14 system/modules/core/pages/PageRegular.php(133): Contao\Controller::getFrontendModule('0', 'main')
#15 system/modules/core/controllers/FrontendIndex.php(285): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#16 index.php(20): Contao\FrontendIndex->run()
#17 {main}
----------------------------------------

**Comment by alnv** [comment]
Die POST-Übertragungsmethode unterstützt nicht die "Filtereinstellungen zurücksetzen" Funktion. Das geht nur mit GET.

Ich empfehle, immer die GET-Übertragungsmethode zu nutzen und erst beim Live gehen die Übertragungsmethode auf POST wechseln. Da sonst das testen erschwert wird, da die POST-Daten Cookie gestützt arbeiten wie im Contao Backend. Das kann dazu führen das bestimmte Werte im Speicher bleiben.

Ich denke, wenn du die Cookies in deinem Browser löscht, geht es wieder.  Oder die Seite mit einem anderen Browser aufrufen.

Wenn du die Seite mit einem anderen Browser aufrufst und der Fehler immer noch da ist, bitte hier posten.

**Comment by 31er** [comment]
GET und POST hatte ich versucht, die Fehlermeldung stammt von der POST-Einstellung. Tatsächlich hat aber das Löschen der Cookies geholfen. Danke für den Hinweis.
