### ISSUE TITLE
FR: Anzahl Datensätze im FE ausgeben

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#86]
Wäre es möglich, im FE gelegentlich die Anzahl Datensätze mit auszugeben? Ich fand das im Listing bzw. EFG Listing immer ganz praktisch.

**Comment by Schmidty2** [comment]
Das Ganze sollte dann aber optional sein, bei vielen Anwendungen die ich kenne, ist es nicht gewünscht die gesamte Anzahl der Datensätze anzuzeigen bzw. zu sehen.

**Comment by Anke** [comment]
Alternativ solltest du das dann eigentlich auch im Template rausnehmen können bzw. per CSS ausblenden

**Comment by alnv** [comment]
Ab v1.19 gibt es in der Listenansicht > Listenansicht-Einstellungen eine entsprechende checkbox zum auswählen: "Anzahl der Datensätze anzeigen".

Weiter kann man im Template (ctlg_view_teaser, ctlg_view_table, mod_catalog_universal) auf die Nummerierung zugreifen:

``` php
<?= $this->entityIndex[0]; // Index ?>
<?= $this->entityIndex[1]; // Gesamtzahl ?>
```
Labels:
```
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['noEntities'] = 'Es wurden keine Einträge gefunden.';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['oneEntity'] = 'Es wurde ein Eintrag gefunden.';
$GLOBALS['TL_LANG']['MSC']['CATALOG_MANAGER']['entitiesAmount'] = 'Es wurden %s Einträge gefunden.';
```
