### ISSUE TITLE
Option für leere Auswahl bei Tags

### ISSUE THREAD

**Issue by Schmidty2** [alnv/catalog-manager#87]
Ist es möglich, bei der Auswahl von Daten die über Tags im Backend eingefügt werden, eine Option hinzuzufügen, so dass eine leere Auswahl angezeigt wird und ein Tag-Eintrag ausgewählt werden muss?
Im jetzigen Stand ist beim Erstellen eines neuen Datensatzes im Backend bereits eine Option sichtbar bzw. vorausgewählt.
Bei der Frontendfilterung ist das ja bereits möglich, nur nicht beim Erfassen von Datensätzen im Backend.

![tags auswahl leere option](https://user-images.githubusercontent.com/2067428/31098607-7c44a3e2-a7c3-11e7-9b25-2b8fd5c538df.jpg)

Danke.

**Comment by alnv** [comment]
Weiter unten unter **Eingabefeld-Einstellungen** findest du die Option **Leere Auswahl hinzufügen**. Im **Leeres Zeichen ersetzen** Textfeld kannst du dein Zeichen eintragen.
