### ISSUE TITLE
Sortiereinstellungen Reihenfolge

### ISSUE THREAD

**Issue by 31er** [alnv/catalog-manager#88]
Unter Sortiereinstellungen > Reihenfolge > Felder lassen sich nur die ersten 14 sichtbaren Werte auswählen. Sind mehr als 14 Werte vorhanden und es muss im Selektmenü gescrollt werden, die diese nicht selektierbar.

**Comment by alnv** [comment]
Unter welchen Browser tritt der Fehler auf? Meinst du die Sortiereinstellungen vom Frontend Modul (Listenansicht) oder den Catalog Einstellungen?

**Comment by 31er** [comment]
Ich meine das FE-Modul Catalog-Listenansicht. Browser ist Firefox 56 unter Win7. Habe eben mal mit Chrome nachgeschaut, da tritt das Problem nicht auf.

Als Workaround habe ich unter den Catalog-Einstellungen das entsprechende Feld nach oben verschoben, so das es im Selektmenü an erster Position steht.

**Comment by alnv** [comment]
Werde ich mir bei Gelegenheit anschauen.

**Comment by alnv** [comment]
Da stimmt was nicht mit Chosen: Siehe https://github.com/harvesthq/chosen
