### ISSUE TITLE
Paginierung bei Filterung fehlerhaft

### ISSUE THREAD

**Issue by 31er** [alnv/catalog-manager#89]
Die Paginierung zeigt immer eine Seitenanzahl aufgrund alle vorhandenen Datensätze an. Werden Datensätze gefiltert, reduziert sich nicht die Seitenanzahl in der Paginierung.

**Comment by alnv** [comment]
Ich kann den Fehler nicht reproduzieren. Wenn du magst kannst auf der Demoseite ein Beispielsetup mit dem Fehler machen.

**Comment by 31er** [comment]
Ich schicke Dir eine PN zu einer Intsllation, wo der Fehler reproduzierbar ist. Müste sonst auf der Demoseite sehr viele Datensätze anlegen, um den Fehler zu reproduzieren.

**Comment by alnv** [comment]
In der v1.16-beta wurde die Paginierung optimiert. Ob es dein Bug miteinschließt, kann ich nicht sagen. Eventuell hängt es auch mit dem Template zusammen.

**Comment by alnv** [comment]
In der v1.7 wurde die Paginierung nochmals überarbeitet. Der Fehler sollte nicht mehr vorkommen.
