### ISSUE TITLE
FR: Catalog-Manager-Tabellen sortieren

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#9]
Hi,

nur eine Kleinigkeit: Es wäre schön, wenn die Tabellen im Catalog Manager nach Titel sortiert wären. Habe jetzt vier Tabellen angelegt; die Listenzeige zeigt keinerlei Sortierung, weder alphabetisch gem. Titel oder Tabellenname noch nach Erstellungsreihenfolge/ID.

VG
Anke

**Comment by alnv** [comment]
Du kannst die Sortierung im Backend Modul einstellen. Siehe Screenshot: [Backend Sortierung](https://catalog-manager.alexandernaumov.de/files/theme/media/screenshots/sortierung/Backend-Sortierung.png). 

- Sortiere nach bestimmen Feld
- Wähle die Reihenfolge aus
- danach den Feld, nach dem du sortieren möchtest.

In dem FE Modul **Catalog Listenansicht** unter der Sortiereinstellungen Palette, kannst du die Reihenfolge der Liste ändern. Siehe Screenshot: [Frontend Sortierung](https://catalog-manager.alexandernaumov.de/files/theme/media/screenshots/sortierung/Frontend-Sortierung.png)

**Comment by Anke** [comment]
Da habe ich mich wohl nicht gescheit ausgedrückt, trotzdem Dank für die schnelle Antwort. Die Sortierung der Felder innerhalb der Backend-Module ist klar und funktioniert wunderbar und auch die Positionierung der Backend-Module im Menü (große Klasse!)

Aber: Wenn man auf Catalog Manager klickt, dann hat man ja die Liste der Datentabellen vor sich mit Titel, Tabellenname und Info. Diese Liste erscheint mir irgendwie nach Zufall sortiert ...

**Comment by alnv** [comment]
Alles klar. Es gibt noch keine Möglichkeit die Sortierung zu ändern. Wenn du eine Idee hast, kannst es mir gerne sagen. Sonst überlege ich da was.

**Comment by Anke** [comment]
owas wie oben ein Panel hinsetzen mit Sortierung, Filter, Suche? (Sorry, bin ja nur Designer und Anwender ...)

**Comment by alnv** [comment]
In der v1.2.8 gibt es jetzt ein Panel für die Filterung und Sortierung der Tabellen/Module.
