### ISSUE TITLE
Rechtevergabe :: Module

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#90]
Kann man die Rechte auf den Modulen entsprechend steuern, so dass bestimmte Nutzer z.B. keine Datensätze anlegen bzw. löschen können?

**Comment by alnv** [comment]
Berechtigungen können im jeweiligen Katalog aktiviert werden. 

Die **Berechtigungseinstellungen** Palette einblenden und einen der beiden Berechtigungstypen auswählen.
- Standard (Nur ausführende Rechte)
- Erweitert ( ausführende Rechte + Datensätze )

![Catalog Manager Rechte](https://catalog-manager.alexandernaumov.de/files/theme/media/github/01-Permissions.png)

Anschließend kannst du unter Benutzer/Benutzergruppen deine rechte zuweisen.

![Catalog Manager Rechte](https://catalog-manager.alexandernaumov.de/files/theme/media/github/02-Permissions.png)
