### ISSUE TITLE
Habe Probleme beim Update von Contao 4.4.3 -> 4.4.7

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#91]
Hallo mal wieder,

habe bei der Nutzung des Contao-Managers folgenden Fehler erhalten:
Exception occured: "/www/system/modules/catalog-manager" is not a link to "/www/vendor/alnv/catalog-manager" (expected "/www/vendor/alnv/catalog-manager" but got "/www/system/modules/catalog-manager")

Wie bekomme ich das gefixt?
Freue mich auf eine baldige Rückmeldung …

Grüße
Michael

**Comment by alnv** [comment]
Normalerweise erzeugt Contao Manager im _system/modules_ Verzeichnis  die _symlinks_ auf jeweilige Module im _vendor_ Ordner. Wenn du Zugriff auf die Kommandozeile (SSH) hast, könntest du es eventuell so beheben:

Erstmal den catalog-manager Ordner im /system/modules/ Verzeichnis löschen:

`rm -rf  /system/modules/catalog-manager`

und ein neues symlink erzeugen:

`ln -s ../../vendor/alnv/catalog-manager`

Davor ein Backup machen. Ich habe es nicht getestet.

**Comment by alnv** [comment]
Eventuell hilft auch das hier: `./bin/console contao:symlinks`

**Comment by codiso** [comment]
Hallo Alexander, danke für deine schnelle Rückmeldung. Ich habe das Problem gefunden! Es war wirklich so dass der Sym-Link in Module Ordner nicht mehr existent war. An dessen Stelle war ein kompletter Ordnerinhalt aus dem Original Ordner gerutscht.

Entstanden ist das Problem durch das transferieren des gesamten Contao Auftritt auf einen anderen Server. Ich habe ein ZIP-Archiv erstellt gehabt welches die Sym-Links nicht beachtet hat!

Habe es aber nun korrigiert bekommen. Also noch mal danke für deine Bemühungen!
