### ISSUE TITLE
[Catalog-Manager] und [printpreview]

### ISSUE THREAD

**Issue by Anke** [alnv/catalog-manager#92]
Hallo Alexander,

obwohl du natürlich nicht für andere Erweiterungen verantwortlich bist, muss ich trotzdem mal was fragen. Ich nutze die [printpreview-Erweiterung](https://contao.org/de/erweiterungsliste/view/printpreview.10000019.de.html), die eine Druckvorschau einer Webseite bereitstellt. Das funktioniert erwartungsgemäß mit den Listenanzeigen, leider aber nicht mit den Detailseiten. Dabei ist es egal, ob die Detailansichten dynamisch generiert werden (in diesem Fall wird die Listenansicht in der Druckvorschau gezeigt) oder auf einer Weiterleitungsseite (führt zu einem 404-Fehler). 

[printpreview] verwendet `PageModel::findPublishedById`. Das funktioniert mit den News, Events und FAQ, und wäre fantastisch, wenn es auch mit den Detailseiten des Catalog-Managers funktionieren würde. 

In diesem Zusammenhang ist mir aufgefallen, dass die CM-Detailseiten sich auch über die FE-Vorschau nicht aufrufen lassen (404). Mir ist klar, dass Contao nicht weiß, welchen Datensatz es angezeigt werden soll, aber nach meinem Verständnis sollte die Seite mit den übrigen Inhaltselementen trotzdem aufrufbar sein (wie bei News usw.). Deshalb meine Frage, ob sich da etwas machen lässt. Vielleicht würde das auch mein Problem mit der Druckvorschau lösen.

VG
Anke

**Comment by alnv** [comment]
Wenn man eine Detailseite mit einer Catalog Detailansicht anlegt wird ein Datensatz erwarten, sonst gibt es 404. Daran möchte ich nichts ändern. 

Aber es gibt hier ein Trick wie man es umgehen kann. Die Catalog Listenansicht, kann auch als Detailansicht verwendet werden. Wenn Alias gesetzt ist, wird die Detailansicht angezeigt wenn nicht, dann ganz normale Liste…

Zu der Printpreview-Erweiterung: Zu der Ursache kann ich nichts sagen, da ich das Modul nicht kenne.
Die `PageModel::findPublishedById` Methode funktioniert auch unter Catalog Manager.
