### ISSUE TITLE
Listenansicht

### ISSUE THREAD

**Issue by nuun** [alnv/catalog-manager#93]
Hi Alexander
Danke für deinen Einsatz rund um den Catalog Manager! Wir haben mit der Extension eine Referenzliste mit Filtern umgesetzt. 
Mein Frage dazu: Im Contao Backend haben wir die Liste der Referenzen. 
1. Ist es möglich das Datum nicht als Zeitstempel sondern als Datum auszugeben?
2. Ist es möglich die Bearbeiten Icons analog dem Contao Nachrichtenmodul zu belegen (also erst Beitrag bearbeiten, dann Beitragseinstellungen bearbeiten) und dieselben Icons zu verwenden wie Contao?
Mein Kunde war etwas verwirrt, da das Handling nicht gleich ist wie bei den Nachrichten.
Gerne höre ich von Dir. Grüsse Sam
![catalog-manager](https://user-images.githubusercontent.com/463227/32592230-2067e822-c523-11e7-8abb-33abb77afb6d.jpg)

**Comment by alnv** [comment]
Hallo, danke für dein Feedback. Das Datum kannst du bei den Eingabefeld-Einstellungen ändern.
Im "Panel Layout-Einstellungen" Reiter gibt es das "Sortierreihenfolge" Select-Menu. Dort kannst du einen entsprechenden flag setzen… Siehe Screenshot.
Alternativ kannst du auch ein Datum-Eingabefeld verwenden. Hier ist der flag automatisch gesetzt.

![Datumsformat ändern](https://catalog-manager.alexandernaumov.de/files/theme/media/feedback/BE-Datumformat-aendern.png)

Was die Reihenfolge der Icons betrifft, da muss ich erstmal paar tests durchführen. Theoretisch wäre eine Anpassung möglich. Ich melde mich später dazu.

**Comment by nuun** [comment]
Hallo - Datum hat einwandfrei funktioniert!
Gerne erwarte ich Deinen Bescheid zu den Icons! Thanks a lot Alexander!

**Comment by alnv** [comment]
Voresst gibt es für die icons keine Lösung, die update sicher ist.
