### ISSUE TITLE
Eltern-Kind-Tabelle Problem mit Anzeige der Kinddatensätze

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#94]
Hallo Alexander,

sitze gerade an meinem 2ten Projekt mit dem Catalog-Manager und habe ein Problem bei Eltern-Kindtabellen Beziehungen.

Ich habe eine Elterntabelle-Tabelle mit Nutzerdaten, welche ich mit Kontaktdaten anreichern will (Kindtabelle). Habe die Tabellen angelegt und auch nach Deiner Doku miteinander verbunden, so dass die Elterntabelle die Kindtabelle kennt und umgekehrt.

![catalog_manager_ _backend_modul_mit_der_id_1_bearbeiten__-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653170-2ab16bac-c607-11e7-8362-5aa9544ac49a.png)

![catalog_manager_ _backend_modul_mit_der_id_9_bearbeiten__-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653206-4c083a7e-c607-11e7-88b2-35c0e2d7b5ee.png)

Ich kann nun vom Elterndatensatz über die Liste auf die Kindtabellenverknüpfungen zugreifen, aber in der Anzeiger der Liste der Kinddatensätze wird nur die ID angezeigt, obwohl ich die An
gabe gemacht habe, was anzuzeigen ist!

![micasa____accounts_-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653243-7833278a-c607-11e7-9a23-d81cdb9cdd1f.png)

![micasa____accounts_ _max_mustermann_-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653324-cddf9cfe-c607-11e7-98b3-76e428a3910d.png)

![catalog_manager_ _backend_modul_mit_der_id_9_bearbeiten__-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653371-f9632148-c607-11e7-9d69-7a5a7c163328.png)

Mache ich was falsch, oder ist das ggf. ein Bug?
Freue mich über eine Rückmeldung von Deiner Seite :-D

**Comment by alnv** [comment]
Der Contao Treiber (DC_Table) kann keine Tabellen im Mode 4/3/5/6 anzeigen.
Was funktioniert ist es den "Bezeichnungsformat" zu überschreiben. Siehe Screenshot.
![Bezeichnungsformat überschreiben](https://catalog-manager.alexandernaumov.de/files/theme/media/github/bezeichnungsformat-ueberschreiben.png)

Wenn du eine Möglichkeit kennst Tabellen auch für Kind-Tabellen anzuzeigen, kannst du es mir gerne verraten :) Bin schon länger auf der Suche… (ohne Drittanbieter)

**Comment by codiso** [comment]
Bezeichner überschreiben geht, aber das ist noch nicht die optimale Lösung für die Darstellung von relationalen Daten 👎 

![micasa____accounts_ _max_mustermann_-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32664132-9c0fb10e-c630-11e7-993f-f0e414d4bb6e.png)

Ich habe mich leider noch nicht mit "DC_Table" beschäftigt. Insofern bin ich da zur Zeit wohl nicht der richtige Ansprechpartner. Könntest Du die Tabelle nicht selber ausgeben?

**Comment by alnv** [comment]
Nicht das ich wüsste. Es gibt hierfür keine Templates. Die Tabellen/Listen etc. werden in der DC_Table Klasse erzeugt.

**Comment by codiso** [comment]
Was sind denn das für Modes (Mode 4/3/5/6)?

**Comment by alnv** [comment]
Im Contao gibt es 7 verschiedene Modes (Darstellungstypen).

- Keine Sortierung
- Sortierung nach einem festen Feld
- Sortierung nach einem variablen Feld
- Darstellung als Baum
- Sortierung der Kinddatensätze anhand eines Baumes
- Sortierung anhand der Elterntabelle
- Darstellung der Kinddatensätze eines Elterndatensatzes

Catalog Manager verwendet diese Modes für die Darstellung. Auf die Modes selber Catalog Manager keinen Einfluss.
