### ISSUE TITLE
Anzeige der Bezeichnung der Kindtabelle

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#95]
Die Anzeige der Kindtabelle in der Liste der Elterntabelle zeigt bei Rollover den Tabellennamen. Dieser ist aber nicht unbedingt immer selbsterklärend, so dass die Anzeige des **"Namens"** oder der **"Information"** sinnvoller wäre.

![bildschirmfoto_2017-11-10_um_11_17_21](https://user-images.githubusercontent.com/2002902/32653626-cab5960e-c608-11e7-8ee8-978fa1cb51dd.png)

![catalog_manager_ _backend_modul_mit_der_id_9_bearbeiten__-_contao_open_source_cms](https://user-images.githubusercontent.com/2002902/32653557-9867f61a-c608-11e7-9bc3-e4a08f5096f6.png)

**Comment by alnv** [comment]
Am besten wäre es hierfür die Beschreibung zu verwenden.
Wenn keine Beschreibung angegeben ist => Wie bisher nur statt den Tabellennamen soll der Name ausgegeben werden.

**Comment by alnv** [comment]
Ist erledigt in v1.16.1. Name & Beschreibung werden für die Kindtabellen verwendet.
