### ISSUE TITLE
Selbstverweise?

### ISSUE THREAD

**Issue by codiso** [alnv/catalog-manager#96]
Wie kann man Selbstverweise im Catalog-Manager realisieren?
Die Tabelle wäre dann ja Eltern- und Kindtabelle in einem, oder sind Kreuztabellen machbar und ich habe es noch nicht gesehen …

![bildschirmfoto 2017-11-10 um 12 19 52](https://user-images.githubusercontent.com/2002902/32656349-be9cbf4c-c611-11e7-8d42-fe80f82e3fc4.png)

**Comment by alnv** [comment]
Kannst du ein groben Fallbeispiel posten?

**Comment by codiso** [comment]
In dem Bild ist eine Kreuztabelle dargestellt, welche eine n:m Beziehung abbildet. Somit kann eine Person beliebig viele Verknüpfungen zu anderen Personen besitzen. Die beiden Felder in der Kreuztabelle "person_has_person" sind zusammen ein eindeutiger Schlüssel. Die Einzelfelder sind FK's (Fremdschlüssel) auf "id_person" in der Tabelle "person".

Für eine 1:1 Relation müsste das mit einem Feld in der Tabelle "person" funktionieren, welches auf die ID einer anderen Person verweist. Somit müsste man im Catalog-Manager ein Feld definieren können, welches aus den Daten der eigenen Tabelle bestückt wird. Dabei sollten dann aber Ringverweise nicht möglich sein!

**Comment by alnv** [comment]
Man kann die Felder unter den Auswahllisten-Einstellungen miteinander verknüpfen. 
![Catalog Manager Auswahllisten-Einstellungen](https://catalog-manager.alexandernaumov.de/files/theme/media/github/auswahllisten-einstellungen.png)
Allerdings wird es bei einer n:m Beziehung etwas komplizierter. Ich denke, man müsste noch den "save_callback" Hook triggern um die Daten in die Kreuztabelle zu übertragen…
