### ISSUE TITLE
Elternelement und Kindelement zusammen in einer Liste und Filtern

### ISSUE THREAD

**Issue by Benjaminscherf** [alnv/catalog-manager#98]
Hallo, 

ich habe eine Frage zu einer Sache von der ich mir denke, dass sie funktioniert, ich es aber nicht ganz verstehe. 

Ich habe einen Catalog namens Firmen und ein Kindkatalog namens Produkte angelegt. Die Zuordnungen funktionieren und das Mitglied kann über das Frontend einen Firmeneintrag anlegen und wiederum über die Firmeneinträge der jeweiligen Firma ein oder mehrere Produkte anlegen.

Ich bekomme im öffentlichen Bereich beide Listen (Firmen und Produkte) gut ausgelesen. Nun möchte ich jedoch eine einzige Liste für beide Kataloge erstellen, so dass der Besucher mittels einer erweiterten Suche die Liste filtert. 

Ist das möglich?
Mit freundlichen Grüßen.

**Comment by alnv** [comment]
Du kannst erstmal eine neue Produktliste erstellen und die Firmen nachträglich verknüpfen. Verknüpfungseinstellungen >  Elternelement verknüpfen. Siehe Screenshot:
![Elterntabelle verknüpfen](https://catalog-manager.alexandernaumov.de/files/theme/media/github/join-parent.png)
Verknüpfte Felder werden bei der Filterung nicht berücksichtigt.

Falls du eine individuelle Filterung einbauen möchtest, kann ich dir ein HOOK bis zum nächsten Update bereitstellen.

**Comment by Benjaminscherf** [comment]
Ok, dass werde ich versuchen. Vielen dank.
